### ISSUE TITLE
2021/01/31 Memo

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#102]
- [x] ~~We shouldn't use vim's complete-item format~~

The reason is that LSP's ComoletinItem more featurefull by default.
Currently, We provided `Source.confirm` for some of expansion but it makes the source depends on `nvim-compe` forcely.

If we use LSP's CompletionItem format, the source can be used on other plugin (such as coc.nvim).
And it makes more easily to create source.

Also performance can be increased maybe.

- [ ] Remove `Source.documentation` (Breaking)

I want to respect VSCode design more closely.
The VSCode uses `LSP.CompletionItem#documentation` for showing documentation preview and it can be resolved later.

In this design, the `Source.documentation` is not needed anymore.

- [x] Move sources to Lua

I don't stick to use Lua or VimL but some users loves Lua (hate VimL).

And Anyway, nvim-compe does not work on Vim so we can decrease VimL may be

- [x] More strict cache management

Currently, nvim-compe will filter items per source. I think it is correct design.
But we can improve caching for it.

For example, If we invoke completion on `foo.go`, nvim-compe will filter twice.

First, the buffer completion was done.
Second, the gopls completion was done.

In secondc case, we can use cache for the buffer source but it is not implemented now.

**Comment by elianiva** [comment]
I agree on making the completion item format as close as the LSP spec, I think it's a good idea.

**Comment by hrsh7th** [comment]
We can convert vim item to LSP item so we can avoid to apply breaking change maybe.

I will try it.

**Comment by coxackie** [comment]
1. Keeping as close to VSCode way of doing things is great: it helps by creating a unifying standard which is sane, and also helps people who have (or like) to use both Neovim and VSCode.
2. I think moving away from VimL and porting more things to Lua is absolutely the right way to go about, given that this is just a Neovim plugin. (If @hrsh7th recalls, I even asked if another extremely popular plugin of his could be ported to Lua.)

**Comment by elianiva** [comment]
I agree with @coxackie, maybe porting more stuff to lua can improve the performance? Though, the current state of nvim-compe is fast already, I never got any performance issue with it.
I can help converting Viml source to Lua if @hrsh7th agrees.

**Comment by hrsh7th** [comment]
I think it would be good if we port some of the sources to Lua (if it posible).
For example, vsnip/tags/spell/path is good.

The vim-lamp/vim-lsp may be hard to port.

**Comment by hrsh7th** [comment]
For example, vim-iced is really awesome plugin that written in VimL.
nvim-compe must support such as these plugins.

**Comment by elianiva** [comment]
yeah, we shouldn't break compatibility with the existing VimL source. I think we should port the builtin ones to Lua if possible but keep the ability to register a VimL source. Maybe I'll start to port them tonight.

**Comment by hrsh7th** [comment]
The path source is one of the most complex source.
So I leave the path source implementation explanation for when you try to port to Lua.

The path source has `g:accept_pattern` is existing to solve the below cases (but the current implementation is not perfect yet)

1. Avoid if the user press `/` for the HTML closing tag (`</|>`)
2. Avoid if the user press `/` for URL (`http:/|`
3. Avoid if the user press `/` for comments (`^/|`)
4. Avoid if the user press `/` for math calculation (`1 / 3`)

I think we can make it more readable and performant if we port it to Lua.

This doesn't have to be ported to Lua, as it can be quite annoying. (If you don't touch to path source, I will tackle it).

**Comment by elianiva** [comment]
Ah, I see. Thanks for the pointers, I'll see what I can do and report back :)

**Comment by hrsh7th** [comment]
Hm... It is difficult to use VSCode items as first-class than my thoughts.
I will continue to do it (will take a lot of time)

**Comment by hrsh7th** [comment]
> More strict cache management

Implemented https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe/source.lua#L221

Now, nvim-compe will re-use the previous filtered items.

https://user-images.githubusercontent.com/629908/106868306-f952f300-6711-11eb-878a-de5f55d8e6d5.mp4

**Comment by hrsh7th** [comment]
If we implement a matching algorithm that increases the candidates by increasing the input string, this optimization must be removed.
