### ISSUE TITLE
expanding lsp source snippets?

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#106]
Hey everyone. I wonder if anyone had the following issue with expanding lsp source snippets. `<cr>` doesn't expand lsp snippet source. `<cr>` is set to `compe#confirm(lexima#expand('<LT>CR>', 'i'))`, I've tried it with `compe#confirm('<cr>')` but seem effect.

https://user-images.githubusercontent.com/65782666/106391304-b46f4980-63fd-11eb-8dc9-33295fe91340.mp4

Also, with vsnip `<CR>` doesn't seem to expand. I have set `vsnip#available(1)  ? '<Plug>(vsnip-expand)` for `<C-l>` but shouldn't it automatically expand on `<CR>`

https://user-images.githubusercontent.com/65782666/106391375-1334c300-63fe-11eb-932a-9ffe25da8fa8.mp4

Additionally, on enter the list get refreshed instead of closing the completion, is this new default ? 

Thanks

**Comment by elianiva** [comment]
That's weird, it works on my setup.

https://user-images.githubusercontent.com/51877647/106391909-34a7a600-6422-11eb-90a7-b71b9768d895.mp4

**Comment by tami5** [comment]
@elianiva  what imap `<cr>` show you. Mine `i  <CR>        * pumvisible() ? "\<C-Y>" : lexima#expand('<CR>', 'i')`

**Comment by elianiva** [comment]
I have this function bound to `<CR>`

```lua
local npairs = require('nvim-autopairs')
Util.trigger_completion = function()
  if vim.fn.pumvisible() ~= 0  then

    if vim.fn.complete_info()["selected"] ~= -1 then
      return vim.fn["compe#confirm"]()
    end

    vim.fn.nvim_select_popupmenu_item(0 , false , false ,{})
    return vim.fn["compe#confirm"]()
  end

  return npairs.check_break_line_char()
end
```

**Comment by tami5** [comment]
one sec let me switch to `nvim-autopairs`  << something I want to do for a long time

**Comment by tami5** [comment]
@elianiva do you have your configuration for `windwp/nvim-autopairs` laying somewhere?

**Comment by elianiva** [comment]
yup, https://paste.sh/lkEQuiZ0#QL8iIzj137-ONsndorhTqpGM

**Comment by tami5** [comment]
> yup, https://paste.sh/lkEQuiZ0#QL8iIzj137-ONsndorhTqpGM
> 
> you might also want [this](https://paste.sh/QKN7ze63#0rryJIlsw-SezkyICEZ2dlw6) since they're kinda mixed up

What does ` Util.check_surroundings()` does or where is it defined?

**Comment by elianiva** [comment]
sorry, forgot to attach that :laughing:

[this function](https://github.com/elianiva/dotfiles/blob/4bbd2a9145f39ca4c80714d03b3b478c2e106635/nvim/.config/nvim/lua/modules/_util.lua#L19-L30) checks the previous and next character from the cursor position and decide whether or not to insert an extra space so I can make `{|}` to `{ | }`

**Comment by hrsh7th** [comment]
Probably, You set https://github.com/cohama/lexima.vim/blob/master/doc/lexima.txt#L245 to false.

Sorry. I'm on the bed.

**Comment by tami5** [comment]
@elianiva Thanks so much I managed to switch to nvim_autopair

But still my first screenshot with clangd won't expand to e.g. `return true;`. However in lua source it does.

@hrsh7th :D glad I'd didn't see your reply :laughing: lexima has so much startup time cost.

But yah is the issue with clangd?

**Comment by elianiva** [comment]
I think so, I didn't even know clangd has a snippet support 😆

**Comment by hrsh7th** [comment]
In my environment, clangd returns `return expression;` as a snippet and it works fine to me.

**Comment by tami5** [comment]
🤔🤔 That's a bit odd. Do u have additional settings for clangd?

Also, I'm having issues with vsnip source in that hitting enter is not as builtin expand e.g.

```
inlinefun<cr>

inlinefunfunction() return end

inlinefun<c-l> // vsnip mapping

function() return end
```

**Comment by hrsh7th** [comment]
Which problem do you have?
1. `vsnip source confirmation`
2.`clangd snippet item confirmation`.

**Comment by hrsh7th** [comment]
Anyway, I might have found a problem with nvim-lsp's `Method not found` related behavior.

**Comment by tami5** [comment]
> Which problem do you have?
> 
> 1. `vsnip source confirmation`
> 
> 2.`clangd snippet item confirmation`.
> 
> 

both 😬

**Comment by hrsh7th** [comment]
Could you provide the full configuration or minimal vimrc based on https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim?

**Comment by hrsh7th** [comment]
I don't have any issue now... Hm... it's weird...

**Comment by tami5** [comment]
I'm going to revisit here after migrating my config to lua. Hopefully in few days from now

**Comment by akinsho** [comment]
I believe I'm experiencing this issue specifically with `lexima`. This I believe used to work a week or so ago but doesn't anymore. When I hit `<CR>` using the config in the readme it just goes to the next line.

my config has
```lua
vim.g.lexima_accept_pum_with_enter = 0
vim.g.lexima_enable_space_rules = 0
map("i", "<CR>", [[compe#confirm(lexima#expand('<LT>CR>', 'i'))]], opts)
```

Am I missing something about how this should work? I tried setting the lexima pum variable to 1 and that just causes the list to refresh. I don't use `clangd` so my issue has nothing to do with that I'm specifically encountering this when I try to expand `lsp` snippets or `vsnip` snippets

**Comment by hrsh7th** [comment]
I've improved docs to use lexima.vim.

I think this issue can be closed.
@tami5 What do you think about it?

**Comment by tami5** [comment]
I haven't got the chance to pinpoint the issue sorry, perhaps few more days till I report back

**Comment by akinsho** [comment]
The new instructions in the docs worked for me @hrsh7th thanks 👍🏿

**Comment by wbthomason** [comment]
I'm seeing this issue with **no** auto-pair plugin and `texlab`. Snippets do not expand and the cursor is placed at the end of the snippet (rather than the first insertion point) after calling `compe#confirm`. I have `snippets.nvim` installed, but not `vsnip`. Is this expected (i.e. do I need `vsnip` for snippet expansion to work)?

**Comment by elianiva** [comment]
> I think so, I didn't even know clangd has a snippet support

I think the problem here is I didn't set `snippetSupport` for nvim-lsp to `true`. After doing this, clangd snippets works fine. Some servers doesn't require me to do this and I think sumneko_lua is one of them.

**Comment by tami5** [comment]
Can anyone please tell just how can you write the letter p while expanding a snippet, for me it just replace the placeholder with registry content in vim-vsnip

edit: I mapped p to "_p maybe thats why

**Comment by hrsh7th** [comment]
If you mapping vnoremap, you can use xnoremap.

And sorry, I can't understand the above explanation.

**Comment by tami5** [comment]
Oh yah it worked, Thanks @hrsh7th, So I shouldn't map anything vnoremap?

**Comment by tami5** [comment]
I believe #106 is no longer an issue

**Comment by hrsh7th** [comment]
Yes. I think you shouldn't use `vnoremap` if you don't use `select-mode` explicitly.

**Comment by p00f** [comment]
```lua
vim.api.nvim_set_keymap("i", "<CR>", [[compe#confirm('<CR>')]], {noremap = true, silent = true, expr = true})
```
does this

https://user-images.githubusercontent.com/36493671/109071316-95708880-7719-11eb-824b-9eb04b378ab3.mp4

**Comment by hrsh7th** [comment]
If you didn't understand, you should use README.md's codes.

The above example is just wrong. You should use the following codes.

```
vim.api.nvim_set_keymap("i", vim.api.nvim_replace_termcodes("<CR>", true, true, true), [[compe#confirm('<CR>')]], {noremap = true, silent = true, expr = true})
```

I can't understand why the people trying to use Lua for mapping.
I think Lua's mapping is very ugly (and difficult to manage).

**Comment by p00f** [comment]
> If you didn't understand, you should use README.md's codes.

The readme has no lua mappings for snippet expansion

> The above example is just wrong. You should use the following codes.

I get the same results with this

**Comment by p00f** [comment]
I'm on neovim `d290da70b`

**Comment by akinsho** [comment]
@p00f I use `map("i", "<CR>", [[compe#confirm(lexima#expand('<LT>CR>', 'i'))]], opts)`, map is essentially an alias to `vim.api.keymap` and `opts` are `{noremap = true, silent = true, expr = true}` and that works fine for me 🤷🏿

**Comment by p00f** [comment]
`vim.cmd([[ inoremap <silent><expr> <CR>      compe#confirm('<CR>') ]])` has the same result

> I use lexima haven't tried a mapping without it

I use https://github.com/jiangmiao/auto-pairs, is that causing the problem?

**Comment by hrsh7th** [comment]
I checked the `auto-pairs`.

Probably, You should configure as following.

```
let g:AutoPairsMapCR = v:false
inoremap <silent><expr> <CR> compe#confirm({ 'fallback': "\<Plug>AutoPairsReturn", 'mode': '' })
```

**Comment by p00f** [comment]
As instructed in the readme for lexima, I ensure `auto-pairs` is loaded in `init.lua` using `packadd`: [init.lua](https://github.com/p00f/dotfiles/blob/main/nvim/.config/nvim/init.lua)
Then I load compe [here](https://github.com/p00f/dotfiles/blob/549c3eea6dca029b0812f5a9a7450a858df0f562/nvim/.config/nvim/lua/packages.lua#L20) and call compe_setup.lua [here](https://github.com/p00f/dotfiles/blob/549c3eea6dca029b0812f5a9a7450a858df0f562/nvim/.config/nvim/lua/packages.lua#L27)

In compe_setup.lua I did as instructed [here](https://github.com/p00f/dotfiles/blob/549c3eea6dca029b0812f5a9a7450a858df0f562/nvim/.config/nvim/lua/compe_setup.lua#L30)

Now pressing `<CR>` doesn't insert "compe#confirm ..." thankfully but snippets aren't expanded either:

(non-snippet completions work properly by pressing `<CR>` on the option)

https://user-images.githubusercontent.com/36493671/109139158-347c9b00-7781-11eb-83ef-fdb0be9b0eaf.mp4

**Comment by hrsh7th** [comment]
Do you get it to work if remove auto-pairs?

**Comment by p00f** [comment]
No (this time "compe#confim......." is inserted when Enter is pressed)

**Comment by hrsh7th** [comment]
I can't repro it even if I use `vim.cmd([[inoremap <silent><expr> <CR> compe#confirm('<CR>')]])` .

Sorry. I can't support all pair-wise plugins.
Could you create minimal config that based on https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim ?

**Comment by p00f** [comment]
huh this one works:
`init.vim`
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-compe'
Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/vim-vsnip'
call plug#end()
PlugInstall | quit

" Options or settings here.
lua require 'ls_setup'
set mouse=a
set clipboard=unnamedplus
lua require 'compe_setup_test'
```
`compe_setup_test`:
```lua
require'compe'.setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;

  source = {
    path = true;
    buffer = true;
    calc = true;
    vsnip = true;
    nvim_lsp = true;
    nvim_lua = true;
    spell = true;
    tags = true;
    snippets_nvim = true;
    treesitter = true;
  };
}
vim.cmd([[inoremap <silent><expr> <CR>      compe#confirm('<CR>')]])
```

**Comment by hrsh7th** [comment]
Sorry. I can't read fnl.

Please provide a minimal reproducible config...

**Comment by p00f** [comment]
It is not reproducible in a minimal config :neutral_face:

**Comment by hrsh7th** [comment]
Hm... Could you check `CR` mapping?
You can use `:imap` command for it.

**Comment by p00f** [comment]
![image](https://user-images.githubusercontent.com/36493671/109174730-1deb3980-77ab-11eb-8031-8fd4cd31b712.png)
Oh and it works if i don't add `vim.cmd([[inoremap <silent><expr> <CR>      compe#confirm('<CR>')]])` to compe_setup.lua and do it after opening neovim in command mode (`:inoremap <silent><expr> <CR>      compe#confirm('<CR>')`)

**Comment by hrsh7th** [comment]
So some of the plugin overwrote your `<CR>` mapping, thought

**Comment by p00f** [comment]
even without writing any mapping in compe_setup.lua, `:imap <CR>` is 
![image](https://user-images.githubusercontent.com/36493671/109177442-d1552d80-77ad-11eb-86fe-3fe88b8eabf8.png)

**Comment by hrsh7th** [comment]
Could you try with moving nvim-compe to bottom in `packages` table?

**Comment by p00f** [comment]
"compe#confirm.." is inserted again, and `:imap <CR>` is the same
I even tried
```lua
vim.cmd([[imapclear]])
vim.cmd([[inoremap <silent><expr> <CR>      compe#confirm('<CR>')]])
```

**Comment by hrsh7th** [comment]
Please remove `tpope/vim-endwise` or configure it.
https://github.com/hrsh7th/nvim-compe/issues/171

**Comment by p00f** [comment]
yeah found it in `:imap verbose <CR>` (thanks elianiva)
