### ISSUE TITLE
sumneko's lua server: no document is displayed

### ISSUE THREAD

**Issue by cloggier** [hrsh7th/nvim-compe#109]
Just to keep track of [that mention](https://github.com/hrsh7th/nvim-compe/issues/69#issuecomment-770233625) in already closed issue.

**Comment by hrsh7th** [comment]
I think you should send issue for sumneko_lua side (maybe).

https://github.com/sumneko/lua-language-server/blob/1458139721646236406825a03a21152d98753515/script/provider/capability.lua#L60

The sumneko_lua language server does not advertise `resolveProvider = true` so nvim-compe does not send request.

**Comment by cloggier** [comment]
Fixed in upstream https://github.com/sumneko/lua-language-server/commit/e3cab3193dc2deffe3a7a7d9340eea13bbf7c787.

**Comment by hrsh7th** [comment]
Thank you~!
