### ISSUE TITLE
Hide completion window if not item is selected

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#11]
Hey @hrsh7th , hope your doing great. 

It would be nice if somehow completion popup will hide when there is one completion suggestion and it the word is typed fully.
For example: Say you type the full word `function` and the completion list has only one item: `function` then it better stop suggesting. I don't know if this possible but is something that will make completion experience better. What do you think?

**Comment by hrsh7th** [comment]
I think it is not a good idea.

Because modern completion can any expandable when select and press `<CR>`.

**Comment by tami5** [comment]
Yah I guess so. Thank @hrsh7th
