### ISSUE TITLE
No longer checking for nil value in completion.lua

### ISSUE THREAD

**Issue by akinsho** [hrsh7th/nvim-compe#110]
Hi firstly thanks for all your hard work on this plugin 🚀 .

I recently updated this plugin and have now noticed I'm getting this error.
```
Error executing vim.schedule lua callback: ...te/pack/packer/start/nvim-compe/lua/compe/completion.lua:247: attempt to index a nil value
```

Looking at the most recent commit it seems that the `preselect` flicker change removed an if guard checking that `item[1]` existed before using it. It seems this value can be nil and is in my case and is now breaking/erroring whilst trying to insert text

**Comment by hrsh7th** [comment]
Thank you. I will fix it soon.

**Comment by hrsh7th** [comment]
Could you try latest master? (To be honest, it does not reproduce on my side).

**Comment by akinsho** [comment]
@hrsh7th thanks for the quick fix I think that's resolved it now 👍🏿

**Comment by akinsho** [comment]
Oh wait I spoke too soon it's back 😓

**Comment by akinsho** [comment]
It seems to be reproducible if you type in something that doesn't match

**Comment by akinsho** [comment]
![compe-bug](https://user-images.githubusercontent.com/22454918/106441719-4f097000-6472-11eb-8d6d-734ddf790749.gif)

**Comment by akinsho** [comment]
The check you added in the previous commit doesn't seem to be the same as you had before. Before you were checking if `item[1]` was nil but the check you just added ignoring the `pumvisible` stuff checks to see if `#items == 0` this seems to be the opposite of what you had? should this be `#items > 0`?

**Comment by hrsh7th** [comment]
Sorry..  I am not good at logical expressions and index operations.
I think latest master fixes this problem :pray:

**Comment by akinsho** [comment]
I think it does just tested it out 👍🏿 tried the same example from my gif and it isn't erroring anymore

**Comment by hrsh7th** [comment]
The bug report is really really helpful to me.
Thank you!
