### ISSUE TITLE
Same keybinding to open or close completion

### ISSUE THREAD

**Issue by coxackie** [hrsh7th/nvim-compe#111]
I do not know if this is a good idea, but I would like to be able to use the same key binding (for example, <C-Space>) to both invoke completion (if not open) and close it (if open). I do not see the point of having to use two different keystrokes. Could this be implemented with a function of the form `complete-or-close` or something? I am thinking of the equivalent `expand-or-jump` that vsnip has.

**Comment by hrsh7th** [comment]
I think we can realize it by `pumvisible() ? compe#close() : compe#complete()` instead.

**Comment by coxackie** [comment]
yes, of course, this works... silly me.

 however, just out of curiosity: can there be cases outside of completion that the "pop-up" menu is visible for some reason? I mean, is `pumvisible()` only referring to the completion menu? If there is no chance of confusion, then I think your suggestion is far better than writing a new function.

**Comment by hrsh7th** [comment]
The `pumvisible` only returns completion-menu's visibility.

But if you use nvim-compe with some other completion plugin, it might not work as you expexted. (I know this use-case is strange).

So you can use pumvisible for it.

Thank you for your idea.
