### ISSUE TITLE
Error whenever a buffer is opened/edited

### ISSUE THREAD

**Issue by urandom** [hrsh7th/nvim-compe#112]
I'm getting the following error when i test the plugin (HEAD):

```
Error executing vim.schedule lua callback: ....config/nvim/plugged/nvim-compe/lua/compe/completion.lua:247: attempt to index a nil value
```

This happens when a file is opened, and each time I type in it.

**Comment by hrsh7th** [comment]
Do you still have this problem?
I think it same as #110

**Comment by urandom** [comment]
After updating, the error no longer appears/
