### ISSUE TITLE
Cannot get vnip working with nvim-compe

### ISSUE THREAD

**Issue by bangn** [hrsh7th/nvim-compe#115]
First of all, thank you very much for working on such a great plugin.
I recently switch to `nvim-compe` and loving it.

Currently, I am trying to get `vsnip` working with `nvim-compe` however  there's no luck so far.

I have browse the issue/document but looks like there's no hint lead to the success attempt.
Im definitely missing something here. Could you please point me to the right direction.

Below is my `init.vim`

```
filetype off
let mapleader = "," " remap leader to comma.

call plug#begin('~/.config/nvim/bundle')

""""""""""""""""""""
" nvim-lsp
""""""""""""""""""""
Plug 'hrsh7th/nvim-compe'
Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'

call plug#end()

""""""""""""""""""""""""""""""""""""""""
" nvim-lspconfig
""""""""""""""""""""""""""""""""""""""""
lua << EOF
  local lspconfig = require('lspconfig')

  local on_attach = function(_, bufnr)
    vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
    local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end

    -- Mappings.
    local opts = { noremap=true, silent=true }
    buf_set_keymap('n', '<C-]>'    , '<cmd>lua vim.lsp.buf.definition()<CR>'            , opts)
    buf_set_keymap('n', 'gD'       , '<cmd>lua vim.lsp.buf.declaration()<CR>'           , opts)
    buf_set_keymap('n', 'gi'       , '<cmd>lua vim.lsp.buf.implementation()<CR>'        , opts)
    buf_set_keymap('n', 'gr'       , '<cmd>lua vim.lsp.buf.references()<CR>'            , opts)
    buf_set_keymap('n', 'gt'       , '<cmd>lua vim.lsp.buf.type_definition()<CR>'       , opts)
    buf_set_keymap('n', 'K'        , '<cmd>lua vim.lsp.buf.hover()<CR>'                 , opts)
  end

  local servers = {
    'jsonls',
    'rnix',
    'solargraph',
    'terraformls',
    'tsserver',
    'yamlls',
    'html',
    'dockerls',
  }

  for _, lsp in ipairs(servers) do
    lspconfig[lsp].setup {
      on_attach = on_attach,
    }
  end
EOF

""""""""""""""""""""""""""""""""""""""""
" nvim-compe
""""""""""""""""""""""""""""""""""""""""
set completeopt+=menu,menuone,noselect
inoremap <silent><expr> <C-Space> compe#complete()
inoremap <silent><expr> <C-y>     compe#confirm('<C-y>')
inoremap <silent><expr> <C-e>     compe#close('<C-e>')

lua << EOF
  require'compe'.setup({
    allow_prefix_unmatch = false;
    debug                = false;
    enabled              = true;
    min_length           = 1;
    preselect            = 'always';

    source = {
      buffer        = { enable = true };
      nvim_lsp      = { enable = true };
      path          = { enable = true };
      vsnip         = { enable = true };
    };
  });
EOF
```

**Comment by ii14** [comment]
What's exactly not working? I just tried those settings and everything seems to be working for me.
Select the snippet with `<C-N>/<C-P>` until it completes the line and press `<C-Y>`.

@hrsh7th I noticed something weird here, when `preselect` is on `always`, the completion item is selected on the popup menu visually, but it doesn't actually complete the line. Is it supposed to work that way?

**Comment by ii14** [comment]
> I noticed something weird here, when `preselect` is on `always`, the completion item is selected on the popup menu visually, but it doesn't actually complete the line. Is it supposed to work that way?

Okay, I get it now, you're just supposed to press `<CR>` or `<C-Y>` and only then it completes the line. Never mind.

**Comment by bangn** [comment]
Hi @ii14 

Thank you for your reply.

> What's exactly not working? I just tried those settings and everything seems to be working for me.
I tried create a new `test.rb` file and only `LSP` and `Buffer` shown as the source of completion (Sorry for the bad screenshot color)
![image](https://user-images.githubusercontent.com/4962863/106546997-73437a80-6560-11eb-8872-6439314cab7a.png)

I just wonder if the text that I used does not trigger `vsnip`?

**Comment by hrsh7th** [comment]
You should add `snippetSupport` for capabilities of all servers.

```
  local capabilities = vim.lsp.protocol.make_client_capabilities()
  capabilities.textDocument.completion.completionItem.snippetSupport = true
  require'lspconfig'.gopls.setup{
    capabilities = capabilities,
    on_attach = on_attach,
    init_options = {
      usePlaceholders = true,
    },
  }
```

**Comment by ii14** [comment]
It's not a completion from vsnip, but from the language server. Completions from vsnip will have a `[Vsnip]` tag.

**Comment by bangn** [comment]
I see. Thanks @ii14 and @hrsh7th.
Do you think it would be good to add it to README or wiki page?

**Comment by hrsh7th** [comment]
I think it is good to mention in README.md with `lspconfig.html.setup` is good for example.
