### ISSUE TITLE
expand placeholder

### ISSUE THREAD

**Issue by glepnir** [hrsh7th/nvim-compe#117]
like this pic show. it has placehoder in snippet preview. so would be better to expand it ?
![image](https://user-images.githubusercontent.com/41671631/106557995-fc0ce700-655d-11eb-9bb2-b9ab4388b2b3.png)

**Comment by hrsh7th** [comment]
Duplicate https://github.com/hrsh7th/nvim-compe/issues/87

Yes. I think we should improve it.

**Comment by hrsh7th** [comment]
We should expand and highlight.

**Comment by hrsh7th** [comment]
Implemented https://github.com/hrsh7th/nvim-compe/commit/d03b2b27870fac0af85b0a74d83a7867a8f66b6f
