### ISSUE TITLE
demo gif

### ISSUE THREAD

**Issue by elianiva** [hrsh7th/nvim-compe#118]
I've added several gifs showing `nvim-compe` feature in the wiki, do you think it's better if it stays there or does it belong in the readme? I noticed there's a `demo` section but it's still tbd, I'd suggest adding a link to the wiki because putting them in the readme will make it so long.

I put this here because I don't know other way to discuss this :laughing:

**Comment by tami5** [comment]
Awesome work @elianiva. I think it belongs somewhere in the readme.

**Comment by elianiva** [comment]
There are a lot of them. But now that I think about it, I guess it doesn't really matter since it's at the bottom anyway.

**Comment by hrsh7th** [comment]
!!!
Thank you very much! 

I want to add these gifs to README.md.

IMO, `auto-importing` / `magic-completion` / 'nvim_lua' / `calc` is good to add.

**Comment by elianiva** [comment]
yeah, `calc` source blows my mind, it's so cool :laughing:

**Comment by elianiva** [comment]
#119
