### ISSUE TITLE
[Feature Request]: nvim_lsp preview

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#12]
...

**Comment by hrsh7th** [comment]
my next task...

**Comment by tami5** [comment]
Thats awesome @hrsh7th looking forward!!!!

**Comment by hrsh7th** [comment]
I've finished the preparation work.
https://github.com/hrsh7th/vim-vital-vs/commit/6d81afeb7657ea31c2576158a59f4613fa41a273#diff-2630632aad0a805cfb3614720509e858fc55c3b3d6c77d0d0103e748f60329a0R8

**Comment by tami5** [comment]
@hrsh7th nice, well done!! looking forward for testing it
