### ISSUE TITLE
CR can't expand snippet with lexima

### ISSUE THREAD

**Issue by glepnir** [hrsh7th/nvim-compe#121]
works fine with delimitMate, but when I try the lexima. faield.
![finder](https://user-images.githubusercontent.com/41671631/106690030-fa99f800-660b-11eb-8812-81e60da9c32d.gif)

**Comment by hrsh7th** [comment]
@glepnir Sorry. I've improved docs.
https://github.com/hrsh7th/nvim-compe/commit/2b1612f10401663c3bac457981e74ac8491eaa61

**Comment by glepnir** [comment]
lazyload with dein on `InsertEnter` autocmd. not works..
```
hook_add : let g:lexima_no_default_rules = v:true
hook_source: call lexima#set_default_rules()
```

**Comment by hrsh7th** [comment]
Hm...
lexima.vim overwrite `<CR>` mapping automatically so we should set `compe#confirm` after lexima.set it.

I have no idea for it...

**Comment by glepnir** [comment]
It's okay .return to delimitMate this works fine

**Comment by hrsh7th** [comment]
Thank you for your point out it.

I think it is not solved but now, it was documented so I'm closing this.
