### ISSUE TITLE
[Breaking change] v3

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#122]
### Remove `Source.documentation` and use `item.info` field as documentation.

This design came from VSCode and vim both.
*** We should consider it more deeply. ***

### Add `metadata` for all source apis

Pass `metadata` that applied user settings.
It makes a breaking change to determine API.

### Remove filetypes/ignored_filetypes from metadata

#174 

### Introduce the `entry` object.

The entry.item can be used for vim.fn.complete.
The entry.data can be used for some compe related data.

This would fix #296 

### Re-design `compe.determine` return value

TBD

**Comment by hrsh7th** [comment]
I will consider migration path

**Comment by kristijanhusak** [comment]
I support these changes. 1. and 2. are really useful. 2. especially for custom sources to allow configuration.
I'm using ignored_filetypes, but I'm ok if it needs sto break. We just need to introduce some changelog I guess.

**Comment by cbarrete** [comment]
FYI https://github.com/neovim/neovim/pull/14686 was merged, which is relevant to the "idiomatic filetype handling" part.
