### ISSUE TITLE
Add option to truncate menu entries

### ISSUE THREAD

**Issue by socamacb** [hrsh7th/nvim-compe#124]
First of all thanks for this nice plugin. 

One important option for me, which is currently missing, is the ability to truncate the menu entries. When programming in C and C++ the entries can get quite long. All other well known completion plugins provide a way to define a max length option for each entry section.

In coc.nvim:
```json
"suggest.labelMaxLength": 55,
"suggest.detailMaxLength": 30,
```

In completion.nvim: (https://github.com/nvim-lua/completion-nvim/issues/245)
```lua
vim.g.completion_abbr_length = 55 -- completion item (left)
vim.g.completion_menu_length = 30 -- extra info for completion item (right)
```

Current situation with `nvim-compe`:
![compe](https://user-images.githubusercontent.com/78479152/106739607-a1d15c00-6619-11eb-8b74-30e2b183e0a4.png)

Current situation with `completion-nvim`:
![completion-nvim](https://user-images.githubusercontent.com/78479152/106739712-bca3d080-6619-11eb-9715-8cd8e8bc8a64.png)

**Comment by cloggier** [comment]
Try setting up `pumheight`. It should limit completion menu's height.

**Comment by socamacb** [comment]
The height is not the problem. The problem is the width of the entries.

**Comment by hrsh7th** [comment]
Duplicate #55 
Thank you for pointing out that other plugins features.

**Comment by hrsh7th** [comment]
BTW, I don't want to add many options as much as possible.
Because IMO, it makes buggy software.
(If the option is really needed, I think it is ok to add)

**Comment by socamacb** [comment]
Without truncation it is impossible to see useful information like the LSP `kind` and the `detail` field. When working with an editor width  of max. 120 character I would not be able to use your plugin. The reason for max. 120 character is that I use a tiling window manager with a browser on 1 half of the screen and Neovim on the other half.

`nvim-compe` in an editor with max. 120 character:
![20210203_130906_grim](https://user-images.githubusercontent.com/78479152/106745575-95510180-6621-11eb-87f1-8447acb5185c.png)

`completion-nvim` in an editor with max. 120 character:
![20210203_130955_grim](https://user-images.githubusercontent.com/78479152/106745643-b44f9380-6621-11eb-8dfe-c84f5688c928.png)

In `completion-nvim` I can cleary see if the entry is of type `Function` or `Class` and would the return type of a given function is.
