### ISSUE TITLE
Provide more completion entry information

### ISSUE THREAD

**Issue by socamacb** [hrsh7th/nvim-compe#125]
Currently the detailed information are missing from the completion popup.

Current situation in `nvim-compe`:
![20210203_122000_grim](https://user-images.githubusercontent.com/78479152/106740195-5c615e80-661a-11eb-8c6f-ce99f4813ddc.png)

Current situation in `completion-nvim`:
![20210203_122023_grim](https://user-images.githubusercontent.com/78479152/106740221-671bf380-661a-11eb-9676-90f75080d478.png)

These information are really helpful and it would be appreciated if `nvim-compe` could also provides these information.

**Comment by hrsh7th** [comment]
It's reasonable. But I don't know how it does.
I will investigate later.

**Comment by hrsh7th** [comment]
Ah. It might be `detail` field... Sorry. In gopls, it is very big and annoying.
So current implementation is intentional.

**Comment by socamacb** [comment]
With https://github.com/hrsh7th/nvim-compe/issues/124 the `detail` field could also be truncated which would prevent long entries from language server.

Alternatively there could be an option to define if the `detail` field should be populated or not.

**Comment by hrsh7th** [comment]
```viml
let g:compe = {}
let g:compe.max_abbr_width = 12
let g:compe.max_kind_width = 0
```

**Comment by elianiva** [comment]
I've implemented this, but do we need `max_kind_width` ?  Since in nvim-compe, all `kind`s are short like `Function`, `Variable`, etc. I don't see something like `Function  long double` or `Function  [2 overloads]` in nvim-compe.

**Comment by hrsh7th** [comment]
@elianiva It is. I've implemented on width branch too. But I noticed your points. So I'm stopping now.

**Comment by socamacb** [comment]
I think you guys are mixing #125 with #124. The purpose of this ticket was to add the `detail` field which will provide the `long double` and `[2 overloads]` entries. @hrsh7th did not like the `detail` field from gopls. That's why I proposed an option to disable the `detail` field if not needed.

The `kind` field (Function/Class/Reference) *does not* need an option for the width in my opinion.

`abbr` and `detail` would be enough like https://github.com/nvim-lua/completion-nvim/issues/245

**Comment by elianiva** [comment]
ah, I see. Sorry, I got a bit confused earlier :laughing:

**Comment by hrsh7th** [comment]
No. vim has only `abbr`/`kind`/`menu` for popupmenu contents.

The abbr and menu already used. We can use only the `kind` field.

But kind field already used for LSP items...

**Comment by hrsh7th** [comment]
Anyway, If you want to use `max_abbr_width/max_kind_width`, you can use `width` branch.

I'm considering experience.

**Comment by elianiva** [comment]
~~What if we use the kind field but concatenate the detail~~ That sounds hacky, not a good idea.

**Comment by socamacb** [comment]
If I interpret the `completion-nvim` code correctly they use the `kind` field for the LSP kind (Function/Class) and the `menu` field for the `detail` field:

https://github.com/nvim-lua/completion-nvim/blob/aa5cc61d24ad1ef149da004a1d9c690beec00acf/lua/completion/source/lsp.lua#L115

https://github.com/nvim-lua/completion-nvim/blob/aa5cc61d24ad1ef149da004a1d9c690beec00acf/lua/completion/source/lsp.lua#L128

**Comment by elianiva** [comment]
but we already use `menu` section for source label like `[LSP]`, `[Buffers]`, `[Vsnip]`, etc :thinking:

**Comment by socamacb** [comment]
Tested the `width` branch and the truncation for the `abbr` is really nice and exactly what I wanted in #124 ❤️ 

The merged information in the `kind` field looks really ugly:

![20210203_153721_grim](https://user-images.githubusercontent.com/78479152/106762026-b6bbe880-6635-11eb-8079-748afcd4fd13.png)

I could gladly do without the extra information from the LSP (`int`/`[2 overloads]`)  if the truncation for the `abbr` field stays.

**Comment by hrsh7th** [comment]
Yes. I think `abbr` is good behavior too. 

Currently, nvim-compe uses `CompletionItemKind` as `vim's kind` field (that defined in `LSP spec`).

In this issue, you want to add `CompletionItem#detail` field to `vim's kind` field.

Hm....

**Comment by socamacb** [comment]
The truncation of the `abbr` field is more important for me. 

We can close this issue if `CompletionItem#detail` is not normally indented to be show in the completion popup. Just came from the `completion-nvim` plugin and saw that this was different. But if `completion-nvim` uses some hacks to provided such functionality which are not indented than I would not follow this feature any longer.

We should try to stay as Neovim conformant as possible without hacks. 😄

**Comment by hrsh7th** [comment]
The width branch has merged now.
