### ISSUE TITLE
Check for 'completeopt' should not use a hardcoded string

### ISSUE THREAD

**Issue by socamacb** [hrsh7th/nvim-compe#126]
With my current configuration I get always an error message that I have to set the `completeopt` option to a specific string.

Current configuration:
```
completeopt = "menu,menuone,noinsert,noselect"
```

Excepted from the plugin:
```
completeopt = "menu,menuone,noselect"
```

The plugin should not throw an error with my current configuration as all needed options are set but the problem is the validation logic https://github.com/hrsh7th/nvim-compe/blob/f2573c9dd52be7e7ced176a6375766758cf646be/autoload/compe.vim#L50

**Comment by hrsh7th** [comment]
I received many issues with `completeopt` so I added explicit validation for it.

I don't know that `"menu,menuone,noinsert,noselect"` is worked.
If you want to remove it, please suggest the correct way (not just removed.)

**Comment by socamacb** [comment]
I would not remove the check. It would be better if the validation logic checks for the required entries in the option string.

Some like: (pseudo-code)
```cpp
if completeopt contains "menu" && completeopt contains "menuone" && completeopt contains "noselect"
...
end
```

That way the order of the options is no longer relevant and other user like me can add additional entries.

**Comment by hrsh7th** [comment]
I don't know the nvim-compe will work correctly even if the user set `noinsert` to completeopt.

Do you know that?

**Comment by socamacb** [comment]
Had no problem with the `noinsert` entry set. The only problem was the error message from `nvim-compe` to change `completeopt`. After pressing Enter `nvim-compe` worked completely fine without any problems.

**Comment by hrsh7th** [comment]
OK. I will change the implementation.
