### ISSUE TITLE
Buffer source is limited to words > 3 character

### ISSUE THREAD

**Issue by socamacb** [hrsh7th/nvim-compe#127]
I would expect from a buffer source to get all words in the current buffer independent of the word length.
But currently only words with more than 3 character are supported:

```lua
if #word > 3 and string.sub(word, #word) ~= '-' then
  table.insert(words, word)
end
```
https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe_buffer/buffer.lua#L77

**Comment by hrsh7th** [comment]
Sorry. I think the current behavior is better.

**Comment by cloggier** [comment]
This could be configurable once sources configuration is implemented.

**Comment by socamacb** [comment]
Not the most important issue for me but it was for the first moment really unexpected as all other plugins show each word in the buffer independent of the length.

I close this issue but it would be good to document this behavior for the `Buffer` source.
