### ISSUE TITLE
[Feature request]: keep completion window on backspace

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#13]
Hey @hrsh7th, hope your having a great weekend so far.

I wonder if it possible to keep completion window refreshed on backspace. I found myself trying to narrow down something and hitting wrong letter then hit backspace and the completion gone :D.

I'd appreciate it if this feature would be something you'd consider adding an option for.

**Comment by hrsh7th** [comment]
Could you provide a animated gif?

Currently, nvim-compe will trigger completion on backspace.
So I don't know `the completion gone` means.

**Comment by tami5** [comment]
Oh, thats wired, it doesn't trigger on backspace for me, here's a gif https://asciinema.org/a/0ZTrKJdceOFsvqEoKOe3Irpuu

**Comment by hrsh7th** [comment]
Thank you.
I found the cause at your vimrc.

It shoud fix nvim-compe side, I think.

**Comment by tami5** [comment]
Hmm what did you find that may caused this bug?

**Comment by hrsh7th** [comment]
Probably, the caise is <Plug>(sexp...)

**Comment by hrsh7th** [comment]
I've fixed it but it has side-effect...

Currently, nvim-compe display pum unexpectedly after confirm completion...

**Comment by hrsh7th** [comment]
the problem should be fixed now.

Could you test with latest master?

**Comment by tami5** [comment]
It is fixed now @hrsh7th, works great like any plugin I experienced :D
