### ISSUE TITLE
Disable completion on trigger characters

### ISSUE THREAD

**Issue by phelipetls** [hrsh7th/nvim-compe#130]
This sometimes freezes my editing, I think because tsserver is slow on my system.

I'd like to disable some or all trigger characters. Thank you.

**Comment by elianiva** [comment]
You could disable it from nvim lsp setup, similar to what I did for svelteserver.

https://github.com/elianiva/dotfiles/blob/c7d50026c495da2b0ba6fd44879a7052551a8a51/nvim/.config/nvim/lua/modules/lsp/init.lua#L165-L167

**Comment by phelipetls** [comment]
That's smart! Thanks.

**Comment by hrsh7th** [comment]
Thank you for your request. It's can be closed.
