### ISSUE TITLE
Rust Magic Completions

### ISSUE THREAD

**Issue by sharksforarms** [hrsh7th/nvim-compe#135]
Hey I've been investigating nvim-compe for a sample config in https://github.com/sharksforarms/vim-rust

I can't seem to get rust magic completion to work, everything else in the LSP seems ok. Any ideas?

Here's the config: https://github.com/sharksforarms/vim-rust/blob/master/neovim-init-lsp-compe.vim

![Peek 2021-02-04 10-13](https://user-images.githubusercontent.com/10912917/106913167-b8d38500-66d1-11eb-9655-0a8e4d1158a8.gif)

**Comment by elianiva** [comment]
I *think* you need vsnip (because rust magic completion is more or less a snippet). Maybe try to install that?

**Comment by sharksforarms** [comment]
> I _think_ you need vsnip (because rust magic completion is more or less a snippet). Maybe try to install that?

I gave that a try and it didn't change the results

**Comment by onsails** [comment]
For me .dbg, .ref, .call and friends are getting expanded with the follwing config:
```lua
require'compe'.setup {
	  enabled = true;
	  debug = false;
	  min_length = 1;
	  preselect = 'enable';
	  allow_prefix_unmatch = false;
	
	  source = {
	    path = true;
	    buffer = true;
	    vsnip = true;
	    nvim_lsp = true;
	  };
	}
	
	vim.api.nvim_exec([[
	    set completeopt=menu,menuone ",noselect
	    inoremap <silent><expr> <C-Space> compe#complete()
	    inoremap <silent><expr> <CR>      compe#confirm({ 'keys': "\<Plug>delimitMateCR", 'mode': '' })
	    inoremap <silent><expr> <C-e>     compe#close('<C-e>')
	
	    inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
	    inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
	    ]], false)
```

**Comment by etrnal70** [comment]
> > I _think_ you need vsnip (because rust magic completion is more or less a snippet). Maybe try to install that?
> 
> I gave that a try and it didn't change the results

I think you use it wrong. Try to create a variable and then type 
```
var.match 
```
It should then offer you a snippet expansion

**Comment by onsails** [comment]
Just checked var.match with my configuration – works correctly.

**Comment by hrsh7th** [comment]
Probably, you should set `snippetSupport = true`.

```
  local capabilities = vim.lsp.protocol.make_client_capabilities()
  capabilities.textDocument.completion.completionItem.snippetSupport = true

  require'lspconfig'.rust_analyzer.setup {
    capabilities = capabilities,
  }
```

**Comment by onsails** [comment]
> Probably, you should set `snippetSupport = true`.
> 
> ```
>   local capabilities = vim.lsp.protocol.make_client_capabilities()
>   capabilities.textDocument.completion.completionItem.snippetSupport = true
> 
>   require'lspconfig'.rust_analyzer.setup {
>     capabilities = capabilities,
>   }
> ```

that's exactly what I have in my config :+1:

**Comment by sharksforarms** [comment]
> Probably, you should set `snippetSupport = true`.
> 
> ```
>   local capabilities = vim.lsp.protocol.make_client_capabilities()
>   capabilities.textDocument.completion.completionItem.snippetSupport = true
> 
>   require'lspconfig'.rust_analyzer.setup {
>     capabilities = capabilities,
>   }
> ```

Thanks! This made a difference. I now have the snippet completions showing up for the LSP. Did I miss something about this in the docs? Also vsnip is required? I have snippets.nvim.. not a big deal, but wasn't obvious to me in the docs.

Without vsnip:
![Peek 2021-02-04 13-31](https://user-images.githubusercontent.com/10912917/106938733-5c7e5e80-66ed-11eb-849f-062f55be4d2a.gif)

With vsnip:
![Peek 2](https://user-images.githubusercontent.com/10912917/106938990-a9facb80-66ed-11eb-827d-ce9049e7d556.gif)

**Comment by onsails** [comment]
@sharksforarms how did configure this icons like this arrow between `while~` and `[LSP]`?

**Comment by sharksforarms** [comment]
I added this to my `on_attach` function

```lua
local nvim_lsp = require('lspconfig')
local protocol = require('vim.lsp.protocol')

local on_attach = function(client)
  protocol.CompletionItemKind = {
    '';   -- Text          = 1;
    '';   -- Method        = 2;
    'ƒ';   -- Function      = 3;
    '';   -- Constructor   = 4;
    '識';  -- Field         = 5;
    '';   -- Variable      = 6;
    '';   -- Class         = 7;
    'ﰮ';   -- Interface     = 8;
    '';   -- Module        = 9;
    '';   -- Property      = 10;
    '';   -- Unit          = 11;
    '';   -- Value         = 12;
    '了';  -- Enum          = 13;
    '';   -- Keyword       = 14;
    '﬌';   -- Snippet       = 15;
    '';   -- Color         = 16;
    '';   -- File          = 17;
    '渚';  -- Reference     = 18;
    '';   -- Folder        = 19;
    '';   -- EnumMember    = 20;
    '';   -- Constant      = 21;
    '';   -- Struct        = 22;
    '鬒';  -- Event         = 23;
    'Ψ';   -- Operator      = 24;
    '';   -- TypeParameter = 25;
  }

  -- ...
end

nvim_lsp.rust_analyzer.setup({
  on_attach=on_attach,
  capabilities=capabilities,
--- ...
})
```

**Comment by onsails** [comment]
very nice, thank you. worth to be a tiny plugin.

> I added this to my `on_attach` function
> 
> ```lua
> local nvim_lsp = require('lspconfig')
> local protocol = require('vim.lsp.protocol')
> 
> local on_attach = function(client)
>   protocol.CompletionItemKind = {
>     '';   -- Text          = 1;
>     '';   -- Method        = 2;
>     'ƒ';   -- Function      = 3;
>     '';   -- Constructor   = 4;
>     '識';  -- Field         = 5;
>     '';   -- Variable      = 6;
>     '';   -- Class         = 7;
>     'ﰮ';   -- Interface     = 8;
>     '';   -- Module        = 9;
>     '';   -- Property      = 10;
>     '';   -- Unit          = 11;
>     '';   -- Value         = 12;
>     '了';  -- Enum          = 13;
>     '';   -- Keyword       = 14;
>     '﬌';   -- Snippet       = 15;
>     '';   -- Color         = 16;
>     '';   -- File          = 17;
>     '渚';  -- Reference     = 18;
>     '';   -- Folder        = 19;
>     '';   -- EnumMember    = 20;
>     '';   -- Constant      = 21;
>     '';   -- Struct        = 22;
>     '鬒';  -- Event         = 23;
>     'Ψ';   -- Operator      = 24;
>     '';   -- TypeParameter = 25;
>   }
> 
>   -- ...
> end
> 
> nvim_lsp.rust_analyzer.setup({
>   on_attach=on_attach,
>   capabilities=capabilities,
> --- ...
> })
> ```

very nice, thank you. worth to be a tiny plugin.

**Comment by onsails** [comment]
> I added this to my `on_attach` function
> 
> ```lua
> local nvim_lsp = require('lspconfig')
> local protocol = require('vim.lsp.protocol')
> 
> local on_attach = function(client)
>   protocol.CompletionItemKind = {
>     '';   -- Text          = 1;
>     '';   -- Method        = 2;
>     'ƒ';   -- Function      = 3;
>     '';   -- Constructor   = 4;
>     '識';  -- Field         = 5;
>     '';   -- Variable      = 6;
>     '';   -- Class         = 7;
>     'ﰮ';   -- Interface     = 8;
>     '';   -- Module        = 9;
>     '';   -- Property      = 10;
>     '';   -- Unit          = 11;
>     '';   -- Value         = 12;
>     '了';  -- Enum          = 13;
>     '';   -- Keyword       = 14;
>     '﬌';   -- Snippet       = 15;
>     '';   -- Color         = 16;
>     '';   -- File          = 17;
>     '渚';  -- Reference     = 18;
>     '';   -- Folder        = 19;
>     '';   -- EnumMember    = 20;
>     '';   -- Constant      = 21;
>     '';   -- Struct        = 22;
>     '鬒';  -- Event         = 23;
>     'Ψ';   -- Operator      = 24;
>     '';   -- TypeParameter = 25;
>   }
> 
>   -- ...
> end
> 
> nvim_lsp.rust_analyzer.setup({
>   on_attach=on_attach,
>   capabilities=capabilities,
> --- ...
> })
> ```

crafted a plugin for it: https://github.com/onsails/lspkind-nvim

> I added this to my `on_attach` function
> 
> ```lua
> local nvim_lsp = require('lspconfig')
> local protocol = require('vim.lsp.protocol')
> 
> local on_attach = function(client)
>   protocol.CompletionItemKind = {
>     '';   -- Text          = 1;
>     '';   -- Method        = 2;
>     'ƒ';   -- Function      = 3;
>     '';   -- Constructor   = 4;
>     '識';  -- Field         = 5;
>     '';   -- Variable      = 6;
>     '';   -- Class         = 7;
>     'ﰮ';   -- Interface     = 8;
>     '';   -- Module        = 9;
>     '';   -- Property      = 10;
>     '';   -- Unit          = 11;
>     '';   -- Value         = 12;
>     '了';  -- Enum          = 13;
>     '';   -- Keyword       = 14;
>     '﬌';   -- Snippet       = 15;
>     '';   -- Color         = 16;
>     '';   -- File          = 17;
>     '渚';  -- Reference     = 18;
>     '';   -- Folder        = 19;
>     '';   -- EnumMember    = 20;
>     '';   -- Constant      = 21;
>     '';   -- Struct        = 22;
>     '鬒';  -- Event         = 23;
>     'Ψ';   -- Operator      = 24;
>     '';   -- TypeParameter = 25;
>   }
> 
>   -- ...
> end
> 
> nvim_lsp.rust_analyzer.setup({
>   on_attach=on_attach,
>   capabilities=capabilities,
> --- ...
> })
> ```

wrapped it up: https://github.com/onsails/lspkind-nvim

**Comment by runiq** [comment]
Do these work *only* if I have vim-vsnip installed, or can I use snippets.vnim for snippets completion too? I'd like to use only one snippets engine if possible, and the flexibility of snippets.nvim's format is something I don't want to miss anymore…

**Comment by hrsh7th** [comment]
Feel free to create PR.
We can use snippets.nvim as snippet engine.

**Comment by runiq** [comment]
I'll take a stab at it :)
