### ISSUE TITLE
Set completionItemKind for [Buffer] 

### ISSUE THREAD

**Issue by beauwilliams** [hrsh7th/nvim-compe#140]
Hi, wondering if this is possible right now. I looked through the code and noticed it did not seem to be there or I am not reading it correctly.

The reason I ask is that I have set completionItemKind for lsp, and would like to be able to set them for buffer also for consistency

Thanks!

**Comment by hrsh7th** [comment]
Sorry. I can't understand.
When we add kind for buffer candidates, what is we show kind?

**Comment by cloggier** [comment]
@beauwilliams wants to set up label for completion item. This is I think done with completion.nvim in a way that makes one think that this is part of LSP label. I am not sure if it is or not but the way to achieve that with compe is to use

```
source = {
  buffer = {menu = 'Whatever you [want]'}
}

**Comment by beauwilliams** [comment]
Thanks cloggier, that is in fact what I meant :)

Yesterday I did manage to customise the label in the source code after some digging. However this is the issue I am finding. When trying to customise the label. It seems the solution you posted achieves that same effect

![image](https://i.ibb.co/Stk6XvJ/Screen-Shot-2021-02-06-at-8-09-13-am.png)

**Comment by cloggier** [comment]
Ah, I see. Will leave it with @hrsh7th as it might require code changes to achieve the effect you want.

**Comment by beauwilliams** [comment]
The main reason I ask is that I would like to, if possible make this completion list look a little more consistent. It's only a cosmetic thing :) 

From memory I noticed in the code that there might be an offset for these kind labels, so I was wondering how we might be able to customise them. It looks like lsp might be the only source that allows for that for now but might be wrong

![example](https://i.ibb.co/pKTK4Hn/Screen-Shot-2021-02-06-at-8-14-52-am.png)

**Comment by elianiva** [comment]
We could probably make the `kind` field customisable through the source config. It shouldn't be that hard, I don't personally use it though.

**Comment by beauwilliams** [comment]
This would make for a great addition at least in my opinion 😀 Guess we can see if other people have this request too

**Comment by cloggier** [comment]
Out of interest. Would go in there?

**Comment by beauwilliams** [comment]
Good point @ cloggier, there is not really an appropriate default text I can think of right now
