### ISSUE TITLE
how to setup the tab completion? 

### ISSUE THREAD

**Issue by rustiever** [hrsh7th/nvim-compe#141]
can you help me pls, coz I'm new to Neovim,
like I want after trigger of completion I want to navigate through tab and S-tab instead of C-n and C-p

**Comment by cloggier** [comment]
You can use something like:

```viml
inoremap <silent><expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
```
From top of my head, so might not work as is. I have the same but in lua, are you interested in lua version?

**Comment by David-Else** [comment]
Awesome @cloggier ! I was just wondering why TAB did not work. Please can it be added to the README? It is what most people will expect to work out of the box :)

**Comment by sblumentritt** [comment]
I am currently using the following function which was taken from `completion-nvim`:

```lua
function smart_tab()
    if vim.fn.pumvisible() ~= 0 then
        vim.api.nvim_eval([[feedkeys("\<c-n>", "n")]])
        return
    end

    local col = vim.fn.col(".") - 1
    if col == 0 or vim.fn.getline("."):sub(col, col):match("%s") then
        vim.api.nvim_eval([[feedkeys("\<tab>", "n")]])
        return
    end

    vim.fn["compe#complete"]();
end
```

The only problem with this approach is that `<c-n>` misbehaves when `nvim-compe` has to expand a snippet. For example:

![20210205_224004_grim](https://user-images.githubusercontent.com/78555315/107092054-1ca99b00-6803-11eb-95ac-765d9410f4bc.png)

`<c-n>` only expands to `[` and a call to `compe#confirm('<cr>')` is needed to correctly expand the entry.
----
I have not found a solution to replace the `<c-n>` call with a `compe#confirm('<cr>')` call.

**Comment by rustiever** [comment]
> You can use something like:
> 
> ```viml
> inoremap <silent><expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
> inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
> ```
> 
> From top of my head, so might not work as is. I have the same but in lua, are you interested in lua version?

yes can share that pls

**Comment by rustiever** [comment]
> I am currently using the following function which was taken from `completion-nvim`:
> 
> ```lua
> function smart_tab()
>     if vim.fn.pumvisible() ~= 0 then
>         vim.api.nvim_eval([[feedkeys("\<c-n>", "n")]])
>         return
>     end
> 
>     local col = vim.fn.col(".") - 1
>     if col == 0 or vim.fn.getline("."):sub(col, col):match("%s") then
>         vim.api.nvim_eval([[feedkeys("\<tab>", "n")]])
>         return
>     end
> 
>     vim.fn["compe#complete"]();
> end
> ```
> 
> The only problem with this approach is that `<c-n>` misbehaves when `nvim-compe` has to expand a snippet. For example:
> 
> ![20210205_224004_grim](https://user-images.githubusercontent.com/78555315/107092054-1ca99b00-6803-11eb-95ac-765d9410f4bc.png)
> 
> `<c-n>` only expands to `[` and a call to `compe#confirm('<cr>')` is needed to correctly expand the entry.
> 
> I have not found a solution to replace the `<c-n>` call with a `compe#confirm('<cr>')` call.

yes even I had that problem, but I mapped dedicated key to expand the snippet, if possible pls resolve that issue

**Comment by David-Else** [comment]
@hrsh7th I am really confused about why we need a huge amount of code https://github.com/hrsh7th/nvim-compe#how-to-use-tab-to-navigate-completion-menu when:
```
  inoremap <silent><expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
  inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
```
Seems to work perfectly? Is there something I don't understand? I am using Neovim 0.5, is it a backward compatibility thing?

**Comment by hrsh7th** [comment]
Why you are confusing?
If your setting works perfectly, you have not to confuse, I think.

It is not for backward compatibility.

**Comment by David-Else** [comment]
I am confused as I don't understand vim script or Lua and would like to use the 'official' settings as I don't really know what I am doing. Why not just suggest users add:
```
  inoremap <silent><expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
  inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
```
Unless there is some problem I am not aware of? Thanks!

**Comment by cloggier** [comment]
There is no problem. It is all about functionality you expect.

Your mappings will check if completion menu is visible (currently displayed) and instruct nvim to use `<C-p>` and `<C-n>` to navigate that menu, otherwise it just sends (I guess) defaults for those keys.

Example from readme extends that functionality. It will also check if snippet expansion is active and if so it will then remap `<tab>` and `<s-tab>` keys to jump between placeholders. It also checks if cursor is on word (if not in completion menu or snippet) in which case it will trigger completion.

There is no 'official' setting, it's just example usage/integration with another plugin. I suggest you use mapping you have until you reach a moment when you think that you would also like your tab do perform some other function under specific circumstance.

**Comment by hrsh7th** [comment]
Thank you very much.
In my english skill, this explanation was too hard.

**Comment by PopeRigby** [comment]
> You can use something like:
> 
> ```viml
> inoremap <silent><expr> <TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
> inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
> ```
> 
> From top of my head, so might not work as is. I have the same but in lua, are you interested in lua version?

@gegoune I'd be interested in the Lua version

**Comment by gegoune** [comment]
@PopeRigby 
```lua
_G.tab_complete = function()
  if vim.fn.pumvisible() == 1 then
    return t '<C-n>'
  elseif luasnip.expand_or_jumpable() then
    return t '<Plug>luasnip-expand-or-jump'
  elseif check_back_space() then
    return t '<Tab>'
  else
    return vim.fn['compe#complete']()
  end
end

_G.s_tab_complete = function()
  if vim.fn.pumvisible() == 1 then
    return t '<C-p>'
  elseif luasnip.jumpable(-1) then
    return t '<Plug>luasnip-jump-prev'
  else
    return t '<S-Tab>'
  end
end

map({ 'i', 's' }, '<Tab>', 'v:lua.tab_complete()', { expr = true, noremap = false })
map({ 'i', 's' }, '<S-Tab>', 'v:lua.s_tab_complete()', { expr = true, noremap = false })
```
Use default mapping API in place of my custom map. It just iterates over modes so I don't have to specify four mappings here.
Tab functions also integrate luasnip which is something you might now want if you are not using that plugin, or don't want your tab to work like that.

**Comment by PopeRigby** [comment]
I'm guessing you have a custom `map` function?

**Comment by gegoune** [comment]
Yes, I do, sorry if I wasn't clear enough in my description. You can just use `vim.api.nvim_set_keymap` instead.

**Comment by PopeRigby** [comment]
Thanks!

**Comment by kaykhancheckpoint** [comment]
I'm having an issue where tab completion only works in my nvim project after i do :source, but its not working anywhere else, just adds a tab. Any ideas why this might be?

**Comment by alex-ross** [comment]
I dont' know if this is solved fixed for you. But I had issues with this as well and Tab didn't do anything at all for me.

This did work for mer at the end.

```lua
local cmp = require('cmp')
local luasnip = require('luasnip')

cmp.setup({
  snippet = {
    expand = function(args)
      require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
    end,
  },

  completion = {
    completeopt = 'menu,menuone,noselect',
  },

  mapping = {
    ['<C-p>'] = cmp.mapping.select_prev_item(),
    ['<C-n>'] = cmp.mapping.select_next_item(),
    ['<C-b>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),
    ['<C-f>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),
    ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),
    ['<C-y>'] = cmp.config.disable, -- Specify `cmp.config.disable` if you want to remove the default `<C-y>` mapping.
    ['<C-e>'] = cmp.mapping({
        i = cmp.mapping.abort(),
        c = cmp.mapping.close(),
      }),
    ["<CR>"] = cmp.mapping.confirm({
        behavior = cmp.ConfirmBehavior.Replace,
        select = true,
      }),
    ['<Tab>'] = function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      elseif luasnip.expand_or_jumpable() then
        luasnip.expand_or_jump()
      else
        fallback()
      end
    end,
    ['<S-Tab>'] = function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      elseif luasnip.jumpable(-1) then
        luasnip.jump(-1)
      else
        fallback()
      end
    end,
  },

  sources = cmp.config.sources({
      { name = 'nvim_lsp' },
      { name = 'luasnip' }, -- For luasnip users.
    }, {
      { name = 'buffer' },
    })
})
```
