### ISSUE TITLE
completion doesn't import the respective packages or modules

### ISSUE THREAD

**Issue by rustiever** [hrsh7th/nvim-compe#143]
im using Golang(gopls server)

**Comment by hrsh7th** [comment]
You should provide detailed information if you want to solve problem (e.g. animated gif, repro steps, your settings).

**Comment by rustiever** [comment]
ok

**Comment by rustiever** [comment]
my lsp settings
```
require'compe'.setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  allow_prefix_unmatch = false;

  source = {
    path = true;
    buffer = true;
    calc = true;
    vsnip = true;
    nvim_lsp = true;
    nvim_lua = true;
    spell = true;
    tags = true;
    snippets_nvim = true;
    treesitter = true;
  };
}
local lspconfig = require 'lspconfig'
local saga = require 'lspsaga'

saga.init_lsp_saga()

lspconfig.gopls.setup {
  cmd = {"gopls", "serve"},
  settings = {
    gopls = {
      analyses = {
        unusedparams = true,
      },
      staticcheck = true,
    },
  },
}
```

**Comment by rustiever** [comment]
https://user-images.githubusercontent.com/60929919/107116587-5e395500-689a-11eb-8d1b-abcb385dd8b3.mov

**Comment by hrsh7th** [comment]
It seems to not map `compe#confirm`

**Comment by rustiever** [comment]
means?

how to check whether I mapped or not?

**Comment by cloggier** [comment]
@hrsh7th Should we add FAQ example of CR mapping to readme?

**Comment by hrsh7th** [comment]
@rustiever I checked it with your animated gif. In the gif, the newline had been inserted when you press `<CR>` (if `compe#confirm` mapping is available, it would not happen)

**Comment by rustiever** [comment]
one more thing is whenever complete the functions or methods It doesn't complete it with parentheses

https://user-images.githubusercontent.com/60929919/107122316-137d0480-68bd-11eb-9f77-79d062e3bc9b.mov

**Comment by hrsh7th** [comment]
Please your full config... it seems vim-go installed

**Comment by rustiever** [comment]
[configs](https://github.com/rustiever/dots)

**Comment by hrsh7th** [comment]
Your config has no `compe#confirm` mapping. Please read the docs.

**Comment by rustiever** [comment]
I updated can you check pls now

**Comment by hrsh7th** [comment]
Hm... current config seems correct. I will investigate it .

**Comment by hrsh7th** [comment]
@rustiever By the way, this problem still exists latest nvim-compe?

**Comment by rustiever** [comment]
yes @hrsh7th

**Comment by hrsh7th** [comment]
@rustiever Sorry. I'm cloning your config but I can't understand your config (It has `lua require'plugins'` but `plugins` directory does not exists...)


So could you provide minimal reproducible config based on https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim ?

**Comment by rustiever** [comment]
I'm using the packer plugin manager, and for this `lua require'plugins'` line in `lua` folder configs are there

**Comment by rustiever** [comment]
`https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim` how to use this to reproduce without affecting my current configs?

**Comment by elianiva** [comment]
`nvim -u minimal.vim`

**Comment by rustiever** [comment]
> > https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim how to use this to reproduce without affecting my current configs?
> 
> `nvim -u minimal.vim`

whether minimal.vim from current directory or I should save anywhere else?

**Comment by elianiva** [comment]
> whether minimal.vim from current directory or I should save anywhere else?

yes, you should save the file locally

**Comment by rustiever** [comment]
`if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-compe'
call plug#end()
PlugInstall | quit

" Options or settings here.
" lua require ('lsp-config')

lua << EOF 
require'compe'.setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  allow_prefix_unmatch = false;

  source = {
    path = true;
    buffer = true;
    calc = true;
    vsnip = true;
    nvim_lsp = true;
    nvim_lua = true;
    spell = true;
    tags = true;
    snippets_nvim = true;
    treesitter = true;
  };
}
local lspconfig = require 'lspconfig'
local saga = require 'lspsaga'

saga.init_lsp_saga()

lspconfig.gopls.setup {
  cmd = {"gopls", "serve"},
  settings = {
    gopls = {
      analyses = {
        unusedparams = true,
      },
      staticcheck = true,
    },
  },
}

EOF 
`

**to reproduce**

**Comment by hrsh7th** [comment]
@rustiever I say again, your reproducible config has no `compe#confirm` mapping.

I have no time to support the user who does't read README.md and instructions.

**Comment by rustiever** [comment]
> @rustiever I say again, your reproducible config has no `compe#confirm` mapping.
> 
> I have no time to support the user who does't read README.md and instructions.

terribly sorry for the trouble I'm causing you

**Comment by rustiever** [comment]
`if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-compe'
call plug#end()
PlugInstall | quit

" Options or settings here.
" lua require ('lsp-config')

lua << EOF 
require'compe'.setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  allow_prefix_unmatch = false;

  source = {
    path = true;
    buffer = true;
    calc = true;
    vsnip = true;
    nvim_lsp = true;
    nvim_lua = true;
    spell = true;
    tags = true;
    snippets_nvim = true;
    treesitter = true;
  };
}
local lspconfig = require 'lspconfig'
local saga = require 'lspsaga'

saga.init_lsp_saga()

lspconfig.gopls.setup {
  cmd = {"gopls", "serve"},
  settings = {
    gopls = {
      analyses = {
        unusedparams = true,
      },
      staticcheck = true,
    },
  },
}

EOF 

set completeopt=menuone,noselect

inoremap <silent><expr> <C-Space> compe#complete()
inoremap <silent><expr> <CR>      compe#confirm('<CR>')
inoremap <silent><expr> <C-e>     compe#close('<C-e>')
inoremap <silent><expr> <C-f>     compe#scroll({ 'delta': +4 })
inoremap <silent><expr> <C-d>     compe#scroll({ 'delta': -4 })
`

**Comment by rustiever** [comment]
> `if has('vim_starting')
> set encoding=utf-8
> endif
> scriptencoding utf-8
> 
> if &compatible
> set nocompatible
> endif
> 
> let s:plug_dir = expand('/tmp/plugged/vim-plug')
> if !isdirectory(s:plug_dir)
> execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
> end
> 
> execute 'set runtimepath+=' . s:plug_dir
> call plug#begin(s:plug_dir)
> Plug 'hrsh7th/nvim-compe'
> call plug#end()
> PlugInstall | quit
> 
> " Options or settings here.
> " lua require ('lsp-config')
> 
> lua << EOF
> require'compe'.setup {
> enabled = true;
> autocomplete = true;
> debug = false;
> min_length = 1;
> preselect = 'enable';
> throttle_time = 80;
> source_timeout = 200;
> incomplete_delay = 400;
> allow_prefix_unmatch = false;
> 
> source = {
> path = true;
> buffer = true;
> calc = true;
> vsnip = true;
> nvim_lsp = true;
> nvim_lua = true;
> spell = true;
> tags = true;
> snippets_nvim = true;
> treesitter = true;
> };
> }
> local lspconfig = require 'lspconfig'
> local saga = require 'lspsaga'
> 
> saga.init_lsp_saga()
> 
> lspconfig.gopls.setup {
> cmd = {"gopls", "serve"},
> settings = {
> gopls = {
> analyses = {
> unusedparams = true,
> },
> staticcheck = true,
> },
> },
> }
> 
> EOF
> 
> set completeopt=menuone,noselect
> 
> inoremap compe#complete()
> inoremap compe#confirm('')
> inoremap compe#close('')
> inoremap compe#scroll({ 'delta': +4 })
> inoremap compe#scroll({ 'delta': -4 })
> `

can you check on this pls

**Comment by hrsh7th** [comment]
You must read README.md

```
inoremap <silent><expr> <C-Space> compe#complete()
inoremap <silent><expr> <CR>      compe#confirm('<CR>')
inoremap <silent><expr> <C-e>     compe#close('<C-e>')
inoremap <silent><expr> <C-f>     compe#scroll({ 'delta': +4 })
inoremap <silent><expr> <C-d>     compe#scroll({ 'delta': -4 })```

**Comment by rustiever** [comment]
> You must read README.md
> 
> ```
> inoremap <silent><expr> <C-Space> compe#complete()
> inoremap <silent><expr> <CR>      compe#confirm('<CR>')
> inoremap <silent><expr> <C-e>     compe#close('<C-e>')
> inoremap <silent><expr> <C-f>     compe#scroll({ 'delta': +4 })
> inoremap <silent><expr> <C-d>     compe#scroll({ 'delta': -4 })```
> ```

yes I read, and also added those in file but still there is problem

**Comment by hrsh7th** [comment]
_Your report is very annoying. Why didn't you check the markdown fenced code block before sending comment?_

Your config seems to completely break to me.

```
let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-compe'
call plug#end()
PlugInstall | quit
```

Your config has only `nvim-compe` but the config uses `lspsaga` and `lspconfig`, I can't understand.


If you can't get nvim-compe work, you can also try other completion-engine.

**Comment by hrsh7th** [comment]
If you are using 'packer.nvim', You should clear packer.nvim's cache before testing.

I think you can't create minimal config.

Please put the `:imap` command result.

**Comment by rustiever** [comment]
![Screenshot 2021-02-28 at 2 15 14 PM](https://user-images.githubusercontent.com/60929919/109412683-6420e280-79cf-11eb-873d-1c25e92276ae.png)


> If you are using 'packer.nvim', You should clear packer.nvim's cache before testing.
> 
> I think you can't create minimal config.
> 
> Please put the `:imap` command result.

**Comment by rustiever** [comment]
`if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-compe'
call plug#end()
PlugInstall | quit

" Options or settings here.
" lua require ('lsp-config')

set completeopt=menuone,noselect

inoremap <silent><expr> <C-Space> compe#complete()
inoremap <silent><expr> <CR>      compe#confirm('<CR>')
inoremap <silent><expr> <C-e>     compe#close('<C-e>')
inoremap <silent><expr> <C-f>     compe#scroll({ 'delta': +4 })
inoremap <silent><expr> <C-d>     compe#scroll({ 'delta': -4 })


lua << EOF
require'lspconfig'.gopls.setup{}
EOF

let g:compe = {}
let g:compe.enabled = v:true
let g:compe.autocomplete = v:true
let g:compe.debug = v:false
let g:compe.min_length = 1
let g:compe.preselect = 'enable'
let g:compe.throttle_time = 80
let g:compe.source_timeout = 200
let g:compe.incomplete_delay = 400
let g:compe.max_abbr_width = 100
let g:compe.max_kind_width = 100
let g:compe.max_menu_width = 100
let g:compe.documentation = v:true

let g:compe.source = {}
let g:compe.source.path = v:true
let g:compe.source.buffer = v:true
let g:compe.source.calc = v:true
let g:compe.source.vsnip = v:true
let g:compe.source.nvim_lsp = v:true
let g:compe.source.nvim_lua = v:true
let g:compe.source.spell = v:true
let g:compe.source.tags = v:true
let g:compe.source.snippets_nvim = v:true
let g:compe.source.treesitter = v:true
let g:compe.source.omni = v:true
`

I'm sorry for troubling you,
can you kindly check on this config
