### ISSUE TITLE
Insert mode incredibly laggy and unusable despite higher timeout values

### ISSUE THREAD

**Issue by weilbith** [hrsh7th/nvim-compe#146]
Hey, 
I'm just about to switch to this plugin for my setup. I tested it on some new random test files. All fine, works good. Then I switched to a bigger and (for for the language server) quite complex code-base. Now the insert mode is incredibly laggy. So basically makes it impossible to write. I randomly set `throttle_time` to `300` and `source_timeout` to `600`. I don't know if these time values are helpful. I also set them once to 3s and 6s. Nothing helps. What do I need to do to make my editor usable again?

**Comment by Shougo** [comment]
I think the test file should be added.

**Comment by ii14** [comment]
Can you post your compe configuration?

**Comment by weilbith** [comment]
> Can you post your compe configuration?

Simply this:
```vim
set completeopt=menu,menuone,noselect

lua require('compe').setup({
      \   throttle_time = 3000;
      \   source_timeout = 6000;
      \   source = {
      \     path = true,
      \     calc = true,
      \     nvim_lsp = true,
      \     nvim_lua = true,
      \     ultisnips = true,
      \     treesitter = true,
      \     tags = false,
      \     vsnip = false,
      \     spell = false,
      \     buffer = false,
      \     snippets_nvim = false,
      \   },
      \ })
```

> I think the test file should be added.

I assume a single would not help here. My exact example is [this repo](https://github.com/raiden-network/light-client) and then just edit `raiden-ts/src/raiden.ts`. I'm using the `tsserver` with `nvim-lspconfig`. The `efm` language server is always running aside, but has completion capabilty disabled.

**Comment by ii14** [comment]
Try disabling all sources and re-enable them one by one. Maybe that will tell us what's causing the lag.

**Comment by weilbith** [comment]
Okay yeah, it is clearly the treesitter source. I can re-enable all my former enabled sources. But when I toggle the treesitter source it switches from super fast to super slow.

**Comment by elianiva** [comment]
That definitely needs some optimisation. In the meantime, I think what you could do is only activate TS source if there's no server running (acts as a fallback for simple completion) and then turn it off when the LSP is attached.

**Comment by weilbith** [comment]
Hmm. My general intention is to use Treesitter only as a faster completion and when the slower LSP hits in, due to the higher priority I only see these candidates. But apparently this assumption is wrong, as the LSP is much faster then treesitter. xD

So as this is just the slow treesitter source, I'll just close the issue. Thanks for the help!

**Comment by hrsh7th** [comment]
I will look into it. thank you!

**Comment by hrsh7th** [comment]
@weilbith Hi, I'm improed a bit on the treesitter source. Thank you.

**Comment by hrsh7th** [comment]
Sorry. I noticed it is still heavy... maybe we should learn treesitter queries if improve it...

**Comment by weilbith** [comment]
Maybe some of the smart guys from the treesitter plugins could provide some useful hints and tips?

**Comment by oberblastmeister** [comment]
We are already using queries, `ts_locals.get_definitions` uses the `locals` query under the hood. I think the issue is that treesitter queries are just slow and are not asynchronous, that is why it is freezing the editor. I wrote a [pr](https://github.com/romgrk/nvim-treesitter-context/pull/27) for `nvim-treesitter-context` to use `locals` queries for the context and also accept nested context. I had the same issue, on medium sized files it would completely block the editor, even when the function was throttled. I think the solution is to make the queries asynchronous, although that is hard.
