### ISSUE TITLE
[Question] Why does buffers source look only for visible windows?

### ISSUE THREAD

**Issue by kristijanhusak** [hrsh7th/nvim-compe#147]
Hi,

I noticed that buffer source autocompletes only buffer values from visible windows. Why is that the case?

**Comment by hrsh7th** [comment]
Because avoiding too large popup menu.

If the more elegant approach is provided, we can change it.

**Comment by kristijanhusak** [comment]
By "Because avoiding too large popup menu." you mean you don't want to show too many autocomplete results from buffer source? I tried changing it to parse all listed buffers, didn't had any issues with it.

**Comment by hrsh7th** [comment]
Hm.. if the user opens 20 buffers, I don't know this approach still effective.

OK. I will try thi patch for daily use.

**Comment by hrsh7th** [comment]
If someone has an opinion on it, feel free to post it.

**Comment by ii14** [comment]
Why not do what [steelsojka/completion-buffers](https://github.com/steelsojka/completion-buffers) for completion-nvim does?
It's separated to two sources, `buffer` and `buffers`. `buffer` completes words only from the current buffer and `buffers` from all loaded buffers.

**Comment by ii14** [comment]
Another solution could be to add an option for `buffer` source to change the behavior. Either by letting the user to select from a set of predefined behaviors or even providing a custom function that returns a list of `bufnr`s.

**Comment by hrsh7th** [comment]
I don't want to add similar two source by built-in but that way can be ok to have.
I can't think always using all buffers is ideal way...

I say again. If someone provides more effective way, I will choose it.

In my current thoughts, it is good to use alternate buffer, I think.

**Comment by matu3ba** [comment]
@hrsh7th This would require some buffer management lib or application (ie jump tags to buffer view and shortcuts what to do, visualization where which buffer is opened etc).
 => However nobody wants alot manual interaction with buffers.

The alternative is implementing self-monitoring and combine the contents of the last used buffers (where cursor was moved). Having a timer would also help to detect regressions.

**Comment by kristijanhusak** [comment]
@hrsh7th could we introduce an option for this, that would be passed down to buffer source? By default to have it as it is now, and if option like `useAllBuffers = true` id set, to use all available buffers. Thst way people will consciously use this and be aware of the issues.

**Comment by kovasap** [comment]
I'm also very interested in using all buffers.  In fact, I'd like a feature where all words from all buffers opened are cached to a file that is used as a source itself.  Maybe this would be unusable in size, but if not it would be amazing.

**Comment by hrsh7th** [comment]
Anyone can create the new source.
