### ISSUE TITLE
Documentation / Preview

### ISSUE THREAD

**Issue by BigfootN** [hrsh7th/nvim-compe#148]
Hello,

I was wondering if this is normal and this is as expected, or if I miss-configured this plugin. 

I mostly write C/C++ and when for example I write `std::vec` in order to have `std::vector` as a match, when hovering over it, the only documentation I get is `12 overloads`.

So is it normal, or did I miss something ?

I am using the latest `neovim` with `clangd 11` and my setup for `clangd` is managed by `nvim-lspconfig`.

Thank you very much in advance for any help hoping I was clear enough.

**Comment by ii14** [comment]
I have this too. I get documentation for some functions, so I think this is just what clangd reports in this particular case.

**Comment by hrsh7th** [comment]
Yes. I think it should be fixed by clangd.

**Comment by BigfootN** [comment]
Thank you for your quick response.
