### ISSUE TITLE
How to toggle <C-x><c-o> omnicompletion

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#15]
Hey @hrsh7th , there many plugin that I use that integrate a server and provide compilation through omni
for example, https://github.com/Olical/conjure/blob/master/doc/conjure.txt#L141

Is it necessary to create a new source?

**Comment by tami5** [comment]
I think it is, could you help creating my first source? just give me a draft of what I need to do to add this source from aysnc 
https://github.com/thecontinium/asyncomplete-conjure.vim/blob/master/autoload/asyncomplete/sources/conjure.vim . its 31 lines of code

**Comment by hrsh7th** [comment]
OK, If you create a custom source, feel free to mention me for asking.
