### ISSUE TITLE
How to configure the kind of a source

### ISSUE THREAD

**Issue by astier** [hrsh7th/nvim-compe#151]
Hello. I read in the documentation that it is possible to set the `kind` of a source. However, I don't understand the vim-syntax how to do it. What is the command to set source-options? I tried

```vim
let g:compe.source.buffer.kind = "B"
```

but it doesn't work. Thank you.

**Comment by hrsh7th** [comment]
It works fine in my config.

```viml
  let g:compe = {}
  let g:compe.enabled = v:true

  let g:compe.source = {}
  let g:compe.source.path = v:true
  let g:compe.source.calc = v:true
  let g:compe.source.buffer = {}
  let g:compe.source.buffer.kind = 'B'
```

**Comment by astier** [comment]
I forgot `let g:compe.source.buffer = {}`. Thanks you.
