### ISSUE TITLE
Documentation should be removed if pum closed

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#152]

**Comment by the42** [comment]
I am affected by this - seemingly - closed bug. I am at commit 5b5f00716 yet the documentation floating window still remains open.

**Comment by hrsh7th** [comment]
@the42 Could you provide repro steps? In my situation, works correctly by latest master.

**Comment by fsouza** [comment]
I'm seeing this on latest master too (more specifically: 819d2e81191986f8068d8ce3acfc0f5b79da6467). Investigating.

**Comment by fsouza** [comment]
OK, it looks like this happens if I close the menu by leaving insert mode (pressing esc):


https://user-images.githubusercontent.com/108725/107316088-d21b5f00-6a4c-11eb-8f00-c8963a6b2d26.mp4

**Comment by hrsh7th** [comment]
Thank you. I can reproduce it.
I've fixed.

**Comment by a420gmoon** [comment]
The more you know, the more you grow

**Comment by kuator** [comment]
> The more you know, the more you grow

The more you know, the more you know

**Comment by the42** [comment]
You guys fix faster than I can respond
