### ISSUE TITLE
Continue completion if the item's word has matched.

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#153]
For example, In typescript-language-server, we can complete in the below position.

```typescript
import { } from '|';
```

And then, we can type `@` to choose the scoped module. But nvim-compe will close the popup menu.
The reason is that determine returns empty if we type `@`.

It is awesome if nvim-compe continues the current completion.

I have no idea for it for now.

**Comment by elianiva** [comment]
Wait, isn't that the current behaviour already? or do I misunderstood you.

https://user-images.githubusercontent.com/51877647/107204780-ab9afb00-6a2f-11eb-8049-d0e6050d84ca.mp4

**Comment by hrsh7th** [comment]
Try with this config. I think the behavior will be improved.

```
Pattern.set_filetype_config('typescript', {
  keyword_pattern = [[\%(/\h\?\w*\|\h\w*\)]];
})
Pattern.set_filetype_config('typescript', {
  keyword_pattern = [[\%(@\w*\|\h\w*\)]];
})
Pattern.set_filetype_config('typescriptreact', {
  keyword_pattern = [[\%(@\w*\|\h\w*\)]];
})
Pattern.set_filetype_config('javascript', {
  keyword_pattern = [[\%(@\w*\|\h\w*\)]];
})
Pattern.set_filetype_config('javascriptreact', {
  keyword_pattern = [[\%(@\w*\|\h\w*\)]];
})
```

**Comment by elianiva** [comment]
You're right, that is so much better! Maybe that should be the default?

**Comment by cloggier** [comment]
If it's better and if it will become default, can it also be enabled for Vue?

**Comment by elianiva** [comment]
I think it should be enabled for all JS/TS related filetypes like Vue, Svelte, etc.

**Comment by hrsh7th** [comment]
Certainly, On second thoughts, my proposed solution would not improve this case... (because the first char is `@`)
So probably, we should improve the keyword pattern.

**Comment by hrsh7th** [comment]
...wait. If `@` is trigger character, my proposed solution is correct way. I will check it.

**Comment by hrsh7th** [comment]
Ah. the `@` is trigger character. so if we determine keyword pattern by returned items is still a good idea... maybe.

**Comment by hrsh7th** [comment]
It is hard to implement, I think. I will tackle it if I have spent time.

**Comment by hrsh7th** [comment]
We can improve the default keyword-pattern at the moment.

**Comment by hrsh7th** [comment]
Hm... I will investigate What is VSCode does.

**Comment by tzachar** [comment]
I think this is something needed in general; 
Currently, after the initial completion list is generated, and the user enters an additional character, the completion list is only filtetered down and sources are not called to provide additional completions based on the new partial input.

I can force compe to regenerate the completion list by preessing Ctrl-Space, but it would be nice to allow a source to indicate that new items can be generated. 

I can achieve this behaviour in compe-tabnine if I set context.manual to true in the determine callback, but this seems hacky.
Any other way to achive this?

**Comment by hrsh7th** [comment]
@tzachar This issue does not relate to your problem. You can use `incomplete` flags that can be found in `compe_tags` source.

**Comment by tzachar** [comment]
> @tzachar This issue does not relate to your problem. You can use `incomplete` flags that can be found in `compe_tags` source.

Cool.

**Comment by hrsh7th** [comment]
This issue is really important. I'm tackling it so other work will stop.
