### ISSUE TITLE
TabNine source

### ISSUE THREAD

**Issue by tzachar** [hrsh7th/nvim-compe#155]
Created a separate repo for a TabNine source: https://github.com/tzachar/compe-tabnine
Can you please link to it on the main page?
10x.

**Comment by hrsh7th** [comment]
Of cource ok.
I will add it.

**Comment by onsails** [comment]
[submitted](https://github.com/NixOS/nixpkgs/pull/111954) to nixpkgs

**Comment by ii14** [comment]
@hrsh7th maybe we should add to README a section that keeps track of 3rd party sources? Like the ones @tamago324 and @tami5 did and the TabNine source.

**Comment by hrsh7th** [comment]
I've added the external sources section to README.md
Thank you very much! @tzachar
