### ISSUE TITLE
clangd wants to replace . with -> but it results in .->

### ISSUE THREAD

**Issue by astier** [hrsh7th/nvim-compe#156]
## Problem

In C you can access the variables of a struct with `->`
clangd is able to complete variables even if instead `.` is typed.
It deletes the `.` and replaces it with `->` on completion.
When using nvim-compe the `.` doesn't get deleted.
Instead the completion results in `.->`

## Info

NVIM v0.5.0-dev+1073-gb894fbcbe
clangd version 11.0.1

## Minimal init.vim

```vim
call plug#begin($XDG_DATA_HOME.'/nvim/plugins')
    Plug 'hrsh7th/nvim-compe'
    Plug 'neovim/nvim-lspconfig'
call plug#end()

let g:compe = {}
let g:compe.source = {}
let g:compe.source.nvim_lsp = v:true
lua require 'lspconfig'.clangd.setup{}
se completeopt=menu,menuone,noselect
```

## Minimal bug.c

```c
struct Foo {
   int foo;
};

int main() {
   struct Foo *foo;
   foo;
}
```

## Reproduce

1. Create `bug.c`
2. Place cursor between `foo` and `;` like `foo|;`
3. Type `.` to trigger completion
4. Select first completion with `<C-n>`

The line with the completion looks now like

```c
foo.->foo;
```

Instead it should look like

```c
foo->foo;
```

**Comment by hrsh7th** [comment]
@astier If you invoke `compe#confirm` when the line is `foo.->foo|`, the compe will replace the line to `foo->foo` correctly. So it is not bug of nvim-compe, I think.

**Comment by elianiva** [comment]
https://user-images.githubusercontent.com/51877647/107307651-a71b2480-6ab9-11eb-8a22-a39907c78445.mp4

You need to invoke `compe#confirm` it, I think. Because this doesn't happen to me, it only happens if I didn't press `<CR>` which I've remapped to `compe#confirm`

**Comment by hrsh7th** [comment]
Oh... coc supports it...
Icthink it relates to #153 

At least, you can fix by `compe#confirm`

**Comment by astier** [comment]
`compe#confirm` works. With lexima I also have to call `call lexima#set_default_rules()` to make it work.

**Comment by hrsh7th** [comment]
regression...

**Comment by hrsh7th** [comment]
I've confirmed this problem is solved.

**Comment by hrsh7th** [comment]
not working... (too difficult...)

**Comment by hrsh7th** [comment]
It maybe works perfectly.

**Comment by cloggier** [comment]
What a rollercoaster. :)

**Comment by tami5** [comment]
@hrsh7th is the best maintainer I ever seen, he doesn't let things slide easily :laughing: . Also, very good at creating great tools :smile:

**Comment by cloggier** [comment]
Ah, I did not mean anything negative. Just enjoyed following this issue. I have nothing but huge admiration for @hrsh7th and all his work. Outstanding! Entire nvim community and what is happening around it these days is breath taking.

**Comment by tami5** [comment]
@cloggier :laughing: :laughing: I know you didn't mean anything, I was kinda agreeing with you :laughing: then I mentioned what great job @hrsh7th does.

**Comment by hrsh7th** [comment]
I will work if interest it.

This issue (and #153) is really interesting about how VSCode/coc.nvim works.

_I felt it again that coc.nvim is great while implementing this._

**Comment by astier** [comment]
After revisiting compe after a while I tried the same example as posted above with the minimal init.vim and bug.c however I have the same issue again. Is it supposed to work now?

**Comment by astier** [comment]
Can we reopen this?

**Comment by hrsh7th** [comment]
I think we can't fix it at the moment...

**Comment by astier** [comment]
So the bot added the wontfix-label. Does it mean there are no plans to ever fix this issue?

**Comment by hrsh7th** [comment]
I think we can't dot-repeatable it... (because this completion item uses `textEdit`.

**Comment by astier** [comment]
Eventually I will open a new issue for this. Thanks for the great work.
