### ISSUE TITLE
Replace text on complete

### ISSUE THREAD

**Issue by tzachar** [hrsh7th/nvim-compe#157]
Hi there.

Suppose that a completion is triggered in the middle of a word, and a completion item was selected.
Can we add an option such that the inserted text will *replace* everything till the next space or trigger character? The current default is to insert the new completion item.

10x

**Comment by cloggier** [comment]
That would be a very nice feature indeed. I believe coc does that?

**Comment by hrsh7th** [comment]
This is low priority feature. In rust-analyzer, it would work because the LSP server returns CompletionItem that annotated for it.

**Comment by tzachar** [comment]
Well, low priority is in the eye of the beholder.....
Can you give some pointers regarding how one can approach this?

**Comment by hrsh7th** [comment]
this feature relates to each source, I think (because rust-analyzer already realizes it).
So I don't know how to solve this problem in a general way...

**Comment by hrsh7th** [comment]
The VSCode supports this feature recently. It is very complex feature... And I don't understand it yet.

**Comment by hrsh7th** [comment]
Maybe we should implement `compe#confirm({ 'key': "<CR>", 'mode': 'n', 'replace': v:true })`

**Comment by tzachar** [comment]
Your approach as for configuration seems to make sense.
Any idea how other completion managers achive this?
If this is something the current rust lsp does, how exactly does it achieve it?

**Comment by hrsh7th** [comment]
I've understood how VSCode to do it maybe.

**Comment by tzachar** [comment]
Interesting.

I think it should also probably be language specific.
Anyway, this is a really usefull feature, as completion sometimes starts in the middle of a word.

**Comment by hrsh7th** [comment]
All VSCode's completion item has `range` property even if the item wan't returned from LSP source and that can be have a `insertRange`, `replaceRange`.

The range can be determined from default pattern maybe.
I have to understand ot more deeply.

**Comment by tzachar** [comment]
Im guessing you mean adding ```insertRange, replaceRange``` to each completion item? 
Does this mean you leave it to each individual source to manage on its own? 
Maybe add a default implementation in case a source does not specify ```insertRange, replaceRange```?

**Comment by hrsh7th** [comment]
Yes. VSCode does it.

**Comment by hrsh7th** [comment]
My next task.

**Comment by tzachar** [comment]
Amazing. 10x

**Comment by tomtomjhj** [comment]
FYI this is part of coc.nvim source that does this: https://github.com/neoclide/coc.nvim/blob/cc1ad5669970956a7e701c6c1b5eca99a6713447/src/completion/complete.ts#L202-L205

**Comment by hrsh7th** [comment]
My current thoughts are 

1. Still use the full `complete-item.word`
2. Replace text when confirming selected item with `compe#confirm({ 'replace': v:true })`

The above thoughts are respecting the VSCode model.
I will consider it in the more vim-friendly way.

**Comment by tzachar** [comment]
I wonder how VSCode behaves upon replace. I have zero experience with VSCode.
Anyway, I don't think the coc approach is best. I would think replacing text untill some kind of stop marker (language dependant). For example, Im thining about replacing text up to the next space, or punctuation mark (basically up to any non alphanum).

**Comment by hrsh7th** [comment]
1. Complete on `my_|word`
2. Select `my_word` from completion-menu
3. The line will be `my_word|_word` now.
4. Invoke `compe#confirm({ 'replace': v:true })` then the line will be `my_word|`

Hm... Is 3 step is annoying?

**Comment by tzachar** [comment]
I can live with it, but can't you also manipulate the entire line while cycling the completion menu?

**Comment by hrsh7th** [comment]
It's very difficult.

We have two options for it.

1. Trimming `v:completed_item.word` for replacing range.

This solution can be avoided 3 in steps.

1. Complete on `my_|word`
2. Select `my_word` from completion menu
3. The line will be `my_|word`
4. Invoke `compe#confirm({ 'replace': v:true })` then the line will be `my_word|`

2. VSCode like behavior
The explanation is the above.

**Comment by tzachar** [comment]
(1) is probably not what I was thinking about.

see the screen grabs from posted by @CKolkey in https://github.com/hrsh7th/nvim-compe/issues/120#issuecomment-806527026_ : 
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/7228095/112456605-370be980-8d5b-11eb-8b3d-6e5df9167e7a.gif)

I wonder how deoplete does it.

**Comment by MahouShoujoMivutilde** [comment]
Hey, please don't close it, it seems like a quite useful feature to have.

**Comment by ajitid** [comment]
stale bot go away!

**Comment by timsofteng** [comment]
It would be great improvement

**Comment by hackthecache** [comment]
Stumbled onto this, sounds like a good default, from **readline**.

`skip-completed-text`
    If set to `on`, this alters the default completion behavior when inserting a single match into the line. It's only active when performing completion in the middle of a word. If enabled, readline does not insert characters from the completion that match characters after point in the word being completed, so portions of the word following the cursor are not duplicated. For instance, if this is enabled, attempting completion when the cursor is after the `e` in `Makefile` will result in `Makefile` rather than `Makefilefile`, assuming there is a single possible completion. The default value is `off`.

**Comment by frangio** [comment]
The behavior of `skip-completed-text` described by @hackthecache sounds great. I often run into situations that would benefit from it.

**Comment by Shougo** [comment]
The feature is not implemented in nvim-cmp?

**Comment by frangio** [comment]
Oh, I was not aware of the deprecation. This is indeed implemented in nvim-cmp by using `cmp.ConfirmBehavior.Replace`. Thanks!

**Comment by Shougo** [comment]
So the issue should be closed.
