### ISSUE TITLE
How can I toggle this plugin on and off?

### ISSUE THREAD

**Issue by David-Else** [hrsh7th/nvim-compe#159]
Thanks for the amazing plugin. 

Could you add a keyboard mapping to toggle this plugin on and off in realtime to the README? I can't work out how to do it. It is a much-needed feature, for example, it constantly suggests words from the buffer in markdown which is very distracting.

**Comment by ii14** [comment]
```viml
" g:compe has to be defined
command! CompeEnable  call compe#setup(g:compe)
command! CompeDisable call compe#setup({'enabled': v:false})
```

**Comment by cloggier** [comment]
@ii14 Wouldn't it override preexisting configuration on enable? Other than that it could be added to FAQ section in readme.

**Comment by ii14** [comment]
It overrides only the internal configuration, but it doesn't mutate the `g:compe` dictionary in any way, so everything is still there.
For lua you can just store the config in a separate variable and do the same thing.

**Comment by ii14** [comment]
Toggling is a little bit more involved and it requires accessing internal variables as of right now, so it might break in the future.
And it works only for global configuration, won't work if you defined configuration local to buffer.

```lua
-- completion.lua
local compe = require('compe')

local M = {}

-- configuration
local config = {
  enabled = true,
  source = {
    buffer = true,
  },
}

-- init compe
compe.setup(config)

M.toggle = function()
  if require('compe.config')._config.enabled then
    compe.setup({enabled = false})
  else
    compe.setup(config)
    -- if you defined configuration in vimscript:
    -- compe.setup(vim.g.compe)
  end
end

vim.cmd([[command! CompeToggle lua require'completion'.toggle()]])

return M
```

**Comment by ii14** [comment]
> requires accessing internal variables

Correction, it doesn't really require accessing internal variables, you can always keep track of it yourself.

@David-Else Let me know if you need toggling completion per buffer, I can help you with writing a function that does that.

**Comment by David-Else** [comment]
@ii14 Thanks for helping! I have been trying:
```
" or if you want to disable/enable for the current buffer only
command! CompeEnable  call compe#setup(g:compe, 0)
command! CompeDisable call compe#setup({'enabled': v:false}, 0)
```
and it seems to work until I open a new buffer, use it there, then return to the original buffer. Then it just stops working.

> Let me know if you need toggling completion per buffer, I can help you with writing a function that does that.

Yes, please! That is exactly the functionality I was looking for. Something like `<leader>ac` to toggle on and off autocomplete would be amazing.

**Comment by ii14** [comment]
Try if this works.

The caveat is that if you do any calls to `compe#setup()` or `compe.setup()` after the initialization, replace it with `CompeSetup()` or `require'completion'.setup()`. Calling the original functions in `init.vim` or `init.lua` is fine, it's just so it won't get confused and think that the completion was turned off after calling `:CompeToggle` and then suddenly `compe#setup()` gets called, turning the completion on. I assume you don't, but just in case.

Call `lua require('completion')` somewhere in your vimrc to get the `:CompeToggle` command.

```lua
-- ~/.config/nvim/lua/completion.lua
local compe = require('compe')

local M = {}

local locals = {}

M.toggle = function()
  local bufnr = vim.api.nvim_get_current_buf()
  if locals[bufnr] then
    compe.setup(locals[bufnr], bufnr)
    table.remove(locals, bufnr)
  else
    locals[bufnr] = vim.deepcopy(require('compe.config').get())
    compe.setup({enabled = false}, bufnr)
  end
end

M.setup = function(config, bufnr)
  local buf = bufnr or vim.api.nvim_get_current_buf()
  if locals[buf] then
    table.remove(locals, buf)
  end
  compe.setup(config, bufnr)
end

vim.cmd([[
function! CompeSetup(config, ...) abort
  call luaeval('require"completion".setup(_A[1], _A[2])', [a:config, get(a:, 1, v:null)])
endfunction
]])

vim.cmd([[command! CompeToggle lua require'completion'.toggle()]])

return M
```

**Comment by ii14** [comment]
Fixed the bug where toggling got stuck and improved `setup` function

**Comment by David-Else** [comment]
@ii14 Nice one, it works well on one buffer. It seems to have a problem that when you use it on two different buffers and switch between them toggling on and off on each one many times then soon it will stop working on the second one.

I think a lot of people would benefit from this function when it is 100% working, would you submit it as a pull request?

Thanks again!

**Comment by ii14** [comment]
> It seems to have a problem that when you use it on two different buffers and switch between them toggling on and off on each one many times then soon it will stop working on the second one.

Have you checked if it still does that after my update? In the previous version I messed up with removing entries from the table, that's why toggling sometimes stopped working.

> I think a lot of people would benefit from this function when it is 100% working, would you submit it as a pull request?

@hrsh7th What do you think, should I do it?

**Comment by hrsh7th** [comment]
I think `compe#get_config(bufnr)/require'compe'.get_config(bufnr)` is ok to have.

**Comment by hrsh7th** [comment]
Hm... But I don't know this method should accepts `bufnr`...

**Comment by ii14** [comment]
`Config.get()` could accept `bufnr` as an optional argument. But the point is about `:CompeToggle` command, which toggles the completion on the current buffer.

**Comment by David-Else** [comment]
@ii14 
> Have you checked if it still does that after my update? In the previous version I messed up with removing entries from the table, that's why toggling sometimes stopped working.

Yes, I am using the latest version.

**Comment by hrsh7th** [comment]
I don't want to add CompeToggle command.
I think it is easy to implement if we provide `compe#get_config`...?

**Comment by ii14** [comment]
> Yes, I am using the latest version.

That's weird, I'm trying to break it, but everything works for me.

> I think it is easy to implement if we provide `compe#get_config`...?

I don't think it's that easy, because different buffers can have different configurations. So with `compe#get_config` the implementation is basically the same as what I've posted above. And the main problem here is with `compe#setup`. When the completion is turned off and `compe#setup` gets called on a buffer, it will turn the completion on again. In this case we should either mark that buffer as having completion turned on, or save the config and load it only after user toggles the completion back on. So to do it properly, `compe#setup` has to be intercepted.

Another solution is to check the value of `enabled`. But in this case what should happen if the configuration was never defined or was disabled on a buffer by calling `compe#setup` and user tries to turn it on with `:CompeToggle`?

**Comment by hrsh7th** [comment]
My solution are

#### `compe#setup` inherit existing buffer configuration
Currently, `compe#setup` will inherit only `global config`.
We should change this behavior to inherit `buffer config` and `global config` both.

#### add `compe#get_config(bufnr)`
This allows checking `enabled` or not.

```
command! CompeToggle call s:compe_toggle()
function! s:compe_toggle()
  if compe#get_config(bufnr('%')).enabled
    call compe#setup({ 'enabled': v:false })
  else
    call compe#setup({ 'enabled': v:true })
  endif
endfunction
```

**Comment by David-Else** [comment]
@ii14 try `nvim random.md` and enter `hello`, go the the next line and start typing `he` and autocomplete is on. toggle it off. now `:e random 2' and do the same thing turning it on and off. Now go back to `random` and turn it on and off a few times testing each time. Soon it stops working and you just can't turn it on anymore with a toggle.

**Comment by hrsh7th** [comment]
If we provide `CompeToggle`, it means we should also add `CompeEnable` and `CompeDisable` (probably `CompeStatus`).
I think there is no end.

**Comment by David-Else** [comment]
@hrsh7th 
> Currently, compe#setup will inherit only global config.
> We should change this behavior to inherit buffer config and global config both.

This seems to enable a nice clean solution with much less code needed to make a toggle function.

**Comment by ii14** [comment]
> @ii14 try `nvim random.md` and enter `hello`, go the the next line and start typing `he` and autocomplete is on. toggle it off. now `:e random2` and do the same thing toggling it on and off. Now go back to `random` and turn it on and off a few times testing each time. Soon it stops working and you just can't turn it on anymore with a toggle.

That was what was happening on the previous version. I tried to do this at least 50 times, switching back and forth between buffers and it seems to be working for me

https://asciinema.org/a/hJyimgyh2KYJF16HA44vStfKM

**Comment by ii14** [comment]
> `compe#setup` inherit existing buffer configuration

So this:
```viml
call compe#setup({
  \ 'param1': 10,
  \ 'param2': 20,
  \ }
```
is equivalent to this?:
```viml
call compe#setup({'param1': 10})
call compe#setup({'param2': 20})
```
Do I understand it correctly?

**Comment by hrsh7th** [comment]
Yes, I intent it.
At least, source key could be replace (because `compe#setup` merge only shallow depth).

**Comment by David-Else** [comment]
@ii14 Thanks for your dedication! I have made it happen many times, I don't know how I just mess about going backwards and forwards and it eventually happens. I double-checked, I am definitely using the newer version.

**Comment by ii14** [comment]
It's a good idea, I'm all for it. It would indeed solve this problem easily
