### ISSUE TITLE
Support multiple start offset

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#16]
We should support multiple start_offset.

For example, In the below state, nvim-compe should work two different sources.

```
some.wor|
↑    ↑
↑    source1 offset
↑
source2 offset
```

**Comment by tami5** [comment]
😍😍😍😍😍

**Comment by hrsh7th** [comment]
Fixed https://github.com/hrsh7th/nvim-compe/commit/1c10241475e847e7c87a87735854ecd895f6083e

**Comment by tami5** [comment]
@hrsh7th doesn't play well with path source, try testing ../, you should see double  `//` in completion menu

**Comment by hrsh7th** [comment]
I couldn't reproduce it.

Hm... but if it's a bug, it is critical so I want to explain me it.

**Comment by tami5** [comment]
No worries @hrsh7th, I think it was something up with my configuration. I longer have it. Thanks a lot
