### ISSUE TITLE
Can't toggle autocomplete on InsertLeave

### ISSUE THREAD

**Issue by fsouza** [hrsh7th/nvim-compe#162]
I have this weird setup in which I manually trigger the initial completion and enable autocomplete, then on InsertLeave I disable autocomplete.

This used to work a couple of days ago, but now it doesn't anymore. Once I enable autocomplete, it remains on, even after calling setup with `autocomplete=false`.

Here's my logic:

https://github.com/fsouza/dotfiles/blob/9f4440930dc8f71a234d79955c99b39c48bacc8d/nvim/lua/fsouza/global/complete.lua#L4-L16

`reattach` is the function that resets autocomplete to false. I poked in the code and can confirm setup is being called with autocomplete=false and that's stored in the internal config, but it has no effect.

I don't understand a lot about the code, but I added some print calls and noticed that `is_completing` remains true here on the second time around. More specifically, this condition evaluates to true (autocomplete is false, manual is false, but is_completing is true): https://github.com/hrsh7th/nvim-compe/blob/a85c6461ddf73fbe307a73b06855e336e298b152/lua/compe/completion.lua#L141

**Comment by fsouza** [comment]
@hrsh7th hey, thanks for the quick feedback, but it didn't work :( It works if I make this change though:

```
％ git diff
diff --git a/lua/compe/completion.lua b/lua/compe/completion.lua
index c1024d6..8a486f1 100644
--- a/lua/compe/completion.lua
+++ b/lua/compe/completion.lua
@@ -128,7 +128,7 @@ Completion.complete = function(manual)
     return
   end

-  local is_completing = Completion._is_completing(context)
+  local is_completing = Completion._is_completing(Completion._context)

   -- Restore pum if closed it automatically (backspace or invalid chars).
   local should_restore_pum = false
```

Not sure if that's the correct behavior though.

**Comment by hrsh7th** [comment]
Hm... I will consider it.

**Comment by cloggier** [comment]
@fsouza Out of interest, what benefits disabling completion on `InsertLeave` brings?

**Comment by fsouza** [comment]
@cloggier I don't like automatic popups. So I want to be able to trigger it manually, but once triggered I don't want to have to re-use the keystroke to reopen the menu until I leave insertion mode.

(To be fair, it's fine if this is not something nvim-compe can't support, I should probably have tagged it as a feature request or something like that)

**Comment by hrsh7th** [comment]
@fsouza 
Please re-check it with latest maater.

**Comment by fsouza** [comment]
Just tested and it seems to work, thank you very much!
