### ISSUE TITLE
when completion confirm the signature will auto insert to buffer

### ISSUE THREAD

**Issue by glepnir** [hrsh7th/nvim-compe#163]
https://user-images.githubusercontent.com/41671631/107514808-1e010c00-6be5-11eb-900a-37eeecbcb2e5.mov

**Comment by hrsh7th** [comment]
lol.

I can't understand this behavior.
Could you create minimal config?

**Comment by oberblastmeister** [comment]
This happens to me too

**Comment by oberblastmeister** [comment]
For me the latest two commits made this happen, resetting to a85c6461ddf73fbe307a73b06855e336e298b152 fixes it.

**Comment by hrsh7th** [comment]
@oberblastmeister Thank you for information.
Could you check this problem still happen on latest master?

**Comment by oberblastmeister** [comment]
@hrsh7th the problem is fixed on the latest master

**Comment by hrsh7th** [comment]
Thank you for your confirmation.
