### ISSUE TITLE
Relax `completeopt` requirement

### ISSUE THREAD

**Issue by cbarrete** [hrsh7th/nvim-compe#165]
From `:help 'completeopt'`:

```
menu	    Use a popup menu to show the possible completions.  The
    menu is only shown when there is more than one match and
    sufficient colors are available.  |ins-completion-menu|

menuone  Use the popup menu also when there is only one match.
    Useful when there is additional information about the
    match, e.g., what file it comes from.
```

From this description, it seems to me that if `menuone` is set, `menu` is redundant. In fact I've used `completeopt=menuone,noselect` for years without issues, except that now `nvim-compe` sometimes gets angry at me.

Unless I'm missing something important here, would you be fine with relaxing the requirements on `completeopt`?
If so, I have submitted a PR at https://github.com/hrsh7th/nvim-compe/pull/164.

Thanks!

**Comment by hrsh7th** [comment]
Thank you.
Probably, you are right. I've merged the PR.

We can fix later if someone reports problem.
