### ISSUE TITLE
Vimtex as custom source?

### ISSUE THREAD

**Issue by seblj** [hrsh7th/nvim-compe#166]
Is it possible to add vimtex as a custom completion source? If yes, how? Couldn't figure it out by reading the docs

**Comment by hrsh7th** [comment]
Sorry. I don't plan to add detailed documentation for now.
And Sorry. I have no time to implement it (and I don't use tex)
If you want to create custom source, please look the existing build-in sources.

**Comment by jdhao** [comment]
@seblj  Since your last visit, omni source support has been added to nvim-compe. So now we can auto-complete for vimtex using nvim-compe. Here is my working config:

```
require'compe'.setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'always';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;

  source = {
    omni = {filetypes = {'tex'}};
    path = true;
    buffer = true;
    spell = {filetypes = {'markdown', 'tex'}};
    emoji = true;
    nvim_lsp = true;
    nvim_lua = true;
    ultisnips = true;
    calc = false;
    vsnip = false;
  };
}
```

Of course, you have to make sure that  vimtex has been properly installed.

**Comment by tgy** [comment]
Thanks a lot @jdhao for sharing your setup. Really helpful
