### ISSUE TITLE
Buffer source works only with latin alphabet

### ISSUE THREAD

**Issue by echasnovski** [hrsh7th/nvim-compe#167]
#### How to reproduce

1. Create buffer with the following content (phrases in English, Italian, and Russian):

```
The quick brown fox jumps over the lazy dog

Quel fez sghembo copre davanti

Съешь ещё этих мягких французских булок, да выпей чаю

фран
```

2. Try complete the last word. It should suggest "французских" but it outputs only words with latin letters. Using Vim's complete (with `<C-x><C-n>`) does correct suggestion.

**Comment by hrsh7th** [comment]
compe does not support multibyte character. sorry.

**Comment by hrsh7th** [comment]
Probably, it depends https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe/pattern.lua#L13

**Comment by hrsh7th** [comment]
@echasnovski
I've added default pattern option.

4f188c2#diff-afad97d34ff4fbf47ec131fefc85113c565aa4e3bfc8b64ed1a7194c3c16beadR238

**Comment by echasnovski** [comment]
This doesn't immediately solve my problems. Could you please help me understand what do I need to do now? How to modify this pattern to work with non-latin words?

**Comment by hrsh7th** [comment]
You can set `let g:compe.default_pattern = '\k\+'` but I think it have side-effect maybe.

**Comment by echasnovski** [comment]
> You can set `let g:compe.default_pattern = '\k\+'` but I think it have side-effect maybe.

I can confirm that this fixes this issue. Used it for couple of minutes, didn't notice any side-effects yet.

**Comment by hrsh7th** [comment]
In progrming language, the multibyte characters sometimes annoying.(this option makes allowing it)

**Comment by hrsh7th** [comment]
Thank you for confirmation!

**Comment by hyperkahler** [comment]
> You can set `let g:compe.default_pattern = '\k\+'` but I think it have side-effect maybe.

Setting `vim.g.compe.default_pattern = '\k\+'`

> You can set `let g:compe.default_pattern = '\k\+'` but I think it have side-effect maybe.

How to make it working with lua 5.4.3? Setting `vim.g.compe.default_pattern = '\k\+'` returns `invalid escape sequence with '''`.

**Comment by MahouShoujoMivutilde** [comment]
@hyperkahler  try `default_pattern = [[\k\+]]`.

**Comment by hyperkahler** [comment]
> @hyperkahler try `default_pattern = [[\k\+]]`.

Seems that I'm still doing totally wrong, obtaining `attempt to index field 'compe' (a nil value)`.

**Comment by MahouShoujoMivutilde** [comment]
Ok, let me elaborate:

~/.config/nvim/init.lua
```lua
-- ...
require('nv-compe')
-- ...
```

~/.config/nvim/lua/nv-compe/init.lua
```lua
require'compe'.setup {
    enabled = true,
    autocomplete = true,
    debug = false,
    min_length = 1,
    preselect = 'disable', -- 'disable' makes it behave like coc.nvim
    throttle_time = 80,
    source_timeout = 200,
    incomplete_delay = 400,
    max_abbr_width = 100,
    max_kind_width = 100,
    max_menu_width = 100,
    documentation = true,

    -- HERE
    default_pattern = [[\k\+]],

    source = {
        path = true,
        buffer = true,
        calc = true,
        vsnip = false,
        nvim_lsp = true,
        nvim_lua = true,
        spell = false,
        tags = true,
        snippets_nvim = true,
        treesitter = true
    }
}

-- ...
```

**Comment by hyperkahler** [comment]
> Ok, let me elaborate:
> 
> ~/.config/nvim/init.lua
> 
> ```lua
> -- ...
> require('nv-compe')
> -- ...
> ```
> 
> ~/.config/nvim/lua/nv-compe/init.lua
> 
> ```lua
> require'compe'.setup {
>     enabled = true,
>     autocomplete = true,
>     debug = false,
>     min_length = 1,
>     preselect = 'disable', -- 'disable' makes it behave like coc.nvim
>     throttle_time = 80,
>     source_timeout = 200,
>     incomplete_delay = 400,
>     max_abbr_width = 100,
>     max_kind_width = 100,
>     max_menu_width = 100,
>     documentation = true,
> 
>     -- HERE
>     default_pattern = [[\k\+]],
> 
>     source = {
>         path = true,
>         buffer = true,
>         calc = true,
>         vsnip = false,
>         nvim_lsp = true,
>         nvim_lua = true,
>         spell = false,
>         tags = true,
>         snippets_nvim = true,
>         treesitter = true
>     }
> }
> 
> -- ...
> ```

Thanks, now it works. 

I also haven't seen any visible side effects so far.
