### ISSUE TITLE
Spell source has trouble working with non-English languages

### ISSUE THREAD

**Issue by echasnovski** [hrsh7th/nvim-compe#168]
#### How to reproduce

Using Russian as non-English language:

1. Set spelling to non-English language: `:set spell spelllang=ru`. Note, that it should be set up.
2. Start typing some word in that language: `прим`.
3. Force 'nvim-compe' completion. For me it does nothing. But using Vim's `<C-x><C-s>` creates completion window with expected outputs.

Repeating this with English language (`:set spell spelllang=en` and typing `examp`) works great and gives spelling suggestions.

**Comment by hrsh7th** [comment]
@echasnovski 
I've added default pattern option.

https://github.com/hrsh7th/nvim-compe/commit/4f188c285852617fe511a89218c24cb5c0f9a712#diff-afad97d34ff4fbf47ec131fefc85113c565aa4e3bfc8b64ed1a7194c3c16beadR238

**Comment by echasnovski** [comment]
Setting `let g:compe.default_pattern = '\k\+'` fixes the issue.
