### ISSUE TITLE
Make the gap between completion menu and floating window removable

### ISSUE THREAD

**Issue by gbrlsnchs** [hrsh7th/nvim-compe#169]
When navigating through completion items, there's a secondary floating window showing definitions (at least for LSP items). There's a small gap between the completion menu and that window, and sometimes there's a character from the background buffer in that gap, making it a little harder to read the floating window sometimes.

I imagine it's someone's preference to have it that way, so it would be cool if that gap was removable via configuration.

**Comment by hrsh7th** [comment]
Feel free to create PR

**Comment by gbrlsnchs** [comment]
Sure, just wanted to document this issue for later, since I can't work on it right now. That's what issues are for, right? Anyway, I might tackle it later when I get some free time. :wink:

**Comment by cloggier** [comment]
@hrsh7th if you could point me to where relevant code is I could try top create PR for that as it did bother me today for the first time too.

**Comment by hrsh7th** [comment]
Thank you.
It's implemented in https://github.com/hrsh7th/nvim-compe/blob/master/autoload/compe/documentation.vim .

**Comment by cloggier** [comment]
Thanks, will have a look over weekend.

**Comment by hrsh7th** [comment]
I think we should remove gap and provide padding

**Comment by cloggier** [comment]
Or maybe even add docked window as an option? Some other completion plugin has that. 

Didn't have time to look into it @hrsh7th, sorry. Might not have time today either.

**Comment by hrsh7th** [comment]
Hm... I didn't understand 'docked window' meaning maybe.

I think we should't have a configuration for documentation window appearance.

But I think we should improve documentation appearance.

**Comment by cloggier** [comment]
Improving it is definitely more important, but what I meant was something like this: https://github.com/ncm2/float-preview.nvim

Could be an option added at some point later.

**Comment by elianiva** [comment]
removing the gap and adding some padding would be the most ideal solution IMO

**Comment by hrsh7th** [comment]
I'm tackling it.

**Comment by hrsh7th** [comment]
@gbrlsnchs I think this problem should be fixed by latest mater now.
