### ISSUE TITLE
Improve stability.

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#17]
In my impression, nvim-compe is a bit unstable now.

So probably, we should refactor some of the codes.

**Comment by hrsh7th** [comment]
I think nvim-compe is stable now...

Let's check a little.

**Comment by tami5** [comment]
I'm getting some times the following error

`Error executing vim.schedule lua callback: ...e/pack/packer/opt/nvim-compe/lua/compe_buffer/buffer.lua:47: Index out of bound`

But with telescope's function live_grep search buffer, my whole screen turned into the above error

blob:https://imgur.com/4a8a578c-ae32-496f-85b3-b00aabc761a8

**Comment by hrsh7th** [comment]
Thank you for your report. I will investigate it.

**Comment by hrsh7th** [comment]
Ah, I change `strict_index` for `nvim_buf_get_lines` so the problem should be fixed now.

**Comment by tami5** [comment]
Nice, let me tested
