### ISSUE TITLE
Enable an option to show completion on backspace(delete) and InsertEnter Event

### ISSUE THREAD

**Issue by ratheesh** [hrsh7th/nvim-compe#172]
Thanks for the wonderful Plugin.

I observe that the completion menu does not show when backspace is pressed or when insert mode is entered (by entering a,I,i etc). I don't see that in documentation as well.

This is supported in deoplete. It will be nice to have this in this plugin as well.

Can you please add this option if it is not already supported or let me know how to configure this?

**Comment by hrsh7th** [comment]
It's reasonable.
I will consider it.
