### ISSUE TITLE
Idiomatic filetype handling

### ISSUE THREAD

**Issue by cbarrete** [hrsh7th/nvim-compe#174]
Currently, users can configure filetypes per source with something like `g:compe.source.omni = { 'filetypes': ['tex'] }`.

This is fine but a bit unidiomatic considering that Vim already has filetype plugins (`:h ftplugin-overrule`) and autocommands (`:h autocmd`). It seems wasteful to me to register all sources and then check if the current filetype is relevant for each of them when we complete. On the other hand, it would be nice if users directly registered specific sources for specific filetypes, with a default (e.g. for path and buffer completion) in their `init.{lua,vim}` (or whatever that is sourced there).

Technically this is already possible of course, but there's still waste with filetype handling in compe and in sources. It also helps avoiding relying on source authors to decide what default filetypes should be (e.g. https://github.com/cbarrete/completion-vcard defaults to the `mail` filetype, but some users might have different preferences). If the user changes the filetypes, it might as well be done in the Vim way rather than a compe specific way that requires to check every time we complete something.

What do you think @hrsh7th? :)

**Comment by hrsh7th** [comment]
I think your hoping solution also can be realized in current compe.

compe has buffer configuration so the below setting will be worked as your expectation.

```viml
autocmd FileType tex call compe#setup({
  'source': {
    'omni': v:true
  }
}, 0)
```

**Comment by cbarrete** [comment]
Yes I agree, and I already do that, but there are two problems in my opinion:

1. Maybe it doesn't align with the source filetype, so I need more configuration. For example, imagine that I have a source for C, that I also want to use for C++. In `after/ftplugin/cpp.vim` I call `compe#setup({'source': {'my_super_c_source': v:true}}, 0)`. Now I still need to edit the filetypes in `g:compe.source.omni`. It's not *terrible*, but redundant.

2. More importantly, if Vim can do that, why should compe do it? IMO it should do as little as possible if it can leverage native features. And especially, why should compe check the filetype every time the text is changed? That's wasteful and unnecessary.

**Comment by hrsh7th** [comment]
The reason is just backward compatibility for now, I think.

And I think the way will be ugly when using Lua.

**Comment by cbarrete** [comment]
>backward compatibility

I agree with this, but also this is a performance issue that can't be fixed without breaking compatibility. And if you want to fix it one day, it might as well be now. People who use Neovim 0.5 expect that things can break. After 0.5 becomes stable, I expect more people to start using compe and to expect it to be stable.
Of course it's your project so you decide what you want to do, but if it is not "fixed" now, there will probably not be a better time later.

Also I don't think that it would break compatibility. If we just ignore the `filetypes` field in sources, it won't break the current ones, they will just be applied to all filetypes by default. For most sources it's fine, and we can easily modify the few exising ones for which it matters. (again, the longer the wait, the harder the switch)

>And I think the way will be ugly when using Lua.

Yeah, I agree with this, until https://github.com/neovim/neovim/issues/12670 is merged. But in the long run it will be fine using Lua, just call `require('compe').setup({...})` in `after/ftplugin/*.lua`. Also https://github.com/neovim/neovim/pull/12378 should be merged soon. The people can do something like `vim.define_autocmd({event = 'FileType', pattern = 'cpp', callback = function() require('compe').setup{...}}))`, which is already pretty cool! It's almost like the current way in compe, but native and without dealing with a custom table/dict.

**Comment by hrsh7th** [comment]
I think this point does not hit to performance...?
If you had profiled it, I hope to know it.

**Comment by cbarrete** [comment]
You're right, I shouldn't have said that without profiling and it's surely fine in practice, still it's weird to me to instantiate/check all sources on each text modification when we can know in advance which ones are relevant for the current file. That, and I'd prefer using native filetype management and not have to adjust the sources default filetypes.

Anyways, I won't waste more of your time with this, if you disagree with me that's fine, compe still works well without this suggestion so feel free to close the issue :)

**Comment by cloggier** [comment]
@cbarrete I agree with you and did not realise this is what compe does. If compe could not perform this check on each keystroke then it definitely will be an improvement.

**Comment by hrsh7th** [comment]
I agree with @cbarrete too.
I'm just clarifying and worrying breaking changes.

I just think performance is not a reason.

**Comment by cloggier** [comment]
@hrsh7th You definitely should not worry about breaking changes at that stage, especially before 0.5.0 is released. @cbarrete made a very good point there.

Go ahead, make all the breaking changes you want now. Probably what's enough it just a Notice section in readme, like this one here for example https://github.com/nvim-lua/lsp-status.nvim#notices

**Comment by hrsh7th** [comment]
In VimL.
```viml

" default config.
let g:compe = {}
let g:compe.enabled = v:true
let g:compe.min_length = 1
let g:compe.source = {}
let g:compe.source.buffer = v:true
let g:compe.source.path = v:true
let g:compe.source.calc = v:true

" specific filetype config.
autocmd FileType tex,vim,typescript * call compe#setup({
\   'source': extend({
\     'nvim_lsp': v:true
\   }, g:compe.source)
\ }, 0)
```

**Comment by hrsh7th** [comment]
I'm closing it because I manage breaking-changes in v3 on #122
