### ISSUE TITLE
Spelling suggestions look weird after #158

### ISSUE THREAD

**Issue by echasnovski** [hrsh7th/nvim-compe#175]
![nvim-compe_issue_spelling-suggestions](https://user-images.githubusercontent.com/24854248/107847041-07c79b80-6df1-11eb-9f70-1bf3b81ab902.gif)

This happens on e63d976929c73f48bd7d05a932aa188d6e94e080 and doesn't happen on bef454eecc11fb13e5bc3f29f443f495904470ef

**Comment by cloggier** [comment]
Can confirm.

**Comment by hrsh7th** [comment]
This problem is very important.
