### ISSUE TITLE
[Question] Can't get priority to work for build-in sources?

### ISSUE THREAD

**Issue by ckipp01** [hrsh7th/nvim-compe#176]
My apologies if I missed this somewhere but I couldn't find it without diving into the code. Is the situation where you have multiple completion sources, is there a way to favor one source over another? For example I often have buffer turned on when also while having nvim_lsp as a source. The vast majority of the time, I want to favor the LSP completion options over the buffer ones. Here is an example:

<img width="934" alt="Screenshot 2021-02-13 at 11 38 58" src="https://user-images.githubusercontent.com/13974112/107847975-59bbf180-6df0-11eb-9fc6-de2fb84a0070.png">

I'm working in a file that has a _bunch_ of buffer options that are close to what I'm wanting to complete, but there is only one actual LSP completion, and that's the one I want. I'd be awesome if there was a way to float that one up to the top. Is that currently possible?

**Comment by cloggier** [comment]
Try setting up this: https://github.com/hrsh7th/nvim-compe/blob/15ea260b40f1305258640e6dbfe11f486ebe9510/doc/compe.txt#L306

**Comment by ckipp01** [comment]
Ah, I did indeed miss that, thanks @cloggier!

However, I still can't seem to get it to work. If I'm understanding it correctly it should be something like this right?

```
    require'compe'.setup {
        enabled = true,
        debug = false,
        min_length = 1,

        source = {
            path = true,
            buffer = {priority = 2},
            vsnip = {filetypes = {'scala', 'html', 'javascript', 'lua', 'java'}},
            nvim_lsp = {
                priority = 1,
                filetypes = {'scala', 'html', 'javascript', 'lua', 'java'}
            }
        }
    }
```

I've tried swapping the priority, and no matter what, the buffer completions seem to come first.

**Comment by hrsh7th** [comment]
Hm... If this config does not affect to priority sorting. It should be a bug.

**Comment by ckipp01** [comment]
> Hm... If this config does not affect to priority sorting. It should be a bug.

When I get a bit of time I'll to get a better minimal reproduction with Lua so it's easier to reproduce.

**Comment by hrsh7th** [comment]
The similar issue (https://github.com/hrsh7th/nvim-compe/issues/179) has closed.
Is this issue still happen?

**Comment by ckipp01** [comment]
Just checked and it is indeed fixed. Thanks!
