### ISSUE TITLE
Priority issues

### ISSUE THREAD

**Issue by kristijanhusak** [hrsh7th/nvim-compe#179]
Hi,

today while working in go I noticed that order of the results is not good. For example, see this screenshot:

![screenshot](https://i.imgur.com/SkZLZxs.png)

For some reason, `tag` source came in first, even though there's a `Variable LSP` that is an exact match on 4th item. Also, LSP has priority of 1000, where tag has priority of 90.

Do you know what can be an issue here? Thanks!

**Comment by hrsh7th** [comment]
It seems completely broken 🤣 
Thank you. I will investigaye it...

**Comment by kristijanhusak** [comment]
Ok, thanks. It happens also with buffer autocompletion being prioritized:

![screenshot](https://i.imgur.com/ySOOteO.png)

So I assume it's general prioritization issue.

**Comment by hrsh7th** [comment]
I have gopls environment. Thank you. I will test with,this situation.

**Comment by hrsh7th** [comment]
Hm... I can't repro... It's very weird...

**Comment by kristijanhusak** [comment]
How can I help debug this?

**Comment by hrsh7th** [comment]
If you can create minimal config based on https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim, It's very helpful.

Or just provide your full config for it.

**Comment by kristijanhusak** [comment]
Ok, I'll do that today.

**Comment by kristijanhusak** [comment]
From what I found, it has to do something with these settings in my config:

```lua
vim.o.smartcase = true
vim.o.ignorecase = true
vim.o.tagcase = 'smart'
```
When I comment them out in my config, it works fine.

For some reason I'm not able to reproduce the same thing in minimal vimrc. I'll continue trying, but posting what I found so far so you maybe can get an idea what's the issue.

**Comment by kristijanhusak** [comment]
Ok, i managed to do it with min vimrc.

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

set rtp+=/home/kristijan/.config/nvim/packa/packager/start/nvim-compe
set rtp+=/home/kristijan/.config/nvim/packa/packager/start/nvim-compe/after
set rtp+=/home/kristijan/.config/nvim/packa/packager/start/nvim-lspconfig
set rtp+=/home/kristijan/.config/nvim/packa/packager/start/nvim-lspconfig/after

lua << EOF
  require'lspconfig'.gopls.setup{}
  vim.o.smartcase = true
  vim.o.ignorecase = true
  vim.o.tagcase = 'smart'
	require'compe'.setup({
  enabled = true,
  debug = false,
  min_length = 1,
  preselect = 'disable',
  source = {
    path = true,
    buffer = { ignored_filetypes = {'sql'} },
    tags = { ignored_filetypes = {'sql'} },
    vsnip = true,
    nvim_lsp = true,
    vim_dadbod_completion = true,
    nvim_lua = false,
    calc = true,
    treesitter = true,
    ripgrep = true,
  }
})
EOF
```

Note that I add to rtp instead of plug, since I wasn't able to reproduce it with plug for some reason.
Also I moved `nvim/pack` to `nvim/packa` to make sure none of the other packages are loaded.

![screenshot](https://i.imgur.com/2UgpkEg.png)

**Comment by hrsh7th** [comment]
Thx. I'll test it.

**Comment by hrsh7th** [comment]
Hm.... It's very weird...

I can't repro with folllowing config.

```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

" execute 'set runtimepath+=' . s:plug_dir
" call plug#begin(s:plug_dir)
" Plug 'hrsh7th/nvim-compe'
" Plug 'neovim/nvim-lspconfig'
" call plug#end()
" PlugInstall | quit

set rtp+=/tmp/plugged/vim-plug/nvim-compe
set rtp+=/tmp/plugged/vim-plug/nvim-compe/after
set rtp+=/tmp/plugged/vim-plug/nvim-lspconfig
set rtp+=/tmp/plugged/vim-plug/nvim-lspconfig/after

lua << EOF
  require'lspconfig'.gopls.setup{}
  vim.o.smartcase = true
  vim.o.ignorecase = true
  vim.o.tagcase = 'smart'
	require'compe'.setup({
  enabled = true,
  debug = false,
  min_length = 1,
  preselect = 'disable',
  source = {
    path = true,
    buffer = { ignored_filetypes = {'sql'} },
    tags = { ignored_filetypes = {'sql'} },
    vsnip = true,
    nvim_lsp = true,
    vim_dadbod_completion = true,
    nvim_lua = false,
    calc = true,
    treesitter = true
  }
})
EOF
```

**Comment by kristijanhusak** [comment]
I'm really sorry. I had a bit outdated version (was on commit 75f629a3ec2b1c097e882c0ca62dc80dedd0f289). I completely forgot that I didn't ran update.
After I did an update everything worked out fine.
Sorry once more for bothering, and thanks for help.

**Comment by hrsh7th** [comment]
Thank you very much work.

I had found some of bugs while in this investigation. So this issue was helpful to me.

**Comment by kristijanhusak** [comment]
Great! At least I helped somehow :)

**Comment by Chaitanyabsprip** [comment]
how do I set the priority for completion options?
I want snippets to come before LSP and then everything and anything else

**Comment by seblj** [comment]
> how do I set the priority for completion options?
> I want snippets to come before LSP and then everything and anything else

You can use something like this:

```Lua
    source = {
        nvim_lsp = true,
        luasnip = {
            priority = <number>,
        },
    },
```

From what I could see nvim_lsp has a priority fo 1000 by default, so if you set the priority of the snippet to higher than 1000, it should work
