### ISSUE TITLE
Should trigger on backspace

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#18]

**Comment by hrsh7th** [comment]
We should check backspace by `TextChangedI,P` with `col('.')`...?

**Comment by tami5** [comment]
Oh thats smart, more progressive then check backspace

**Comment by hrsh7th** [comment]
It should be fixed by https://github.com/hrsh7th/nvim-compe/commit/b51b699a4c906876f60480e09f69299d14904b4a

**Comment by tami5** [comment]
Works very well
