### ISSUE TITLE
nvim-compe in opt dir, not work

### ISSUE THREAD

**Issue by hamsterBiscuit** [hrsh7th/nvim-compe#181]
https://user-images.githubusercontent.com/19209958/107871787-b34f1980-6edf-11eb-8cd6-d1b4cfd85818.mp4

see this video.

I use packadd to use it ,but is not work

**Comment by hrsh7th** [comment]
I think it relates with https://github.com/vim/vim/issues/1994

I have no idea for it (and I don't try it) Sorry.

**Comment by hamsterBiscuit** [comment]
OK,thanks.
It looks like this.
thanks for this.
