### ISSUE TITLE
Completion preview doesn't automatically disappear

### ISSUE THREAD

**Issue by BigfootN** [hrsh7th/nvim-compe#182]
Hello,

I don't know if this issue is specifically due to this plugin or `neovim` in general.

Sometimes I notice that when I see a preview of the completion list, it doesn't disappear automatically. I have no problem completion list, only with the preview of the hovered item in the list.

I don't really know precisely what makes it disappear. Sometimes it does, and sometimes it doesn't.

You can see an example here (`clangd`), hoping it helps:

![2021-02-14-151332_475x121_scrot](https://user-images.githubusercontent.com/1183923/107879179-9adb0100-6ed7-11eb-968b-3c59cfe96ca1.png)

As you can see the completion menu disappeared but not the preview.

### neovim version
NVIM v0.5.0-dev+1085-g52397aaa0
Build type: RelWithDebInfo
LuaJIT 2.0.5

### nvim-compe version
Latest possible

Thank you very much in advance for any help

**Comment by elianiva** [comment]
FWIW I also encounter this issue while I was playing around with the documentation window. It seems to be happening randomly and hard to reproduce.

**Comment by hrsh7th** [comment]
I think this problem solve in #186 but that does not stable now.

**Comment by BigfootN** [comment]
Thank you for your answers and help.

Looking forward to #186

**Comment by hrsh7th** [comment]
I think this problem had been solved in #186

**Comment by BigfootN** [comment]
Thank you for your hard work.

I'll reopen this issue if I ever encounter another problem.

Thank your for this plugin

**Comment by BigfootN** [comment]
I'm sorry, but it seems I am still facing the same issue.

**Comment by hrsh7th** [comment]
@BigfootN I improved bunch of codes. Please re-check your problem again.
