### ISSUE TITLE
option to disable completion on backspace or improve 

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#183]
Hey, recently someone asked about completion refresh on backspace, I think its great feature however I'm having some issue with completion window opening in empty lines.

![come032](https://user-images.githubusercontent.com/65782666/107977516-4c5b5e80-6fcc-11eb-94df-2a372aa40412.gif)

**Comment by hrsh7th** [comment]
Thank you.

Currently, compe is unstable.... I will tackle it.

**Comment by tami5** [comment]
Another preview 
![comp323](https://user-images.githubusercontent.com/65782666/107979078-f50abd80-6fce-11eb-87ca-106c8c542c49.gif)

**Comment by hrsh7th** [comment]
@tami5 Is this problem still happen on latest compe ?

**Comment by tami5** [comment]
YESSSS that fixed the main issue, thanks a lot @hrsh7th 

the other preview shows a very annoying behavior, I don't know if its favorable to you or not but `Word\s<bs>` shouldn't trigger the completion window, I already wrote `Word\s` I don't want any suggestions, maybe if I do `Word\s<bs><bs>` then it make sense to trigger. 

What do you think?

**Comment by hrsh7th** [comment]
I have same opinion. It definitely can be solved. But too difficult to adjust. I will tackle it.

**Comment by hrsh7th** [comment]
I think this case had been improved in #186.

**Comment by tami5** [comment]
Thanks @hrsh7th , I'll test it out tom

**Comment by hrsh7th** [comment]
I think it can be closed.
