### ISSUE TITLE
Provide a helper-function for omni-completion

### ISSUE THREAD

**Issue by the42** [hrsh7th/nvim-compe#184]
I would be able to trigger completion using omni-completion functionality `C-x C-o`. In tried `set omnifunc=compe#complete()` but this results in an error, probably because the function signature doesn't match the expected signature `:help compl-omni`

A omni-completion helper fuinction provided by nvim-compe would be IMHO handy.

**Comment by hrsh7th** [comment]
Currently, nvim-compe provides `let g:compe.autocomplete = v:false` and `inoremap <C-Space> compe#complete()` mapping. Isn't it enough?

**Comment by elianiva** [comment]
Does remapping `<C-x><C-o>` to `compe#complete()` not enough? I never used omnicomplete so I don't know what's good about it.

**Comment by the42** [comment]
I tried the following which seems to be the right way to do:

First my config:
```
let g:compe = {}
let g:compe.enabled = v:true
let g:compe.autocomplete = v:true
let g:compe.source = {}
let g:compe.source.path = v:true
let g:compe.source.buffer = v:true
let g:compe.source.calc = v:true
let g:compe.source.vsnip = v:true
let g:compe.source.nvim_lsp = v:true
let g:compe.source.omni = v:false
inoremap <silent><expr> <C-Space> compe#complete()
set omnifunc=compe#complete() 
```

I set `let g:compe.source.omni = v:false` only to prevent a recursion problem -- just in case.

With this setup pressing `C-x C-o` results in the following error:
```
E117: Unknown function: compe#complete()
```

although for the current buffer nvim-compe works (buffer completion)

**Comment by hrsh7th** [comment]
You should remove `set omnifunc=compe#complete()`.
You can use `inoremap <expr> <C-x><C-o> compe#complete()` instead.

**Comment by the42** [comment]
This works. I think though that assign a custom compe-provided function  to omnifunc would be more 'idiomatic'.

**Comment by hrsh7th** [comment]
I don't think it is idiomatic.
because omni completion can't realize fuzzy matching, documentation, confirm.

**Comment by voyeg3r** [comment]
> You should remove `set omnifunc=compe#complete()`.
> You can use `inoremap <expr> <C-x><C-o> compe#complete()` instead.

How would be the mapping in lua?
