### ISSUE TITLE
No definition/description during autocomplete with the Deno LSP

### ISSUE THREAD

**Issue by David-Else** [hrsh7th/nvim-compe#187]
The `tsserver` lsp (https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#tsserver) shows a definition of the function during autocomplete:

![tsserver-definition-in-autocomplete](https://user-images.githubusercontent.com/12832280/108098305-1f19b980-707b-11eb-9dfc-ea8d0cee8394.png)

but the `denols` lsp (https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#denols) does not:

![denols-fetch-no-definition-in-autocomplete](https://user-images.githubusercontent.com/12832280/108098334-25a83100-707b-11eb-92f4-63a2805f9454.png)

but the definition is there as it is shown when `K` (`lua vim.lsp.buf.hover()`) is pressed:

![denols-fetch-definition](https://user-images.githubusercontent.com/12832280/108098367-3062c600-707b-11eb-857c-fdcad5bcc291.png)

Is this a problem with `nvim-compe` or the `denols`? Thanks.

NVIM v0.5.0-dev+1089-gdc3ca16a9 (updated today to latest version)
nvim-compe (updated today to latest version)

**Comment by elianiva** [comment]
`denols` doesn't provide documentation for the completion item so `nvim-compe` can't display it. Here's what `tsserver` gave to `nvim-compe`
```lua
{
  commitCharacters = { ".", ",", "(" },
  data = {
    entryNames = { "fetch" },
    file = "/home/elianiva/codes/scratch/caesar.ts",
    line = 27,
    offset = 3
  },
  detail = "function fetch(input: RequestInfo, init?: RequestInit): Promise<Response>",
  insertTextFormat = 2,
  kind = 3,
  label = "fetch",
  sortText = "5"
}
```
compared to what `denols` gave
```lua
{
  insertTextFormat = 2,
  kind = 3,
  label = "fetch",
  sortText = "5"
}
```

Pretty sure it's in `denols`'s todo list, we'll have to wait, I guess.

**Comment by hrsh7th** [comment]
@elianiva Thank you for your work. I'm very saved to your work around issue responsing.

**Comment by David-Else** [comment]
Good news, it now works with the latest version of Deno. Bad news, the formatting of the text looks bad, big empty grey area at the top.

![Screenshot from 2021-04-24 09-45-31](https://user-images.githubusercontent.com/12832280/115953243-35604d80-a4e2-11eb-80c9-33d682e75d91.png)

**Comment by hrsh7th** [comment]
Hm... OK. I will check it. Thank you.

**Comment by David-Else** [comment]
There is a new issue for the bad formatting https://github.com/hrsh7th/nvim-compe/issues/373

The issue with no definition/description during autocomplete with the Deno LSP seems solved so I will close the issue.
