### ISSUE TITLE
Parentheses not included on method completion

### ISSUE THREAD

**Issue by jemag** [hrsh7th/nvim-compe#189]
## Description 
Selecting a method within the completion items will not add parentheses, which will then require the user to add them manually.

So far I have seen it happen with Typescript, Java and Go.

Version: 3ce7f98158e604d4578f44ed4181b6f9a4d37900

## Reproduction
I have done a quick minimal config to reproduce it with Go:
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-compe'
Plug 'neovim/nvim-lspconfig'
call plug#end()
PlugInstall | quit

set completeopt =menuone,noinsert,noselect
let g:compe = {}
let g:compe.enabled = v:true
let g:compe.autocomplete = v:true
let g:compe.debug = v:false
let g:compe.min_length = 1
let g:compe.preselect = 'enable'
let g:compe.throttle_time = 80
let g:compe.source_timeout = 200
let g:compe.incomplete_delay = 400
let g:compe.max_abbr_width = 100
let g:compe.max_kind_width = 100
let g:compe.max_menu_width = 100
let g:compe.documentation = v:true

let g:compe.source = {}
let g:compe.source.path = v:true
let g:compe.source.buffer = v:true
let g:compe.source.calc = v:true
let g:compe.source.vsnip = v:true
let g:compe.source.nvim_lsp = v:true
let g:compe.source.nvim_lua = v:true
let g:compe.source.spell = v:true
let g:compe.source.tags = v:true
let g:compe.source.snippets_nvim = v:true
let g:compe.source.treesitter = v:true
let g:compe.source.omni = v:true
inoremap <silent><expr> <C-Space> compe#complete()
inoremap <silent><expr> <CR>      compe#confirm('<CR>')
inoremap <silent><expr> <C-e>     compe#close('<C-e>')
inoremap <silent><expr> <C-f>     compe#scroll({ 'delta': +4 })
inoremap <silent><expr> <C-d>     compe#scroll({ 'delta': -4 })
lua <<EOF
require'lspconfig'.gopls.setup{
  on_attach = on_attach_common
}

EOF
```

## Usefulness

This is usually the default behavior for most completion engines, I believe it would be useful, if only for the repeated time saving it allows.

**Comment by hrsh7th** [comment]
The snippet expansion is supported. You can found the way to enable it on https://github.com/hrsh7th/nvim-compe#how-to-use-lsp-snippet

**Comment by jemag** [comment]
> The snippet expansion is supported. You can found the way to enable it on hrsh7th/nvim-compe#how-to-use-lsp-snippet

I am confused, do you mean that snipped expansion is required for simply having parentheses on function/method completion? 



What I mean is simply getting parentheses when selecting such a method/function. For example, here I am selecting the Fatal function in Go : 
![image](https://user-images.githubusercontent.com/7985687/108150758-32407f80-70a3-11eb-9022-8ea5791628ad.png)

And upon selection, parentheses will not be there:
![image](https://user-images.githubusercontent.com/7985687/108150783-41273200-70a3-11eb-99f1-28023d29e7c4.png)


What I would expect upon selection would be for the parentheses to be already there with the cursor neatly placed in-between, like so:
![image](https://user-images.githubusercontent.com/7985687/108150837-6025c400-70a3-11eb-8ef3-464709c675e1.png)

**Comment by hrsh7th** [comment]
If we add `just adding parenthese`, it will be following behavior.

```
fmt.P|<Tab>
↓↓↓
fmt.Println()|
// `|` is cursor
```

But I think you want to move cursor to inside a parenthese like below.

```
fmt.P|<Tab>
↓↓↓
fmt.Println(|)
// `|` is cursor
```

I think the last one is just snippet behavior.

**Comment by hrsh7th** [comment]
In LSP, your intented behavior is realized by `snippet`.

You should enable snippet like  https://github.com/hrsh7th/nvim-compe#how-to-use-lsp-snippet

**Comment by thallium** [comment]
Could you explain a bit further how to create lsp snippet and use it?

**Comment by thallium** [comment]
It works as intended in completion-nvim and coc.nvim. However, clangd can put the cursor inside a parenthese in nvim-compe. I'm not sure if this is a bug?

**Comment by cloggier** [comment]
@thallium did you enable snippet support for that language server?

**Comment by thallium** [comment]
I did what is described in https://github.com/hrsh7th/nvim-compe#how-to-use-lsp-snippet, anything else to be done?

**Comment by mackarelfish** [comment]
> I did what is described in https://github.com/hrsh7th/nvim-compe#how-to-use-lsp-snippet, anything else to be done?

Mine seems to work just fine, are you sure that you installed and enabled vsnip?

**Comment by thallium** [comment]
> > I did what is described in https://github.com/hrsh7th/nvim-compe#how-to-use-lsp-snippet, anything else to be done?
> 
> Mine seems to work just fine, are you sure that you installed and enabled vsnip?

Never mind, it's working now... Don't know what happened.

**Comment by jemag** [comment]
@hrsh7th thank you for the clarification. I did not know that this behavior was implemented through snippet. Previously the other completion engines I used just had the behavior out of the box. 

Perhaps a small note regarding snippet requirement for method/function parentheses in the FAQ could be useful for other newcomers. 

Thanks again

**Comment by hrsh7th** [comment]
The documentation improvements are welcome. Good to hear solved your original issue.
