### ISSUE TITLE
Should source have filetype parameter? 

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#19]
I notice coc provide filetype praameter when regesting sources. Is this something to consider. I'm not sure

```
function! coc#source#iced#init() abort
  return {
        \ 'priority': 3,
        \ 'shortcut': 'iced',
        \ 'filetypes': ['clojure'],
        \ }
endfunction
```

**Comment by hrsh7th** [comment]
In my random thoughts, we should return empty dict by `Source:datermine` if the filetype didn't expect.

But your suggestion seems reasonable to me.

**Comment by tami5** [comment]
> In my random thoughts, we should return empty dict by Source:datermine if the filetype didn't expect.

That's works as well, but to support the ease of creating sources, this should be added.

**Comment by hrsh7th** [comment]
Implement https://github.com/hrsh7th/nvim-compe/commit/f9072b099618b9e6461b85f080e44e080968025a

**Comment by tami5** [comment]
Nice @hrsh7th  thanks a lot, I'm about to create vim-iced source so this is very helpful
