### ISSUE TITLE
How to enable floating signature window when typing parameter

### ISSUE THREAD

**Issue by vpeopleonatank** [hrsh7th/nvim-compe#191]
Like this
![image](https://user-images.githubusercontent.com/30976876/108323872-c3296f00-71f9-11eb-99aa-8b1052c0951d.png)

**Comment by hrsh7th** [comment]
Sorry. The LSP spec's signature help feature is out of scope.
It should be supported by other LSP-related plugins.

**Comment by tami5** [comment]
nvim-compe is a completion framework with some "complimentary" integrations with lsp like info/doc, browse window c-f/c-d, snippets, if you like to have this you can do it yourself, it isn't that hard:

```viml
nn <c-s> :lua vim.lsp.buf.signature_help()<cr> 
autocmd CursorHoldI * call v:lua.vim.lsp.buf.signature_help()
```

or use [lspsaga.nvim](https://github.com/glepnir/lspsaga.nvim) like I do

![](https://i.imgur.com/ze7IKiW.png)

cc @hrsh7th lspsaga has an awesome highlight with dark background enabled by border, it may be worth looking into, it looks amazing
![](https://i.imgur.com/pKPn5CO.png)

**Comment by vpeopleonatank** [comment]
@tami5 I also use lspsaga.nvim. Can you share your signature_help config of lspsaga to show floating window above function name like this. ![image](https://camo.githubusercontent.com/271feebd13c2c1ae885d7328880b72aae5a6ee155ce3e8df37370ea4197b34b6/68747470733a2f2f692e696d6775722e636f6d2f7a6537494b69572e706e67)

This is mine: when call `lua require('lspsaga.signaturehelp').signature_help()`
![image](https://user-images.githubusercontent.com/30976876/108371833-bd9b4b80-7230-11eb-801e-3aa7fd011b7e.png)

**Comment by tami5** [comment]
@vpeopleonatank oh I think this limited by the amount of text the server returns, here a custom function with no docs. 

@glepnir do you think its best to have a specific/limit size of help signature window to serve as "signature help" and not another way to hover? I believe signature help should do its purpose and not provide a huge lines of documentation. maybe an option idk, what do you see?

**Comment by glepnir** [comment]
should be add limit，add it tomorrow

**Comment by ray-x** [comment]
In case anyone want this feature. I ported completion-nvim `signature while typing parameter` feature to this plugin:
https://github.com/ray-x/lsp_signature.nvim
