### ISSUE TITLE
Not showing all available LSP completions

### ISSUE THREAD

**Issue by jose-elias-alvarez** [hrsh7th/nvim-compe#192]
First: thanks for all of your work on this plugin. It's one of the main reasons I've been able to switch to Neovim's LSP for most of my work.

I've been having an issue with LSP completions from [typescript-language-server](https://github.com/theia-ide/typescript-language-server). For some objects, nvim-compe only shows one completion, but completion.nvim shows all available completions.

This is from nvim-compe:

<img width="406" alt="Screen Shot 2021-02-19 at 3 08 07 PM" src="https://user-images.githubusercontent.com/54108223/108464914-5cbd5300-72c4-11eb-87c2-535ebf5acf4b.png">

And this is the same object using completion.nvim (which matches what VS Code shows): 

<img width="406" alt="Screen Shot 2021-02-19 at 3 10 49 PM" src="https://user-images.githubusercontent.com/54108223/108465076-ac038380-72c4-11eb-9d2d-36b52f29d140.png">

The issue occurs when using the following minimal nvim-compe configuration:
`
require"compe".setup {
    source = {
        nvim_lsp = true
    }
}
`

Let me know if I can provide any more information.

**Comment by hrsh7th** [comment]
It's bug. I will fix it by #186

**Comment by jose-elias-alvarez** [comment]
I see. Thanks for the quick reply!

**Comment by hrsh7th** [comment]
It should be fixed.

**Comment by jose-elias-alvarez** [comment]
![Screen Shot 2021-02-23 at 12 04 01 AM](https://user-images.githubusercontent.com/54108223/108726407-bb0b5f80-756a-11eb-9be8-3f54e3456126.png)

Working beautifully, thank you so much!
