### ISSUE TITLE
API for enabling a source

### ISSUE THREAD

**Issue by Julian** [hrsh7th/nvim-compe#195]
Hi.

Given a custom source, calling `compe.register_source` registers the source, but doesn't enable it.

This was surprisingly tricky for me to figure out (why my source wasn't producing additional results no matter how simple I made it), though in retrospect I guess it seems silly.

It'd be nice to both document that in `register_source` (that the source is not autoenabled), but then also would be nice to have an explicit API to do the enabling. From what I can tell reading the source, the way to do so programmatically, assuming someone has called `compe.setup` already, is to do something like `require'compe.config'.get().source[name] = { disabled = false }`

**Comment by sblumentritt** [comment]
Well as you already said `register_source` registers the source which the name implies. 😄 From the function name is should be clear that the source is not enabled as it is not something like `register_and_enable_source`.

----

A question to the explicit source enabling. You want an API to force-enable your source even when a user just downloads your source (via a plugin manager) without enabling it in the `compe.setup` step? This seems to be really inconvenient and goes against the current plugin flow. I can also not see any benefit for providing such an API but maybe you can enlighten me.

**Comment by Julian** [comment]
Fair enough thanks.
