### ISSUE TITLE
Autoimport not working with tsserver and default compe config

### ISSUE THREAD

**Issue by at74S6v** [hrsh7th/nvim-compe#196]
I'm using built-in LSP, the latest `nvim-lspconfig`, and `typescript-language-server` on Windows 10. Compe configured with default configs. [Vimconfig](https://pastebin.com/7SLwjnYb)

Autocomplete suggestions are completely fine and way better than completion-nvim, but autoimport is not working at all. [Here](https://gifyu.com/image/VXcr) I'm trying to reproduce autocomplete demo gif.

Nvim version `NVIM v0.5.0-dev+1083-g1aec5ba85`

Any ideas?

**Comment by tami5** [comment]
It doesn't work with rust server as well

**Comment by at74S6v** [comment]
> It doesn't work with rust server as well

So it's a known issue?

**Comment by tami5** [comment]
Maybe not supported by nvim-compe idk.

**Comment by at74S6v** [comment]
> Maybe not supported by nvim-compe idk.
It seems working for JS on this [demo ](https://github.com/hrsh7th/nvim-compe#auto-import)

**Comment by tami5** [comment]
Okay it's a server thing, 

> And the auto import completions, enabled with the rust-analyzer.completion.autoimport.enable setting and the corresponding LSP client capabilities. Those are the additional completion options with automatic use import and options from all project importable items, fuzzy matched agains the completion imput.

now I have auto import

**Comment by elianiva** [comment]
you need to call `compe#confirm` to resolve the autoimport

**Comment by mackarelfish** [comment]
Mine seems to work just fine, make sure to bind the confirm key (mine bound to `<Tab>`) to `compe#confirm` just like @elianiva commented.
![](https://i.imgur.com/Uir2CCU.gif)

**Comment by at74S6v** [comment]
@mackarelfish @elianiva thanks, but no luck, unfortunately. I have remapped `compe#confirm` to `<Tab>` and removed all other tab bindings to double-check. 

https://user-images.githubusercontent.com/58348048/108621285-db3fff00-7442-11eb-8458-a0890a162c91.mp4


I'm going to try with minimal nvim config now. 

Current `compe` bindings: 
`inoremap <silent><expr> <C-Space> compe#complete('<C-Space>')
inoremap <silent><expr> <Tab>      compe#confirm('<CR>')
inoremap <silent><expr> <C-e>     compe#close('<C-e>')
inoremap <silent><expr> <C-f>     compe#scroll({ 'delta': +4 })
inoremap <silent><expr> <C-d>     compe#scroll({ 'delta': -4 })`

`Lsp-config` https://pastebin.com/bu8UJc1E

**Comment by at74S6v** [comment]
Ok, so minimal `vimconfig` makes no difference, but removing `jsconfig.json` does - npm modules and project-wide functions exports suggestions disappear from autocompletion. Seems like LSP / Tsserver issue, anyone got it working with the `create-react-app` project (without TS)?

**Comment by at74S6v** [comment]
Adding `"checkJs": true` in `jsconfig.json` helped me to get the `Cannot find name` diagnostic error with working import code action, but autoimport still not working. 
Compe.debug doesn't throw any errors.

**Comment by hrsh7th** [comment]
I don't use `.js` file.
if you can get the correct result with `.ts`, it should be Language server related problem.

**Comment by at74S6v** [comment]
> I don't use `.js` file.
> if you can get the correct result with `.ts`, it should be Language server related problem.

Same thing with `.ts` files and different projects. No errors in the server logs as well, code action import works absolutely fine. Any ideas on how to find the cause?

**Comment by hrsh7th** [comment]
Could you peovide minimal config based on https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim ?
I can't reproduce it.

**Comment by kettttt** [comment]
For me, I use the same config on windows and macos. On macos it work fine, but on windows it's not working.

**Comment by hrsh7th** [comment]
Hm. I have no windows environment...

@kettttt Thank you for your information. It's very helpful.
Are you using another language server on windows?
If so, please tell me this problem only happens in tsserver or not.

**Comment by at74S6v** [comment]
@hrsh7th 
[Here](https://pastebin.com/9k6rnmAt) it is. Suggestions and code actions are working well with minimal setup.
I am using [this](https://github.com/creepinson/typescript-template) template to test TypeScript project. 
Also, I can send you a short log file from tsserver if it helps.

**Comment by kettttt** [comment]
> Are you using another language server on windows?


No. I'm using the same Language server on windows and macos.

**Comment by hrsh7th** [comment]
@at74S6v Thank you very much.
I sent PR for testing (#200). Could you provide a displayed message with this PR?

@kettttt Sorry for my poor English. I want to know compe is not able to auto-importing even if the user uses another language server on windows.

**Comment by at74S6v** [comment]
@hrsh7th 
Can confirm: minimal config + default `pyright` setup autoimport works flawlessly.

**Comment by hrsh7th** [comment]
Thank you so this problem depends on the Language server... 😢

**Comment by at74S6v** [comment]
> @at74S6v Thank you very much.
> I sent PR for testing (#200). Could you provide a displayed message with this PR?
> 

Here is my result on the TS project https://pastebin.com/0dtjB5Cs

**Comment by hrsh7th** [comment]
@at74S6v The issue has found in https://github.com/theia-ide/typescript-language-server/issues/135 ...

**Comment by at74S6v** [comment]
> @at74S6v The issue has found in [theia-ide/typescript-language-server#135](https://github.com/theia-ide/typescript-language-server/issues/135) ...

Huge thanks! How did I miss this... Dug through all issues on every involved plugin. Manual fix from https://github.com/theia-ide/typescript-language-server/issues/135#issuecomment-570519535 works!

Finally, my nvim is complete, thank you so much!

**Comment by cloggier** [comment]
> Finally, my nvim is complete, thank you so much!

Could be a good slogan for compe - "completes your Neovim", or something like that. :)
