### ISSUE TITLE
Issues completion with /

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#20]
Hey @hrsh7th I'm thinking there some issues with completion when typing / . You can see in the gif that typing str/ stop completion but pasting str/ bring the completion back for items under the prefix. 

![](https://i.imgur.com/c4rZ106.gif)

Do you think something builtin is conflicting with the source?

Thanks

**Comment by hrsh7th** [comment]
Probably, it means should handle the `/` as a trigger character.

(I couldn't get the `str/index-of` item from vim-iced...)


Could you try it?
```
function! s:datermine(context) abort
  let l:offset = compe#pattern#get_offset(a:context, '[[:alnum:]!$&*\-_=+:<>./?]\+$')
  if l:offset > 0
    return {
    \   'keyword_pattern_offset': l:offset,
    \   'trigger_character_offset': index(['/'], a:context.before_char) >= 0 ? a:context.col : -1
    \ }
  end
  return {}
endfunction
```

**Comment by hrsh7th** [comment]
If you want to debug more easily, I will add the debug API for custom source.

**Comment by tami5** [comment]
> Could you try it?

Awesome will do that and report back.

> debug API

Definitely, I plan to develop another source that would integrate some sort of english dictionary with definitions. So debug helpers willllll be extremely valued.

**Comment by tami5** [comment]
Awesome it worked very well thanks. I didn't expected to be something wrong with the determine function.

@hrsh7th I just noticed that you didn't get str/ completion, sorry I forgot to mention that you must first require it `(ns project.core (:require [clojure.string :as str]))` in order to get it working.
