### ISSUE TITLE
Error message on complete

### ISSUE THREAD

**Issue by yech1990** [hrsh7th/nvim-compe#201]
![image](https://user-images.githubusercontent.com/5415510/108765080-55c96580-758e-11eb-9610-a74dcc98c0e9.png)

```
E5108: Error executing lua ...vim/site/pack/packer/opt/nvim-compe/lua/compe/source.lua:63: attempt to index local 'state' (a nil value) 
```

**Comment by hrsh7th** [comment]
@yech1990 `require"compe"._complete` is private function. Why do you using that?

And I can't reproduce it.
You should provide more detailed information if you hope to solve it.

**Comment by yech1990** [comment]
Thank you @hrsh7th, this message appear when there is not complete choice. 

I post my configuration on github, could me help me to check it out at link: https://github.com/yech1990/myneovim.lua

**Comment by hrsh7th** [comment]
@yech1990 Thank you for your information. But this problem already solved, I think.

Could you test with latest master?

**Comment by hrsh7th** [comment]
Your configuration seems good.

**Comment by yech1990** [comment]
Thank you for your help. I will test the lastest release now and let you
know if I have any questions.

**Comment by yech1990** [comment]
Hi @hrsh7th,

I'm sorry to have disturbed you. I still have a small problem in using `nvim-compe`. `source.spell` has been set to be true in my configuration, but I still can not get the [Spell] complete from `nvim-compe` plugin.

**Comment by hrsh7th** [comment]
@yech1990 You should set `set spell` in your vimrc to enable spell source.

**Comment by yech1990** [comment]
Hi hrsh7th, I wonder is there a way to enable Spell source without enabling spell check in vim?

**Comment by yech1990** [comment]
https://user-images.githubusercontent.com/5415510/108808505-bb930d00-75e1-11eb-9ab3-ff1e9bff5980.mp4

**Comment by hrsh7th** [comment]
I don't know. the spell source uses `spellsuggest` function that vim's builtin-function.
