### ISSUE TITLE
Automatically select and insert entry when there's only a single one

### ISSUE THREAD

**Issue by YorickPeterse** [hrsh7th/nvim-compe#202]
I'm using manual completion with compe, as I found this less distracting compared to auto completion. One thing I'm missing compared to coc.nvim is the automatic expansion/confirmation when there's only a single entry. 

Imagine the following input (here `|` indicates the cursor) which would expand to `foobar()`:

```
foo|
```

In coc.nvim, if I trigger completion and there's only a single match, the entry is selected and expanded automatically. This means I'd end up with:

```
foobar()|
```

With compe I instead need to do the following:

1. Trigger completion. This will show a popup with a single entry that isn't selected
2. Manually select the first and only entry
3. Confirm the selection

Would adding support for this be an option? Thanks!

**Comment by hrsh7th** [comment]
@YorickPeterse Your expected behavior is already supported by `preselect = 'always'`, I think.

**Comment by hrsh7th** [comment]
Ah... I had a misunderstanding maybe.

1. Invoke manual completion
2. Automatic expand first item (if candidates length is 1 only)

Hm..., Should we add `doautocmd User compe#completed` autocmd?
I think if it implemented the user can expand by themselves.

**Comment by YorickPeterse** [comment]
@hrsh7th The preselect option only selects the first entry, but it doesn't also inserts its text into the buffer. As such, you still need a manual confirmation.

When using auto-completion that's probably desired, but when using manual completion it results in more manual steps than should be necessary.

I'm not sure if an `autocmd` is the right option. For example, how would it detect there's only a single entry versus multiple entries?

**Comment by hrsh7th** [comment]
Sorry. I don't think it is a good feature.

#203 has contained in latest nvim-compe. Should this issue still open?

**Comment by YorickPeterse** [comment]
@hrsh7th Is there a way I could perhaps implement this manually? Probably I'd need a custom completion function that first runs `compe#confirm`, then checks if there's a single entry and if so select/expand it. Is this possible?

**Comment by hrsh7th** [comment]
1. Trigger manual completion
2. Multiple sources will be triggered (buffer / lsp, etc.)
3. First, the buffer source is completed and draws the completion-menu
4. Next, the lsp source is completed and redraws the completion-menu

How would you like it to work if there is only one completion item at timing 3?

**Comment by YorickPeterse** [comment]
@hrsh7th Good point. I guess this can be left out, as I can live with not automatically selecting the first entry. Thanks for your time! :smiley:
