### ISSUE TITLE
When using manual completion, insert the text of the first entry automatically

### ISSUE THREAD

**Issue by YorickPeterse** [hrsh7th/nvim-compe#203]
This is related to https://github.com/hrsh7th/nvim-compe/issues/202, but slightly different.

When using manual completion, triggering completion doesn't automatically insert the text of the first entry. This means manual completion requires at least two steps when you want the first entry:

1. Trigger the initial completion to show suggestions
2. Navigate to the first entry manually

It would be nice if there was a way to not just select the first entry in the menu (using the `preselect` option), but to also have its text inserted automatically.

**Comment by hrsh7th** [comment]
I think it is not good idea.
I suggest to realize it by `<CR>` and `preselect = 'always'`.

If you can't agree, please clarify it more detailed.

**Comment by YorickPeterse** [comment]
@hrsh7th That doesn't quite achieve the same ease of use, as you still need to manually confirm the first entry. Consider the following example:

```
Vec::with_|
```

Here `|` is the cursor location. When using manual completion, chances are the number of matches is small, as completion starts later compared to auto completion. In fact, I find that most of the time there are only a few matches, with the first one usually being the one I want to have inserted. Imagine that for the above example, there are two possible matches:

- `Vec::with_capacity()`
- `Vec::with_capacity_in()`

Most of the time I want `Vec::with_capacity()`. In coc.nvim this works nicely, because it matches the shortest match first. Combined with my feature request, this means that in most cases I just need to trigger completion to get my results, without also having to confirm the selection (or making the selection in the first place). Since I have completion mapped to tab, this means I can complete most code with a single key press.

With compe this isn't possible at the moment, and instead requires a more tedious process of:

1. Triggering completion (e.g. using tab)
1. Selecting the first entry yourself
1. Confirming the selection

**Comment by hrsh7th** [comment]
I think this issue fixed by https://github.com/hrsh7th/nvim-compe/commit/398b06ccc9863f068e9103a7f8403f363f0d7bcb

I don't think #202 is good but this issue is reasonable.

**Comment by YorickPeterse** [comment]
@hrsh7th Thanks! This helps a lot :smile:
