### ISSUE TITLE
fancy markdown render.

### ISSUE THREAD

**Issue by glepnir** [hrsh7th/nvim-compe#204]
![image](https://user-images.githubusercontent.com/41671631/108790814-90e08e80-75b8-11eb-9e4f-95cac166c0cb.png)

**Comment by hrsh7th** [comment]
I've updated `sumneko_lua` and `neovim` to latest master but I can't reproduce it.

Could you provide minimal config ?

**Comment by hrsh7th** [comment]
`let g:compe.debug = v:true` allows displaying error messages.
If you have time, please provide an error message to me.

**Comment by hrsh7th** [comment]
https://user-images.githubusercontent.com/629908/108801093-25a6b480-75d8-11eb-8d9a-1869c23aa014.mp4

**Comment by glepnir** [comment]
Don't know what happen. now works.

**Comment by hrsh7th** [comment]
Thank you for your confirmation.
