### ISSUE TITLE
problem: cursor abnormal

### ISSUE THREAD

**Issue by hamsterBiscuit** [hrsh7th/nvim-compe#206]
sorry my bad english. I do not know how to describe the problem.

![2021-02-23 10-22-38 2021-02-23 10_23_04](https://user-images.githubusercontent.com/19209958/108796838-ab206980-75c4-11eb-8fee-c02a029f90ce.gif)

I edit `html` DOM attribute value, Will have this problem。

I disable `compe`, and it is no problem.

Could you help me solve this problem?

thanks.

**Comment by hrsh7th** [comment]
I can't reproduce it.

Could you provide minimal config based on https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim ?

**Comment by hamsterBiscuit** [comment]
I can reproduce it.
config:
```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8
 
if &compatible
  set nocompatible
endif
 
let s:plug_dir = expand('~/.vim')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end
 
execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-compe'
call plug#end()
 
let g:compe = {}
let g:compe.enabled = v:true
let g:compe.autocomplete = v:true
let g:compe.debug = v:false
let g:compe.min_length = 1
let g:compe.preselect = 'enable'
let g:compe.throttle_time = 80
let g:compe.source_timeout = 200
let g:compe.incomplete_delay = 400
let g:compe.max_abbr_width = 100
let g:compe.max_kind_width = 100
let g:compe.max_menu_width = 100
let g:compe.documentation = v:true
 
let g:compe.source = {}
let g:compe.source.path = v:true
let g:compe.source.buffer = v:true
let g:compe.source.calc = v:true
let g:compe.source.vsnip = v:true
let g:compe.source.nvim_lsp = v:true
let g:compe.source.nvim_lua = v:true
let g:compe.source.spell = v:true
let g:compe.source.tags = v:true
let g:compe.source.snippets_nvim = v:true
let g:compe.source.treesitter = v:true
let g:compe.source.omni = v:true
```

I use neovim nightly.

**Comment by hrsh7th** [comment]
@hamsterBiscuit Don't you use language server?

**Comment by hrsh7th** [comment]
And sorry. Please reproducible `config` and `steps`.

**Comment by hamsterBiscuit** [comment]
my config, I used.
minimal config not use LSP.
it is both the problem.

**Comment by hrsh7th** [comment]
OK. I will test it.
But I want to know `reprodusible steps`.

How to reproduce this bug?

**Comment by hamsterBiscuit** [comment]
I did nothing extra.
open `html` file. and edit it.

**Comment by hrsh7th** [comment]
Thank you. I've completely understand.

This is `omni-source` related problem.
I will fix it.

**Comment by hamsterBiscuit** [comment]
like this

![2021-02-23 12-49-03 2021-02-23 12_50_14](https://user-images.githubusercontent.com/19209958/108803498-c8116880-75d5-11eb-8dac-12fcfab8777e.gif)

**Comment by hamsterBiscuit** [comment]
thank you very much

**Comment by hrsh7th** [comment]
@hamsterBiscuit I've fixed. Thank you~.
