### ISSUE TITLE
Case sensitive matching

### ISSUE THREAD

**Issue by YorickPeterse** [hrsh7th/nvim-compe#208]
compe currently seems to perform a case-insensitive match. For example, take this Rust code:

```rust
const NUMBERS: usize = 32;

fn main() {
    let mut numbers = vec![10, 20, 30];

    numbers.push(10);

    println!("{:?}", numbers);
}
```

If I type `num` and trigger a completion, compe suggests both `NUMBERS` and `numbers`:

![Screenshot from 2021-02-23 18-23-59](https://user-images.githubusercontent.com/86065/108882281-82b85f80-7604-11eb-8333-7917452caddd.png)

Since I have already type `num` in lowercase, I would like it to suggest only symbols that match the casing. Is this currently possible with  nvim-compe? If not, is that something that could be added? Thanks! :smiley:

**Comment by tami5** [comment]
Oh this issue I had for the longest time, specially when using spell source and buffer source and writing non-code related stuff. I'd have `Word` and then I type `wo` it suggest `Word`, the suggestions should worry about what casing we used before and should default to what casing the user is using and complete based on it. 

In other words, typing `wo` should show `word` and on confirm it would post `word`. The same goes when I have `word` in the completion items, typing `Wo` will suggest `Word` and on confirm it would post `Word`.

**Comment by YorickPeterse** [comment]
Thinking about this: to support this, nvim-compe would have to add some sort of option to match from the start, with the same case. That is, say your input is like so:

```
foo|
```

And the possible options are:

* foo
* foo_bar
* bar_foo
* FOO
* FOO_BAR
* BAR_FOO

Then the only options suggested should be:

* foo
* foo_bar

If the input is this:

```
FOO|
```

Then the suggested options should be:

* FOO
* FOO_BAR

**Comment by cloggier** [comment]
Better solution could be smart case matching.

`foo` would present `foo`, `Foo`, `FOO`, but `foo` should have highest score (lazy user detected, compe being as helpful as possible).
`F` would only present `Foo` and `FOO` (explicitly requested by user).

Could be a setting: `smartcase`, `matchcase`

**Comment by hrsh7th** [comment]
I will investigate intellij/vscode bejaivior

**Comment by hrsh7th** [comment]
Or, Feel free to put it here if someone knows it.

**Comment by hrsh7th** [comment]
The smartcase approach looks good.

**Comment by zhengpd** [comment]
Hi @hrsh7th , any update on this? A setting to be case sensitive would be really great.
