### ISSUE TITLE
Add source debug API

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#21]
My random thoughts are...

1. `s:get_metadata` can return `'debug': v:true'
2. show `invoke completion` with `keyword_pattern_offset`, `trigger_character_offset`, `input`, `items`.

**Comment by tami5** [comment]
Additionally, maybe a function that accept (input, source-name &filetype) and returns dict of the completion items printed with print(vim.inspect( . Its kind like query function that returns a dict that tells us if everything is working as we expect them to be.
