### ISSUE TITLE
Sorting of LSP symbols

### ISSUE THREAD

**Issue by YorickPeterse** [hrsh7th/nvim-compe#210]
When creating sources, the `sort` option can be specified, signaling that a source can be sorted. I don't see this option set for the LSP source, and symbols appear to be returned in an unspecified order:

![Screenshot from 2021-02-23 18-42-34](https://user-images.githubusercontent.com/86065/108884442-e9d71380-7606-11eb-80dc-013941ad6cc8.png)

Is it possible to have these entries sorted somehow (e.g. alphabetically)? Thanks!

**Comment by hrsh7th** [comment]
It's sorted by length. Not unspecofied order.

**Comment by YorickPeterse** [comment]
@hrsh7th OK, that makes sense.is it possible to perhaps offer the option to sort the output alphabetically instead (perhaps using an option)? :smiley:

**Comment by hrsh7th** [comment]
Hm... VSCode seems to sort in alphabetical order...

**Comment by hrsh7th** [comment]
I've changed the default sort logic to alphabetical.
