### ISSUE TITLE
Custom source options in `require('compe').setup`?

### ISSUE THREAD

**Issue by YaBoiBurner** [hrsh7th/nvim-compe#211]
What's the intended way to get custom source configuration keys that are set during `require('compe').setup`?

I noticed that data from `require('compe').setup` can be obtained through `require('compe.config').get()`, but I'm not sure if that's supposed to be used or not.

Related to https://github.com/tzachar/compe-tabnine/pull/4

So for example, a config like:
```lua
require'compe'.setup {
	enabled = true,
	source = {
		tabnine = {
			max_lines = 500; -- default is 1000
		},
	},
}
```

Is it safe to then get `max_lines` through `require'compe.config'.get().source.tabnine.max_lines`?

**Comment by hrsh7th** [comment]
It will be supported in v3. Currentle, No.
