### ISSUE TITLE
When using the buffer source, don't suggest the currently typed word

### ISSUE THREAD

**Issue by YorickPeterse** [hrsh7th/nvim-compe#212]
When using the buffer source for completion, compe's suggestions include the currently typed word. For example:

![Screenshot from 2021-02-23 22-20-29](https://user-images.githubusercontent.com/86065/108909838-5a8d2880-7625-11eb-908b-46ee0c20ee40.png)

Since this isn't very useful, it would be nice if there was a way of excluding the currently typed word.

**Comment by cloggier** [comment]
@YorickPeterse side question - what colorscheme is that?

**Comment by YorickPeterse** [comment]
@cloggier It's [this one](https://gitlab.com/yorickpeterse/vim-paper).

**Comment by YorickPeterse** [comment]
@hrsh7th Thanks! :fireworks:
