### ISSUE TITLE
Tag completion stopped working

### ISSUE THREAD

**Issue by kristijanhusak** [hrsh7th/nvim-compe#218]
Hi,

today I noticed that Tags completion stopped working. I bisected and found out that issue started from commit a143932199f0d1a232630dd0a18e7db3e3735ab9. When I check out to previous commit 34fcd123f9ae8e364caa81f5195adcc03a43cd5a, everything works fine.

**Comment by hrsh7th** [comment]
Thank you. I've fixed it.

**Comment by kristijanhusak** [comment]
It works now, thanks!
