### ISSUE TITLE
Improve start-up time?

### ISSUE THREAD

**Issue by dimbleby** [hrsh7th/nvim-compe#220]
I'm experimenting with nvim-compe, and notice that it makes a modest dent in my start-up time.  (Not much, but, still!)

I notice that we are sourcing and registering all of these sources, although I am not using most of them:
```
116.734  000.989  000.989: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_buffer.vim
117.543  000.793  000.793: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_calc.vim
118.461  000.901  000.901: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_nvim_lsp.vim
119.273  000.794  000.794: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_nvim_lua.vim
119.995  000.707  000.707: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_omni.vim
120.839  000.829  000.829: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_path.vim
121.607  000.751  000.751: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_snippets_nvim.vim
122.311  000.686  000.686: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_spell.vim
123.017  000.690  000.690: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_tags.vim
124.047  001.015  001.015: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_treesitter.vim
124.948  000.884  000.884: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_ultisnips.vim
125.008  000.044  000.044: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_vim_lsc.vim
125.038  000.013  000.013: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_vim_lsp.vim
125.794  000.744  000.744: sourcing /home/dch/.vim/plugged/nvim-compe/after/plugin/compe_vsnip.vim
```
Perhaps it would be worthwhile to arrange that these things are loaded only if the configuration says that they will be used?

**Comment by hrsh7th** [comment]
Good point.
I think we should separate some of the built-in sources that need external sources.

I'm just lazy so all sources are built-in.

**Comment by hrsh7th** [comment]
Separating the sources is simply a hassle.

**Comment by elianiva** [comment]
the question is, where are we going to put all of those sources? An org as a central place that keeps all of them so people could find them easier (similar to how telescope do it) or do we want to find *someone* who wants to maintain a source?

**Comment by hrsh7th** [comment]
If we create `nvim-compe/compe` repo & org, we can put all sources that depends on external plugins.

But yes, I don't well know how/who maintein some of the sources.

**Comment by tzachar** [comment]
Initializing all built in sources takes 10ms as seen above.
I think you can safely postpone this until a 10ms is deemed an issue.

**Comment by dimbleby** [comment]
It's true that 10ms is not very much (which is what I said a the start).

However I raised this issue at this plugin because 10ms is rather more than most take; certainly if every plugin added 10ms to startup time then we'd really notice.

Also, I had hoped that there might be a relatively easy win here - though of course when the maintainer says that it would be a hassle, I'm sure they're right!

**Comment by tzachar** [comment]
Maybe just check if the source is enabled before requiring it?
For example, in ```compe_calc.vim```, checking if the user enabled ```calc``` b4 calling ```lua require'compe'.register_source('calc', require'compe_calc')``` might do the trick?

**Comment by thallium** [comment]
My solution is that add a few lines like this
```vim
let g:loaded_compe_treesitter=1
let g:loaded_compe_calc=1
let g:loaded_compe_snippets_nvim=1
let g:loaded_compe_spell=1
let g:loaded_compe_vim_lsc=1
let g:loaded_compe_vim_lsp=1
```
and my start time:
```
075.867  000.795  000.795: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_buffer.vim
075.903  000.013  000.013: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_calc.vim
076.663  000.744  000.744: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_nvim_lsp.vim
077.141  000.457  000.457: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_nvim_lua.vim
077.597  000.438  000.438: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_omni.vim
078.131  000.516  000.516: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_path.vim
078.168  000.015  000.015: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_snippets_nvim.vim
078.233  000.012  000.012: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_spell.vim
078.680  000.432  000.432: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_tags.vim
078.712  000.013  000.013: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_treesitter.vim
079.131  000.400  000.400: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_ultisnips.vim
079.161  000.013  000.013: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_vim_lsc.vim
079.185  000.010  000.010: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_vim_lsp.vim
079.595  000.396  000.396: sourcing /home/thallium/.cache/dein/.cache/init.vim/.dein/after/plugin/compe_vsnip.vim
```

**Comment by dimbleby** [comment]
Ugh, I hate the stalebot.  

I don't expect that the passage of time will make this issue any less valid.  (Probably the same is true for most issues).

Of course you are very much within your rights to decide to close this out as wontfix or whatever, if that's what you want to do.

But: I would very much prefer for that to be a deliberate decision made by a human than for it to be swept up by the unthinking bot.

**Comment by dimbleby** [comment]
That's a pretty aggressive stale bot that _ignores_ activity.
