### ISSUE TITLE
[Question] Do I need setup both `Vim script Config` and `Lua Config` ?

### ISSUE THREAD

**Issue by ray-x** [hrsh7th/nvim-compe#221]
Hi, I am trying to set the plugin up.
At first, I only added Lua Config in my init.lua. But I found the build in source e.g. buffer, calc. do not enabled out of box. Even though I have following in init.lua:

```lua
require'compe'.setup {
  enabled = true;
  autocomplete = true;
  debug = true;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;
  source = {
    path = true;
    buffer = true;
    calc = true;
    vsnip = true;
    nvim_lsp = {
        menu = "";
    };
    nvim_lua = true;
    tabnine = {
        max_line = 100;
        max_num_results = 10;
    };
    spell = true;
    tags = true;
    snippets_nvim = true;
    treesitter = true;
  };
}
```

I have to copy paste the vim script script to my init.vim to enable buffer/calc etc.
Is that a expected behavior?

**Comment by hrsh7th** [comment]
You should setup only Vim or Lua. Not both.

**Comment by ray-x** [comment]
Ok. It might be the confliction of those two setups.
So I do have another question. 
I need to disable auto complete for file type `clap_input`
If I have a lua setup. 
I will add `ao filetype clap_input lua require'compe'.setup{autocomplete = false}` in init.vim
And also need to turn compe on by  `ao BufRead *.py lua require'compe'.setup{autocomplete = true}`
But this is not working. Looks like I need to put everything in setup

```lua
require'compe'.setup {
  enabled = true;
  autocomplete = true;
  debug = true;
  ... 
}
```
Is there an easy to change only one setup in lua?
Also if I have a lua setup. How to check value of `compe.source.buffer` is on or off?

**Comment by hrsh7th** [comment]
In my following config, I'm getting to work as expected.

```
  let g:compe = {}
  let g:compe.enabled = s:config.complete ==# 'compe'
  let g:compe.debug = v:true
  let g:compe.preselect = 'always'
  let g:compe.autocomplete = v:true
  let g:compe.documentation = v:true

  let g:compe.source = {}
  let g:compe.source.path = v:true
  let g:compe.source.calc = v:true
  let g:compe.source.nvim_lua = v:true
  let g:compe.source.buffer = v:true

  let g:compe.source.tags = v:true
  let g:compe.source.spell = v:false
  let g:compe.source.omni = v:false
  let g:compe.source.treesitter = v:false

  let g:compe.source.nvim_lsp = s:config.lsp ==# 'nvim'
  let g:compe.source.vim_lsp = s:config.lsp ==# 'lsp'
  let g:compe.source.vim_lsc = s:config.lsp ==# 'lsc'
  let g:compe.source.lamp = s:config.lsp ==# 'lamp'
  let g:compe.source.vsnip = s:config.snippet ==# 'vsnip'
  let g:compe.source.ultisnips = s:config.snippet ==# 'ultisnips'
  let g:compe.source.snippets_nvim = s:config.snippet ==# 'snippets_nvim'

  autocmd! vimrc FileType vim call compe#setup({
  \   'autocomplete': v:false,
  \ }, 0)
```

**Comment by ray-x** [comment]
Thanks. It seems the only way to make it works is by using vim script. Because after lua setup, if I want to change `g:compe.enabled`, vim will complain `g:compe` undefined.

**Comment by hrsh7th** [comment]
No. You can.

```
require'compe'.setup {
 ...
}

vim.cmd [[ autocmd FileType vim call compe#setup({ 'autocomplete': v:true }, 0) ]]

**Comment by ray-x** [comment]
Cool, this will do the tricks. Thanks!

**Comment by ray-x** [comment]
In case anyone is checking how to disable nvim-compe for specific file type, here is the setup.   (I am disable it for clap_input)

```vim
autocmd FileType clap_input call compe#setup({ 'enabled': v:false }, 0)
```

**Comment by hrsh7th** [comment]
I tried and it worked fine for me.
I guess you have multiple `autocmd FileType clap_input` so it had overwritten.

Please re-check it before question here.

**Comment by ray-x** [comment]
Thanks. It works for me as well. Only thing is need to setup `enabled` instead of `autocomplete`

**Comment by hrsh7th** [comment]
Hm... In my environment, enabled is able to overwritable... ???
Anyway, Good to hear it worked on your machine.
