### ISSUE TITLE
nvim#compe inserts junk text

### ISSUE THREAD

**Issue by phelipetls** [hrsh7th/nvim-compe#222]
Instead of triggering completion, it inserts `<t_ý>5` for me.

It seems that 677269cb introduced the bug.

**Comment by hrsh7th** [comment]
I can't reproduce.

**Comment by phelipetls** [comment]
Try calling it with nvim#compe() with set completeopt=menuone,noselect,noinsert

**Comment by hrsh7th** [comment]
OK. I will try it...

**Comment by phelipetls** [comment]
Sorry I wasn't using it as intended. It worked before but after using what the README recommends it worked.

**Comment by hrsh7th** [comment]
Thank you.
I can't reproduce even if I set `completeopt=menuone,noselect,noinsert`
