### ISSUE TITLE
Completion without LSP

### ISSUE THREAD

**Issue by JoeyGrajciar** [hrsh7th/nvim-compe#224]
Hi,

thank you for a great plugin :)
I have a question is it possible to set up `compe` to show completion menu even for files which are not covered by any LSP?
Particularly I have an issue triggering it in `.md` files.

**Comment by hrsh7th** [comment]
You can set up to use `buffer` source completion via following config.

```
let g:compe = {}
let g:compe.source = {}
let g:compe.source.buffer = v:true
```

**Comment by JoeyGrajciar** [comment]
I have that option already enabled :) This is the config I am using.

```lua
require'compe'.setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;

  source = {
    path = true;
    buffer = true;
    calc = true;
    vsnip = true;
    nvim_lsp = true;
    nvim_lua = false;
    spell = true;
    tags = true;
    snippets_nvim = false;
    treesitter = true;
    omni = true;
  };
}
```

Also tried setting up `setl omnifunc=v:lua.vim.lsp.omnifunc`.

**Comment by cloggier** [comment]
@JoeyGrajciar And what is it exactly that doesn't work for you? I have compe working in every single buffer, regardless to whether LSP is attached to it or not.

**Comment by hrsh7th** [comment]
Your config seems to correct to me.
Don't you get the buffer completion with your config?

**Comment by JoeyGrajciar** [comment]
@cloggier @hrsh7th The issue is I don't get any completion currently. Default <C-n> completion works.

**Comment by hrsh7th** [comment]
you are invoking omnifunc manually, right?

If so, compe will do nothing.

You should invoke `compe#complete` instead of omnifunc(`<C-x><C-o>`)

**Comment by hrsh7th** [comment]
`inoremap <silent><expr> <C-x><C-o> compe#complete()` will be done as you expected.

**Comment by JoeyGrajciar** [comment]
So I guess I found the issue :) In config I have `treesitter = true`, but I do not have `nvim-treesitter` installed so that was probably breaking the chain :)
`inoremap <silent><expr> <C-x><C-o> compe#complete()` uncovered the issue.
