### ISSUE TITLE
Consider adding sponsor button

### ISSUE THREAD

**Issue by gegoune** [hrsh7th/nvim-compe#226]
I wouldn't mind rewarding your hard work! Great plugin!

**Comment by hrsh7th** [comment]
Thank you for your words.

I haven't ever put the sponsor button. I will put it on a trial.

**Comment by runiq** [comment]
Heyyyy where's that sponsor button? :)

**Comment by cloggier** [comment]
Bad bot!

**Comment by hrsh7th** [comment]
I was stopped by W-8BEN

**Comment by cloggier** [comment]
Ah, I am completely unaware of tax implications. It's a shame, I hope there is a way!

**Comment by hrsh7th** [comment]
fixed https://github.com/hrsh7th/nvim-compe/commit/a46dfe7d7fc8f7af5bb84006db45ba11fb7b786c
