### ISSUE TITLE
Disable 'pattern not found' message

### ISSUE THREAD

**Issue by jghauser** [hrsh7th/nvim-compe#229]
First of all, thanks a lot for this plugin, it's been very useful!

Is there a way to disable the 'Pattern not found' message that appears in the command line when there isn't a match at the current cursor position? I use Ultisnip's snippets because they support in-word completion (expanding for example `wordcm` to `word<!-- comment -->`). This unfortunately means that at almost every character that I type this message flashes, which is very distracting.

**Comment by Shougo** [comment]
set shortmess+=c

**Comment by hrsh7th** [comment]
Thank,you @Shougo !
