### ISSUE TITLE
Suggestion list doesn't update on method completion with clangd

### ISSUE THREAD

**Issue by thallium** [hrsh7th/nvim-compe#230]
Sorry for my bad english if the title looks confusing.
The suggestion list doesn't update when typing method.

![image](https://user-images.githubusercontent.com/20818480/109576299-85fa9200-7ac1-11eb-8a8a-9c20f86482a1.png)

But it updates on deletion.

![image](https://user-images.githubusercontent.com/20818480/109576356-99a5f880-7ac1-11eb-962d-ecdb34479c6d.png)

**Comment by cloggier** [comment]
@thallium Did you resolve it?

**Comment by thallium** [comment]
It's magically working again. I didn't remember doing anything special.

**Comment by thallium** [comment]
The issue appeared again...

**Comment by hrsh7th** [comment]
May be fixed by #234

**Comment by thallium** [comment]
Unfortunately, the issue still exists.

**Comment by hrsh7th** [comment]
Please reproducible minimal cpp file.

**Comment by thallium** [comment]
First I want to clarify that it behaves normally sometimes, but I believe most of the time it doesn't. When it happens, it seems unrelated to files.

**Comment by hrsh7th** [comment]
I couldn't repro...
Hm... I hope someone provides more detailed info. .:pray:

**Comment by dfangx** [comment]
I can reproduce with following code:

```
int find_client(){
    return 1;
}

int main(int argc, char *argv[]) {
    return 0;
}
```

Screenshot
![2021-03-04_124504](https://user-images.githubusercontent.com/23224188/110006528-b33d7f00-7d11-11eb-8a4f-3ea142f00146.png)

In main(), I type 'find' the first time and it works properly, then I backspace until only 'f' is remaining. Then I retype 'ind' (remainder of the word 'find') and list does not update until I hit <BS>.

Also using clangd.

**Comment by thallium** [comment]
I tried to reproduce with a minimal config file and I found that if I put the lsp setup code in a separate lua file the autocompletion won't work.

init.vim:
```vim
if &runtimepath !~# '/dein.vim'
    set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim
endif
let s:data_path='~/.cache/dein/'
if dein#load_state(s:data_path)
    call dein#begin(s:data_path)
    call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')

    call dein#add('neovim/nvim-lspconfig')

    call dein#add('hrsh7th/nvim-compe')

    call dein#end()
    call dein#save_state()
endif

let g:compe = {}
let g:compe.enabled = v:true
let g:compe.autocomplete = v:true
let g:compe.debug = v:false
let g:compe.min_length = 1
let g:compe.preselect = 'always'
let g:compe.throttle_time = 80
let g:compe.source_timeout = 200
let g:compe.incomplete_delay = 400
let g:compe.max_abbr_width = 100
let g:compe.max_kind_width = 100
let g:compe.max_menu_width = 80
let g:compe.documentation = v:true

let g:compe.source = {}
let g:compe.source.path = v:true
let g:compe.source.buffer = v:true
let g:compe.source.nvim_lsp = v:true
let g:compe.source.nvim_lua = v:true
let g:compe.source.tags = v:true
let g:compe.source.ultisnips = v:true
let g:compe.source.omni = v:true

lua <<EOF
-- local nvim_lsp = require('lspconfig')
-- local servers = { "clangd" }
-- for _, lsp in ipairs(servers) do
--     nvim_lsp[lsp].setup{ }
-- end

require'lsp'
-- require('lspconfig').clangd.setup{}
-- require('lspconfig')["clangd"].setup{}

EOF
```
lsp.lua:
```lua
local nvim_lsp = require('lspconfig')
local servers = { "clangd" }
for _, lsp in ipairs(servers) do
    nvim_lsp[lsp].setup{ }
end
```

**Comment by thallium** [comment]
In my own config, I have this in my lua file:
```lua
vim.api.nvim_buf_set_option(0, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
```
removing it resolved the issue.

**Comment by hrsh7th** [comment]
Thank you for your investigation!

I think it should be added to README.md.

**Comment by hrsh7th** [comment]
I've added it to README.md.  Thank you again.
