### ISSUE TITLE
CR map can't close popmenu when confirm

### ISSUE THREAD

**Issue by glepnir** [hrsh7th/nvim-compe#231]
`i  <CR>        * compe#confirm({ 'keys': "\<Plug>delimitMateCR", 'mode': '' })` this works like this

![finder](https://user-images.githubusercontent.com/41671631/109614662-e2b38680-7b6d-11eb-813f-10161d161447.gif)

**Comment by hrsh7th** [comment]
It's occurred by trigger characters.
The sumneko_lua returns all alphabetical chars as trigger characters.

Hm... I will add a workaround for it.
