### ISSUE TITLE
error when manually triggering completion

### ISSUE THREAD

**Issue by smartding** [hrsh7th/nvim-compe#24]
I'm trying to use tab to manually trigger completion, and I have the following key mapping:
```lua
check_backspace = function()
  local col = vim.fn.col('.') - 1
  if col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') then
    return true
  else
    return false
  end
end

vim.api.nvim_set_keymap(
  'i', '<Tab>',
  'pumvisible() ? "<C-n>" : v:lua.check_backspace() ? "<Tab>" : <C-r>=compe#complete()<CR>',
  { noremap=true, expr=true }
)
```
I get an error as following every time I use tab to trigger completion manually:
```
E15: Invalid expression: ^R=compe.completion()^M
```
Steps to reproduce:
1.  type something, completion is automatically triggered
1. stop completion with C-e
1. type tab to trigger completion manually

I guess there's something wrong with my key mapping here, any help would be appreciated.

**Comment by hrsh7th** [comment]
I don't know the reason but it should be below, I think.

```
vim.api.nvim_set_keymap(
  'i', '<Tab>',
  'pumvisible() ? "<C-n>" : v:lua.check_backspace() ? "<Tab>" : "<C-r>=compe#complete()<CR>"',
  { noremap=true, expr=true }
)
```

**Comment by smartding** [comment]
problem solved! thanks.
