### ISSUE TITLE
No menu popup after recent commit

### ISSUE THREAD

**Issue by svermeulen** [hrsh7th/nvim-compe#241]
I noticed that I wasn't seeing any popup suggestions anymore after updating this plugin.  I used git bisect to narrow it down to commit 72ef96b.  If I use the one before that (3ce7f98) everything seems to work fine and I get suggestions again.  Was there a breaking change there I missed?

Thanks for your work on this

**Comment by hrsh7th** [comment]
Hm... I'm using the latest compe that works fine.

Please put a minimal config based on https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim

My guessing are followings.

1. The problem occured by omni=true
2. The problem occured by specific LSP server

**Comment by svermeulen** [comment]
Ok I tested with the following vimrc:

```
call plug#begin()
Plug 'hrsh7th/nvim-compe', { 'commit': '72ef96b' }
" Plug 'hrsh7th/nvim-compe', { 'commit': '3ce7f98' }
call plug#end()

set completeopt=menuone,noselect

let g:compe = {}
let g:compe.enabled = v:true
let g:compe.autocomplete = v:true
let g:compe.debug = v:false
let g:compe.min_length = 1
let g:compe.preselect = 'enable'
let g:compe.throttle_time = 80
let g:compe.source_timeout = 200
let g:compe.incomplete_delay = 400
let g:compe.max_abbr_width = 100
let g:compe.max_kind_width = 100
let g:compe.max_menu_width = 100
let g:compe.documentation = v:true

let g:compe.source = {}
let g:compe.source.path = v:true
let g:compe.source.buffer = v:true
let g:compe.source.calc = v:true
let g:compe.source.vsnip = v:true
let g:compe.source.nvim_lsp = v:true
let g:compe.source.nvim_lua = v:true
let g:compe.source.spell = v:true
let g:compe.source.tags = v:true
let g:compe.source.snippets_nvim = v:true
let g:compe.source.treesitter = v:true
let g:compe.source.omni = v:true
```

Repro steps:
- Open Vim
- Run `PlugUpdate`
- Restart Vim
- Open any file
- Start typing a word that exists in the file
- Observe no suggestions

Similar to with my own vimrc, running with 72ef96b produces no buffer suggestions, and running with 3ce7f98 produces buffer suggestions

I'm using terminal neovim 0.5 (compiled myself from commit 52397aaa0) on mac osx

**Comment by hrsh7th** [comment]
Reproduced.

I removed `omni/treesitter/snippets.nvim/vsnip/spell/tags` sources then it works again.

I'm investigating it.

**Comment by svermeulen** [comment]
Can confirm that it's fix on master for me.  Thanks!
