### ISSUE TITLE
No match still show popupmenu

### ISSUE THREAD

**Issue by glepnir** [hrsh7th/nvim-compe#242]
like this. input 0 and it gave me a popup menu.

![finder](https://user-images.githubusercontent.com/41671631/110292909-e0976f00-8028-11eb-82e8-102e304049f6.gif)

**Comment by glepnir** [comment]
lol I saw you used `''` to avoid match :)

**Comment by hrsh7th** [comment]
Sorry! It is just my mistake...:cry:
https://github.com/hrsh7th/nvim-compe/commit/3d93356032fda2329d9ba34da9d142166e39bf5c
