### ISSUE TITLE
compe breaking on files after/plugin/*

### ISSUE THREAD

**Issue by jotamudo** [hrsh7th/nvim-compe#244]
I'm opening a new issue to get some help and try to get to the root of the following:
I've been playing around with it and "found" the issue, but didn't nail it down yet. What was this [line](https://github.com/hrsh7th/nvim-compe/blob/7a998c5716c2bb9a25276cf1ce7076f99582a45a/autoload/compe.vim#L11) supposed to do?
I've tried to print and echo the config and bufnr on both the compe.setup and Completion.setup functions but it doesn't seem to print anything to the :messages. I can print anything before the line I've mentioned and can see the config is being correctly passed the config and the bufnr is always being set as v:null from the get(a:, 1, v:null).
I've changed that line to:
```vim
  echo 'a:config = ' a:config
  echo 'get(a:, 1, v:null) = 'get(a:, 1, v:null)
  call luaeval('require"compe".setup(_A[1], _A[2])', [a:config, get(a:, 1, v:null)])
```
and the output is as follows:
```
a:config = {'throttle_time': 80, 'source_timeout': 200, 'max_abbr_width': 100, 'prese
lect': 'enable', 'source': {'nvim_lsp': v:true, 'path': v:true, 'buffer': v:true}, 'i
ncomplete_delay': 400, 'enabled': v:true, 'max_menu_width': 100, 'min_length': 1, 'do
cumentation': v:true, 'debug': v:true, 'max_kind_width': 100, 'autocomplete': v:true}

get(a:, 1, v:null) =  v:null
Error detected while processing function compe#setup:
... (same as before)
```
As mentioned, changing trying to make either compe.setup() or Completion.setup() didn't print anything (I'm still using the same init.vim), so I came to ask some help on it

_Originally posted by @jotamudo in https://github.com/hrsh7th/nvim-compe/issues/227#issuecomment-789246015_

**Comment by hrsh7th** [comment]
Sorry.
I can't understand what is the problem and I can't repro with your minimal config.

**Comment by ii14** [comment]
It simply calls [this lua function](https://github.com/hrsh7th/nvim-compe/blob/7a998c5716c2bb9a25276cf1ce7076f99582a45a/lua/compe/init.lua#L41).

To test what it does on a command line:
```
:lua require'compe'.setup(vim.g.compe, null)
```
`g:compe` should be defined before that.

In lua `print('test')` should log everything to `:messages`.

**Comment by jotamudo** [comment]
Thanks for the clarification :)
After another bunch of hours it seems it's a problem with my system, so I'll call it bad luck on some weird package combination. I've tried and successfully installed it in another machine on both windows and arch linux (same as the first one).

**Comment by jotamudo** [comment]
As a final note, after creating another user, accidentally deleting some files, and looking after a lot of environment variables, I noticed I had left a file to put compe's configs on my lua folder (lua/compe.lua) and that was the cause of the weird behavior
