### ISSUE TITLE
miss match.

### ISSUE THREAD

**Issue by glepnir** [hrsh7th/nvim-compe#248]
look like miss `delete` right? expect behavior?

![image](https://user-images.githubusercontent.com/41671631/110755836-5ea38200-8284-11eb-9a48-bd1fe8f1e85a.png)

**Comment by hrsh7th** [comment]
It's not expected but it seems difficult to fix.
I will be tracking it.

**Comment by cideM** [comment]
Out of curiosity, what makes this difficult to fix? Because I often notice that certain words are missing from the buffer source even though they're clearly part of the current buffer.

**Comment by hrsh7th** [comment]
Because it may or may not happen. I can't detect the root cause.
