### ISSUE TITLE
lua version of plugin setup?

### ISSUE THREAD

**Issue by smartding** [hrsh7th/nvim-compe#25]
I'm trying to convert the plugin setup in README to lua, what's the lua version of the follow vim script call?
```vim
call compe#source#vim_bridge#register('path', compe_path#source#create())
```
I read the article "Getting started using Lua in Neovim" and tried the following, but it didn't work:
```lua
vim.fn['compe#source#vim_bridge#register']('path', vim.fn['compe_path#source#create']())
```

**Comment by hrsh7th** [comment]
The `vim.fn['compe_path#source#create']` will return dict that includes a `function reference`.
So you can't go and come between Lua and Vim script for it. Sorry.

**Comment by hrsh7th** [comment]
@tami5 Do you have any idea?

**Comment by tami5** [comment]
@hrsh7th I personally use  
```lua
vim.cmd [[call compe#source#vim_bridge#register('path',  compe_path#source#create())]]
```

But I think after #23 we can do something like 

```
require'compe'.register_source("vsnip") -- or
vim.g.compe_sources{ "vsnip", "path" }
```

@smartding just use what use for now .

**Comment by smartding** [comment]
> @hrsh7th I personally use
> 
> ```lua
> vim.cmd [[call compe#source#vim_bridge#register('path',  compe_path#source#create())]]
> ```
> 
> But I think after #23 we can do something like
> 
> ```lua
> require'compe'.register_source("vsnip") -- or
> vim.g.compe_sources{ "vsnip", "path" }
> ```
> 
> @smartding just use what use for now .

ok, thanks.
small world, tami5's everywhere:)

**Comment by tami5** [comment]
@smartding :$ wait you will see in your sleep :laughing:
