### ISSUE TITLE
[lsp] Markdown not fully rendered 

### ISSUE THREAD

**Issue by cloggier** [hrsh7th/nvim-compe#250]
Hi @hrsh7th

I have noticed that completion documentation coming back from css lang server (your other repo) has some escape characters printed out. Please see screenshot below.

<img width="1047" alt="Screenshot 2021-03-11 at 10 43 26" src="https://user-images.githubusercontent.com/69750637/110767512-9e537500-8256-11eb-877c-442b773b0fc2.png">

I have noticed that you are using your own implementation of Markdown renderer (Vital). There is one built in in Neovim, I believe, that is being worked on by @mjlbach, perhaps using it would simplify compe's code? Just a thought.

https://github.com/neovim/neovim/issues/14032
https://github.com/neovim/neovim/pull/14073

**Comment by hrsh7th** [comment]
I think this problem should be fixed by #249

**Comment by hrsh7th** [comment]
vim-vital-vs is used by vim-lsp/nvim-compe/vim-lamp. So it should be improved for me.

But if the neovim's fancy float would be accurately handled markdown, I will change to it.

Currently, it can be done by the simple patch, I think.

IMO, The LuaJIT is incredibly fast so we can parse markdown and generate detailed highlight for markdown (this way has a benefit that is enabling accurately calculate floating window sizes. Currently, we can't it because concealed characters.

**Comment by cloggier** [comment]
Ah, alright then. Will wait for #249 and keep this issue open for now. Thanks for all your effort once again!

**Comment by mjlbach** [comment]
FYI currently what we are doing in core is just adding a custom syntax file and setting the conceal level (to 2) in the floating markdown window which hides the escape characters. I made a PR that strips escape characters when parsing the return from the language server, but IMO the syntax rule + conceal approach is more flexible.

**Comment by hrsh7th** [comment]
@mjlbach Thank you for your FYI.

I've implemented escape chars/html entities as https://github.com/hrsh7th/vim-vital-vs/blob/master/autoload/vital/__vital__/VS/Vim/Syntax/Markdown.vim#L10

IMO, the `conceal` approach can't calculate the correct floating window sizes but it is enough solution.

**Comment by cloggier** [comment]
@hrsh7th great work with `improve` branch. Thanks!

I have noticed that markdown breaks words into new line. Like here:
<img width="980" alt="Screenshot 2021-03-13 at 11 38 18" src="https://user-images.githubusercontent.com/69750637/111027459-ca0a6280-83f0-11eb-8f98-99f9db755851.png">

Also would be good to avoid that extra indentation in last paragraph.

**Comment by hrsh7th** [comment]
Hm... I was investigating it but the current approach can't solve it.

We should add the padding sub-window for it but it needs to fix neovim itself first.

**Comment by cloggier** [comment]
I see! Since original issue is solved feel free to close that issue, unless you would like to keep it open for that last problem I mentioned.

**Comment by hrsh7th** [comment]
Thank you.

If neovim improve floating window composition, I will try to fix it.

**Comment by mjlbach** [comment]
Bfredl is currently working on borders which would let us remove the padding operation we currently do, the indentation in the paragraph above may be due to conceal rules applied to nbsp, not sure.

**Comment by hrsh7th** [comment]
Hm... the documentation data is following (it has no `&nbsp`...

```
[
  ' ```lua function pcall(f: function, arg1?: any, ...) ',
  '   -> success: boolean ',
  '   2. result: any ',
  '   3. ... ``` ',
  ' --- ',
  '  ',
  '  ',
  ' Calls the function `f` with the given arguments in *protected mode*. This means that any error inside `f` is not propagated; instead, `pcall` catches the error and returns a status code. Its first result is the status code (a boolean), which is true if the call succeeds without errors. In such case, `pcall` also returns all results from the call, after this first result. In case of any error, `pcall` returns `false` plus the error object. ',
  '  ',
  '  ',
  '  ',
  ' [View documents](http://www.lua.org/manual/5.1/manual.html#pdf-pcall) '
]
```

Current approach uses `&breakindent` and `&wrap` combination. I guess this problem relates to linebreak behavior.

**Comment by hrsh7th** [comment]
Hm... we shouldn't use wrap and should use manual linebreak implementation...?
