### ISSUE TITLE
Order of appearance in source setup

### ISSUE THREAD

**Issue by hrqmonteiro** [hrsh7th/nvim-compe#252]
As i could see, in a config like this:

```
require "compe".setup {
  documentation = true,
  source = {
    path = {menu = ""},
    buffer = {menu = ""},
    vsnip = {menu = ""},
    nvim_lsp = {menu = "LSP"},
  }
}
```

When the autocomplete suggestion triggers, it will show the "word" (mandatory), then the "kind", then the "menu".

Could i change this order? For it to appear, like: king, word, menu, or something?

**Comment by Shougo** [comment]
It cannot.  Because this is Vim/neovim feature.

**Comment by hrqmonteiro** [comment]
I see. Thanks for clarification.
