### ISSUE TITLE
PR #249 broke preview fenced code block highlighting

### ISSUE THREAD

**Issue by cehoffman** [hrsh7th/nvim-compe#253]
The only change was the merge of #249 made completion preview documentation stop highlighting the fenced code block. Obviously the PR was expecting some changes around markdown and fenced code blocks, but I couldn't pick out if there are any expected changes I should be making on my side to resolve this.

Commit Before:
<img width="847" alt="Screen Shot 2021-03-13 at 5 33 06 PM" src="https://user-images.githubusercontent.com/27545/111053100-a19d5b00-8426-11eb-8d0f-6544bf625359.png">

After:
<img width="942" alt="Screen Shot 2021-03-13 at 5 33 47 PM" src="https://user-images.githubusercontent.com/27545/111053105-ae21b380-8426-11eb-9109-02d1b7ad40bf.png">

This is running with neovim `NVIM v0.5.0-dev+nightly-14-gd38508d88` and pinned tree-sitter 0.18.3 compiled ~14 hours ago from master

**Comment by hrsh7th** [comment]
Please put your dotfiles.

I think it relates to other plugin.

**Comment by cehoffman** [comment]
I got a chance to do a bit of searching disabling and enabling plugins to narrow it down to https://github.com/tpope/vim-markdown. Removing that fixed the issue.

**Comment by hrsh7th** [comment]
Thank you for investigation.

I've fixed it.

**Comment by akinsho** [comment]
Just to point out this issue is the same if using https://github.com/plasticboy/vim-markdown, I was having the same issue and disabling it fixes it. Is the correct solution here to remove markdown plugins? seems kind of limiting to not be able to have my markdown highlighted so it doesn't interfere with compe?
