### ISSUE TITLE
disable default `<CR>` mapping

### ISSUE THREAD

**Issue by oberblastmeister** [hrsh7th/nvim-compe#254]
By default when you click `<CR>` an item from the completion menu will be selected. Is there any way to disable it?

**Comment by hrsh7th** [comment]
I can't umderstand your mean...

Please check with `compe.preselect = 'dosabled'`

**Comment by oberblastmeister** [comment]
Okay I understand now. I was using `preselect = always`. I wanted the `compe#confirm` to preselect but also not preselect always without comfirming. I made a pr #256 to do this.
