### ISSUE TITLE
Function signature cut off on tab-completion

### ISSUE THREAD

**Issue by ruffson** [hrsh7th/nvim-compe#257]
I was playing aroung with [this](https://github.com/sharksforarms/vim-rust/blob/master/neovim-init-lsp-compe.vim) minimal config setting up neovim 0.5 for rust development.

I have got it to a pretty good working state, however when I tab-to-complete, the documentation is cutting off the function signature. It comes up alright when I get the documenation on `vim.lsp.buf.hover()`.
Is this a known issue?

Here is what I see when I `<tab>`:
![Screenshot from 2021-03-14 20-41-09](https://user-images.githubusercontent.com/1185812/111118065-9b16fc80-8568-11eb-9bf6-00958652b5c7.png)

And here when I press `K` with the cursor over the function which triggers `hover()`:
![Screenshot from 2021-03-14 20-46-19](https://user-images.githubusercontent.com/1185812/111118129-b2ee8080-8568-11eb-88ff-00ed12cfad6d.png)

**Comment by hrsh7th** [comment]
The documentation is not the same as hover information in LSP spec.

So I can't solve it. Sorry.

**Comment by ruffson** [comment]
So you are saying this is coming from the lsp server or is a bug in the lsp client, so neovim?
But this is cut-off documentation is not a problem other completion plugins like `completion-nvim`, just with compe.

**Comment by hrsh7th** [comment]
1. LSP has `textDocument/hover` request.
2. LSP has `textDocument/completion` request (the returned value includes `CompletionItem[]` and it can be have a `documentation`

The `textDocument/hover` provides more detailed information than `textDocument/completion`'s documentation. (includes VSCode)

Most LSP client uses `textDocument/completion`'s documentation for completion-menu's documentation.

**Comment by ruffson** [comment]
Okay thank you, then I will open an issue over at the rust-analyzer repo, if the problem lies in what comes back as `textDocument/completion`.

**Comment by ruffson** [comment]
So just to nail down where the problem is here.
When I do the same with a [minimal config](https://github.com/sharksforarms/vim-rust/blob/master/neovim-init-lsp.vim) and use `completion-nvim` with the same lsp server, neovim version, etc. I do get the correct documentation on completion:

![Screenshot from 2021-03-16 09-00-51](https://user-images.githubusercontent.com/1185812/111275419-6a04fd80-8636-11eb-84ba-62bd32343058.png)

So I guess that that extension is using `hover` even on auto completion.

**Comment by hrsh7th** [comment]
Yes. completion-nvim uses `textDocument/hover` in completion.

I think it is not general behavior. completion-nvim specific things.

**Comment by ruffson** [comment]
> Yes. completion-nvim uses `textDocument/hover` in completion.
> 
> I think it is not general behavior. completion-nvim specific things.

Thank you for clearing that up and btw thank you for your work on this in general!
