### ISSUE TITLE
Pattern not found

### ISSUE THREAD

**Issue by momofor** [hrsh7th/nvim-compe#259]
every time I try to make a new line using 'o' or just typing while getting completions I get the error pattern not found but the completions still work . 
[compe config](https://github.com/momofor/dotfiles/blob/master/nvim/.config/nvim/lua/compe-config.lua)
This is the only thing stopping me from using native lsp and compe please help.
Sorry if this is the wrong structure this is my first issue in here , any help is apreciated :D

Edit: 
fixed by setting showmode to true.

**Comment by hrsh7th** [comment]
You can set `set shortmess+=c`

**Comment by momofor** [comment]
> You can set `set shortmess+=c`

thank you very much I dindn't find that in the docs so I was lost for a while
