### ISSUE TITLE
how to trigger golang lsp snippet completion

### ISSUE THREAD

**Issue by smartding** [hrsh7th/nvim-compe#26]
I've enabled vsnip completion by adding the following  to my vimrc:
```vim
`call compe#source#vim_bridge#register('vsnip', compe_vsnip#source#create())`
```
and also added the following 2 plugins:
```vim
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
```
golang lsp server has a [snippet](https://github.com/golang/tools/blob/6d151481565cdd477137cd2cc2e7abf48022bb79/internal/lsp/source/completion/snippet.go#L56) to add parentheses after a function call completion , but how do I trigger this snippet? Nothing happens after a function name is auto completed.

**Comment by hrsh7th** [comment]
You should install vim-vsnip and vim-vsnip-integ both.

The vim-vsnip supports common snippet feature.
The vim-vsnip-integ supports some integrations such as LSP.

**Comment by smartding** [comment]
> You should install vim-vsnip and vim-vsnip-integ both.
> 
> The vim-vsnip supports common snippet feature.
> The vim-vsnip-integ supports some integrations such as LSP.

I have already installed them both, as I said in the above post. Is there any additional config I should add?

**Comment by hrsh7th** [comment]
Oh, Sorry...

Could you provide tour gopls's lspconfig?

**Comment by smartding** [comment]
> Oh, Sorry...
> 
> Could you provide tour gopls's lspconfig?

here's my config:
```lua
local custom_attach = function(client)
  require'compe_nvim_lsp'.attach(client)
  require'lsp-status'.on_attach(client)
end

require'lspconfig'.gopls.setup{
  on_attach = custom_attach,
  capabilities = require'lsp-status'.capabilities
}

**Comment by hrsh7th** [comment]
```
local custom_attach = function(client)
  require'compe_nvim_lsp'.attach(client)
  require'lsp-status'.on_attach(client)
end

local capabilities = require'lsp-status'.capabilities
capabilities.textDocument.completion.completionItem.snippetSupport = true

require'lspconfig'.gopls.setup{
  on_attach = custom_attach,
  capabilities = capabilities,
  init_options = {
    usePlaceholders = true,
  }
}
```

Could you try it?

**Comment by smartding** [comment]
> local capabilities = require'lsp-status'.capabilities
> capabilities.textDocument.completion.completionItem.snippetSupport = true

it works, thanks.
the auto-parentheses gopls snippet has an option called `placeholders`,  you can see the code [here](https://github.com/golang/tools/blob/6d151481565cdd477137cd2cc2e7abf48022bb79/internal/lsp/source/completion/snippet.go#L82), where should I set this `placeholder` option?
