### ISSUE TITLE
How to use with vim-closer

### ISSUE THREAD

**Issue by toniz4** [hrsh7th/nvim-compe#262]
I tried using it with [vim-closer](https://github.com/rstacruz/vim-closer) but i didn't find a way to make it work.
When vim-closer is enabled it binds `<CR>` to `<CR><Plug>CloserClose`, I tried using that inside compe#confirm, but with no success.

**Comment by hrsh7th** [comment]
```
compe#confirm({ 'keys': "\<CR>\<Plug>CloserClose", 'mode': '' })
```

The `<Plug>` map example is in the README.md.

Please try it.

**Comment by toniz4** [comment]
Using that just makes nvim freeze.

**Comment by astier** [comment]
Maybe this has something to do with this https://github.com/rstacruz/vim-closer/issues/37
