### ISSUE TITLE
Question about prerequisites

### ISSUE THREAD

**Issue by vonshednob** [hrsh7th/nvim-compe#264]
Sorry for asking here, but I couldn’t find a better way to get in contact with any developers.
I’m trying to get nvim-compe to run on my system, but I keep getting errors during startup of neovim:
```
Error detected while processing function compe#setup:
line    1:
E5108: Error while calling lua chunk for luaeval(): /home/robertl/.config/nvim/lua/compe/context.lua:20: attempt to index field 'b' (a nil value)
```

I suspect that I’m missing something obvious in the prerequisites. Is by any chance version 0.5 of neovim a requirement?

**Comment by hrsh7th** [comment]
I don't know how to find neovim's API version history but I think it depends on neovim version.

**Comment by vonshednob** [comment]
As discussed in #265 neovim 0.5 is a minimum requirement for nvim-compe to work.
