### ISSUE TITLE
Issues when running with `set debug=throw`

### ISSUE THREAD

**Issue by kyazdani42** [hrsh7th/nvim-compe#266]
simply installing nvim-compe and using the `debug=throw` option (useful for debugging plugins), the plugin throws this errors on every keystroke:
```
Error executing vim.schedule lua callback: Vim(let):E94: No matching buffer for VS.Vim.Buffer:
 2: VS.Vim.Buffer.Default
 ```
 Not sure if this is expected but i think this should not happen :)
 Anyway thanks for the plugin !

**Comment by hrsh7th** [comment]
Thank you a lot!
I will turn it on in my vimrc and test it.

**Comment by hrsh7th** [comment]
This is very hard to fix but it is still important.

**Comment by hrsh7th** [comment]
I think it was fixed.
