### ISSUE TITLE
Provide some hook that can pass user custom callback

### ISSUE THREAD

**Issue by glepnir** [hrsh7th/nvim-compe#267]
Hey can you provide some hooks like `CompletionDone` or something else. then we can pass a callback function like `lspsaga signature help` ?

**Comment by hrsh7th** [comment]
It's reasonable.
What do you want to hook? It's timing of after `compe#confirm`, right?

**Comment by glepnir** [comment]
yep .

**Comment by glepnir** [comment]
maybe should consider the user use snippets when completion done. this does not work for me. when I confirm completion nothing happen :)

`vim.cmd [[autocmd User CompeConfirmDone * :Lspsaga signature_help]]`

**Comment by hrsh7th** [comment]
@glepnir The `User` autocmd does not accept `*` arguments.

```
vim.cmd [[autocmd User CompeConfirmDone :Lspsaga signature_help]]
```

**Comment by glepnir** [comment]
right I forget compile config file. there has a problem.

![Untitled](https://user-images.githubusercontent.com/41671631/111778626-ea09bc80-88ef-11eb-9151-cdb8800f7db9.gif)

**Comment by hrsh7th** [comment]
Probably, I had met your problem before past time on vim-lamp.
https://github.com/hrsh7th/vim-lamp/blob/master/autoload/lamp/view/cursor.vim#L30

I guess your problem relates to https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/signaturehelp.lua#L159

After snippet expansion, the vsnip will select placeholder, and cursor is located to the left of the visual range.

Do you get the correct result if you remove `usePlaceholders = true` from your gopls settings?

**Comment by glepnir** [comment]
test it later
