### ISSUE TITLE
Compe performs garbage edits on enter in large files

### ISSUE THREAD

**Issue by YaBoiBurner** [hrsh7th/nvim-compe#271]
I was able to get this to happen with the `vsnip` and `nvim_lua` sources, so I don't think it's related to the source itself.

Can't reproduce it in small files either.

Generally it does anything from inserting some text onto the previous line, to occasionally deleting 20-ish lines of text. It also sometimes breaks tree-sitter highlights, but that's probably a side effect.

Example (sorry about low video quality):

https://user-images.githubusercontent.com/10004812/111725107-735bb900-8834-11eb-9c24-0e66258c90b8.mp4

**Comment by hrsh7th** [comment]
1. What language server do you use?
2. Could you point out the reproducible file?

I think the tree-sitter problem does not relates to compe.

**Comment by YaBoiBurner** [comment]
tree-sitter stuff isn't related to compe.

I was running into this with the sumneko lua language server, but I can also reproduce it with gopls while editing FiloSottile/age@[master/x25519.go](https://github.com/FiloSottile/age/blob/master/x25519.go).

**Comment by hrsh7th** [comment]
@YaBoiBurner Sorry. I can't reproduce it with x25519.go...

Sorry for annoying. Please create minimal reproducible configuration with https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim

**Comment by YaBoiBurner** [comment]
i can't reproduce it anymore with that, so i guess it's not compe related.
