### ISSUE TITLE
Wrong word wrapping in method's documentation

### ISSUE THREAD

**Issue by baco** [hrsh7th/nvim-compe#273]
When showing method's documentation the text wrapping breaks words in halves instead of breaking the line at the last white space possible:

![Screenshot from 2021-03-18 16-27-55_](https://user-images.githubusercontent.com/102958/111783490-09292f80-8899-11eb-92ef-27ddd7fa3343.png)
![Screenshot from 2021-03-19 09-38-31_](https://user-images.githubusercontent.com/102958/111783518-0e867a00-8899-11eb-92b9-591edcf1bc2e.png)

The correct behaviour here would be to send `sys.breakpointhook()`, `debugger` and `point` to the line below, not breaking words in halves.

**Comment by hrsh7th** [comment]
Hm.... Sorry for my poor english.

Please point out the `actual` and `expected`.

**Comment by baco** [comment]
Both screenshots are examples of actual behaviour. The expected behaviour is not on screenshots, but would be something like:

```
builtins                                    
                                            
breakpoint(*args: Any, **kws: Any) -> None

breakpoint(*args, **kws)

Call sys.breakpointhook(*args, **kws).
sys.breakpointhook() must accept
whatever arguments are passed.

By default, this drops you into the pdb
debugger.
```
for the first screenshot. And:
```
FILE *

From <stdio.h>
Open a file and create a new stream for it.
This function is a possible cancellation
point and therefore not marked with __THROW.
```
for the second one.

The complete words are move down and a newline is inserted at the last whitespace possible
