### ISSUE TITLE
Attempt to get length of local 'text' (a number value)

### ISSUE THREAD

**Issue by pedropmedina** [hrsh7th/nvim-compe#276]
Getting the following error: 

```Error executing vim.schedule lua callback: .../pack/packer/start/nvim-compe/lua/compe/utils/string.lua:24: attempt to get length of local 'text' (a number value)```

It happens mainly when assigning a type in typescript e.g. ```transformTransactionInput: TransformTransactionInput```

**Comment by gblock0** [comment]
I'm seeing this in Typescript as well. I _think_ it may be related to adding `treesitter` as a source. When I remove `treesitter = true;` from the `source` table, the error does not repro for me.
