### ISSUE TITLE
Manual omni and text completion broken since commit 72c4500

### ISSUE THREAD

**Issue by bluz71** [hrsh7th/nvim-compe#278]
Hello hrsh7th,

I use a combination of nvim-compe auto-completion and traditional-Vim manual completion (text and omni).

That *was* working fine.

But it seems [commit 72c4500](https://github.com/hrsh7th/nvim-compe/commit/72c450056300081a25fdf142173a6a94c3f0921b) broke traditional-Vim manual completion.

Example file `foo.txt`, please make sure that no nvim-compe auto-completion is enable for this file type:

```
Hello
Goodbye

|
```

At the `|` cursor type `He<CTRL-p>`, I would expect `Hello` to appear in the manual completion menu, but I don't see anything.

Likewise at the `|` position type `/usr/local<CTRL-x><CTRL-f` (omni-file completion), file choices should appear but don't.

If I checkout commit [2517075](https://github.com/hrsh7th/nvim-compe/commit/25170751944b64bb7b65af1e35772361485bc936) just before `72c4500` everything works just fine when I invoke manual completion.

It would be nice to fix this since having both auto-completion and manual-completion working at the same time is very useful.

Best regards.

**Comment by hrsh7th** [comment]
Thank you for your bisecting.
I will check it.

**Comment by bluz71** [comment]
Hopefully it will be repeatable for you.

**Comment by bluz71** [comment]
@hrsh7th,

Partially fixed, but I still encounter text completion issue. I think this should be re-opened.

Omni file-path completion is now working, problem solved.

But manual keyword completion via `CTRL-n` and `CTRL-p` is still an issue for me for this case:

```
Hello

He<CTRL-n>/<CTRL-p>
```

I am not seeing keyword completion. If I downgrade to commit `2517075` it works.

**Comment by hrsh7th** [comment]
Hm... It's weird...

I noticed, `<C-x><C-n>` is works fine but `<C-n>` does not work.

**Comment by bluz71** [comment]
Just updated and all appears good. Hopefully all corner cases have been found.

Many thanks.

Best regards.
