### ISSUE TITLE
nvim-compe invalidated some keymap(<c-n> and <c-p>)

### ISSUE THREAD

**Issue by 66RING** [hrsh7th/nvim-compe#279]
nvim-compe invalidated some keymap(<c-n> and <c-p>) in insert mode.

minimal vimrc:

```
set nocompatible
set runtimepath=$VIMRUNTIME
set runtimepath+=/home/ring/.local/share/nvim/site/pack/packer/opt/nvim-compe

lua << EOF
  require'compe'.setup {}
EOF

inoremap <C-n> <esc>:echo 'hi'<cr>
inoremap <C-p> <esc>:echo 'hi'<cr>
```

press `<c-n>` but nothing happen.

**Comment by hrsh7th** [comment]
@66RING It isn't a nvim-compe's problem, I think.

The vim does not support `<C-n>` and `<C-p>` mapping when the completion-menu is showing.

**Comment by 66RING** [comment]
@hrsh7th I have no idea. I pressed `<c-p>` to test it in insert mode when the completion-menu was not show.

this mapping work well when `set completeopt=menuone,noinsert,noselect`. 

And I have also tried other plugins([nvim-lua/completion-nvim](https://github.com/nvim-lua/completion-nvim)) and they work well.

**Comment by 66RING** [comment]
well, it good since last commit

**Comment by hrsh7th** [comment]
Sorry. I've misunderstood what your mean. Good to hear that works.
