### ISSUE TITLE
Feature request: resolve path alias

### ISSUE THREAD

**Issue by elianiva** [hrsh7th/nvim-compe#28]
I don't know if this possible or not, but basically, I want to be able to get path completion when using an alias. e.g `"@/components/stu| <- cursor"` will be treated as if it looks like `"{cwd}/src/components/stu| <- cursor"` where the alias replacement (`{cwd}/src`) can be just defined by the user. Again, I don't know if this is possible or not, so feel free to close this issue if it's not possible. Thanks! :)

**Comment by hrsh7th** [comment]
Do you know the some other completion-engine that realized it?
If so, I want to ask you about it.

In my impression, it is difficult in general solution.

**Comment by elianiva** [comment]
There's no completion that does this as far as I'm aware. So this might be impossible to do, even if it's possible then it might be difficult. 

Just asking, how do compe-nvim generate path completion? Is it reading the previous word and then gives the autocomplete items? I have an idea to replace the alias to a certain word and then lookup on that directory, but I don't know if this will work or not, just a thought on my head.

If that wouldn't work either, feel free to close this issue. It's not that I _really_ want it but it's a nice thing to have, just curious if it's actually possible or not. Thanks!

**Comment by hrsh7th** [comment]
If we provide the below config, I think this features can be implemented (but it is not a general solution, I think)
```
let g:compe_path_alias = {
\   '@': { bufnr -> SomeYourProjectRootDetection(bufnr) . '/src' },
\ }
```

**Comment by elianiva** [comment]
Yeah, defining it manually is not a good solution in my opinion but that's doable. I'll try to play around with it to see if I can come up with something. I don't think it is worthy enough to merge it into master though since only a fraction amount of people that uses it, including me.
Closing this issue for now.

**Comment by hrsh7th** [comment]
I had considered it before.

In my previous thoughts, it is `absolute path mode`.

For example, Your suggested example is converting `@/components/stu` to `%ROOT%/src/components/stu`.

We can think it is an upward search for project structure.

```
/%ROOT%
    /src
        /components
            /student
                index.tsx
            /school
                index.tsx
        /app
            index.tsx
```

In `/app/index.tsx`, `@/components/stu` is `../components/stu`.
In `/components/school/index.tsx`, `@/components/stu` is `../../components/stu`.

But this solution makes unexpected behavior if `/src/components/components/school/index.tsx` is existing.

Probably, this solution can be a general solution with more careful consideration.
