### ISSUE TITLE
Spell source seems to be broken

### ISSUE THREAD

**Issue by ChristianChiarulli** [hrsh7th/nvim-compe#280]
Noticed recently I don't have access to spell in markdown

**Comment by hrsh7th** [comment]
You should `set spell` for enabling spell source.

**Comment by chunyunma** [comment]
Sorry for posting in a closed issue. 
I enjoy the spell suggestions from compe when I am writing in markdown. 
However, I dislike the highlighted spelling errors.
Is there anyway I can get the spell suggestions without having to turn on "set spell"?

Thank you for your help!

**Comment by hrsh7th** [comment]
I have the same opinion. I dislike the spell highlight too.
But sorry... I didn't find the solution for it.
