### ISSUE TITLE
The completion menu is not aligned correctly

### ISSUE THREAD

**Issue by Verf** [hrsh7th/nvim-compe#282]
System: Windows 10  20H2 19042.867
Version: nvim v0.5.0-dev+1157-g0ab88c2ea
Configs: [minimal vimrc](https://github.com/Verf/vimrc/blob/debug/init.lua)

![1](https://user-images.githubusercontent.com/22053969/112077761-1bb4a900-8bb8-11eb-87c5-406b376495b7.png)

As shown in the figure, the completion menu is not properly indented and aligned. How can i make them aligned?

**Comment by elianiva** [comment]
seems like you're using a Neovim GUI client. Which one is it? (I'm guessing it's nvim-qt). Try disabling the GUI for the popup menu.
