### ISSUE TITLE
Recognise multible filetypes for snippets_nvim

### ISSUE THREAD

**Issue by z4m1n0** [hrsh7th/nvim-compe#283]
I use the plugin Snippets.nvim for sinppets. If i have a buffer with one filetype all is fine, but if i have multible filetypes it doesn't find the corresponding snipptes.

I looked in `lua/compe_snippets_nvim/init.lua` that the filetype is just used as a string:

```lua
local snippets_list = vim.tbl_extend ('force',
  snippets_nvim.snippets._global or {},
  snippets_nvim.snippets[vim.bo.filetype] or {}
)
```

but the filetypes are speparted by a `.` in `vim.bo.filetype`. In `:h ft` you can find:

```
When a dot appears in the value then this separates two filetype
names.  Example:
	/* vim: set filetype=c.doxygen : */ ~
This will use the "c" filetype first, then the "doxygen" filetype.
This works both for filetype plugins and for syntax files.  More than
one dot may appear.
```
I changed the code to:

```lua
local snippets_list = snippets_nvim.snippets._global or {}
local filetypes = vim.split(vim.bo.filetype, ".", true)
for _ , ft in ipairs(filetypes) do
  snippets_list = vim.tbl_extend ('force',
    snippets_list,
    snippets_nvim.snippets[ft] or {}
  )
end
```

and now it is working.

I saw that `vim.bo.filetype` is used "wrong" in the same way in other locations.

**Comment by hrsh7th** [comment]
Sorry. I don't use snippets.nvim and it's source.

Feel free to create PR. Thanks.

**Comment by hrsh7th** [comment]
This feature is `determine suitable snippets for current buffer` so I think originally it should be implemented by the snippet engine itself.

**Comment by z4m1n0** [comment]
> I think originally it should be implemented by the snippet engine itself.

You are right.

I created a pull request
