### ISSUE TITLE
SQLComplete error when writing sql

### ISSUE THREAD

**Issue by eruizc-dev** [hrsh7th/nvim-compe#286]
Without any completion configuration for SQL I get the following error when writing a sql file:

```
SQLComplete:the dbext plugin must be loaded for dynamic SQL completion
```

Picture:
![SQLComplete:the dbext plugin must be loaded for dynamic SQL completion](https://user-images.githubusercontent.com/58179604/112198707-2a1cb800-8bec-11eb-95ee-196c3417c258.png)

The error comes up every couple milliseconds which makes writing impossible. I'm not interested in configuring SQL completion at the moment, I just want to write SQL without completion.

**Comment by eruizc-dev** [comment]
### Workaround update

I found an [issue in SpaceVim](https://github.com/SpaceVim/SpaceVim/issues/1714) about the same thing. I was able to workaround this issue with [pgavlin approach](https://github.com/SpaceVim/SpaceVim/issues/1714#issuecomment-751887412)

**Comment by hrsh7th** [comment]
I think this problem occurred by `omni` source.

The omni source is really problematic. Please disable it if you had problem.
