### ISSUE TITLE
very hard to figure out matching for custom sources

### ISSUE THREAD

**Issue by ExpandingMan** [hrsh7th/nvim-compe#287]
I am trying to create a source for latex to unicode, but I find myself rather mystified by the regex matches in the existing examples.

I think I want to match something like `\\\w*` (backslash and then word or number of any length) but the matching done by `compe.helper` does not resemble normal regex in any obvious way.  I'm looking at the regex `\%(\s\|^\)\zs:\w*` for emojis which only seems to be matching on `:` but I cannot make any sense of it.

Would it be possible to provide more documentation for how to do matching for a custom source?

**Comment by hrsh7th** [comment]
The `compe.helper` uses vim's regex (because Lua's pattern matching is too simple).

```
return compe.helper.determine(context, {
  keyword_pattern = [[\\\w*$]]
})
```

**Comment by ExpandingMan** [comment]
Ah, that makes sense, I should have thought of that.

Again, if at some point you have the time to expand the docs on custom sources, it would be appreciated.  Thanks!
