### ISSUE TITLE
Feature request: fallback action

### ISSUE THREAD

**Issue by echasnovski** [hrsh7th/nvim-compe#288]
Currently my preferred completion workflow (with 'completion-nvim') is to look at some "complex" sources (like LSP and snippets) but fall back to Vim's completion (triggered by `<C-n>`) if there are no items there. This is a simple variant of chain completion, which you said you won't implement. However, maybe adding a setting for fallback action is more aligned with your views on this plugin? This should be a function which will be triggered if 'compe sources' returned no result.

I managed to implement this functionality with the following:
- Added these lines [here](https://github.com/hrsh7th/nvim-compe/blob/a39284243014c1414134b99ee2f7ae1fdd070273/lua/compe/completion.lua#L238):
```lua
if Completion._is_completing(context) then
  Config.get().fallback_action()
end
```
- Defined custom (almost one-to-one copy from 'completion-nvim') fallback action in `setup`:
```lua
fallback_action = function()
  local timer = vim.loop.new_timer()
  timer:start(80, 0, vim.schedule_wrap(function()
    mode_keys = vim.api.nvim_replace_termcodes('<c-g><c-g><c-n>', true, false, true)
    vim.api.nvim_feedkeys(mode_keys, 'n', true)
    timer:stop()
    timer:close()
  end))
end;
```

This seems to work as expected. Arguably, this functionality might be better as a different source, but I didn't manage to create one replicating Vim's `<C-n>` funcionality (with its completion from opened buffers, tags, dictionary, etc.). Also it might be difficult to implement in async fashion.

**Comment by hrsh7th** [comment]
I think it would be useful but probably it's very difficult.

Because nvim-compe is async completion engine so it will be show completion-menu even if all sources doesn't finish completion.

For example, if the user enables `buffer` source and `lsp` source.

1. Type keyword `lo|`
2. Invoke `buffer` and `lsp` source
3. First, the `buffer` source completed and completion-menu shown
4. Second, the `lsp` source completed and completion-menu redrawn

I think we should call fallback action on 4 in steps.

**Comment by echasnovski** [comment]
Yeah, any asynchronous execution is not easy.

Could you please help clarifying why the following change in `Completion._display()` seems to work (Vim's completion is shown only if no other source has candidate)? And when it can break?

```diff
diff --git a/lua/compe/completion.lua b/lua/compe/completion.lua
index e39c48b..b10b6c2 100644
--- a/lua/compe/completion.lua
+++ b/lua/compe/completion.lua
@@ -236,6 +236,9 @@ Completion._display = guard(function(context)

     if #items == 0 then
       Completion._show(0, {})
+      if Completion._is_completing(context) then
+        Config.get().fallback_action()
+      end
     else
       Completion._show(start_offset, items)
     end
```

Here is an example of how it works. I enabled `buffer` and `nvim_lua` compe sources, added `C-n` fallback action, and enabled Vim's spelling (detailed init.vim below):
![compe_fallback-action](https://user-images.githubusercontent.com/24854248/112618910-54aa8300-8e2f-11eb-9db1-21d75db2c161.gif)

<details>
<summary>Gif is created with this 'init.vim'</summary>

```vim
call plug#begin('~/.config/nvim/autoload/plugged')
  Plug 'hrsh7th/nvim-compe'
call plug#end()

set spell
set spelllang=en
set complete+=kspell

set completeopt=menuone,noselect

lua << EOF
compe = require'compe'

compe.setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;

  fallback_action = function()
    local timer = vim.loop.new_timer()
    timer:start(80, 0, vim.schedule_wrap(function()
      mode_keys = vim.api.nvim_replace_termcodes('<c-g><c-g><c-n>', true, false, true)
      vim.api.nvim_feedkeys(mode_keys, 'n', true)
      timer:stop()
      timer:close()
    end))
  end;

  source = {
    buffer = true;
    nvim_lua = true;
  };
}

vim.api.nvim_set_keymap(
  'i', '<CR>', [[compe#confirm('<CR>')]],
  {silent = true, expr = true, noremap = true}
)
EOF
```
</details>

**Comment by hrsh7th** [comment]
I will consider it.

I think your patch is not enough about some corner cases.

1. We should check if all sources completed or not.
2. We should fallback only if the completion invoked manually.
