### ISSUE TITLE
Error: buffer id not valid 

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#29]
I'm having issue with buffer id not valid 

I add this around line 54 and still testing it, i'm not sure it would fix the problem though
```
      if not vim.api.nvim_buf_is_valid(self.bufnr) then return end
```

![image](https://user-images.githubusercontent.com/65782666/100047931-af51b500-2e24-11eb-8af5-ebd30089ca6a.png)

**Comment by hrsh7th** [comment]
Thank you.
It's the correct solution for this problem to me.
I will fix it.

**Comment by tami5** [comment]
@hrsh7th basically it is triggered by telescopes' grep_string function, which shows create a temp buffer

**Comment by hrsh7th** [comment]
Thank you!
I will look into `grep_string` function if I have spent time.

**Comment by tami5** [comment]
Thanks @hrsh7th

**Comment by tami5** [comment]
I'm facing the similar issue 

`Error executing vim.schedule lua callback: ...ite/pack/packer/opt/nvim-compe/lua/compe_buffer/init.lua:63: attempt to
 index a nil value
`

Also related to telescope picker "help with buffer preview"

**Comment by tami5** [comment]
Also some times `Error executing vim.schedule lua callback: ...e/pack/packer/opt/nvim-compe/lua/compe_buffer/buffer.lua:111: bad argum
ent #1 to 'ipairs' (table expected, got string)`
