### ISSUE TITLE
Icons for completion items

### ISSUE THREAD

**Issue by Shatur95** [hrsh7th/nvim-compe#290]
It would be great to have this feature to visually differentiate between completion items.
For example, how completion looks in VSCode:
![изображение](https://user-images.githubusercontent.com/22453358/83648151-61b76680-a5be-11ea-97c2-f42fbf221401.png)

The same feature available in [completion-nvim](https://github.com/nvim-lua/completion-nvim).

**Comment by hrsh7th** [comment]
You can use https://github.com/onsails/lspkind-nvim

**Comment by Shatur95** [comment]
Thanks!

**Comment by Shatur95** [comment]
@hrsh7th, but is it possible to have icons for other completion sources (buffer, for example).

**Comment by cloggier** [comment]
You might achieve that by changing `menu` field for each source to something like `<icon> buffer`.

**Comment by Shatur95** [comment]
@cloggier, thanks!
