### ISSUE TITLE
Sort by shortest match first

### ISSUE THREAD

**Issue by dstadelm** [hrsh7th/nvim-compe#292]
I've got the case that I'm typing proc (exact match) and I've got 20+ entries proc_xxx which 'hide' the proc completion. It seems that the entries are sorted by source first [tag] then [ultisnips] then [buffer].

Can this behavior be configured or does it require a change?

**Comment by hrsh7th** [comment]
I can't understand... sorry.

Please more clarification.

Currently, source priority can be configured by following settings.

```
let g:compe = {}
let g:compe.source = {}
let g:compe.source.buffer = { 'priority': 1000 }
let g:compe.source.tags = { 'priority': 500 }
```

**Comment by dstadelm** [comment]
![image](https://user-images.githubusercontent.com/3010527/113057380-40f37980-91ad-11eb-9e5c-971888fc76d1.png)

In the attached image, you can see that I'm typing pro. I'm wondering, why proc is not at first place, as it is currently the 'best' match.

How can I find out the default priority you are describing?

**Comment by tami5** [comment]
I kinda have the exact same issue where it always bothered me.

**Comment by dstadelm** [comment]
Although the issue has been closed, the problem for me remains. Could you elaborate why it is closed, or what has to be configured to achieve the desired effect?

Thanks for your hard work, I really appreciate it!

**Comment by hrsh7th** [comment]
Hm... nvim-compe will sort items as follows.

1. priority sort.
2. score sort
3. alphabetical sort

I'm guessing you don't want to sort with priority. If so, you should set priority as same value for each all sources.

**Comment by cooper-anderson** [comment]
It would be great to be able to set the priority of specific ItemKinds to be higher. For example, if I want all the fields of an object to appear first, then its methods, and then extra stuff that the language puts there (like JS's prototype, etc)

**Comment by dstadelm** [comment]
Thank you, that solved my issue!

For others here the lua equivalent config:

  source = {
  sort = { priority = 500; };
  tags = { priority = 500; };
  spell = { priority = 500; };
  path = { priority = 500; };
  buffer = { priority = 500; };
  calc = { priority = 500; };
  nvim_lsp = { priority = 500; };
  nvim_lua = { priority = 500; };
  ultisnips = { priority = 500; };
  nvim_treesitter = { priority = 500; };
  };

**Comment by dstadelm** [comment]
I'm kind of missing the feature I've once had in emacs, where tab would complete until the next character where you have to make a distinctive selection. It is the same as e.g. on the terminal when changing directories, where it will expand until to the character for which all possible options are equal, then you can type a further letter and expand further. But maybe that is off topic, or topic for a different issue...

**Comment by cooper-anderson** [comment]
@dstadelm I was just thinking of that feature from the JetBrains IDEs yesterday! It would be a great feature

**Comment by ExpandingMan** [comment]
I'm having a similar, but distinct problem.  I have defined a custom source [here](https://gitlab.com/ExpandingMan/compe-latex).  Despite having messed around some with the `sort_text` property of the items, I cannot get suggestions to appear in a reasonable order.

For example, if I type `\chi`, you would expect the first completion in the list to be `\chi`, after all, it's exactly the same string, but instead the first suggestion is `\Chi` and `\chi` appears way down the list.  This basically renders it unusable.  I think I could fix some special cases by putting in `sort_text` properties, but so far I can't find a general way of ensuring it returns a reasonable list without writing my own elaborate filtering and sorting methods.

**Comment by hrsh7th** [comment]
@ExpandingMan You can specify `sort = false` for your custom sources' metadata.

**Comment by hrsh7th** [comment]
The `sort=false` means compe will keep an order that item arrays returned from source.

**Comment by PSeitz** [comment]
I have a similar issue where the exact match is not at the top.
`sort=false` or `sort=true` doesn't help.

![Screenshot from 2021-06-17 08-52-45](https://user-images.githubusercontent.com/1109503/122348351-5d50b800-cf4b-11eb-8277-68980c4aff5c.png)
