### ISSUE TITLE
Auto Import makes a new import instead of using the old one

### ISSUE THREAD

**Issue by jaydamani** [hrsh7th/nvim-compe#295]
When an object is imported by auto import and there is already an import from the same module, auto import will insert a new line for import instead of reusing the old one.

Expected output :
```js
import { Message, Channel } from 'discord.js'
```
![vid](https://user-images.githubusercontent.com/62935927/112748589-43ea4080-8fda-11eb-876f-95bd91f2b053.gif)

**Comment by elianiva** [comment]
Weird, it's working just fine for me.

https://user-images.githubusercontent.com/51877647/112753889-c3403a00-9003-11eb-9c3f-9fbd4efda877.mp4
