### ISSUE TITLE
Feature request: linked/chained completion mode

### ISSUE THREAD

**Issue by gegoune** [hrsh7th/nvim-compe#299]
mucomplete supports something they call 'extended completion', basically it helps quickly complete sequences of words by looking for word past one just matched.

It is separate mode which requires calling another completion method.

Please look at "Extending completion" example in https://github.com/lifepillar/vim-mucomplete to see exactly what I mean.

It was very nice to have when I was using mucomplete, I could see that being part of `buffer` source and definitely would use it daily. What do you think @hrsh7th?

**Comment by hrsh7th** [comment]
Interesting.....!!!

Hmm... mucomplete uses vim's native completion features. it does not fit the compe's approach...

But I think it is very nice feature! I will consider it. And feel free to post your idea!

**Comment by cloggier** [comment]
Still relevant and pretty desired feature.

**Comment by lourenci** [comment]
This is the only thing I miss in nvim-compe. Please, consider to add it. :) Thanks

**Comment by Shougo** [comment]
The feature is discussed in https://github.com/hrsh7th/nvim-compe/issues/120.

**Comment by gegoune** [comment]
@hrsh7th Do you think you could maybe move this issue to nvim-cmp? Would you consider it as part of amp-buffer source or even separate source? Would love to have that. :)

**Comment by Shougo** [comment]
You can request it in nvim-cmp issues.

**Comment by gegoune** [comment]
Absolutely, it's just that this issue already has some context added to it and moving it over would preserve it.

**Comment by Shougo** [comment]
I have read the feature.
It seems accept current completion and fire the next auto completion.

It is not for sources feature.

**Comment by Shougo** [comment]
And the issue title seems confusing.
The title is for chained completion but you have described extended completion.
They are different features.

**Comment by gegoune** [comment]
Apologies of it wasn't clearly reported. Not sure why it's called exactly. 

Do you think this is something that has to be provided by nvim-cmp's core or could be done as a source?

**Comment by Shougo** [comment]
It can be provided by nvim-cmp's core.
