### ISSUE TITLE
VS.Vim.Syntax.Markdown errors

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#301]
Hey @hrsh7th, 

I've getting these error recently: 

```
[VS.Vim.Syntax.Markdown] The `toml` is not valid filetype! You can add `"let g:markdown_fenced_languages = ["FILETYPE=toml"]`.
[VS.Vim.Syntax.Markdown] The `text` is not valid filetype! ... add `"let g:markdown_fenced_languages = ["FILETYPE=text"]`
```

Is that normal?

**Comment by tami5** [comment]
Do I need to to add this languages like toml to markdown_fenced_languages?

**Comment by hrsh7th** [comment]
You seem not to have a `toml` syntax so this warning is shown.

If you install toml syntax file, it will be fixed.
