### ISSUE TITLE
Question regarding autocompletion of function arguments (signatures)

### ISSUE THREAD

**Issue by andersevenrud** [hrsh7th/nvim-compe#302]
Hi! I love this project. Thank you so much for your work.

I'm transitioning over from coc.nvim to this plugin and it does not look like autocompletion of arguments (signatures) is working for all language servers. I've tried solving this myself for a few days and posted on [reddit](https://www.reddit.com/r/neovim/comments/mdy1c8/function_signature_autocompletion_with_nvimcompe/), but no solution so far.

I'm using this plugin in combination with delimitMate, vsnip and configration pasted from your README. ([Link to configs if needed configurations](https://github.com/andersevenrud/dotfiles/tree/master/.config/nvim)).

Since this worked for me in coc.nvim my question is this: Is this a missing feature in compe, or does coc.nvim have some custom non-standard features that is not in the typescript language server ?

## Rust Example

I get suggestions (with the `~` that indicates snippets):

![lsp-rust-01](https://user-images.githubusercontent.com/161548/112913513-109ed300-90fa-11eb-9b85-8b1f2b2f61ca.png)

Parentheses (`()`) and arguments on <kbd>enter</kbd>:

![lsp-rust-00](https://user-images.githubusercontent.com/161548/112913511-10063c80-90fa-11eb-8be4-1c8622d91f9f.png)

## TypeScript Example

I get suggestions (documentation preview does work, there's just no documentation in this source):

![lsp-ts-00](https://user-images.githubusercontent.com/161548/112913514-109ed300-90fa-11eb-8ad3-41434aafe094.png)

But no arguments or parentheses (`()`) on <kbd>enter</kbd>:

![lsp-ts-01](https://user-images.githubusercontent.com/161548/112913515-109ed300-90fa-11eb-9e40-7089ae2f822c.png)

**Comment by hrsh7th** [comment]
coc's typescript server has a good implementation than a typescript-language-server so this can't solve by nvim-compe side sorry.

**Comment by andersevenrud** [comment]
Okay! Thank you for the clarification.

**Comment by folke** [comment]
@andersevenrud I've created a small workaround to make signature completion work with compe and tsserver:
```lua
local Helper = require "compe.helper"
Helper.convert_lsp_orig = Helper.convert_lsp
Helper.convert_lsp = function(args)
  local response = args.response or {}
  local items = response.items or response
  for _, item in ipairs(items) do
    -- 2: method
    -- 3: function
    -- 4: constructor
    if item.insertText == nil and (item.kind == 2 or item.kind == 3 or item.kind == 4) then
      item.insertText = item.label .. "(${1})"
      item.insertTextFormat = 2
    end
  end
  return Helper.convert_lsp_orig(args)
end
```

Just add that code in your compe config.

It basically adds a snippet for completion items that are function like.

To get signature help after completion, you can additionally add something like:
```lua
vim.cmd [[autocmd User CompeConfirmDone :Lspsaga signature_help]]
```

**Comment by folke** [comment]
@hrsh7th if you're interested I'm willing to make a PR for the workaround in my previous comment.
Maybe a configuration option `add_missing_function_snippets` that is `false` by default and that can be enabled for certain LSP clients like *tsserver*?

**Comment by hrsh7th** [comment]
Thank you~!

I'm considering to use `LSP` item as first-class citizen.
So helper.convert_lsp will change or remove.

**Comment by andersevenrud** [comment]
@folke Sweet! This seems to be be working in my initial testing :) The only issue I have is that the autocomplete popup re-appears when I complete an item so the saga signature help is overlapped and not visible. Probably something on my end.

**Comment by siduck76** [comment]
> @andersevenrud I've created a small workaround to make signature completion work with compe and tsserver:
> 
> ```lua
> local Helper = require "compe.helper"
> Helper.convert_lsp_orig = Helper.convert_lsp
> Helper.convert_lsp = function(args)
>   local response = args.response or {}
>   local items = response.items or response
>   for _, item in ipairs(items) do
>     -- 2: method
>     -- 3: function
>     -- 4: constructor
>     if item.insertText == nil and (item.kind == 2 or item.kind == 3 or item.kind == 4) then
>       item.insertText = item.label .. "(${1})"
>       item.insertTextFormat = 2
>     end
>   end
>   return Helper.convert_lsp_orig(args)
> end
> ```
> 
> Just add that code in your compe config.
> 
> It basically adds a snippet for completion items that are function like.
> 
> To get signature help after completion, you can additionally add something like:
> 
> ```lua
> vim.cmd [[autocmd User CompeConfirmDone :Lspsaga signature_help]]
> ```

can this be done without lspsaga? also for all languages

**Comment by andersevenrud** [comment]
@siduck76 The compe helper code above should work for all languages. 

As for signature help, you can do that with the native function:

```
vim.cmd [[autocmd User CompeConfirmDone :lua vim.lsp.buf.signature_help]]
```

**Comment by Melkster** [comment]
@andersevenrud I tried your suggestions but I couldn't get them to work. The error `...config/nvim/packages/nvim-compe/lua/compe/completion.lua:160: Vim(lua):E5107: Error loading lua [string ":lua"]:1: '=' expected near '<eof>'` gets ouputted when I try to complete a snippet-like completion function.

Here's a minimal config that still causes named error:

```lua
call plug#begin('~/.config/nvim/packages/')
Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/nvim-compe'
Plug 'kabouzeid/nvim-lspinstall'
call plug#end()

lua << EOF
require('lspinstall').setup()
local servers = require('lspinstall').installed_servers()
for _, server in pairs(servers) do
  require'lspconfig'[server].setup({})
end

require('compe').setup {
  preselect = 'always',
  source = {
    path     = true,
    nvim_lsp = true,
  }
}

vim.api.nvim_set_keymap('i', '<Tab>', 'compe#confirm()', {expr = true, noremap = false})

vim.cmd('autocmd User CompeConfirmDone :lua vim.lsp.buf.signature_help')
EOF
```

**Comment by andersevenrud** [comment]
@Melkster Oh... my bad. It should probably be `autocmd User CompeConfirmDone lua vim.lsp.buf.signature_help()`.

**Comment by Melkster** [comment]
@andersevenrud Thank you, that seems to fix the error. However,

```lua
vim.cmd('autocmd User CompeConfirmDone lua vim.lsp.buf.signature_help()')
```

only outputs "`No signature help available`" and

```lua
vim.cmd('[autocmd User CompeConfirmDone Lspsaga signature_help]')
```

does nothing when I try to complete functions like `require`, `assert`, etc. that show up in my autocompletion popup list in Lua files. Is this expected behaviour for Lua?

**Comment by andersevenrud** [comment]
@Melkster I think the issue here is that the signature help does not display anything unless it completes with parentheses, which is usually provided via snippets, which does not seem to be a thing in the Lua language server (usually shown in completion popup with a tilde symbol).

**Comment by Melkster** [comment]
@andersevenrud Yeah that seems to check out.

What I personally would like is for functions provided by the LSP to be completed with parentheses and template arguments in Lua. This functionaly is available for some languages, for instance in Java (Eclipse JDTLS with Lombok). For example, in the poupup menu the function `assert` shows up with template argument like so: `assert(v, message)~`, so it seems reasonable to get this functionality for Lua as well? Is this a limitation on the language server for Lua (sumneko)?

**Comment by andersevenrud** [comment]
@Melkster What you're describing there is exactly why I opened this issue. This is a limitation in the language servers (I believe it's the `insertText` parameter for `completionItem`s in the spec).

As mentioned in the OP, this was available for me in coc.nvim with TypeScript -- turns out that coc used a port of the VSCode TypeScript integration (that supports parentheses *and* parameter completion on functions via snippets), which is not the same as the [TS LSP server](https://github.com/theia-ide/typescript-language-server).
