### ISSUE TITLE
Message "Client 1 quit with exit code 1 and signal 0"

### ISSUE THREAD

**Issue by saahiluppal** [hrsh7th/nvim-compe#303]
This is the <a href='https://gist.github.com/saahiluppal/241ba70a3f6cfaaa21420a9373fef757'>init.vim</a>
Using only one language server for python i.e. ""pyright""

Following message pops out as soon as i open any python file
```bash
Client 1 quit with exit code 1 and signal 0
```
What should i do?

**Comment by hrsh7th** [comment]
nvim-compe does not affect when opening files so it is not nvim-compe's issue, I think.

I guess your lspconfig setup is wrong. you should check `:LspInfo` results.
