### ISSUE TITLE
For Vue 3 does not show autocomplete

### ISSUE THREAD

**Issue by lbavendanos** [hrsh7th/nvim-compe#305]
I'm not really sure if this issue is from nvim-compe, lspconfig, or vetur. But in the same way, I comment on it here because this functionality is what is needed.

It happens that I do not get the autocomplete for Vue 3. But if I have help for Vue 2. On the other hand, I also use lspsaga which if I get help with the imported one. So, I would like to know if someone else happens this to him, and how I can solve it. Maybe it's some configuration in LSP but I'm not really sure.

### nvim-compe
<img width="412" alt="Captura de Pantalla 2021-03-30 a la(s) 11 40 49" src="https://user-images.githubusercontent.com/28379400/113025318-70729980-914d-11eb-981a-5a22fc76859f.png">

### lspsaga
<img width="469" alt="Captura de Pantalla 2021-03-30 a la(s) 11 41 29" src="https://user-images.githubusercontent.com/28379400/113025417-8d0ed180-914d-11eb-9af6-d042153ae393.png">

#### Another link with the similar problem
https://www.reddit.com/r/neovim/comments/jte9cq/vue_lsp/

#### Versions:
- vls@0.7.2
- NVIM v0.5.0-dev+aa6adac

**Comment by hrsh7th** [comment]
I hadn't ever use vetur but it seems auto_import disabled by default.
https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/vuels.lua#L21

**Comment by lbavendanos** [comment]
You are right, thank you very much for your help and your prompt response.
The configuration would be like this:
```
require('lspconfig').vuels.setup {
  init_options = {
    config = {
      vetur = {
        completion = {
          autoImport = true
        }
      }
    }
  }
}
```
