### ISSUE TITLE
Error - attempt to call 'get_metadata' (a nil value)

### ISSUE THREAD

**Issue by ecosse3** [hrsh7th/nvim-compe#306]
Hi, yesterday after compe update via vim-plug I have an error when pressing <C-Space> in insert mode. Compe stopped working at all.

![image](https://user-images.githubusercontent.com/17691791/113119482-c6f4dc00-9210-11eb-99ff-606c3dd6e12b.png)

Space is mapped to `compe#complete()`

NVIM v0.5.0-dev+nightly-166-gc20ae3aad
Build type: Release
LuaJIT 2.1.0-beta3
macOs Catalina 10.15.7

My full config: https://github.com/ecosse3/nvim

Didn't try to reproduce yet on minimal config.

**Comment by hrsh7th** [comment]
It's weird.

I can't reproduce your configuration like setting.

Sorry. Please check with minimal config.

**Comment by ecosse3** [comment]
Didn't have much time yet today but I was able to find where is the problem. When I commented out **tabnine** plugin from nvim-compe sources then it works correctly. (4 files from bottom)

```jsx
require'compe'.setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;

  source = {
    path = true;
    buffer = true;
    calc = true;
    vsnip = true;
    nvim_lsp = true;
    nvim_lua = true;
    spell = true;
    tags = false;
    snippets_nvim = false;
    treesitter = true;
    -- tabnine = true;
    ultisnips = true;
  };
}

```

So it's a problem caused by **tzachar/compe-tabnine** plugin. I think here issue can be closed. I'll open a new one on compe-tabnine repo.

**Comment by tzachar** [comment]
this should be solved with the latest commit in tzachar/compe-tabnine
