### ISSUE TITLE
Buffer source missing words

### ISSUE THREAD

**Issue by cloggier** [hrsh7th/nvim-compe#309]
I have a plain text file with about 1500 unique words and I have noticed that compe misses to provide completion for some of the words. I don't know if there is pattern, at the moment I know about two words that are not being provided completions for, even if I type full word. Both words are three characters long, one is capitalised (Foo), another one is all caps (FOO).

How could I debug it?
Thanks!

**Comment by hrsh7th** [comment]
Yes. It's a known issue. I don't know why happen.

**Comment by hrsh7th** [comment]
https://github.com/hrsh7th/nvim-compe/issues/248

**Comment by cloggier** [comment]
Ah, didn't realise that. Apologies. Gonna close this now. Thanks!
