### ISSUE TITLE
Implement border, padding and some pretty staff in documentation.

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#31]
It should be implemented in https://github.com/hrsh7th/vim-vital-vs

**Comment by tami5** [comment]
Thats amazing @hrsh7th , are you going to copy the code over here?

**Comment by hrsh7th** [comment]
I'm using vital.vim.
It has embeddable module system.

**Comment by tami5** [comment]
Just got an overview of vital.vim, seems interesting. But just to make sure nothing in  https://github.com/hrsh7th/vim-vital-vs are duplicated here, right?

**Comment by hrsh7th** [comment]
Yes. vital.vim is `embeddable` library so I embedded some modules to vim-vsnip, nvim-compe, vim-lamp and vim-candle.

**Comment by tami5** [comment]
Oh nice. seems to be very interesting
