### ISSUE TITLE
How to autoselect the first match?

### ISSUE THREAD

**Issue by jojoyuji** [hrsh7th/nvim-compe#324]
Is there an easy way to auto select the first match without having to navigate through the completion list?

example of what I want to achieve:
typed `"as"` and the completion pops up with the first match selected `"async"`
<img width="632" alt="Captura de Tela 2021-04-08 às 09 42 36" src="https://user-images.githubusercontent.com/675317/114037537-165d8c80-984f-11eb-9753-2dbdc4d44031.png">

As it is now, I type `"as"` and have to manually select the first match in the completion menu since it's not selected by default:
<img width="504" alt="Captura de Tela 2021-04-08 às 09 42 54" src="https://user-images.githubusercontent.com/675317/114037969-748a6f80-984f-11eb-8038-b5fb531a4efc.png">

I saw the `preselect` option in config but dunno what it really does...

Can anyone help me?

**Comment by hrsh7th** [comment]
You can use `preselect = 'always'`

**Comment by jojoyuji** [comment]
Lovely! tysm!
