### ISSUE TITLE
Rust Analyzer server auto-import issue

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#326]
Hey everyone, I'm having issue with auto-import, for some reason it stopped working. Does anyone has auto-import working with rust-analyzer?

Thanks

**Comment by tami5** [comment]
```lua
 local capabilities = vim.lsp.protocol.make_client_capabilities()
    capabilities.textDocument.completion.completionItem.snippetSupport = true
    capabilities.textDocument.completion.completionItem.resolveSupport = { properties = { 'additionalTextEdits' } }
```
credit @Unoqwy

**Comment by hrsh7th** [comment]
I'ved added it to README.md

**Comment by smartding** [comment]
@tami5 
I've configured lsp capabilityes according to readme.
```lua
local updated_capabilities = vim.lsp.protocol.make_client_capabilities()
updated_capabilities = vim.tbl_deep_extend("keep", updated_capabilities, require'lsp-status'.capabilities)
updated_capabilities.textDocument.completion.completionItem.snippetSupport = true
updated_capabilities.textDocument.completion.completionItem.resolveSupport = {
  properties = {
    "documentation",
    "detail",
    "additionalTextEdits",
  },
}
```
But how do I actually use this auto import feature from rust-analyzer?

Let's say I'm calling the `from_str` funciton on `u64`, after typing `u64::` and hitting tab, `from_str` isn't one of the completion items from lsp server. There's no way to inform lsp server that I want to call the `from_str` funtion and it should auto import `std::str::FromStr`
