### ISSUE TITLE
ultisnips interpolation

### ISSUE THREAD

**Issue by horseinthesky** [hrsh7th/nvim-compe#327]
I'm using UltiSnips as one of the sources:
```
require'compe'.setup {                           
  preselect = 'disable',                         
  source_timeout = 100,                          
                                                 
  source = {                                     
    path = {kind = ""},                         
    buffer = {kind = ""},                       
    calc = {kind = ""},                         
    nvim_lsp = {kind = ""},                     
    nvim_lua = {kind = ""},                     
    spell = {kind = ""},                        
    ultisnips = {kind = ""},                    
    tabnine = {kind = "", priority = 50},       
    emoji = {kind = "ﲃ", filetypes={"markdown"}},
  },                                             
}                                                
```

And `compe` doesn't show what is inside the snippet.
![image](https://user-images.githubusercontent.com/19948672/114235470-ea462680-9988-11eb-90dd-c97b4267e19e.png)
It is also doesn't expand the snippet: if I press `<CR>` it just paste `addaarg`.

Is it possible to achieve `CoC` way of doing this?
![image](https://user-images.githubusercontent.com/19948672/114235597-13ff4d80-9989-11eb-9a0f-0f0460bd1429.png)

**Comment by hrsh7th** [comment]
PR welcome. :)

**Comment by horseinthesky** [comment]
I wish I know how this even works =)

**Comment by fullstopslash** [comment]
I'm  having  the same problem, I cant for the life of me figure out how to get ultisnips to even function. I've been coming at the problem for almost a week now and **nothing** has worked for me. Clearly it can work because there's a gif of it working. An example of a functioning setup would be nice. Not just a gif.

**Comment by horseinthesky** [comment]
@fullstopslash The only thing ultisnips needs is a set of mappings:
```
vim.g.UltiSnipsExpandTrigger = "<C-s>"      
vim.g.UltiSnipsJumpForwardTrigger = "<C-j>" 
vim.g.UltiSnipsJumpBackwardTrigger = "<C-k>"
```
So it functions perfectly fine.

But the only way to expand the snippet is to trigger ExpandTrigger key which is not that bad but still needs to have the option to expand from dropdown menu (as on pic.).
The bigger drawback is at the moment there is no way to see what is inside the particular snippet until it is expanded.

**Comment by baldore** [comment]
Maybe https://github.com/fhill2/telescope-ultisnips.nvim has a clue for this. It works with Telescope and it actually shows the preview. Pretty cool thing.

**Comment by horseinthesky** [comment]
@baldore Well, this certainly could be used but this is definitely not the desired workflow.

I see it like this:
1) I'm in the INSERT mode starting to write the keyword of the snippet, completion plugin (compe in this case) finds it in the snippet source (ultisnips in this case) and shows it to me in the completion menu. This part works perfectly fine already.
2) Now I `<tab>` to the desired snippet in the completion menu, check if it is going to expand to the text I am expecting and press `<CR>` to expand it. This part doesn't work.

**Comment by baldore** [comment]
If I understand correctly the issue, the idea is this:

- The editor is in INSERT mode.
- I start to type and compe shows the snippets.
- I select one of the options with <C-n> / <C-p>
- This is the important one: while the snippet is selected, it shows an additional popup with the snippet body.
- Hitting <CR> expands the snippet.

I think this is the most efficient behavior. Just to show the body additionally when a ultisnips option is highlighted.

**Comment by horseinthesky** [comment]
That is correct. My second screenshot shows exactly this behavior which is implemented in `CoC` at the moment.
Would be great to have it in `compe`.

**Comment by baldore** [comment]
Again, the solution is in telescope ultisnips. I could work on this, but it will take some time since I have a lot of work. Let me know if it's fine and I'll work on it.

**Comment by horseinthesky** [comment]
@baldore Absolutely fine. There is no hurry. Just clarifying how I see it should work.
Would be great if can achieve that whenever you have time.

**Comment by baldore** [comment]
Got it, I'll work on it!

**Comment by baldore** [comment]
@horseinthesky this is what you want, right?

![image](https://user-images.githubusercontent.com/3131037/114788563-892aa400-9d36-11eb-8ad1-5b16ed39b388.png)

btw, @hrsh7th does the popup have a way to set a filetype? so it displays with the UltiSnips highlight?

**Comment by horseinthesky** [comment]
> @horseinthesky this is what you want, right?

Yes. And it should expand by pressing `<CR>`. At the moment it would paste `ife`.

**Comment by hrsh7th** [comment]
@baldore 
You can specify filetype as follows.

https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe_vsnip/init.lua#L36

The documentation uses markdown syntax. So you should wrap content by `\```filetype %CONTENT% \``` `

**Comment by baldore** [comment]
@horseinthesky I just checked and it seems it's already possible to expand the snippet with `<CR>`. It's in the documentation, but I add it here for reference:

```vim
inoremap <silent><expr> <CR>      compe#confirm('<CR>')
```

Just by adding this, when you press `<CR>` it expands the snippet. Tested it myself and works like a charm!

**Comment by baldore** [comment]
It seems like the UltiSnips highlight is not as easy as I thought. For what I see in other plugins like `coc-snippets`, it needs to have the syntax file and source it in the buffer. I need to take a deeper look at the code, but just by using triple quoutes and the filetype `snippets` (Taken from `se ft?` in a ultisnips file) is not enough.

**Comment by hrsh7th** [comment]
I think you shouldn't use `snippets` filetype. You should use `args.context.filetype` as filetype.

**Comment by horseinthesky** [comment]
> ```viml
> inoremap <silent><expr> <CR>      compe#confirm('<CR>')
> ```

Ah yeap. It works.

**Comment by baldore** [comment]
> I think you shouldn't use `snippets` filetype. You should use `args.context.filetype` as filetype.

Yes, much better! Not sure why I closed myself to the idea of using ultisnips highlight. I'll send the PR soon. Thanks a lot!

**Comment by horseinthesky** [comment]
@baldore Thanks a lot for this.

I've looked through the code and can't understand where/when this new buffer/window for snippet is created.

At the moment this floating window has no background and it is way too narrow.
![image](https://user-images.githubusercontent.com/19948672/115660195-5723ce00-a344-11eb-92c9-1b4f79fe9787.png)

**Comment by baldore** [comment]
@horseinthesky not sure about that. I think you should create another ticket for it or see if @hrsh7th can give you a quick answer here.
