### ISSUE TITLE
<C-y>/<C-e> behavior

### ISSUE THREAD

**Issue by rudotriton** [hrsh7th/nvim-compe#329]
Whenever the pop-up is open, the usual insert mode behavior for C-y and C-e breaks. Can I map, whatever they are used for right now, under something else, such as a meta key, so that I can keep my C-y/e? I realize that I can somewhat get around this by manually triggering the popup and then having C-y/e close it, but this feels very clumsy.

**Comment by hrsh7th** [comment]
I didn't understand your means.

Please your expected (but broken) configuration.

**Comment by rudotriton** [comment]
normally, in insert mode `c-y` and `c-e` would insert characters above and below the cursor, respectively.


https://user-images.githubusercontent.com/14181026/114366101-ca2e8700-9b83-11eb-9aec-96f63a653a3c.mov

With `autocomplete = true`, I can press `c-y` or `c-e` once before the popup opens and the usual behavior of `c-e` and `c-y` breaks.


https://user-images.githubusercontent.com/14181026/114366427-1ed20200-9b84-11eb-9bf0-2a8dda653df7.mov

With `autocomplete =  false` and something like this:

```vim
inoremap <silent><expr> <C-Space> compe#complete()
inoremap <silent><expr> <C-y> compe#close('<C-y>')
inoremap <silent><expr> <C-e> compe#close('<C-e>')
```

I can somewhat keep the normal `c-y` and `c-e` behavior as the first press closes the popup and the next one inserts the character from above or below, but now I obviously have to manually open the popup.

I was wondering if it is possible to keep the usual insert mode behavior of `c-e` and `c-y` while still having `autocomplete = true`?

**Comment by hrsh7th** [comment]
Oh! I didn't know the `<C-y>` and `<C-e>` behavior.

It's bit hard to fix... so it will be take a time.

**Comment by ewok** [comment]
this worked for me:
```
inoremap <silent><expr> <C-e>     compe#close('<C-e>')
inoremap <expr> <C-y> pumvisible() ? "\<C-e>\<C-y>" : "\<C-y>"
inoremap <expr> <C-e> pumvisible() ? "\<C-e>\<C-e>" : "\<C-e>"
```

**Comment by ewok** [comment]
This is working for me as expected:
```
inoremap <expr> <C-y> pumvisible() ? "\<C-y>\<C-y>" : "\<C-y>"
```
but this  kind of buggy, sometimes it stucks
```
inoremap <expr> <C-e> pumvisible() ? "\<C-y>\<C-e>" : "\<C-e>"
```

**Comment by hrsh7th** [comment]
We should check if printable chars inserted on`InsertCharPre` for auto-completion.

**Comment by lewis6991** [comment]
I use`<C-y>` and `<C-e>` a lot and found this issue particularly annoying when switching to this plugin. Would really appreciate it if we could raise the priority of this.

I can take a look myself if someone could give some quick tips on what part of the codebase needs fixing.

**Comment by andymass** [comment]
If you use something like airline it's strange that after using c-e you are
still in "insert complete mode".  This does not happen without compe.
