### ISSUE TITLE
`nvim-compe` hangs when completing long (non-English) words

### ISSUE THREAD

**Issue by mrossinek** [hrsh7th/nvim-compe#330]
I ran into this weird issue when trying to write out the German word `Aktiengesellschaft` (stock corporation). Whenever I would get to roughly `Aktiengesel` my Neovim would hang to type the following key presses until I abort some process with `Ctrl-C` (or after >2 seconds). I assume, that the hanging process is the spell-completion of `nvim-compe` because the problem goes away when turning off `nvim-compe` or at least its `spell` completion.

That being said, I cannot yet reproduce this issue with `nvim --clean` because I cannot even get `nvim-compe` to get to work in that setting. I can only get it to work with `nvim -u minimal_config.vim` with the following contents:
```vim
set completeopt=menuone,noselect
set spell
set spelllang=en_us,de

let g:compe = {}
let g:compe.enabled = v:true
let g:compe.autocomplete = v:true
let g:compe.debug = v:false

let g:compe.source = {}
let g:compe.source.spell = v:true
```
This obviously still uses my normal plugin path but I have not got it to complete anything otherwise.

Completion of long English words performs better but it is hard to find an example where the process is as slow as with the German example above.

I tried to play around with the folliowing settings but to no avail:
```
let g:compe.throttle_time = 200
let g:compe.source_timeout = 20
```

I am not sure whether I am misunderstanding some of these settings but I would hope to get a proper timeout to work which will prevent the hanging or to see an option which does *not* attempt to complete words greater than a certain length (i.e. a threshold similar to `compe.min_length` but being the `max_length`).

Even better would be a more immediate completion but I don't think that `nvim-compe` is to be blamed for this as it performs very well in all other scenarios which I came across so far :slightly_smiling_face: 

### Some system information:
OS: `uname -r: 5.11.12-arch1-1`
Neovim:
```
nvim --version:
NVIM v0.5.0-dev+1239-g2e156a3b7
Build type: Debug
LuaJIT 2.1.0-beta3
```
nvim-compe version: master @ f167a13

**Comment by hrsh7th** [comment]
Sorry for annoying. The spell source uses vim's built-in function. So if the function is slow, we can't fix it.

If you get same behavior on `call spellsuggest('Aktiengesellschaft')`, it is the cause.

**Comment by mrossinek** [comment]
Yes you are right, it is in fact the internal method which is the problem.
In fact, Bram seems to be aware of this issue: https://github.com/vim/vim/blob/master/runtime/doc/todo.txt#L269-L270

**Comment by languitar** [comment]
Just got hit by this as well. Is there any chance to make completion sources such as the spell source completely async to run in the background?
