### ISSUE TITLE
Showing overloads/parameters when inputting parameters

### ISSUE THREAD

**Issue by sam20908** [hrsh7th/nvim-compe#331]
When typing in parameters for e.g. function call, it'd be nice to allow showing parameters and overloads.

**Comment by hrsh7th** [comment]
If your means is `LSP's signature help`, it is out of scope of nvim-compe.

**Comment by mwcz** [comment]
@hrsh7th I think what @sam20908 was suggesting is that it would be nice if the signature help stayed visible while typing in the parameters.

With nvim lsp + compe:
![nvim-compe-sig-help](https://user-images.githubusercontent.com/364615/120005545-ef494e80-bfa5-11eb-99ca-99bad2c82971.gif)

With coc-nvim:
![nvim-coc-sig-help](https://user-images.githubusercontent.com/364615/120006666-194f4080-bfa7-11eb-8733-85dcdb16f201.gif)

@sam20908, is that what you were requesting?

**Comment by sam20908** [comment]
> @hrsh7th I think what @sam20908 was suggesting is that it would be nice if the signature help stayed visible while typing in the parameters.
> 
> With nvim lsp + compe:
> ![nvim-compe-sig-help](https://user-images.githubusercontent.com/364615/120005545-ef494e80-bfa5-11eb-99ca-99bad2c82971.gif)
> 
> With coc-nvim:
> ![nvim-coc-sig-help](https://user-images.githubusercontent.com/364615/120006666-194f4080-bfa7-11eb-8733-85dcdb16f201.gif)
> 
> @sam20908, is that what you were requesting?

Yes that was what I was suggesting.
