### ISSUE TITLE
nvim-compe loaded but doesn't work

### ISSUE THREAD

**Issue by krisfans** [hrsh7th/nvim-compe#332]
I select [vim-packager](https://github.com/kristijanhusak/vim-packager) as my plugin manager , which  utilizes `jobs` and `pack` features. but when i lazy load `nvim-compe` on `InsertEnter` , completion can't work .
See  kristijanhusak/vim-packager#33

**Comment by hrsh7th** [comment]
I think this problem similar to this (https://github.com/wbthomason/packer.nvim/issues/214).
I suggest you don't setup lazy load.

I think it can't fix by nvim-compe side.
