### ISSUE TITLE
Support `commitCharacters`

### ISSUE THREAD

**Issue by baldore** [hrsh7th/nvim-compe#333]
Hello everyone!

In VS Code, when you have autocompletion opened and you press `.`, it inserts the selected option. This also happens when you press `(`. Is there a way to make Neovim to work like this when `preselect` is `always`? so it inserts the first option. It works amazing when you select another option with <C-n>, but when it's the first option, I need to press <CR> or select the first option. 

Thanks in advance.

**Comment by hrsh7th** [comment]
It's called `commitCharacters` in LSP spec.

**Comment by hrsh7th** [comment]
That is a valid issue.
I think it needs to be implemented in v3.

However, v3 is so difficult and busy that I don't know when it can be implemented.

**Comment by baldore** [comment]
Just to add to it: I think it's a great feature, but not sure if the effort worth it. Vim autocomplete with auto-insert is pretty good and it's just when it happens with the first element. In VS Code this feature actually worth it because otherwise you have to press Enter plus the `commitCharacter`.

**Comment by gegoune** [comment]
It would be nice to have actually.
