### ISSUE TITLE
intelephense completion parameters missing

### ISSUE THREAD

**Issue by weeman1337** [hrsh7th/nvim-compe#334]
#### Describe the bug

Code completion with [intelephense](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#intelephense) does not complete parameter snippets.

#### To Reproduce

Requirements:

- intelephense installed `npm install -g intelephense`
- PHP

```
mkdir test
cd test
git init
touch composer.json
vim -u minimal.vim
```

Paste this minimal code into any `.php` file:

```
<?php

function test($param) {}
```

- Type `tes`
- Select `test` and trigger complete by enter

#### Actual behavior

Completes to `test()`

#### Expected behavior

Completes to `test($param)`

~(Works with deoplete. But I want to use compe because imho it functions nicer.)~

#### Screenshots (optional)

![Peek 2021-04-13 20-45](https://user-images.githubusercontent.com/6216686/114604745-92196800-9c99-11eb-8442-80de497ed6d3.gif)

#### Additional context

- Latest NeoVim 0.5

```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/nvim-compe'
Plug 'hrsh7th/vim-vsnip'
call plug#end()
PlugInstall | quit

lua << EOF
local lspconfig = require("lspconfig")
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

require('lspconfig').intelephense.setup{
    capabilities = capabilities
}

require('compe').setup({
    source = {
        nvim_lsp = true,
    }
})
EOF

inoremap <silent><expr> <CR>      compe#confirm('<CR>')
```

**Comment by hrsh7th** [comment]
I think It's LSP server's problem (or just not implemented).

The following response returns from intelephense.
The `test($0)` should be `test(${1:\$param})` for the your expect.

```
{'id': 97, 'jsonrpc': '2.0', 'result': {'label': 'test', 'data': 6343161458720787, 'textEdit': {'range': {'end': {'character': 1, 'line': 6}, 'start': {'character': 0, 'line': 6}}, 'newText': 'test($0)'}, 'detail': 'test($param)', 'sortText': '07492', 'kind': 3, 'filterText': 'test', 'documentation': {'kind': 'markdown', 'value': '__test__```php<?phpfunction test($param) { }```_@param_ `mixed $param`_@return_ `int`'}, 'command': {'title': 'Trigger Parameter Hints', 'command': 'editor.action.triggerParameterHints'}, 'insertTextFormat': 2}}
```

It's interesting why deoplete works.
Could you provide config of deoplete version?

**Comment by weeman1337** [comment]
> It's interesting why deoplete works.

Nevermind. Cannot reproduce it anymore. Tested it with phpactor. There the parameters are displayed correctly. I will open a feature request for intelephense. Anyway thanks for the explanation of the LSP response.
