### ISSUE TITLE
Complete emojis from junegunn/vim-emoji or abbreviations

### ISSUE THREAD

**Issue by pinpox** [hrsh7th/nvim-compe#335]
#### Is your feature request related to a problem? Please describe.
The very simple plugin from junegunn [vim-emoji](https://github.com/junegunn/vim-emoji) allows inserting emojis, which is nice for textfiles like markdown. I have installed it and pressing <ctrl+x><ctrl+u> correctly shows the completion menu. nvim-compe however doesn't show completions for that source.

#### Describe the solution you'd like
I'd like nvim-compe to show the completion for emojis when typing their shortcode. E.g. when typing `:app` it should show the completion for `:apple:` which, when accepted, inserts the :apple: emoji

#### Describe alternatives you've considered
I tried using abbreviations for each emoji like this:
```vim
iabbrev :apple: 🍎
```
The abberviation works (I can type the shortcode+<space> and the emoji character is inserted), but nvim-compe doesn't complete the abbreviations either. If that where the case, that would work as a solution for me aswell, in fact that might also have other possible use-cases as abbreviations can be anything.

**Comment by hrsh7th** [comment]
nvim-compe has a `emoji` source in built.
Your opinion is we should improve it, right?

**Comment by pinpox** [comment]
@hrsh7th It's not listed [in the list of builtin sources](https://github.com/hrsh7th/nvim-compe#built-in-sources) ?
I didn't know it already had that, how can I activate it then?

**Comment by hrsh7th** [comment]
Oh. Sorry! It listed only in the docs not README.md.
I will add it to README.md.

**Comment by pinpox** [comment]
Thanks (also for the great plugin in general)! I totally overlooked the text docs, my bad.
