### ISSUE TITLE
compe#confirm({ 'select': v:true }) causes flicker

### ISSUE THREAD

**Issue by Shatur95** [hrsh7th/nvim-compe#336]
The issue is a question. I'm trying to insert first item from the completion menu on `<Tab>` as in VSCode. Here is my mappings:

```lua
vim.api.nvim_set_keymap('i', '<Tab>', [[luaeval('require("utils.completion").tab_complete()')]], { expr = true })
vim.api.nvim_set_keymap('s', '<S-Tab>', [[luaeval('require("utils.completion").s_tab_complete()')]], { noremap = true, expr = true })
```

And here is my function:

```lua

function M.tab_complete()
  if vim.fn.pumvisible() == 1 then
    return vim.api.nvim_replace_termcodes('<C-n><CR>', true, true, true)
  elseif require('luasnip').expand_or_jumpable() then
    return vim.api.nvim_replace_termcodes('<Plug>luasnip-expand-or-jump', true, true, true)
  else
    return vim.api.nvim_replace_termcodes('<Tab>', true, true, true)
  end
end
```

It works as expected. But when the first condition is met, the interface flickers because it selects the first item, draws selection and then accepts it.
I tried to replace `return vim.api.nvim_replace_termcodes('<C-n><CR>', true, true, true)` with the following:

```lua
vim.api.nvim_select_popupmenu_item(0, false, false, {})
vim.fn['compe#confirm']()
return ''
```

But it looks like `vim.fn['compe#confirm']()` does not detect selection from `nvim_select_popupmenu_item`. How can I fix it?

**Comment by hrsh7th** [comment]
Probably, You want a `compe#confirm({ 'select': v:true })`

**Comment by Shatur95** [comment]
> Probably, You want a compe#confirm({ 'select': v:true })

This behaves the same as `vim.api.nvim_replace_termcodes('<C-n><CR>', true, true, true)`. E.g. selects first item and them confirms it. Is it possible to avoid dsiplay of the visual selection of the first item? This is what `nvim_select_popupmenu_item` does, but I cannot combine it with `compe#confirm`.

**Comment by hrsh7th** [comment]
I can't understand what you want.

I hope the following snippet will help you.
```
  let g:compe = {}
  let g:compe.preselect = 'disable'
  inoremap <silent><expr><Tab>      compe#confirm({ 'keys': "\<Tab>", 'mode': 'n', 'select': v:true })
```

**Comment by Shatur95** [comment]
Unfortunately, this is not exactly what I am trying to achieve :(
I will try to explain in more detail. My code from the first post and what you suggested works the same. When I press <Kbd>Tab</Kbd>, I get this:

1. The first element is selected visually.
2. Text is inserted.
3. The context menu is closed.

What I am trying to do is avoid the 1 point. Since all actions take place quickly, the visual selection of the first element when inserted looks very jerky. The function `nvim_select_popupmenu_item` allows to select first element without visual representation, but `compe#confirm` does not respect this selection.

**Comment by hrsh7th** [comment]
So you just want to avoid flicker. I've understand.

**Comment by Shatur95** [comment]
> So you just want to avoid flicker. I've understand.

Yes :)

**Comment by Shatur95** [comment]
2ab0204 do not have any effect for me. with `vim.fn['compe#confirm']({select = true})` it selects the first item and confirm it (e.g. blinks).

**Comment by hrsh7th** [comment]
I've completely fixed it.

**Comment by Shatur95** [comment]
After  888d9ec tab-selection stop working at all. Here is my function:

```lua
function M.tab_complete()
  if vim.fn.pumvisible() == 1 then
    vim.fn['compe#confirm']({select = true})
    return ''
  elseif require('luasnip').expand_or_jumpable() then
    return vim.api.nvim_replace_termcodes('<Plug>luasnip-expand-or-jump', true, true, true)
  else
    return vim.api.nvim_replace_termcodes('<Tab>', true, true, true)
  end
end
```

**Comment by hrsh7th** [comment]
Please read the docs.
https://github.com/hrsh7th/nvim-compe#how-to-use-tab-to-navigate-completion-menu

The tab_complete function returns `<C-n>` when pumvisible is `1`.

**Comment by Shatur95** [comment]
> The tab_complete function returns <C-n> when pumvisible is 1.

This is different. The documentation describes how to use Tab for navigation.
I am trying to do something different - select the first item from the list and accept it. This is how it works in VSCode - <Tab> just select and accept the best match.

And before 888d9ec it worked, but with flickering.

**Comment by hrsh7th** [comment]
```
    inoremap <silent><expr><Tab>      compe#confirm({ 'keys': "\<Tab>", 'select': v:true })
```
It's worked fine for me.

**Comment by Shatur95** [comment]
Ah, my mistake, the following works just as expected:

```lua
function M.tab_complete()
  if vim.fn.pumvisible() == 1 then
    return vim.fn['compe#confirm']({keys = '<Tab>', select = true})
  elseif require('luasnip').expand_or_jumpable() then
    return vim.api.nvim_replace_termcodes('<Plug>luasnip-expand-or-jump', true, true, true)
  else
    return vim.api.nvim_replace_termcodes('<Tab>', true, true, true)
  end
end
```

Thank you!

**Comment by F4IL3D** [comment]
I'm sorry if I interfere here, but I think the changes have broken the previous behavior.
As soon as I use <Tab> or >S-Tab>to navigate through the list, I cannot confirm the selected item with <CR> and the completion menu remains open.

**Comment by Shatur95** [comment]
@F4IL3D, you probably misconfigured something. For example, I did not return a value from `compe#confirm`.

**Comment by F4IL3D** [comment]
@Shatur95 Thanks for the reply. Indeed, it is very likely ^^
I check it again, but at first glance it looks the same as in the readme.

The config worked without any problems for weeks and the only thing I did today was `PackerSync`  ;-)

**Comment by khalid151** [comment]
888d9ec definitely broke the old behavior. Using `inoremap <silent><expr> <CR> compe#confirm('<CR>')` (as mentioned [here](https://github.com/hrsh7th/nvim-compe#mappings)) doesn't work anymore.
It only expands snippets **without** closing the completion menu.

**Comment by sindrip** [comment]
I'm having the same problem, I just updated and pressing <CR> to confirm a selection only expands snippets but doesn't close the menu. For non-snippets, the menu stays open.

**Comment by hrsh7th** [comment]
Sorry for annoying bit it doesn't reproduce. Please minimal vimrc.

**Comment by sindrip** [comment]
> Sorry for annoying bit it doesn't reproduce. Please minimal vimrc.

If it helps, apparently if I walk through the menu with the arrow keys it doesn't happen. I use \<C-n\>, \<C,p\> to choose an entry and if I do that, it fails.

**Comment by hrsh7th** [comment]
Thank you. I will check it.

**Comment by F4IL3D** [comment]
@sindrip and @khalid151 Thank you so much for the confirmation. I thought I was too stupid. ^^

In the meantime someone else opened an issue with the same problem #338

@hrsh7th With minimal vimrc i have the same behavior as described by sindrip.

**Comment by hrsh7th** [comment]
I've fixed menu closing behavior but the issue #338 seems to not same as it, I think...

**Comment by F4IL3D** [comment]
@hrsh7th I'll test it as soon as I have access to a computer again.

I'll give you feedback

**Comment by F4IL3D** [comment]
@hrsh7th 7d46b1ccb51232f6d8012c4216b6b24c62c889b8 fixed my issue. Many Thanks

**Comment by sindrip** [comment]
@hrsh7th [7d46b1c](https://github.com/hrsh7th/nvim-compe/commit/7d46b1ccb51232f6d8012c4216b6b24c62c889b8) is perfect, it also fixed a different bug that I had when completing inside snippets too fast!
