### ISSUE TITLE
No longer able able to confirm items or expand snippets from completion menu.

### ISSUE THREAD

**Issue by rafamadriz** [hrsh7th/nvim-compe#338]
#### Describe the bug
Don't know if it was an update or what but yesterday was all working all fine, but now `compe#confirm` doesn't seem to be doing anything. I can't confirm items from completion menu or expand snippets coming from vsnip. 

#### To Reproduce
Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

This is my config:
```lua
local t = function(str)
    return vim.api.nvim_replace_termcodes(str, true, true, true)
end

local check_back_space = function()
    local col = vim.fn.col(".") - 1
    if col == 0 or vim.fn.getline("."):sub(col, col):match("%s") then
        return true
    else
        return false
    end
end

-- Use (s-)tab to:
--- move to prev/next item in completion menuone
--- jump to prev/next snippet's placeholder
_G.tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-n>"
    elseif vim.fn.call("vsnip#available", {1}) == 1 then
        return t "<Plug>(vsnip-expand-or-jump)"
    elseif check_back_space() then
        return t "<Tab>"
    else
        return vim.fn["compe#complete"]()
    end
end
_G.s_tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return t "<C-p>"
    elseif vim.fn.call("vsnip#jumpable", {-1}) == 1 then
        return t "<Plug>(vsnip-jump-prev)"
    else
        return t "<S-Tab>"
    end
end

vim.api.nvim_set_keymap("i", "<CR>", "compe#confirm('<CR>')", {expr = true})
vim.api.nvim_set_keymap("i", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("s", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("i", "<S-Tab>", "v:lua.s_tab_complete()", {expr = true})
vim.api.nvim_set_keymap("s", "<S-Tab>", "v:lua.s_tab_complete()", {expr = true})
```
All of that is taken from the compe and vsnip docs. 

1. Use default config from compe and vsnip docs
2. Start typing 
3. try to confirm an item or expands snippet from completion menu

#### Actual behavior
Doesn't confirm item from completion menu.

#### Expected behavior
confirm item from completion menu

#### Additional context (optional)

As explained before, I had no problems whatsoever working with compe and using the config showed in the docs. Everything was working perfectly fine but today I realized I can't confirm an item from completion menu or expand snippets coming from vsnip. I have updated multiple times in the last days, not sure if this is a new bug or is just happening to me.

**Comment by hrsh7th** [comment]
Could you test with latest master? @rafamadriz

**Comment by rafamadriz** [comment]
> Could you test with latest master? 

I've already updated, didn't work... 

Also, I just tested in another machine I have and confirm items or expanding snippets was working just a minute ago, But after updating is no longer working 😢

**Comment by hrsh7th** [comment]
Hm... It's weird. Please minimal reproducible config `based on https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim`

**Comment by JoseConseco** [comment]
I think the problem is that if you have <tab>  set to : 
- <C-n> (next item in compe list)   and at same time as  <Jump to next vnip position> 
then  tab will fail in situation like so:

https://user-images.githubusercontent.com/13521338/115116639-e7f05780-9f9a-11eb-84e6-e7c212ab7dce.mp4

I can expand higlighted vsnip using <Ret> but then <tab> just suggests new auto-completion, rather than to jump to next vsnip placeholder.
The way around is to swap first if check with second like below: 

```
if vim.fn.call("vsnip#available", {1}) == 1 then
        return t "<Plug>(vsnip-expand-or-jump)"
elseif vim.fn.pumvisible() == 1 then
        return t "<C-n>"
```
Then <tab> will jump around expanded vsnip. 
But then new  problem arise - when you have you completion-popup - and you tab into vsnip  - when it becomes highlighted you wont be able to jump to next element in auto-completion popup, but rather you will always jump into expanded vsnip. So <tab> will only work up to first vsnipp selection. 

Imo there is no way to setup  <Tab> for both  : jump to next suggestion, and  jump-expanded-vsnip-placeholder

I just have <C-n/p>  - for selecting suggestions
<C-space> - accept selected item or expand vsnip
<tab> - jump around in expanded vsnip

**Comment by rafamadriz** [comment]
> Hm... It's weird. Please minimal reproducible config **based on https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim**

So I've solved the issue and it was because of [nvim-autopairs](https://github.com/windwp/nvim-autopairs), in the docs of this plugin they suggest using this with compe to get the correct indentation on curly braces, etc.

```lua
local remap = vim.api.nvim_set_keymap
local npairs = require('nvim-autopairs')

-- skip it, if you use another global object
_G.MUtils= {}

vim.g.completion_confirm_key = ""
MUtils.completion_confirm=function()
  if vim.fn.pumvisible() ~= 0  then
    if vim.fn.complete_info()["selected"] ~= -1 then
      vim.fn["compe#confirm"]()
      return npairs.esc("")
    else
      vim.api.nvim_select_popupmenu_item(0, false, false, {})
      vim.fn["compe#confirm"]()
      return npairs.esc("<c-n>")
    end
  else
    return npairs.check_break_line_char()
  end
end


remap('i' , '<CR>','v:lua.MUtils.completion_confirm()', {expr = true , noremap = true})
```  

But as I said before, everything was working perfectly fine. There must has been an update from either compe or vim-autopairs that broke the code above. 

To get the correct indentation I'm now using this `inoremap {<Enter> {<Enter>}<Esc>O` which I found on reddit. However it doesn't work as good as what I had before. This remap only works when the curly braces are at the start of the line.

Examples:

Without any remap to handle indentation:
```
{
|}
```
with the code above which use to work:
```
{
    |
} 
```

```
function() {
    |
}
``` 

With this inoremap `{<Enter> {<Enter>}<Esc>O` remap:
```
{
    |
}
```
``` 
function() {
|
}
``` 

If anyone knows how to get autopairs and compe to work together nicely I would appreciate it.

**Comment by JoseConseco** [comment]
I dont know about auto brackets. Anyway I managed to make Tab config for compe and vsnip that works
Here is config for future reference:

```
_G.tab_complete = function()
		if vim.fn.call("vsnip#jumpable", {1}) == 1 then
				return t "<Plug>(vsnip-jump-next)"
    elseif vim.fn.pumvisible() == 1 then
        return t "<C-n>"
    elseif check_back_space() then
        return t "<Tab>"
    else
        return vim.fn["compe#complete"]()
    end
end
_G.s_tab_complete = function()
		if vim.fn.call("vsnip#jumpable", {-1}) == 1 then
				return t "<Plug>(vsnip-jump-prev)"
    elseif vim.fn.pumvisible() == 1 then
        return t "<C-p>"
    else
        return t "<S-Tab>"
    end
end

vim.api.nvim_set_keymap("i", "<CR>", "compe#confirm('<CR>')", {expr = true})
vim.api.nvim_set_keymap("i", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("s", "<Tab>", "v:lua.tab_complete()", {expr = true})
vim.api.nvim_set_keymap("i", "<S-Tab>", "v:lua.s_tab_complete()", {expr = true})   
```

**Comment by Antonio-Bennett** [comment]
@rafamadriz The new fix is posted on autopairs github on the main page readMe but for people that don't want to go there here it is

```
local remap = vim.api.nvim_set_keymap
local npairs = require('nvim-autopairs')

-- skip it, if you use another global object
_G.MUtils= {}

vim.g.completion_confirm_key = ""
MUtils.completion_confirm=function()
  if vim.fn.pumvisible() ~= 0  then
    if vim.fn.complete_info()["selected"] ~= -1 then
      return vim.fn["compe#confirm"](npairs.esc("<c-r>"))
    else
      return npairs.esc("<cr>")
    end
  else
    return npairs.autopairs_cr()
  end
end


remap('i' , '<CR>','v:lua.MUtils.completion_confirm()', {expr = true , noremap = true})
```

**Comment by rafamadriz** [comment]
@Antonio-Bennett thanks!
