### ISSUE TITLE
How to use the compe#confirm with tmsvg/pear-tree

### ISSUE THREAD

**Issue by blackCauldron7** [hrsh7th/nvim-compe#339]
I tried this:
`compe#confirm({ 'keys': "\<Plug>PearTreeExpand", 'mode': '' })`

- [https://github.com/tmsvg/pear-tree](https://github.com/tmsvg/pear-treel)

**Comment by nanotee** [comment]
You have to put parentheses around `PearTreeExpand`. This works for me:

`imap <expr> <CR> compe#confirm("\<Plug>(PearTreeExpand)")`
