### ISSUE TITLE
Improve matching algorithm

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#34]
We need tests for lua...

**Comment by tami5** [comment]
Its a bit hard and you will need custom shell and lua scripts, if you want I can walk through running your first test busted framework

**Comment by hrsh7th** [comment]
I'm implementing it...


#### benchmark
v1: elapsed time: 2.401
v2: elapsed time: 0.342


```
local M1 = require'compe.completion.matcher'
local M2 = require'compe.completion.matcher2'

local attempts = 100000

x = os.clock()
for j = 1, attempts do
    tmp = M1.score('nvimgetbufline', 'nvimgetbufline', 'nvim_g_et_b_uf_line')
end
elapsed = os.clock() - x
print(string.format("V1: elapsed time: %.3f", elapsed))

x = os.clock()
for j = 1, attempts do
    tmp = M2.score('nvimgetbufline', 'nvim_g_et_b_uf_line')
end
elapsed = os.clock() - x
print(string.format("V2: elapsed time: %.3f", elapsed))
```

**Comment by tami5** [comment]
Oh wow :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes: :heart_eyes:  Nice well done @hrsh7th

**Comment by hrsh7th** [comment]
I will add the feature of remaining char match.

Currently, nvim-compe does not match `fnamemodify` with `fmodify`.
This feature makes matching it.

**Comment by hrsh7th** [comment]
> I will add the feature of remaining char match.

> Currently, nvim-compe does not match fnamemodify with modify.
> This feature makes matching it.

Sorry. It bit hard to implement. So I will merge performance improvements before implementing them.
