### ISSUE TITLE
Menu closing immediately, only stays open the second time

### ISSUE THREAD

**Issue by elkowar** [hrsh7th/nvim-compe#341]
#### Describe the bug
Whenever I manually trigger autocompletion, the window opens for a split second, and then vanishes again. Triggering it a second time afterwards makes it stay open.

#### To Reproduce
This seems to only happen if i'm triggering completion without having already typed something - i.e. on an empty line, or directly after a `.`, without starting to type whatever method/field I want. If I trigger completion at `.f` or something, it will work properly.

#### Actual behavior
Popupmenu closes immediately at first
#### Expected behavior
Popup menu stays open in all cases

**Comment by hrsh7th** [comment]
Reproduced.

Your explanation is very helpful. I will investigate it.

**Comment by elkowar** [comment]
Any updates on this?

**Comment by EdwarKenedy** [comment]
hi, apparently this behaviour only appears when autocomplete option is set to false, i found that this is caused by ```is_manual_completing``` variable in the completion.lua file, assigning false to this variable solves the problem.
I hope this is helpful.

**Comment by hrsh7th** [comment]
I think it was fixed.
