### ISSUE TITLE
lsp + gopls does not work with experimentalPostfixCompletions (vim-go does). 

### ISSUE THREAD

**Issue by WhoIsSethDaniel** [hrsh7th/nvim-compe#342]
```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-dowRBs/neovim-0.5.0+ubuntu2+git202104172335-63b64ebab-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-dowRBs/neovim-0.5.0+ubuntu2+git202104172335-63b64ebab-d569569c9/build/config -I/build/neovim-dowRBs/neovim-0.5.0+ubuntu2+git202104172335-63b64ebab-d569569c9/src -I/build/neovim-dowRBs/neovim-0.5.0+ubuntu2+git202104172335-63b64ebab-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-dowRBs/neovim-0.5.0+ubuntu2+git202104172335-63b64ebab-d569569c9/build/src/nvim/auto -I/build/neovim-dowRBs/neovim-0.5.0+ubuntu2+git202104172335-63b64ebab-d569569c9/build/include
Compiled by buildd@lcy01-amd64-021

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

```
$ gopls version
golang.org/x/tools/gopls v0.6.10
    golang.org/x/tools/gopls@v0.6.10 h1:8Ebz8PymS2umcuCFhoz67unyJfWsipjTIrkBUF9kypg=
```

```
nvim-compe
$ git rev-parse HEAD
7d46b1ccb51232f6d8012c4216b6b24c62c889b8
```

The latest gopls added a feature named [experimentalPostfixCompletions](https://github.com/golang/tools/blob/master/gopls/doc/settings.md#completion). With vim-go/deoplete it works fine. With nvim + lsp + nvim-compe it does not work at all.  It should look like this: https://user-images.githubusercontent.com/5856771/114612163-c5df9800-9c6f-11eb-959c-8fe529018a21.gif

With vim-go the completion LSP interaction looks like the following (logs are from gopls):
```
[Trace - 11:52:58.956 AM] Sending request 'textDocument/completion - (4)'.
Params: {"textDocument": {"uri": "file:///home/seth/src/nvim-lsp-problem/main.go"}, "position": {"character": 3, "line": 4}}


[Trace - 11:52:58.958 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///home/seth/src/nvim-lsp-problem/main.go","version":4,"diagnostics":[{"range":{"start":{"line":4,"character":4},"end":{"line":4,"character":4}},"severity":1,"source":"syntax","message":"expected selector or type assertion, found '}'"}]}


[Trace - 11:52:58.959 AM] Received response 'textDocument/completion - (4)' in 3ms.
Result: {"isIncomplete":true,"items":[{"label":"append!","kind":15,"detail":"append and re-assign slice","preselect":true,"sortText":"00000","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":3},"end":{"line":4,"character":3}},"newText":"x = append(x, $0)"},"additionalTextEdits":[{"range":{"start":{"line":4,"character":1},"end":{"line":4,"character":3}},"newText":""}]},{"label":"copy!","kind":15,"detail":"duplicate slice","sortText":"00001","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":3},"end":{"line":4,"character":3}},"newText":"xCopy := make([]int, len(x))\ncopy(xCopy, x)\n"},"additionalTextEdits":[{"range":{"start":{"line":4,"character":1},"end":{"line":4,"character":3}},"newText":""}]},{"label":"last!","kind":15,"detail":"s[len(s)-1]","sortText":"00002","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":3},"end":{"line":4,"character":3}},"newText":"x[len(x)-1]"},"additionalTextEdits":[{"range":{"start":{"line":4,"character":1},"end":{"line":4,"character":3}},"newText":""}]},{"label":"print!","kind":15,"detail":"print to stdout","sortText":"00003","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":3},"end":{"line":4,"character":3}},"newText":"fmt.Printf(\"x: %v\\n\", x)"},"additionalTextEdits":[{"range":{"start":{"line":4,"character":1},"end":{"line":4,"character":3}},"newText":""},{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"range!","kind":15,"detail":"range over slice","sortText":"00004","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":3},"end":{"line":4,"character":3}},"newText":"for i, v := range x {\n\t$0\n}"},"additionalTextEdits":[{"range":{"start":{"line":4,"character":1},"end":{"line":4,"character":3}},"newText":""}]},{"label":"reverse!","kind":15,"detail":"reverse slice","sortText":"00005","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":3},"end":{"line":4,"character":3}},"newText":"for i, j := 0, len(x)-1; i \u003c j; i, j = i+1, j-1 {\n\tx[i], x[j] = x[j], x[i]\n}\n"},"additionalTextEdits":[{"range":{"start":{"line":4,"character":1},"end":{"line":4,"character":3}},"newText":""}]},{"label":"sort!","kind":15,"detail":"sort.Slice()","sortText":"00006","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":3},"end":{"line":4,"character":3}},"newText":"sort.Slice(x, func(i, j int) bool {\n\t$0\n})"},"additionalTextEdits":[{"range":{"start":{"line":4,"character":1},"end":{"line":4,"character":3}},"newText":""},{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"sort\"\n"}]},{"label":"var!","kind":15,"detail":"assign to variable","sortText":"00007","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":3},"end":{"line":4,"character":3}},"newText":"i := x"},"additionalTextEdits":[{"range":{"start":{"line":4,"character":1},"end":{"line":4,"character":3}},"newText":""}]}]}
```

With  nvim-compe the completion interaction looks like (logs are from gopls):
```
[Trace - 11:51:55.649 AM] Sending request 'textDocument/completion - (2)'.
Params: {"context": {"triggerCharacter": ".", "triggerKind": 2}, "textDocument": {"uri": "file:///home/seth/src/nvim-lsp-problem/main.go"}, "position": {"character": 3, "line": 4}}


[Trace - 11:51:55.651 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///home/seth/src/nvim-lsp-problem/main.go","version":4,"diagnostics":[{"range":{"start":{"line":4,"character":4},"end":{"line":4,"character":4}},"severity":1,"source":"syntax","message":"expected selector or type assertion, found '}'"}]}


[Trace - 11:51:55.652 AM] Received response 'textDocument/completion - (2)' in 2ms.
Result: {"isIncomplete":true,"items":[]}
```

A minimal program that exhibits the problem:
```go
package main

func main() {
	var x []int
	x
}
```

If the cursor is just after the 'x' on line 5 simply type '.' (a period) and the completion should appear.

I will attach complete LSP (from gopls) logs.  One for vim-go and one for nvim + lsp + nvim-compe.
[vim-go.log](https://github.com/hrsh7th/nvim-compe/files/6331818/vim-go.log)
[nvim-lsp.log](https://github.com/hrsh7th/nvim-compe/files/6331819/nvim-lsp.log)

**Comment by WhoIsSethDaniel** [comment]
Configuration for nvim-compe:
```
lua <<EOF
require'compe'.setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;

  source = {
    path = true;
    buffer = true;
    calc = true;
    emoji = true;
    vsnip = false;
    nvim_lsp = true;
    nvim_lua = true;
    spell = true;
    tags = false;
    snippets_nvim = false;
    treesitter = true;
  };
}
EOF

```

**Comment by hrsh7th** [comment]
Why do you think it is a nvim-compe's problem?
The gopls does not returns postfix completion items so it is a server configuration issue.

**Comment by WhoIsSethDaniel** [comment]
> Why do you think it is a nvim-compe's problem?
> The gopls does not returns postfix completion items so it is a server configuration issue.

Because it works with other clients as I showed in the ticket. The server is configured the same way for each client. The only client that fails to work is nvim-compe.

**Comment by hrsh7th** [comment]
@WhoIsSethDaniel So Do you checked an nvim-lsp omnifunc?

nvim-compe uses `nvim-lsp` internally.
If nvim-lsp's omnifunc could work but nvim-compe doesnt, I will investigate it.

**Comment by WhoIsSethDaniel** [comment]
> @WhoIsSethDaniel So Do you checked an nvim-lsp omnifunc?
> 
> nvim-compe uses `nvim-lsp` internally.
> If nvim-lsp's omnifunc could work but nvim-compe doesnt, I will investigate it.

okay, I will test that.  

FWIW, the only reason I brought this here is because neovim's github explicitly says that if the problem has to do with autocompletion the problem should be taken upstream.  Considering this problem does not exist with other LSP clients / completion engines I assume this is an issue with either Neovim native LSP or with nvim-compe.  If either of those assumptions are wrong please let me know. But I can tell you the server configuration is the same between all the tests I've done with other clients and neovim+lsp+compe.

**Comment by hrsh7th** [comment]
@WhoIsSethDaniel 

It works on my side.

```
    init_options = {
      gofumpt = true,
      usePlaceholders = true,
      semanticTokens = true,
      staticcheck = true,
      experimentalPostfixCompletions = true,
      ui = {
        completion = {
          experimentalPostfixCompletions = true,
        }
      },
      hoverKind = 'Structured',
      analyses = {
        nilness = true,
        shadow = true,
        unusedparams = true,
        unusedwrite = true,
        fieldalignment = true
      },
      codelenses = {
        gc_details = true,
        tidy = true
      }
    }
```

**Comment by WhoIsSethDaniel** [comment]
> @WhoIsSethDaniel
> 
> It works on my side.
> 
> ```
>   require'lspconfig'.gopls.setup {
>     capabilities = capabilities,
>     on_init = on_init;
>     init_options = {
>       gofumpt = true,
>       usePlaceholders = true,
>       semanticTokens = true,
>       staticcheck = true,
>       experimentalPostfixCompletions = true,
>       ui = {
>         completion = {
>           experimentalPostfixCompletions = true,
>         }
>       },
>       hoverKind = 'Structured',
>       analyses = {
>         nilness = true,
>         shadow = true,
>         unusedparams = true,
>         unusedwrite = true,
>         fieldalignment = true
>       },
>       codelenses = {
>         gc_details = true,
>         tidy = true
>       }
>     }
>   }
> ```

It doesn't work for me with nvim-compe or with omnifunc.  The gopls response is always an empty list, unlike with other clients where gopls returns the new postfix completion responses.  And I noticed your slight change to my configuration, but sadly that didn't change anything when I added it to mine.

I will take your word for it that it works for you.  What neovim are you using?  I just retrieved a new update of neovim at 66f9dd3c6.

Considering omnifunc doesn't work I know it's not an nvim-compe problem. So my apologies for bothering you.  That was not my intent.

**Comment by hrsh7th** [comment]
OK. I will update neovim.

**Comment by hrsh7th** [comment]
Hm... sorry. My suggested configuration was wrong.

```
  require'lspconfig'.gopls.setup {
    capabilities = capabilities,
    on_init = on_init;
    init_options = {
      gofumpt = true,
      usePlaceholders = true,
      semanticTokens = true,
      staticcheck = true,
      experimentalPostfixCompletions = true,
      hoverKind = 'Structured',
      analyses = {
        nilness = true,
        shadow = true,
        unusedparams = true,
        unusedwrite = true,
        fieldalignment = true
      },
      codelenses = {
        gc_details = true,
        tidy = true
      }
    }
  }
```

it worked fine with latest neovim.

**Comment by hrsh7th** [comment]
```
  x := []int{ 1,2,3 }
  x.|
```

**Comment by WhoIsSethDaniel** [comment]
> Hm... sorry. My suggested configuration was wrong.
> 
> ```
>   require'lspconfig'.gopls.setup {
>     capabilities = capabilities,
>     on_init = on_init;
>     init_options = {
>       gofumpt = true,
>       usePlaceholders = true,
>       semanticTokens = true,
>       staticcheck = true,
>       experimentalPostfixCompletions = true,
>       hoverKind = 'Structured',
>       analyses = {
>         nilness = true,
>         shadow = true,
>         unusedparams = true,
>         unusedwrite = true,
>         fieldalignment = true
>       },
>       codelenses = {
>         gc_details = true,
>         tidy = true
>       }
>     }
>   }
> ```
> 
> it worked fine with latest neovim.

I have to believe it's a configuration issue. I have a very plain configuration, but will attempt to figure out what is wrong. Thanks for your help.
