### ISSUE TITLE
Completion autoimport only gives one option when there's more

### ISSUE THREAD

**Issue by Pablo1107** [hrsh7th/nvim-compe#343]
#### Describe the bug
When completing a TS object that is exported in several files, it only gives one option.

#### To Reproduce
Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. Write a TS file that exports some object, and another one that exports all objects from the former file.
2. Complete that object on another file and see one auto-import option.

#### Actual behavior
It show one auto-import option.

#### Expected behavior
It should give two auto-import option, one from the file that holds the object and another one from the exports file.

#### Screenshots (optional)
![image](https://user-images.githubusercontent.com/17091659/115252069-84346e80-a101-11eb-93a0-f6864380bfc9.png)

![image](https://user-images.githubusercontent.com/17091659/115252966-526fd780-a102-11eb-9982-e0fd3810754e.png)
Not showing this file for import.

**Comment by hrsh7th** [comment]
It isn't compe's problem...... You must send issue to upstream repo (typescript-language-server).

**Comment by Pablo1107** [comment]
`coc-tsserver` uses the same LSP but manages to get multiple import options, that's why I thought maybe there could be something to do here...

**Comment by hrsh7th** [comment]
coc-tsserver isnzt same server.
https://github.com/neoclide/coc-tsserver/tree/master/src/server/features

There is bunch of specific implementations.

**Comment by Pablo1107** [comment]
Thanks for clarifying that.
