### ISSUE TITLE
Blacklisting a language server

### ISSUE THREAD

**Issue by tom-anders** [hrsh7th/nvim-compe#348]
#### Is your feature request related to a problem? Please describe.

I use ccls and clangd simultaneously when writing C++ (I need features from both of them). Unfortunately, this means that completion items are usually duplicated.

#### Describe the solution you'd like

Some kind of optional like g:blacklistedServers to turn of completion for specific servers.

#### Describe alternatives you've considered

Probably this could also be done on the server side? I'm using nvim-lspconfig, but I'm not sure how to do it. Can I somehow turn off completion for a specific language server alltogether?

**Comment by pockata** [comment]
Hey @tom-anders, I believe you can achieve this via `lspconfig`. Set `capabilities` where you initialize the LSP servers via the `setup` function and you should be good to go. 

```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion = false

require('lspconfig').ccls.setup({
    on_attach: ...,
    capabilities: capabilities
})
```
