### ISSUE TITLE
Ccls snippets not working

### ISSUE THREAD

**Issue by toniz4** [hrsh7th/nvim-compe#351]
#### Describe the bug
Some time ago snippets just stopped appearing using the ccls language server, maybe after an update. Using the same client capabilities with clangd woks as expected. I'm not sure if this is a bug with compe, if it's a bug with lsp-config please tell me.

#### To Reproduce
relevant part of the configuration
```lua
local lspconfig = require('lspconfig')

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
capabilities.textDocument.completion.completionItem.resolveSupport = {
  properties = {
    'documentation',
    'detail',
    'additionalTextEdits',
  }
}

lspconfig.ccls.setup {
	capabilities = capabilities,
	init_options = {
		cache = {
			directory = "/tmp/ccls"
		},
		index = {
			threads = 4;
		},
	}
}
```

#### Actual behavior
using ccls:
![img](https://user-images.githubusercontent.com/14265358/116216760-595ca280-a71f-11eb-92c2-f25957bc45d0.png)

#### Expected behavior
using clangd:
![img](https://user-images.githubusercontent.com/14265358/116216907-814c0600-a71f-11eb-985c-ef857ce7a384.png)

using this client configuration:
```lua
lspconfig.clangd.setup {
	capabilities = capabilities
}
```
But clangd is buggy with their imports, and ccls used to provide better snippets.

**Comment by hrsh7th** [comment]
@toniz4 If this problem caused by updating nvim-compe, Please `git bisect` it.

**Comment by toniz4** [comment]
Tried going back some releases, but i didn't find a working commit. Tried the same thing with lsp-config with no success. There is any way I can debug this?

**Comment by hrsh7th** [comment]
Please provide your config. Do you set up mapping for confirmation?

**Comment by toniz4** [comment]
Here is my nvim configuration: https://github.com/toniz4/neovim-config

> Do you set up mapping for confirmation?

Yes, all the important configuration is at `lua/modules/lsp.lua`, but snippets works fine with clangd, lua-lsp-server and gopls.
