### ISSUE TITLE
Documentation window is not displayed under neovim gui

### ISSUE THREAD

**Issue by zdm** [hrsh7th/nvim-compe#355]
#### To Reproduce
Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. run neovim-qt
2. trigger snuppets

#### Actual behavior
1. When selecting some snippet - no docs window is displayed. But it works when I run nvim under terminal.
2. In pop-up window snippet type labels are not aligned, pls, look at screenshot.

#### Screenshots (optional)

![image](https://user-images.githubusercontent.com/1025608/116659190-e0b54a80-a999-11eb-919d-21a712978747.png)

#### Additional context (optional)
neovim 0.5.0.1282
windows 10 x64

**Comment by elianiva** [comment]
you should disable the GUI popup

**Comment by zdm** [comment]
Thanks!
