### ISSUE TITLE
How to auto confirm the first one if not selected?

### ISSUE THREAD

**Issue by singlexyz** [hrsh7th/nvim-compe#357]
I map `compe#confirm` to enter.
`inoremap <silent><expr> <cr> compe#confirm('<cr>')`

Then I hope that when I press enter, if the option is not selected,
it will automatically select the first one for me and confirm.
In other words, don't need to select the first one manually.

e.g.
Typeing:
<img width="369" alt="截屏2021-05-02 上午3 32 18" src="https://user-images.githubusercontent.com/4456413/116793057-05730480-aaf7-11eb-927b-443b75ad1f1e.png">

Hit enter, output:
<img width="74" alt="截屏2021-05-02 上午3 34 55" src="https://user-images.githubusercontent.com/4456413/116793133-68649b80-aaf7-11eb-9d4c-672fc21481bf.png">

**Comment by cloggier** [comment]
Try `preselect`. It's described in readme.

**Comment by singlexyz** [comment]
> Try `preselect`. It's described in readme.

I set it, but not working.

**Comment by singlexyz** [comment]
``` vim
function! compe#_select_confirm() abort
  if !exists('*complete_info')
    throw 'compe#_select_confirm requires complete_info function to work'
  endif
  let selected = complete_info()['selected']
  if selected != -1
     return compe#confirm()
  elseif pumvisible()
     return compe#confirm() " How to send a <down> key before compe#confirm() 
  endif
  return ''
endfunction

inoremap <silent><expr> <cr> pumvisible() ? compe#_select_confirm() : '<cr>'
```

I found a solution from coc.nvim, but I don't know how to return a <down> key before `compe#confirm()`
😂
