### ISSUE TITLE
How to set priority for "Snippets" from "nvim_lsp" source?

### ISSUE THREAD

**Issue by xeho91** [hrsh7th/nvim-compe#359]
Hi!

Thank you for your amazing plugin. This one is a real game-changer with speed and performance!

I am trying to configure the "priority" for **Snippets** only from `nvim_lsp` source, so they will always be at the very top of my available completion list.
I want it to take precedence over other available completions from `nvim_lsp` such as _Keyword_, _Text_, etc.?

How can I achieve it?

EXTRA: I am also using [compe-tabnine](https://github.com/tzachar/compe-tabnine), and I want the aforementioned **Snippets** only to take higher priority than TabNine suggestions. Is it possible?

**Comment by shaunsingh** [comment]
Just wanted to say I would love to have a priority for snippets as well. I love the performance of the plugin, but its slightly annoying having my tabbing suggestions above my snippets

**Comment by windwp** [comment]
it will be nice if have a key to show only snippet and hide lsp

**Comment by qazip** [comment]
I also want this! Damn, it is the one thing missing from my config..

**Comment by doums** [comment]
Hi, same question here. I don't even know if it's possible to override a source priority without having to provide a full declaration of the source dictionary.
In the help `:h compe-source` there are some notes about source configuration but nothing on how to actually use that stuff.

**Comment by timsofteng** [comment]
same here

**Comment by loshjawrence** [comment]
is priority sorted ascending or descending? does it matter if it starts from 0 or 1? is having a dictionary assigned mean its true in addition to the things in the dictionary or do you still have to have `enabled=true` or something in the dictionary?
