### ISSUE TITLE
preselect misbehaving

### ISSUE THREAD

**Issue by elianiva** [hrsh7th/nvim-compe#36]
(don't know if the issue title is correct)

Maybe related to [this comment](https://github.com/hrsh7th/nvim-compe/issues/30#issuecomment-733453989)

https://streamable.com/ttvto9
As you can see, it preselect the item even though I set `compe_auto_preselect` to `false` and sometimes I can't delete the word.

Here's my minimal vimrc to reproduce.
```vim
call plug#begin("~/.loca/share/nvim/plugged")
  Plug 'hrsh7th/nvim-compe'
call plug#end()

let g:compe_enabled = v:true
let g:compe_auto_preselect = v:false

inoremap <expr><CR>  compe#confirm('<CR>')
inoremap <expr><C-e> compe#close('<C-e>')
inoremap <silent><C-Space> <C-r>=compe#complete()<CR>

lua require'compe':register_lua_source('buffer', require'compe_buffer')
call compe#source#vim_bridge#register('path', compe_path#source#create())
```

But the weird thing is, it only applies to some filetypes (yaml has this, but lua doesn't have this issue (well, sometimes it has but it's so rare))
My neovim version is `NVIM v0.5.0-880-gdd00c7473`.
Ask me if you need more details. Thanks!

**Comment by hrsh7th** [comment]
No. preselect is using `nvim_select_popupmenu_item` API.
It would not insert any text (it just select only).

I think your environment broken a bit.
Could you investigate it?

I will investigate it too...

**Comment by elianiva** [comment]
Hmm. Alright then, I will try to investigate since I think I'm the only one that has this issue. Will report back once I found the culprit.

**Comment by hrsh7th** [comment]
I'm trying to use your dotfiles

**Comment by hrsh7th** [comment]
Reproduced.

**Comment by hrsh7th** [comment]
@elianiva I'm really sorry. This problem maybe fixed now.

**Comment by elianiva** [comment]
It hasn't fixed unfortunately. But I think this issue is coming from buffer source, not the nvim-compe itself. The other sources that I tried doesn't have this issue, only the buffer one.

**Comment by hrsh7th** [comment]
@elianiva I was put `set completeopt=menu,menuone,noinsert` in your init.vim's final line then nvim-compe worked fine.

Hm... I don't know why this line doesn't effected for it... https://github.com/hrsh7th/nvim-compe/commit/1b52fa0211e08bc04dbe4d4d55580091ef02542d#diff-56524c7070bca4a73516373d9b215abd6f8f9abd9a8bf8c0d7a3a679a26ebcb7R228

**Comment by elianiva** [comment]
Maybe we need to change that line into vim call instead of using `vim.o.completeopt` according to [this](https://github.com/nanotee/nvim-lua-guide#caveats-3)

**Comment by hrsh7th** [comment]
I've fixed it. Thank you.
