### ISSUE TITLE
How to config the first item is always selected? How to config auto-complete behaves like VSCode?

### ISSUE THREAD

**Issue by phanlong2811** [hrsh7th/nvim-compe#360]
**I would like to config auto-complete behaves like VSCode since I used VSCode for a long time.**
- When I'm editing, auto-completion pop up without inserting
- The first item is always selected.
- When I hit the tab, if the auto-complete candidate is a snippet then the snippet is automatically expanded
 (we can hit tab to navigate to the next placeholder) else insert that auto-complete candidate.

How to config the first item is always selected? How i can config that with vsnips?

P/s : I am using lua with packer.nvim to manager plugin

**Comment by TornaxO7** [comment]
> When I'm editing, auto-completion pop up without inserting

<details>

Put that into your `~/.config/nvim/init.vim`:
```
set completeopt=menu,preview,noinsert
```
For more information take a look into `:h 'completeopt`.

</details>

> The first item is always selected.

<details>

According to the help page of nvim-compe:
```
preselect ~
    Preselect behaviour.
      Type: |String|
      Accepted values:
        "enable"      Preselect completion item only if the source told
                      nvim-compe to do so. Eg. completion from gopls.
        "disable"     Never preselect completion item regardless of source
        "always"      Always preselect completion item regardless of source
      Default: "enable"
```
So you need to add this:
```lua
require(local completer = require("compe")

completer.setup {
    -- ....
    preselect = 'always';
    -- ...
}
```

</details>

> When I hit the tab, if the auto-complete candidate is a snippet then the snippet is automatically expanded
(we can hit tab to navigate to the next placeholder) else insert that auto-complete candidate.

<details>

I think you mean somehting like `:h compe-quickstart`, so in this case put that into your `~/.config/nvim/init.vim`:
```vim
inoremap <silent><expr> <Tab> compe#confirm('<Tab>')
```
But be careful, it might happen that you already have a mapping on `<Tab>`. If it doesn't work try `:imap <Tab>` in vim and look if tab is already mapped on another key.

</details>

**Comment by phanlong2811** [comment]
> > When I'm editing, auto-completion pop up without inserting
> 
> > The first item is always selected.
> 
> > When I hit the tab, if the auto-complete candidate is a snippet then the snippet is automatically expanded
> > (we can hit tab to navigate to the next placeholder) else insert that auto-complete candidate.

it works for me, tks you so much <33333
