### ISSUE TITLE
Mapping Return to compe#confirm('<CR>') inserts the text into the buffer instead of calling the function

### ISSUE THREAD

**Issue by MonstrousOgre** [hrsh7th/nvim-compe#361]
#### Describe the bug

I tried using the mappings from the readme. All of them are working except `compe#confirm`. When I hit return after doing this, it just inserts ```
compe#confirm('
')
``` into the buffer. This doesn't happen when I map it to `<C-y>` or something else. I'm able to reproduce this even with the minimal vimrc.

#### To Reproduce
Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. Copy everything from the [mappings section](https://github.com/hrsh7th/nvim-compe#mappings) of the Readme to the end of the minimal vimrc.
2. Hit return/enter when the completion menu is open

#### Actual behavior

It exits the completion menu, and the following text gets inserted into the buffer:
```
compe#confirm('
')
```

#### Expected behavior

It should expand the snippet and/or auto import

**Comment by cloggier** [comment]
Seems like misconfiguration on your part. Can you replicate it with minimal config?

**Comment by MonstrousOgre** [comment]
@cloggier like I mentioned, I'm able to reproduce this even with the minimal config

**Comment by MonstrousOgre** [comment]
If it helps, I was able to reproduce it with this config. It's just the minimal config followed by the default config in the readme

```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-compe'
call plug#end()
PlugInstall | quit

" Options or settings here.

set completeopt=menuone,noselect

let g:compe = {}
let g:compe.enabled = v:true
let g:compe.autocomplete = v:true
let g:compe.debug = v:false
let g:compe.min_length = 1
let g:compe.preselect = 'enable'
let g:compe.throttle_time = 80
let g:compe.source_timeout = 200
let g:compe.incomplete_delay = 400
let g:compe.max_abbr_width = 100
let g:compe.max_kind_width = 100
let g:compe.max_menu_width = 100
let g:compe.documentation = v:true

let g:compe.source = {}
let g:compe.source.path = v:true
let g:compe.source.buffer = v:true
let g:compe.source.calc = v:true
let g:compe.source.nvim_lsp = v:true
let g:compe.source.nvim_lua = v:true
let g:compe.source.vsnip = v:true

inoremap <silent><expr> <C-Space> compe#complete()
inoremap <silent><expr> <CR>      compe#confirm('<C-y>')
inoremap <silent><expr> <C-e>     compe#close('<C-e>')
inoremap <silent><expr> <C-f>     compe#scroll({ 'delta': +4 })
inoremap <silent><expr> <C-d>     compe#scroll({ 'delta': -4 })
```

**Comment by CallumHoward** [comment]
I am also seeing this (haven't tried with minimal config yet).

`"inoremap <silent><expr> <CR>      compe#confirm('<CR>')"` from the Readme gives me infinite recursion of
```
'compe#confirm('compe#confirm('compe#confirm('compe#confirm
```

`:imap <CR>` shows 
```
i  <CR>          compe#confirm('<CR>')<Plug>CloserClose
```

and `"inoremap <silent><expr> <C-y>      compe#confirm('<C-y>')"` works as expected.

The CloserClose comes from https://github.com/rstacruz/vim-closer, perhaps this one is incompatible. I'll try to isolate further

**Comment by CallumHoward** [comment]
Yep, this is definitely my config I think. I can get it to work with:
```lua
vim.api.nvim_set_keymap("i", "<C-y>", "compe#confirm('<C-y>')", {expr = true})
vim.api.nvim_set_keymap("i", "<CR>", "<C-y>", {})
```

**Comment by entropitor** [comment]
I had this issue as well and I was able to solve it by putting the mappings in an "after" file. Maybe it has something to do with the package manager? I'm using vim-plug as well

**Comment by Quintasan** [comment]
I believe this is related. With minimal config, create the following snippet:

```ruby
module Enums
  module Vulnerability
    REPORT_TYPES = {                                
      sast: 0,                                      
      secret_detection: 4
    }.with_indifferent_access.freeze
  end
end
```

go to line with `secret_detection: 4`, put a comma `,` after it and then press Enter. I get only spaces even if I keep pressing Enter

**Comment by Quintasan** [comment]
> Yep, this is definitely my config I think. I can get it to work with:
> 
> ```lua
> vim.api.nvim_set_keymap("i", "<C-y>", "compe#confirm('<C-y>')", {expr = true})
> vim.api.nvim_set_keymap("i", "<CR>", "<C-y>", {})
> ```

I tried this:

```
vim.api.nvim_set_keymap('i', '<C-Space>', [[compe#complete())]], {silent = true, expr = true})
vim.api.nvim_set_keymap('i', '<CR>', [[compe#confirm('<CR>')]], {silent = true, expr = true})
vim.api.nvim_set_keymap('i', '<C-e>', [[compe#close('<C-e>')]], {silent = true, expr = true})
vim.api.nvim_set_keymap('i', '<C-f>', [[compe#scroll({ 'delta': +4 })]], {silent = true, expr = true})
vim.api.nvim_set_keymap('i', '<C-d>', [[compe#scroll({ 'delta': -4 })]], {silent = true, expr = true})
```

but I still get this weird behavior

**Comment by dlants** [comment]
I had the same issue. @Quintasan's workaround worked for me.

**Comment by dlants** [comment]
I had this same issue, and discovered that this was a conflict with `vim-endwise`. I diagnosed using the following:

```
:imap <CR>
i  <CR>        & compe#confirm('<CR>')<SNR>41_DiscretionaryEnd
```

Removing endwise fixed the issue. Thanks for the debug tip @CallumHoward
