### ISSUE TITLE
Confirm without <CR>?

### ISSUE THREAD

**Issue by acomagu** [hrsh7th/nvim-compe#365]
Hi, I use the auto-importing feature and it works well, but I need to hit `<CR>`. Because, I guess, the `compe#confirm()` should be called to trigger auto-import. Any way/configuration to do without `<CR>` mapping? For example, when I type `.` on selecting a completion item, `compe#confirm()` doesn't called(and popup-menu closes).

I tried mapping `.` to trigger `compe#confirm()` but didn't work well...(auto-importing works, but `.` is not printed in the buffer).

```vim
inoremap <expr> . F()

function F()
  if pumvisible()
    return compe#confirm('.')
  endif
  return '.'
endfunction
```

And I tried calling `compe#confirm()` in `InsertCharPre` autocmd, but it didn't work well also...(auto-importing didn't work).

Any idea? Thanks!!!

---

NVIM v0.5.0-dev+1295-g3fc71ea22

**Comment by nawordar** [comment]
I think that the autocommand would be `CompleteDone` or `CompleteDonePre`. I tried calling `compe#confirm` on `CompleteDonePre`, but it seems that it's called too late

**Comment by weilbith** [comment]
Would be pretty cool if this could be implemented. My workflow is also to select an entry and then just continue to type. Just that then the `additionalTextEdits` do not get applied.

**Comment by nawordar** [comment]
Bump. Don't close it, I would really like to have that feature

**Comment by acomagu** [comment]
I noticed [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) does this without special configuration.

<details>
<summary>fyi my cmp setup:</summary>

```
local cmp = require('cmp')
cmp.setup {
  preselect = cmp.PreselectMode.None,
  mapping = {
    ['<Tab>'] = cmp.mapping.select_next_item(),
    ['<S-Tab>'] = cmp.mapping.select_prev_item(),
    ['<C-x><C-o>'] = cmp.mapping.complete(),
    ['<CR>'] = cmp.mapping.confirm({ select = false }),
  },
  sources = {
    { name = 'calc' },
    { name = 'nvim_lsp' },
    { name = 'path' },
  },
}
```

</details>
