### ISSUE TITLE
Unknown function: vsnip#available with recommended settings

### ISSUE THREAD

**Issue by paljenczy** [hrsh7th/nvim-compe#366]
I do not have vim-vsnip installed. With the settings recommended in the README, I get the following error when typing `<TAB>` in insert mode:

```
Unknown function: vsnip#available
```

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):
1. Make sure vim-vsnip plugin is not installed
2. Hit `<TAB>` in Insert mode

**Comment by tamago324** [comment]
I think the settings listed in the README are examples of settings when `vsnip` is present.
So, if you don't have `vsnip` installed, wouldn't it work if you remove that if condition?

If you can, could you show us your minimum configuration vimrc?
I may be able to give you some advice.

**Comment by paljenczy** [comment]
I actually installed vsnip and it works now. I guess yes, you are fine with removing that section - it would be great if you could add a pointer in the README about that.
