### ISSUE TITLE
Improve to setup some configurarion

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#37]

**Comment by hrsh7th** [comment]
#### What should be configurable in nvim-compe?
- global config
    - g:compe_throttle_time
    - g:compe_auto_preselect
- source config
    - All `get_metadata` parameters should be overridable

#### Where should place the setup?
- Lua, Vim script both.

#### How to setup?

##### In Vim script
```viml
let g:compe = {}
function g:compe.setup(config) abort
  let a:config.source.nvim_lsp = {
  \   'enabled': v:true,
  \ }
  let g:config.source.nvim_lua = {
  \   'enabled': v:true,
  \   'filetypes': ['lua', 'lua.pad']
  \ }
  let g:config.source.buffer = v:true
  let g:config.source.path = v:true
endfunction
```

##### In Lua
```lua
require'compe'.setup(function(config)
  config.source.nvim_lsp = {
    enabled = true;
  }
  config.source.nvim_lua = {
    enabled = true;
    filetype = { 'lua', 'lua.pad' };
  }
  config.source.buffer = true
  config.source.path = true
end)
```

**Comment by tami5** [comment]
Hmm I like about that it lets you declaratively configure sources. 

How about global variables?

**Comment by hrsh7th** [comment]
I provide `compe#source#register(name, dict)` and `require'compe':register_lua_source(name, dict)` as low level API.
I think we should leave it (but I want to organize it...)
But the sources have `name` so we can also provide the easy API to configure per sources.

**Comment by tami5** [comment]
Good idea

**Comment by hrsh7th** [comment]
I'm worried to handle the differences between `buffer` source and `nvim-lsp` source.

I will consider it and if I decided the design, I will implement it.

**Comment by tami5** [comment]
Yep that can be an issue, my solution was to do add abstraction layer over sources

```lua
builtin.nvim_lsp_source = function()
  vim.fn.execute('augroup compe_nvim_lsp') 
  -- it may be better to have the autocmd require this file
  vim.fn.execute('autocmd InsertEnter * lua require"compe.builtin.nvim_lsp".register()')
  vim.fn.execute('augroup END')
end

builtin.buffer_source = function()
 return compe:register_lua_source("buffer", require'compe.builtin.buffer')
end

```

**Comment by hrsh7th** [comment]
I think we should notify to source authors before this change.

- https://github.com/tami5/compe-conjure
- https://github.com/tami5/vim-iced-compe
- https://github.com/kristijanhusak/vim-dadbod-completion

**Comment by tami5** [comment]
What changes? will changes effect external source? if so in what way?. Also, In telescope has an interesting way of adding extension, maybe have a quick look?

**Comment by hrsh7th** [comment]
My thinking the changes are...

1. Remove `compe#source#register(source_id, source)` and `require"compe":register_lua_source(source_id, source)`
I think the `source_id` should be handling by nvim-compe side maybe.

2. Introduce `compe#register_source(source)` and `require"compe":register_source(source)`
It returns `source_id` that can be used for `unregister_source`.

3. The `source` must have `name?/group?` property.
It needed by `nvim_lsp` source and `lamp` source.

The nvim_lsp source will register multiple sources but user want to configure all sources at once by `config.source.nvim_lsp = { ... }` so we should add the `source_name` for it.

**Comment by tami5** [comment]
Nice, anything that will make interface less confusing is best.

Also, here is an inspiration from telescope :

- Source creators: place source definition in `lua/compe/_source/source_name.lua`
- In `compe/_source/init.lua` we have something similar to [here](https://github.com/nvim-telescope/telescope.nvim/commit/2ac0582c06d8a52a42907dde106983e44ae989ef)
- Users can do 

```lua
require'compe'.register_source('conjure')
-- Or in setup method 
require'compe'.setup(function(config)
  config.source.nvim_lsp = {
    enabled = true;
  }
  config.source.nvim_lua = {
    enabled = true;
    filetype = { 'lua', 'lua.pad' };
  }
  config.source.buffer = true
  config.source.path = true
  config.source.conjure = true or {
     enable = true,
     filetypes = {'fennel', 'clojure'}
     priority = 100
  }
end)

```

Also in regards to setup method I think it might much cleaner to have it as a method that only accepts dict where users can have something like

```lua 
require'compe'.setup({
  min_length = 1,
  sources = {
    buffer = true,
    path = true
    conjure = true or {
       enable = true,
       filetypes = {'fennel', 'clojure'}
       priority = 100
    } 
  }
})

```

**Comment by kristijanhusak** [comment]
Here's a PR with an implementation for overriding metadata https://github.com/hrsh7th/nvim-compe/pull/43. It's backward compatible, and allows overriding metadata when registering source.

**Comment by hrsh7th** [comment]
Currently, my random thoughts are

1. The source must be registered always by the source authors.
- The plugin author should register the source manually.

2. The source settings must be configured by the user.
- The override configuration can be setup on this time.

3. If the user installs the custom source but the user does not enable it. it will be ignored.
- It means the user must configure all sources by themselves.

**Comment by kristijanhusak** [comment]
It's either 1 or 3, can't be both. For 1, plugin author can provide a way to override the options (via variable or similar), and for 3, just allow user to do what is implemented in the PR.

**Comment by hrsh7th** [comment]
If the user does not define configuration, all registered source will be ignored.

```viml
Plug 'hrsh7th/compe-english-words'

let g:compe = {}
let g:compe.source = {}
let g:compe.source.buffer = v:true
let g:compe.source.path = {
\   'filetypes': ['vim']
\ }

" the `english_words` source does not configured, so it will be ignored.
```

**Comment by tami5** [comment]
Why let g:var ... this should be abstracted inside setup method. Users can still use them becuase setup method just sets the g:var to what ever value passed via the setup method.

> " the `english_words` source does not configured, so it will be ignored.

Wait so if the source doesn't configure filetypes, prorities .. etc it will be ignored. what about sources that communicate directly to compe registry, should this even be allowed?

**Comment by hrsh7th** [comment]
I will write pseudo code sometimes on this discussion.

My desired interface was described on https://github.com/hrsh7th/nvim-compe/issues/37#issuecomment-734921220
(But I'm wondering which is better to use `function` or `dict`)


Currently, I thinking compe will be that the source must always be configured by the user and otherwise, it should not affect behavior.

1. the source must be registered by the source author to compe (Usually, `plugin/*.vim` is a better place to do it)
2. the source must be configured by the user (Usually, `init.vim` or `init.lua` is a better place to do it)
3. the source must not affect if it is not configured.

**Comment by hrsh7th** [comment]
If the user uses `let g:compe.nvim_lsp = v:true`, the nvim_lsp should work with it's default metadata.

Hm... I'm wondering.

**Comment by kristijanhusak** [comment]
I'm ok with any way of setup, as long as I can do configuration per source.

**Comment by hrsh7th** [comment]
It should be fixed on latest master.
