### ISSUE TITLE
After wiping out buffer , all words related data still remain in _G table.

### ISSUE THREAD

**Issue by prss-us** [hrsh7th/nvim-compe#370]
#### Describe the bug
Firts let me say this plugin is great and really fast. Thank you for your work!

So  i am learning lua and was playing around dumping the _G table when i noticed that the plugin seems to fail to remove buffer information after buffer being wiped out. 

#### To Reproduce
This is what i did and is shown in  screenshot:
- open empty lua file
- vsplit a txt file where i'm typed this
- dump _G lua table with vim.inspect (into buffer 4) (command and function in init.lua in bottom section)
- no words array at this time , makes sense...
- insert 'help' word into lua file
- dump table again
- now there are 3 words array , one per buffer

a) buffer 1 for lua file is ok

b) buffer 2 is for this window and has a  words array is 1100 bytes which is ok.

c) buffer 4 has been wipedout by the previous dump of table _G (this latest dump goes into buffer 8).
Buf 4 is not anywhere listed or unlisted but it still shows up here 
with an array of words over 48k long.

- now at this point insert 'function' word into lua file
- dump _G table again 
- buffers 4 and 8 remain even though they have been wiped out.  buffer 8 words array is over 88k.

After a while this gets really bad.

#### Expected behavior
IMHO these buffers information should be removed. Additionally , the dump buffer is a scratch buffer , should the plugin index it?
What happens with buffers that are not code but data like huge csv files, sql data dumps, etc.?
How to prevent plugin from indexing those files or is this by design?

#### Screenshots (optional)
![image](https://user-images.githubusercontent.com/57577581/117858756-9323c200-b264-11eb-9c0a-ce1b1cf1f403.png)

#### Additional context (optional)
Latest neovim nightly build
minimal config with packer and nvim-compe installed.
init.lua follows:
--------------------------------------------------
--- Neovim startup configuration file
--------------------------------------------------
vim.api.nvim_command([[set statusline=Bufnr\ %{bufnr()}\ %f\ %h%m%r%=%-14.(%l,%c%V%)\ %P]])

-- plugins to load
require 'plugins.install'
require 'plugins.packer'
require 'plugins.nvim-compe'

local fn  = vim.fn
local cmd = vim.cmd
local api = vim.api

function outw(strcmd)
  local lines = fn.split(fn.execute(strcmd, 'silent'), "[\n\r]")
  if fn.bufexists('OutputWindow') >= 1 then
    cmd "bwipeout! OutputWindow"
  end
  cmd "vnew OutputWindow"
  api.nvim_buf_set_option(0,'buftype'   , 'nofile' )
  api.nvim_buf_set_option(0,'bufhidden' , 'hide'   )
  api.nvim_buf_set_option(0,'swapfile'  , false    )
  api.nvim_buf_set_option(0,'buflisted' , true     )
  api.nvim_win_set_option(0,'wrap'      , false    )
  fn.append(fn.line('$'), lines)
end

-- dump command output to scratch buffer --> P lua print(vim.inspect(_G))
vim.api.nvim_command([[command! -nargs=1 P lua outw(<q-args>)]])

**Comment by hrsh7th** [comment]
Thank you for your reporting.

It should be improved.

**Comment by prss-us** [comment]
Thanks to you.  Glad to help.

**Comment by hrsh7th** [comment]
I think it was fixed.
