### ISSUE TITLE
Add option for controlling the height of documentation window.

### ISSUE THREAD

**Issue by winston0410** [hrsh7th/nvim-compe#372]
#### Is your feature request related to a problem? Please describe.

Yes. My feature request is related to the documentation floating window. It is too small and I have no control over it.

#### Describe the solution you'd like

To be able to set the height of the floating window (with option I guess)?

#### Describe alternatives you've considered

To use scroll function. But I don't want to waste any keystroke on it.

#### Additional context

My question posted on Reddit with screenshot: https://www.reddit.com/r/neovim/comments/nb5t5v/how_to_increase_documentation_size_of_nvimcompe/

**Comment by hrsh7th** [comment]
I think we should improve documentation window size calculation.

Currently, the implementation is very simple.

https://github.com/hrsh7th/nvim-compe/blob/master/autoload/compe/documentation.vim#L42

**Comment by hrsh7th** [comment]
Feel free to post your solution.

**Comment by David-Else** [comment]
+ and width :)
