### ISSUE TITLE
slow on startup

### ISSUE THREAD

**Issue by siduck76** [hrsh7th/nvim-compe#374]
nvim-compe takes so much time on startup time. ( I know it depends on hardware too but it takes more time than coc or completion.nvim  )

nvim-compe on my old pc , with hdd 
![image](https://user-images.githubusercontent.com/59060246/118135779-0a05ba00-b421-11eb-87bf-55a3a25c1cff.png)

main pc on ssd 
![image](https://user-images.githubusercontent.com/59060246/118136073-581abd80-b421-11eb-842a-f8209798476f.png)

my config : https://github.com/siduck76/neovim-dotfiles/blob/main/lua/compe-completion.lua

**Comment by ii14** [comment]
Slow startup is related to #369

For now what you can do is manually disabling sources you're not using.
For example, if you're using buffer, calc, nvim_lsp, path and ultisnips:
```vim
" let g:loaded_compe_buffer = 1
" let g:loaded_compe_calc = 1
let g:loaded_compe_emoji = 1
let g:loaded_compe_luasnip = 1
" let g:loaded_compe_nvim_lsp = 1
let g:loaded_compe_nvim_lua = 1
let g:loaded_compe_omni = 1
" let g:loaded_compe_path = 1
let g:loaded_compe_snippets_nvim = 1
let g:loaded_compe_spell = 1
let g:loaded_compe_tags = 1
let g:loaded_compe_treesitter = 1
" let g:loaded_compe_ultisnips = 1
let g:loaded_compe_vim_lsc = 1
let g:loaded_compe_vim_lsp = 1
let g:loaded_compe_vsnip = 1
```

**Comment by siduck76** [comment]
@ii14 I use nvim-lsp tho so compi_omni shouldnt be disabled too right?

**Comment by ii14** [comment]
You don't need omni for neovim's LSP. I think it's just for plugins that support omnicompletion only

**Comment by siduck76** [comment]
thanks a lot buddy , this really helps . I just use neovim lsp and vsnip+friendly-snippets . This made my neovim even more faster :D 

![image](https://user-images.githubusercontent.com/59060246/118344976-26077980-b54f-11eb-9e4e-3db2720b9a59.png)

**Comment by hrsh7th** [comment]
https://github.com/hrsh7th/nvim-compe/pull/376

**Comment by siduck76** [comment]
> Slow startup is related to #369
> 
> For now what you can do is manually disabling sources you're not using.
> For example, if you're using buffer, calc, nvim_lsp, path and ultisnips:
> 
> ```viml
> " let g:loaded_compe_buffer = 1
> " let g:loaded_compe_calc = 1
> let g:loaded_compe_emoji = 1
> let g:loaded_compe_luasnip = 1
> " let g:loaded_compe_nvim_lsp = 1
> let g:loaded_compe_nvim_lua = 1
> let g:loaded_compe_omni = 1
> " let g:loaded_compe_path = 1
> let g:loaded_compe_snippets_nvim = 1
> let g:loaded_compe_spell = 1
> let g:loaded_compe_tags = 1
> let g:loaded_compe_treesitter = 1
> " let g:loaded_compe_ultisnips = 1
> let g:loaded_compe_vim_lsc = 1
> let g:loaded_compe_vim_lsp = 1
> let g:loaded_compe_vsnip = 1
> ```



> Slow startup is related to #369
> 
> For now what you can do is manually disabling sources you're not using.
> For example, if you're using buffer, calc, nvim_lsp, path and ultisnips:
> 
> ```viml
> " let g:loaded_compe_buffer = 1
> " let g:loaded_compe_calc = 1
> let g:loaded_compe_emoji = 1
> let g:loaded_compe_luasnip = 1
> " let g:loaded_compe_nvim_lsp = 1
> let g:loaded_compe_nvim_lua = 1
> let g:loaded_compe_omni = 1
> " let g:loaded_compe_path = 1
> let g:loaded_compe_snippets_nvim = 1
> let g:loaded_compe_spell = 1
> let g:loaded_compe_tags = 1
> let g:loaded_compe_treesitter = 1
> " let g:loaded_compe_ultisnips = 1
> let g:loaded_compe_vim_lsc = 1
> let g:loaded_compe_vim_lsp = 1
> let g:loaded_compe_vsnip = 1
> ```

@ii14 how do I not source those in compe now? 

do I make changes in the source section? :

![image](https://user-images.githubusercontent.com/59060246/119772948-93b38e00-bedd-11eb-80ec-e627af216f18.png)

**Comment by ii14** [comment]
You can remove `let g:loaded_compe_* = 1` entirely now, no need to change anything else. Each source will be loaded only when it's actually needed.

By the way, all sources are disabled by default, so you can remove `* = false` lines if you want.
