### ISSUE TITLE
Matching completion items in the middle or suffix

### ISSUE THREAD

**Issue by mickael-menu** [hrsh7th/nvim-compe#375]
#### Is your feature request related to a problem? Please describe.

I'm a maintainer of an LSP server for a [Markdown-based notebook](https://github.com/mickael-menu/zk) and trying to figure out the best possible config for Neovim's built-in LSP client.

I'm using auto-completion to create links to other notes. Unfortunately, with nvim-compe I have to type the first letter (prefix) of the completion item otherwise it won't match. Here's a screencast showing the problem.

You can see that I can't match "A future-proof..." with `fp`, I need to type `afp`.

https://user-images.githubusercontent.com/58686775/118142862-1121cd80-b40b-11eb-94be-41a25bcc43b2.mov

#### Describe the solution you'd like

It would be helpful to match in the middle or end of completion items too, possibly with a lower score than prefix matching. This is the behavior I have using coc.nvim, for example.

This feature could be exposed as an additional option to not change the current behavior.

Apart from that I really enjoyed using nvim-compe which has the most efficient completion I tried, thanks for the effort you put in!

**Comment by mickael-menu** [comment]
@hrsh7th Would you welcome a pull request for this?

**Comment by hrsh7th** [comment]
@mickael-menu Thank you for your reporting.

It's weird. I think the current compe has this feature.


https://user-images.githubusercontent.com/629908/119767631-2100dd80-bef2-11eb-8852-b23660c8c8ec.mp4


Yes. PR are welcome!!! very helpful.

**Comment by mickael-menu** [comment]
Okay I'll try to debug to see what's going on in my case.

**Comment by mickael-menu** [comment]
@hrsh7th I found the issue (two actually) but I'm not 100% sure about the best way to fix this for nvim-compe.

### Issue 1: Label is broken at first "invalid character"

The "word" used for matching is extracted with [`String.get_word()`](https://github.com/hrsh7th/nvim-compe/blob/c7cd3bf1380ce3c6ef2a55537ace40c3a3897c50/lua/compe/utils/string.lua#L54) which stops at the first invalid character, [including spaces](https://github.com/hrsh7th/nvim-compe/blob/c7cd3bf1380ce3c6ef2a55537ace40c3a3897c50/lua/compe/utils/string.lua#L6).

The problem is that my completion items are full sentences which can contain spaces and special characters, such as "Automating frequent tasks".

Because of the filter in `String.get_word()`, `Matcher.match()` will for example receive this item, which ignores anything after "Automating":

```
{
    abbr = "Automating frequent tasks",
    filter_text = "Automating frequent tasks docs/automation.md",
    ...
    original_word = "Automating",
    sort_text = "Automating frequent tasks",
    word = "Automating"
  }
```

### Issue 2: LSP filter text is ignored

If the filtering user input doesn't start with the first character of the `filter_text`, the filter text is ignored:

https://github.com/hrsh7th/nvim-compe/blob/c7cd3bf1380ce3c6ef2a55537ace40c3a3897c50/lua/compe/matcher.lua#L18-L20

This is a problem for me because as you can see in the example above, I'm adding more information in the LSP `filterText` expecting that the user can filter with it. Here, I append the path of the file to auto complete in the filter text:

`Automating frequent tasks docs/automation.md`

### How to fix these issues?

I'm probably missing something as I don't understand the purpose of `get_word()` and checking the first character of `filter_text`, at least in an LSP context. I guess it's for some edge case with other sources?

I suggest (at least for the LSP source) to always use the full content of `filter_text` for the word/matching, without sanitizing. This would fix these two problems and match the LSP specifications as well as the other completion plugins implementing LSP I tested.

> ```typescript
> /**
>  * A string that should be used when filtering a set of
>  * completion items. When `falsy` the label is used as the
>  * filter text for this item.
>  */
> filterText?: string;
> ```
> https://microsoft.github.io/language-server-protocol/specification#textDocument_completion

**Comment by hrsh7th** [comment]
Thanl you! I've understood.

The issue1 is expected behaivior.
We should fix issue2.

**Comment by mickael-menu** [comment]
> We should fix issue2.

Okay I'll send a PR for this 👍 I think this should also solve my problem without fixing issue 1 because the filter text will take precedence.

**Comment by danymat** [comment]
Hello everyone (@mickael-menu), I'm in the process of creating a very basic lsp for Zettelkasten notes supporting barebones Zettelkasten (https://github.com/lsp-zettelkasten/lsp-zettelkasten) . I stumbled upon this post, when I had the same issue. For internal testing (and for my personal usage), I'm using your pull request #390, and it works well.

Thank you for helping the community with this use-case

**Comment by mickael-menu** [comment]
@danymat We have exactly the same use case 😄 You can check out my own Zettelkasten LSP server here: https://github.com/mickael-menu/zk/issues/22 I would be interested to discuss with you if you have different ideas or ways of tackling specific features.
