### ISSUE TITLE
[dartls] text input blocks on typing inside parens

### ISSUE THREAD

**Issue by akinsho** [hrsh7th/nvim-compe#380]
#### Describe the bug
Hi there 👋🏾 , thanks for your work on this plugin. It's pretty crucial to my daily workflow 👍🏾 .

I've been using it with [`dartls`](https://github.com/dart-lang/sdk/blob/master/pkg/analysis_server/tool/lsp_spec/README.md) and find that my input blocks frequently  especially whilst trying to type inside parentheses preventing further typing. I've tried disabling other sources and it seems to be coming from the `nvim_lsp` source and happens primarily when using dartls.

https://user-images.githubusercontent.com/22454918/118640954-7988fa00-b7d1-11eb-94b6-eeff515617f3.mp4

#### To Reproduce
Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. Install `dartls` can be done via homebrew I believe `brew install dart`
2. Setup dart lsp via lspconfig, using the lsp config snippet above
3. Create a dart file e.g. 
```dart
void doSomething(String p1, String p2) {
  print('$p1 and $p2');
}

void main() {
  // start typing doSomething(, by the time you start writing inside parens things start to lag
  doSomething( // <-- bug here, you might need to try a few times +/- open and close parens a few times
}
```

#### Actual behavior
Input lags significantly blocking further input.

#### Expected behavior
Completion should not block whilst typing

EDIT: I'm using `nvim-autopairs` in the example but this happens regardless of if that plugin is enabled or not

**Comment by nghialm269** [comment]
I think the `completeFunctionCalls` issue is of upstream.
* If the function has only one parameter, I can't jump out of the function (maybe there's no placeholder outside)
* If the function has > 1 parameters, it works fine for me.

maybe related: https://github.com/dart-lang/sdk/issues/43571

**Comment by nghialm269** [comment]
> @nghialm269 can you share the config you use to get it working.

My lsp config (use `flutter-tools.nvim`):
```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = vim.tbl_extend('keep', capabilities or {}, lsp_status.capabilities)
capabilities.textDocument.completion.completionItem.snippetSupport = true

------
  lsp = {
    on_attach = on_attach,
    capabilities = capabilities,
    flags = {
      debounce_text_changes = 150
    },
    settings = {
      dart = {
        enableSdkFormatter = true,
        lineLength = 80,
        completeFunctionCalls = true,
        showTodos = true,
      }
    },
  },
```

My compe setup:
```lua
    {
      'hrsh7th/nvim-compe',
      require = {
        {'neovim/nvim-lspconfig'},
        {'hrsh7th/vim-vsnip'},
      },
      config = function ()
        vim.o.completeopt = "menuone,noselect"
        require'compe'.setup {
          enabled = true,
          autocomplete = true,
          debug = false,
          min_length = 1,
          preselect = 'enable',
          throttle_time = 80,
          source_timeout = 200,
          incomplete_delay = 400,
          max_abbr_width = 100,
          max_kind_width = 100,
          max_menu_width = 100,
          documentation = true,
          source = {
            path = true,
            buffer = true,
            calc = true,
            vsnip = {priority = 100},
            nvim_lsp = {priority = 101},
            nvim_lua = true,
            spell = true,
            tags = true,
            treesitter = false,
            snippets_nvim = false,
          },
        }
      end,
    },

```

**Comment by akinsho** [comment]
Thanks @nghialm269 that part (which I've now removed from the issue definitely seems to be my config) on a minimal init.vim it seems to work without issue, so something in my config must be removing it

**Comment by akinsho** [comment]
@nghialm269 not sure if you are still experiencing this but I think it might be resolved 🤞🏿 will close it out and revisit it if it comes up again
