### ISSUE TITLE
Vsnip expanding placeholder stopped working

### ISSUE THREAD

**Issue by JoseConseco** [hrsh7th/nvim-compe#383]
#### Describe the bug
It seems we can no select option from Vsnip  placeholder:
![image](https://user-images.githubusercontent.com/13521338/118857895-d58a7600-b8d8-11eb-9adf-13b2cf737882.png)

#### To Reproduce
Use following snippet (pytho):
```
  "ReportOperator": {
    "prefix": "report",
    "description": "Draw report for operator",
    "body": [
      "self.report({'${1|INFO,WARNING,DEBUG,ERROR|}'}, f'{$0}')\r",
      ""
    ]
  }, 
```
After expanding above snippet try select different report type (warning, debug etc)

#### Actual behavior
we cant select any option from the list  (warning, debug etc)
I tested on other snippets and they do not work too. It worked ok some time ago (week or two)

**Comment by hrsh7th** [comment]
Thank you for your reporting.
It's nvim-compe's bug. I will fix it.

**Comment by JoseConseco** [comment]
@hrsh7th  Now when I try to select suggestions from expanded vsnip I get this error: 
![image](https://user-images.githubusercontent.com/13521338/121210374-eb59de00-c87b-11eb-890e-65e86509f363.png)

**Comment by liuxian1990** [comment]
I have the same problem
