### ISSUE TITLE
Is assigning color to each individual `kind` possible?

### ISSUE THREAD

**Issue by 3nuc** [hrsh7th/nvim-compe#385]
#### Is your feature request related to a problem? Please describe.
It'd be cool to have visual (color) separation between LSP completions (important) and buffer completions (less important, good fallback if LSP is not present or stopped working). For example, completions from LSP would be bright red and buffer completions would be dark gray.

#### Describe the solution you'd like
I'm not sure. In theory, "kind" is a concept that is already built into even the old Vim (but exists in neovim also) and even there it says that kind can be colored. I'm not the first person to ponder about this: [here](https://stackoverflow.com/questions/10063210/vim-completion-menu-item-colors) and [here](https://vi.stackexchange.com/questions/28561/how-to-use-colored-icons-for-autocomplete-menu-nvim-coc)

If you look at `:h complete-items`, you'll find this:
<pre>
The "kind" item uses a single letter to indicate the kind of completion.  <b>This
may be used to show the completion differently (different color or icon).</b>
Currently these types can be used:
	v	variable
	f	function or method
	m	member of a struct or class
	t	typedef
	d	#define or macro

When searching for matches takes some time call |complete_add()| to add each
match to the total list.  These matches should then not appear in the returned
list!  Call |complete_check()| now and then to allow the user to press a key
while still searching for matches.  Stop searching when it returns non-zero.
</pre>

I was  hoping this means each kind automatically creates a highlight group but I haven't been able to confirm or deny that.
If it does though, there would be no action needed on compe's part. The user would just have to make sure to define the correct hlgroups
#### Describe alternatives you've considered
I was wondering if it'd be possible to pass a "hlgroup" dictionary entry to the "source" object. I assume not, since compe probably just communicates with nvim's API.

#### Additional context
None

**Comment by Shougo** [comment]
It is not possible.
It is Vim/neovim limitation.

**Comment by hrsh7th** [comment]
Yes. It's very difficult.

I think we should use floating-window instead of completion pum if support it.

I have no plan to support it. Sorry.
