### ISSUE TITLE
nvim-compe doesn't complete properly if the candidate contains apostrophe

### ISSUE THREAD

**Issue by pulcinello** [hrsh7th/nvim-compe#386]
#### Describe the bug
When the candidate from lsp contains apostrophe, nvim-compe only completed all the characters before that apostrophe.
![Screenshot from 2021-05-24 20-43-23](https://user-images.githubusercontent.com/3975367/119349942-567ab080-bcd1-11eb-952a-5957526702bc.png)
I wonder if I missed some settings to make the completion work properly.

#### To Reproduce

<details>
<summary>Here's the minimal nvim config.</summary>
<p>

```viml
call plug#begin('~/.config/nvim/plugged')

  Plug 'hrsh7th/nvim-compe'
  Plug 'neovim/nvim-lspconfig'

call plug#end()

set completeopt=menuone,noselect

lua << EOF
require'compe'.setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;

  source = {
    path = true;
    buffer = true;
    calc = true;
    nvim_lsp = true;
    nvim_lua = true;
    vsnip = true;
    ultisnips = true;
  };
}

require'lspconfig'.hls.setup{}
EOF

```

</p>
</details>

**Comment by roginfarrer** [comment]
I think I have discovered a similar issue. In my case, `$` is being stripped from the autocompletion field.

In the result below, the menu shows the correct option, e.g., `$blue400`, but the autocompletion strips out the special character, printing `blue400` instead.

![](https://i.imgur.com/sha9jjp.gif)
