### ISSUE TITLE
Turn off completion when in ultisnips snippet trigger

### ISSUE THREAD

**Issue by rickalex21** [hrsh7th/nvim-compe#387]
#### Is your feature request related to a problem? Please describe.

When I'm inside a tab expansion jumping from tab to tab, the completion messes things up. I would like
to turn completion off. Since I'm in insert mode, I'm not sure if there is a way for compe to know
when I'm in the middle of a snippet? Then turn it back on when I reach the end $0. 

#### Describe the solution you'd like

Compe to figure out if I'm in the middle of a snippet ? 

```lua
ultisnips = {trigger = false}
```
You could name the option anything else other than trigger, but the idea is to turn it off when a user
is in the middle of a snippet. 

DOCS: When trigger is set to false, ulitsnips will be off when completing a snippet. This allows
the user to jump forward or backward without any completions.

#### Describe alternatives you've considered

I presume I could call a function from Ultisnips snippets to turn compe off, but that would mean I would
have to do it for all the snippets I have.

I could turn off the ```preselect = 'always'``` but then I have to turn it back on once I'm done with the
tab triggers (I reached $0). 

#### Additional context

Thanks for the plugin.

**Comment by cloggier** [comment]
You can use `C-e` to close completion window.

**Comment by rickalex21** [comment]
@cloggier It doesn't work, it comes back on thanks. I'm currently replicating the problem on a new user
account with minimal settings.

**Comment by rickalex21** [comment]
@cloggier Even trying to turn it off my ultisnips stops. So if I have this:

```snippets
snippet log "log stuff"
echo $1 $1 $2 $2 $3 $3
endsnippet
```

When I do ```<c-e>``` on $2 it will stop and I won't get to $3.

This is my settings: 

```vim

let g:UltiSnipsExpandTrigger="<F1>"
let g:UltiSnipsUsePythonVersion = 3
let g:UltiSnipsSnippetDirectories=[$HOME.'/snippets']
let g:UltiSnipsEditSplit="vertical"
let g:UltiSnipsExpandTrigger="<tab>"
"Don't have a way right now to turn off completion in a snippet: if in ultisnips completion off.
let g:UltiSnipsJumpForwardTrigger = '<tab>'



lua <<EOF
	require'compe'.setup {
		enabled          = true,
		autocomplete     = true,
		debug            = false,
		min_length       = 3,
		preselect        = 'always', -- always select the first
		throttle_time    = 80, -- default is 80,
		source_timeout   = 400, -- default is 400,
		incomplete_delay = 400,
		max_abbr_width   = 100,
		max_kind_width   = 100,
		max_menu_width   = 100,
		documentation    = true,

		source = {
			path      = true,
			calc      = true,
			nvim_lsp  = true,
			nvim_lua  = true,
			spell     = false,
			buffer    = {filetypes = buffers},
			vsnip     = false,
			ultisnips = true,
		};
	}

vim.cmd [[
inoremap <silent><expr> <C-Y>      compe#confirm('<CR>')
inoremap <silent><expr> <C-e>     compe#close('<C-e>')
]]
EOF



```

**Comment by cloggier** [comment]
I am not sure what you are trying to do but with examples from readme (tab mappings for vsnip) once snippet expansion happens and completion menu pops after inserting some text I can either select completion or cancel it and tab to next placeholder with no problem.

**Comment by rickalex21** [comment]
@cloggier I'll make a video if needed to explain better sorry. Right now I can't replicate the
problem in my other account, so it might have something to do with my config settings on
my other account. Still working on this.

**Comment by rickalex21** [comment]
I can't replicated on a new account but if I figure it out later I will post an update. The problem is
that inserting a tab inserts a tab instead of jumping to $3 $4. I disabled my plugins, disabled mappings
looking to disable more stuff so might be a while before I figure this one out. I usually can
figure out things pretty quickly but since in the process of switching to nvim it might be
a while before I figure this one out. I don't think it's a problem with compe.

**Comment by rickalex21** [comment]
@cloggier I figured it out the problem, everything should make sense now. See  #389
