### ISSUE TITLE
Completion gets stuck with lsp using Ultisnips

### ISSUE THREAD

**Issue by rickalex21** [hrsh7th/nvim-compe#389]
#### Update

It looks like ```preselect =false``` does fix the problem, it shouldn't get you stuck in a tabstop 
like that if you have 'always' set but it does fix it. The only problem with that is that I don't get
to see the info automatically like with ```preselect='always'``` I have to select it to see more info.

Using

#### Describe the bug

When attempting to jump from one tabstop to another and the vim lsp is enabled
it gets stuck in a ultisnips tabstop. When the lsp is disabled it works fine,
I have tested the same snippet in lua and it works fine.

#### To Reproduce
Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

Note: Make sure you have the nightly version of neovim. It can be found [here.](https://github.com/neovim/neovim/releases)

1. Clone my test repo [here.](https://github.com/rickalex21/completion)
2. Install vim lsp 

```sh
npm install -g vim-language-server
```

3. Install python if needed for neovim.

```sh
python3 -m pip install --user --upgrade pynvim
```
4. Use my config file I have everything setup for you.

```sh
nvim -u init.vim
```

5. Install the plugins.

```vim
:PlugInstall
```

Try to complete 'log' as shown in the video. When log comes up enter tab to trigger the completion.
Enter the word 'ech' so something can come up in the menu then jump to the next tabstop with
```<c-j>```, you will get stuck.

Now disable lsp with ```let enable_vim_lsp = 0``` exit and go back in. Do the same thing and it
works now. You will not get stuck.

This has been reproduced on mac and linux.

#### Actual behavior

Completion gets stuck in a tabstop.

#### Expected behavior

Move forward to the next tab stop.

#### Screenshots (optional)

I have included a youtube video [here.](https://www.youtube.com/watch?v=TVid3IH3XzI)

Here is the image.

![](/rickalex21/completion/blob/main/images/completion.gif?raw=true)

**Comment by baldore** [comment]
I'm having the same issue, but I don't think the problem is the LSP. I can reproduce the issue when I select one of the items with <c-n> or <c-p>. Once one item is selected, I cannot jump to the next occurrence and it seems like UltiSnips assumes that you cannot jump anymore (tried with `echo UltiSnips#CanJumpForwards()`). Looking forward to a solution...

**Comment by jdhao** [comment]
Same issue here, I guess current, we should not use `preselect = 'always'` if we want to use ultisnips together with nvim-compe.
