### ISSUE TITLE
Buffer completion does not work for cyrrilic buffers

### ISSUE THREAD

**Issue by hyperkahler** [hrsh7th/nvim-compe#391]
#### Describe the bug
Buffer completion does not work for cyrrilic buffers (tested only for russian symbols though).

#### To Reproduce
Just type any russian symbols and trigger autocompletion. Tested with the default nvim-comple configuration alongside with the option `vim.o.encoding = 'utf-8'`

### Screencast
![screencast](https://i.imgur.com/Ca6VlVc.gif)

**Comment by hrsh7th** [comment]
Please check https://github.com/hrsh7th/nvim-compe/issues/167
