### ISSUE TITLE
Text before cursor is removed when emoji completion is selected

### ISSUE THREAD

**Issue by Akeboshiwind** [hrsh7th/nvim-compe#396]
#### Describe the bug
When I try to complete an emoji, the text before the emoji is deleted.
Here's an example:

<img src="https://user-images.githubusercontent.com/8889986/120712544-ab2fdf80-c4b8-11eb-9943-d84a7cf483d2.gif" width=500>

#### To Reproduce

Using this config:

<details><summary>init.vim</summary>

```viml
set completeopt=menuone,noselect
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'hrsh7th/nvim-compe'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close

lua << EOF

require'compe'.setup {
  enabled = true,

  source = {
    buffer = true,
    emoji = true,
  },
}

EOF

inoremap <silent><expr> <CR>      compe#confirm('<CR>')
```

</details>

1. open vim using `nvim -nu init.vim` and the config above
2. follow the example in the gif above
    1. Type `test`
    2. Type two newlines
    3. Type `:smile`
    4. Type `<CR>` to complete the line

#### Actual behavior

Text beore the completion is removed

#### Expected behavior

The emoji is inserted in-place

**Comment by hrsh7th** [comment]
I will check it.

**Comment by Akeboshiwind** [comment]
Perfect! Thanks :)
