### ISSUE TITLE
Defining client_capabilities without having to setup capabilities for every language-server individually

### ISSUE THREAD

**Issue by astier** [hrsh7th/nvim-compe#397]
#### Problem

Right now the documentation says that when the client_capabilities are defined then they have to be passed to every single language-server individually. For example I am using clangd and the jedi_language_server. After defining the capabilities I pass the capabilities to both servers like that:

```lua
require 'lspconfig'.clangd.setup{capabilities = capabilities}
require 'lspconfig'.jedi_language_server.setup{capabilities = capabilities}
```

Is it possible to define the capabilities globally without needing to pass the capabilities to every single server such that I could replace the two lines above with:

```lua
require 'lspconfig'.clangd.setup{}
require 'lspconfig'.jedi_language_server.setup{}
```

#### Solution

I don't have a solution.

#### Alternatives

No alternatives either.

#### Context

Out of context.

**Comment by hrsh7th** [comment]
It's out of scope of compe.
It should be supported on nvim-lspconfig.
