### ISSUE TITLE
Ultisnips 'kind' setting

### ISSUE THREAD

**Issue by ErikEkstedt** [hrsh7th/nvim-compe#400]
#### Describe the bug

Using Ultisnips for snippets does not allow the user to change 'kind'.

#### To Reproduce

Setting the 'menu' value for the Ultisnips source works fine (as do other sources) but (I believe) Compe overwrites the 'kind' value for Ultisnips.

In the example below i change the 'menu'-item to '[US]' which works great and then the 'kind'-value to anything.

```lua
compe.setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;

  source = {
    path = true;
    buffer = {menu='[B]'};
    calc = true;
    nvim_lsp = true;
    nvim_lua = true;
    ultisnips = {menu='[US]', kind='WHATEVER'}; 
}
```

#### Actual behavior

The 'kind' value for Ultisnips is always set to 'Snippet'.

#### Expected behavior

The user defined value of 'kind' is used.

#### Screenshots (optional)

![compe-us](https://user-images.githubusercontent.com/16295873/120922085-7fcf0f80-c6c7-11eb-8997-9c688727e9ac.png)

#### Additional context (optional)

I believe the problem could be in the [Ultisnips-settings](https://github.com/hrsh7th/nvim-compe/blob/888d9eccfe7b9092dcbfcdfabfad601ce63f3eb5/lua/compe_ultisnips/init.lua) on line 29. Here compe seems to always define the kind of Ultisnips as 'Snippet'.

Cheerio!

**Comment by hrsh7th** [comment]
Thank you. PR welcome :)
