### ISSUE TITLE
How to install this ?

### ISSUE THREAD

**Issue by NooneXe** [hrsh7th/nvim-compe#402]
I'm completely new to vim stuff and its not clear in readme file How to install this plugin

**Comment by hrsh7th** [comment]
OK. I understand that you are new to vim, but don't delete the issue template.

You can use some plugin manager to install plugin.

You can use one of the following plugins.

https://github.com/junegunn/vim-plug
https://github.com/wbthomason/packer.nvim
https://github.com/Shougo/dein.vim
