### ISSUE TITLE
Selected one entry but got completion of another entry

### ISSUE THREAD

**Issue by thallium** [hrsh7th/nvim-compe#403]
#### Describe the bug
As the title suggests. More specifically, got completion of the first entry of the previous completion list (see example below for better understanding)
#### To Reproduce
Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):
```vim
if &runtimepath !~# '/dein.vim'
    set runtimepath+=~/.local/share/dein/repos/github.com/Shougo/dein.vim
endif
let s:data_path='~/.local/share/dein'
if dein#load_state(s:data_path)
    call dein#begin(s:data_path)
    call dein#add('~/.local/share/dein/repos/github.com/Shougo/dein.vim')

    call dein#add('neovim/nvim-lspconfig')

    call dein#add('hrsh7th/nvim-compe')

    call dein#end()
    call dein#save_state()
endif

let g:compe = {}
let g:compe.enabled = v:true
let g:compe.autocomplete = v:true
let g:compe.debug = v:false
let g:compe.min_length = 1
let g:compe.preselect = 'always'
let g:compe.throttle_time = 80
let g:compe.source_timeout = 200
let g:compe.incomplete_delay = 400
let g:compe.max_abbr_width = 100
let g:compe.max_kind_width = 100
let g:compe.max_menu_width = 80
let g:compe.documentation = v:true

let g:compe.source = {}
let g:compe.source.path = v:true
let g:compe.source.buffer = v:true
let g:compe.source.nvim_lsp = v:true
let g:compe.source.nvim_lua = v:true
let g:compe.source.ultisnips = v:true


inoremap <silent><expr> <CR>      compe#confirm('<CR>')

lua <<EOF
require('lspconfig').clangd.setup{}
EOF
```
1. open a cpp file
2. create a vector `vector<int> a;`
3. type `a.p` and got two option: `pop_back` and `push_back`
4. type `u`, now only got one option `push_back`
5. hit enter but got `a.pop_back`

#### Actual behavior
got `a.pop_back`
#### Expected behavior
get `a.push_back`
#### Screenshots (optional)
no need
#### Additional context (optional)
May be completion-source-specific, currently encountered with clangd and buffer source, seems no problem with gopls but not sure about other source.

**Comment by hrsh7th** [comment]
Thank you. It's high priority bug.

But I'm busy now... If you have a solution, feel free to PR.

**Comment by thallium** [comment]
Seems not fully fixed, the example still happened.

**Comment by hrsh7th** [comment]
Hm... Sorry. I can't reproduce. `a.p` does not show `pop_back` and `push_bach`.

**Comment by thallium** [comment]
Maybe you didn't declare the vector properly? Use `std::vector<int> a;`, here's a screenshot 
![image](https://user-images.githubusercontent.com/20818480/121627291-12afd700-ca45-11eb-92a8-acfaa7eb5ee4.png)

**Comment by hrsh7th** [comment]
reproduced! I will fix it soon. Thank you.
