### ISSUE TITLE
Floating window preview breaks on second pass.

### ISSUE THREAD

**Issue by MetriC-DT** [hrsh7th/nvim-compe#404]
#### Describe the bug
Going to a Pmenu option with floating window preview breaks when going to the same selection a second time.
#### To Reproduce
Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. Trigger Pmenu autocomplete open
2. Ctrl-N to an option with a floating window preview.
3. Ctrl-N then Ctrl-P to go back to the option with floating window preview.

#### Actual behavior
Floating window preview displays backticks and drops color.
#### Expected behavior
Floating window preview does not display backticks and keeps color.
#### Screenshots (optional)
First pass
<a href="https://ibb.co/r6H10NW"><img src="https://i.ibb.co/Fwzj3CP/1623220352.png" alt="1623220352" border="0"></a>
Second pass
<a href="https://ibb.co/JmvVnn9"><img src="https://i.ibb.co/CmbgBBf/1623220360.png" alt="1623220360" border="0"></a><br />

**Comment by MetriC-DT** [comment]
This is still broken. Behavior is that if we go to an option with a preview, then navigate to one that is not, then back to the one with a preview, the preview window displays the backticks and no color. Is this a problem with compe or neovim's floating window?

**Comment by systemctl603** [comment]
I am also able to reproduce.

> Is this a problem with compe or neovim's floating window?
I believe this is an issue with `nvim-compe` as default lsp hover window works fine.

**Comment by hrsh7th** [comment]
It's compe's bug.
But it's difficult to fix... Hm...

**Comment by skanev** [comment]
As far as I can tell, changing [this line](https://github.com/hrsh7th/nvim-compe/blob/master/autoload/vital/_compe/VS/Vim/Syntax/Markdown.vim#L18) to `if v:true` solve the issue for me. Not really perfectly, but at least it stops breaking after the first pass.

Would you care to share to some insight on what the problem is? Maybe one of us can help out with a PR :)
