### ISSUE TITLE
 Still get a complete entry from the preview

### ISSUE THREAD

**Issue by Julpikar** [hrsh7th/nvim-compe#407]
#### Describe the bug
I can still complete from the previous preview, after I choose another entry.

#### To Reproduce
```
  vim.o.completeopt = "menuone,noselect"
  vim.cmd("set pumheight=15")
  vim.cmd("set shortmess+=c")

  require "compe".setup {
    enabled = true,
    autocomplete = true,
    debug = false,
    min_length = 1,
    preselect = "always",
    throttle_time = 80,
    source_timeout = 200,
    incomplete_delay = 400,
    max_abbr_width = 100,
    max_kind_width = 100,
    max_menu_width = 100,
    documentation = true,
    source = {
      path = true,
      buffer = true,
      calc = true,
      nvim_lsp = true,
      nvim_lua = true,
      vsnip = true
    }
  }
```
#### Screenshots (optional)
- first key
![Untitled](https://user-images.githubusercontent.com/17688038/121446658-37ad3700-c9be-11eb-9ea8-53ec7483267b.png)
- second key
![Untitled2](https://user-images.githubusercontent.com/17688038/121446677-40057200-c9be-11eb-8d99-45827337d848.png)
If I select composer, the complete entry that will appear is from vsnip

**Comment by hrsh7th** [comment]
Sorry. I can't reproduce it...

**Comment by Julpikar** [comment]
It's ok, I downgrade to version 2
