### ISSUE TITLE
Document how to close with the ESC key

### ISSUE THREAD

**Issue by kikito** [hrsh7th/nvim-compe#408]
#### Is your feature request related to a problem? Please describe.

My problem is that I was expecting that pressing ESC would close the autocomplete window (I've seen that referred as ... "pug" in the issues?). It does not, by default. But the suggested mappings in the doc don't explain how to accomplish this.

I am not super familiar with the different ways Vim allows mapping keys (imap vs innoremap) so perhaps I am missing something on that side.

#### Describe the solution you'd like

I'd like the docs to include a mapping that makes ESC close the autocomplete window.

#### Describe alternatives you've considered

I tried doing this:

```
inoremap <silent><expr> <ESC>     compe#close('<ESC>')
```

It did not go well because:
* It did not close the window
* It showed an error message 
* It made it impossible to go back to normal mode in Vim xD. I had to edit my init.vim file in nano in order to rescue it.

#### Additional context

As an extra, I usually don't use `<ESC>`, but a combination of `j` and `k`. So I have this on my conf:

```
imap jk <ESC>
imap Jk <ESC>
imap JK <ESC>
```

Ideally (for me) the provided mapping should be compatible with that (so pressing `jk` in rapid succession would close the autocomplete window, but otherwise individual presses of `j` and `k` allow selecting from alternatives on it.

**Comment by hrsh7th** [comment]
I tried to map `compe#close('<esc>')` to `<Esc>` but I couldn't.
I investigated it then I found the cause that is lexima.vim.

If you can't map `<esc>` in insert-mode, you should check `imap` results.

**Comment by kikito** [comment]
Ok my problem was that I had the `vim-autoclose` plugin installed, and it interfered with the usage of the `<ESC>` key. This issue has been reported in other autocompletion plugins ( https://github.com/Shougo/deoplete.nvim/issues/386 , https://github.com/ycm-core/YouCompleteMe/issues/9).

The fix seems to be adding the following setting for the vim-autoclose plugin:
```
let g:AutoClosePumvisible = {"ENTER": "<C-Y>", "ESC": "<ESC>"}
```

I've sent a PR which documents this in #409 . Thank you for creating this plugin!
