### ISSUE TITLE
Feature request: support preview for source info field 

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#41]
Hey @hrsh7th 

I wonder if there is a support for source like iced-vim that provide info field having documentation in it. 
If so can you share a quick snippet for vim source I can start with.
Thanks

**Comment by hrsh7th** [comment]
You should implement `soirce.datermie` by yourself.

See compe_vsnip source.

**Comment by tami5** [comment]
Nice thanks

**Comment by tami5** [comment]
hmmm I'm getting the following error 

```vim 
Error executing vim.schedule lua callback: Vim(let):E474: Unidentified byte: clojure.core/defn-
([name & decls])
Macro
  same as defn, yielding non-public def
```

Something about callback I'm not getting

```vim
function! s:documentation(args) abort
  let l:completed_item = a:args.completed_item
  if empty(get(l:completed_item, 'info', ''))
    return a:args.abort()
  endif
  if type(l:completed_item.info) == type('')
    let l:user_data = json_decode(l:completed_item.info)
  else
    let l:user_data = l:completed_item.info
  endif
  if !has_key(l:user_data, 'iced')
    return a:args.abort()
  endif

  call a:args.callback(l:user_data.info)
endfunction


```

**Comment by hrsh7th** [comment]
Could you try it?
You can print debug `echomsg string(l:completed_item)`.
```
function! s:documentation(args) abort
  let l:completed_item = a:args.completed_item
  if empty(get(l:completed_item, 'info', ''))
    return a:args.abort()
  endif
  call a:args.callback(l:completed_item.info)
endfunction
```

**Comment by tami5** [comment]
With the above I'm getting `Error executing vim.schedule lua callback: Vim(call):E5108: Error executing lua Vim(for):E714: List required`

Its an issue with callback. What does args.callback accept?

**Comment by tami5** [comment]
From original version tried `return l:user_data` but same err ``

```vim
Error executing vim.schedule lua callback: Vim(let):E474: Unidentified byte: clojure.core/defn
([name doc-string? attr-map? [params*] prepost-map? body] [name doc-string? attr-map? ([params*] prepost-map? body) + attr-map?])
Macro
  Same as (def name (fn [params* ] exprs*)) or (def
    name (fn ([params* ] exprs*)+)) with any doc-string or attrs added
    to the var metadata. prepost-map defines a map with optional keys
    :pre and :post that contain collections of pre or post conditions.
```

**Comment by hrsh7th** [comment]
It should be work.
```
function! s:documentation(args) abort
  let l:completed_item = a:args.completed_item
  if empty(get(l:completed_item, 'info', ''))
    return a:args.abort()
  endif
  call a:args.callback(split(l:completed_item.info, "\n", v:true))
endfunction
```

**Comment by tami5** [comment]
Nice Thanks a lot, Is it parsed as markdown? also, I noticed with different source that the first match doesn't show documentation, and if its the only match also not show. Should I report

**Comment by hrsh7th** [comment]
Yes. The documentation must be markdown.

If you want to show documentation as specific filetype, You can simply add the `\`\`\`%FILETYPE``` and `\`\`\` for document text.

**Comment by hrsh7th** [comment]
Currently, nvim-compe does not show item that selected by `auto_preselect` feature.

I think to support it is difficult by performance, user-experience.

But I will try it.

**Comment by tami5** [comment]
I disabled auto_preselect feature and still the same 

Also @hrsh7th is there a method where I can transact the additonal text beyond threshold with `.....`

https://i.imgur.com/e6VHDN2.png

**Comment by hrsh7th** [comment]
Probably, I couldn't understand your mean...

Could you explain me the your expectation by more simple way?

**Comment by tami5** [comment]
So the window is very wide because of the source function args  (multi). I want to shortent the width of completion popup and not let it stretch to the end of the screen

![](https://i.imgur.com/e6VHDN2.png)

**Comment by hrsh7th** [comment]
OK. I understand.

So we shoulda add `max pum width` option?

**Comment by tami5** [comment]
Oh thats really useful to have. so sources can't hijack compe popup
