### ISSUE TITLE
Key not present in Dictionary: "item.word, 'n')"

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/nvim-compe#412]
#### Describe the bug

Starting from 58432ef3d40d6f6330554c5a6518415b1a5023cc I have the following error:

```
E5108: Error executing lua Vim(call):E716: Key not present in Dictionary: "item.word, 'n')"
```

when I using `vim.fn['compe#confirm']({keys = '<C-Space>', select = true})` for completion confirmation. 

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. Create `completion.lua`:

```lua
local completion = {}

function completion.trigger_completion()
  if vim.fn.pumvisible() ~= 0  then
    return vim.fn['compe#confirm']({keys = '<C-Space>', select = true})
  else
    return vim.fn['compe#complete']()
  end
end

return completion
```
2. Add shortcut to call it in configuration:

```
vim.api.nvim_set_keymap('i', '<C-Space>', [[luaeval('require("completion").trigger_completion()')]], { noremap = true, expr = true, silent = true })
```

3. Start typing something to get completion
4. Do not select any item and press `<C-Space>`.

#### Actual behavior

The error is described above.

#### Expected behavior

It should complete first item from the completion list.

**Comment by hrsh7th** [comment]
@Shatur Could you test with latest master?

**Comment by Shatur** [comment]
Fixed, thank you!
