### ISSUE TITLE
I can't write a tab

### ISSUE THREAD

**Issue by gmr458** [hrsh7th/nvim-compe#413]
#### Describe the bug
I cant write a tab
#### To Reproduce
Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. press tab in insert mode

#### Actual behavior
![image](https://user-images.githubusercontent.com/53343401/121837836-3de03380-cc9c-11eb-9f1d-445d78d6578b.png)
when I type Esc a zero appears
#### Expected behavior
write a tab

**Comment by hrsh7th** [comment]
You should install vim-vsnip.
