### ISSUE TITLE
Same candidate show many times in the popup from tags

### ISSUE THREAD

**Issue by QiBaobin** [hrsh7th/nvim-compe#418]
#### Checkhealth

Put result of `:checkhealth compe`.

```
health#compe#check
========================================================================
  - ERROR: No healthcheck found for "compe" plugin.


```

#### Describe the bug
Same item show many times, maybe because that function have other overload functions.

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. Create a tag file in a project that define two methods with same name
2. Set tags source to true
3. Open a new buffer, and type that function name,

#### Actual behavior
 a popup show with two items

#### Expected behavior
Only one item

#### Screenshots (optional)
<img width="424" alt="Screen Shot 2021-06-18 at 1 23 58 PM" src="https://user-images.githubusercontent.com/7072/122510692-9dda2f80-d038-11eb-8d98-e035dfffebd5.png">
<img width="424" alt="Screen Shot 2021-06-18 at 1 24 12 PM" src="https://user-images.githubusercontent.com/7072/122510699-a03c8980-d038-11eb-8dbd-313994eff015.png">

#### Additional context (optional)
The <C-X><C-]> only shows one item.

**Comment by 00sapo** [comment]
Hey, can you provide a file where this happens?

**Comment by QiBaobin** [comment]
Maybe it's related with that I have more than one tags files in the root directory. Let me close this for now, thanks!
