### ISSUE TITLE
Show document when the item was selected by auto-preselect.

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#42]

**Comment by tami5** [comment]
It would be a bad behavior though, because usually you'd favor auto-preselect for stuff like snippets, quickly hitting enter on frist match. Perhaps adding adding latency would make it better, idk.

**Comment by hrsh7th** [comment]
It will be good feature but bit difficult...

**Comment by tami5** [comment]
@hrsh7th it would be a good idea to focus first on ongoing issue with not showing doc without pre_select for the first item

**Comment by hrsh7th** [comment]
Ah! Finally, I get the your expectation.

I think your suggetion is not good...

My understanding is

1. disable auto preselect
2. type any char to show pum
3. select first itm by `<C-n>`
4 you expects no documentarion now

**Comment by tami5** [comment]
> Ah! Finally, I get the your expectation maybe.
> 
> I think your suggetion is not good...
> 
> My understanding is
> 
> 1. disable auto preselect
> 2. type any char to show pum
> 3. select first itm by `<C-n>`
> 4. you expects no documentarion now

Yes, because some times it the first selection that has doc I want to look at

**Comment by hrsh7th** [comment]
I think compe should show always the documentation for each the item selected.

Because the documentation is very very very important on typescript.

The typescript can be exported the same identifier from multiple modules.

For example, The A and B modules exported `getSomething`.

In this case, we will see the two `getShomething` on the pum but the user can't know the module name for each items.
(Usualy, the user select item and look the documentation popup to know that)

**Comment by tami5** [comment]
It does, but not consistence here is gif of the behavior https://i.imgur.com/ECli1v8.gif

**Comment by hrsh7th** [comment]
It seems a bug and I have met similar behavior.

**Comment by hrsh7th** [comment]
@tami5 Could you test with latest compe?

I've fixed some of the bugs that I found.

**Comment by tami5** [comment]
It is definitely better now, but still some issues https://i.imgur.com/JtmFnfG.gif, maybe source related?

**Comment by tami5** [comment]
Tested on lsp lua works

**Comment by hrsh7th** [comment]
Hm.... but the `defonce` seems to have documentation (it looks like sometimes shows, sometimes not...)

Yes. It can be source related but I don't confidence it... It's weird

**Comment by tami5** [comment]
I'll do further testing later

**Comment by hrsh7th** [comment]
You can add the `echomsg string(candidates)` on https://github.com/tami5/vim-iced-compe/blob/master/ftplugin/clojure.vim#L29.

If `defonce` candidate has no documentation, it means this problem source related.

**Comment by hrsh7th** [comment]
Ah... Sorry. It's a bit difficult (because it is written in Vim script... 😂

You can use it.
```viml
if exists('g:loaded_vim_iced_compe')
  finish
endif
let g:loaded_vim_iced_compe = 1

function! s:get_metadata() abort
  return { 'priority': 1000, 'dup': 1, 'filetypes': ['clojure'] }
endfunction

function! s:datermine(context) abort
  let l:offset = compe#pattern#get_offset(a:context, '[[:alnum:]!$&*\-_=+:<>./?]\+$')
  if l:offset > 0
    return {
    \   'keyword_pattern_offset': l:offset
    \ }
  end
  return {}
endfunction

function! s:complete(args) abort
  if !iced#repl#is_connected()
    return a:args.abort()
  endif

  if !iced#nrepl#check_session_validity(v:false)
    return a:args.abort()
  endif

  call iced#complete#candidates(a:args.input, { candidates -> [
  \   s:log(candidates),
  \   a:args.callback({
  \     'items': candidates
  \   })
  \ }])
endfunction

function! s:log(...)
  echomsg string(a:000)
endfunction

let s:source = {
\   'get_metadata': function('s:get_metadata'),
\   'datermine': function('s:datermine'),
\   'complete': function('s:complete'),
\ }

call compe#source#vim_bridge#register('iced', s:source)
```

**Comment by tami5** [comment]
Where does it log, I don't see anything printing, also the source stop working

**Comment by hrsh7th** [comment]
```viml
if exists('g:loaded_vim_iced_compe')
  finish
endif
let g:loaded_vim_iced_compe = 1

function! s:get_metadata() abort
  return { 'priority': 1000, 'dup': 1, 'filetypes': ['clojure'] }
endfunction

function! s:datermine(context) abort
  let l:offset = compe#pattern#get_offset(a:context, '[[:alnum:]!$&*\-_=+:<>./?]\+$')
  if l:offset > 0
    return {
    \   'keyword_pattern_offset': l:offset
    \ }
  end
  return {}
endfunction

function! s:complete(args) abort
  if !iced#repl#is_connected()
    return a:args.abort()
  endif

  if !iced#nrepl#check_session_validity(v:false)
    return a:args.abort()
  endif

  call iced#complete#candidates(a:args.input, { candidates -> [
  \   s:log(candidates),
  \   a:args.callback({
  \     'items': candidates
  \   })
  \ ]})
endfunction

function! s:log(...)
  echomsg string(a:000)
endfunction

let s:source = {
\   'get_metadata': function('s:get_metadata'),
\   'datermine': function('s:datermine'),
\   'complete': function('s:complete'),
\ }

call compe#source#vim_bridge#register('iced', s:source)
```

Sorry... try it...

**Comment by tami5** [comment]
Thats okay,

![](https://i.imgur.com/o3SoPLd.gif)

**Comment by hrsh7th** [comment]
Does defonce have info when the document is not displayed?

**Comment by hrsh7th** [comment]
The improved version of the logging function is below.

```viml
function! s:log(candidates)
  echomsg string(filter(copy(a:candidates), 'v:val.word ==# "defonce"'))
endfunction
```

**Comment by tami5** [comment]
How about this one 

![](https://i.imgur.com/JxNxKls.gif)

**Comment by hrsh7th** [comment]
Hm... It seems like a bug on the nvim-compe side... I will investigate it.

**Comment by hrsh7th** [comment]
Implemented.

**Comment by tami5** [comment]
That's awesome @hrsh7th thank you I'll test it out tom

**Comment by hrsh7th** [comment]
Sorry. I have reverted it... (it had a bug...)

BTW, I don't occur your problem anymore that documentation sometimes shows sometimes not.

Do you still have the problem?

**Comment by tami5** [comment]
Just update nvim-comp since 2 weeks ago and the documentation don't even work :(. Let try to find out why

**Comment by hrsh7th** [comment]
OK. It could be a potential bug of nvim-compe.
I will create new separated issue for it.

**Comment by hrsh7th** [comment]
Fixed
