### ISSUE TITLE
Completion menu has to be triggered twice when autocomplete disabled

### ISSUE THREAD

**Issue by ldelossa** [hrsh7th/nvim-compe#421]
#### Checkhealth

Put result of `:checkhealth compe`.

```

health#compe#check
========================================================================
## compe:snippet
  - INFO: snippet engine is not detected.

## compe:mapping
  - OK: `compe#complete` is mapped: (`i  <C-Space>   * compe#complete()`)
  - OK: `compe#confirm` is mapped: (`i  <CR>        * compe#confirm('<CR>')`)
  - OK: `compe#close` is mapped: (`i  <C-E>       * compe#close('<C-E>')`)
  - OK: `compe#scroll` is mapped: (`i  <C-D>       * compe#scroll({ 'delta': -4 })`)

```

#### Describe the bug
I do not use "autocomplete" and rely on key sequence to open completion menu

Often I open the completion menu with no text to get a list of items I could use for completion. 

When I do this, the menu opens up shortly, then disappears, and I have to open it again. I esentially have to trigger the completion menu twice. This is not the case if I provide the first few letters of a value. 

#### To Reproduce

1. Turn off autocomplete
2. Setup some command to open completion menu
3. Open completion menu with no text preset at all 

for instance in go 
```
struct{ 
   {open completion menu here}
}
```

#### Actual behavior
Need to open the completion menu twice then it sticks around.

#### Expected behavior
Do not need to open completion menu twice.

**Comment by hrsh7th** [comment]
I've fixed it (maybe). Thank you for your report.
