### ISSUE TITLE
Keymap not recognised

### ISSUE THREAD

**Issue by LamprosPitsillos** [hrsh7th/nvim-compe#425]
#### Checkhealth
health#compe#check
========================================================================
## compe:snippet
  - OK: snippet engine detected.

## compe:mapping
  - OK: `compe#complete` is mapped: (`i  <C-Space>   * compe#complete()`)
  - INFO: `compe#confirm` is not mapped
  - OK: `compe#close` is mapped: (`i  <C-E>       * compe#close('<C-E>')`)
  - OK: `compe#scroll` is mapped: (`i  <C-D>       * compe#scroll({ 'delta': -4 })`)

```
```

#### Describe the bug
I cant get snippets to work for the life of me...
The FAQ says just use the mapping for `compe#confirm`.
I did but it doesnt work for some reason. Check health also says i have not mapped it , when i have. (Just copied the mappings)

I even followed the LSP snippets in the faq but nothing changed.

**Comment by hrsh7th** [comment]
Could you provide your vimrc?

**Comment by FOSSilizedDaemon** [comment]
> Could you provide your vimrc?

I am no OP, but am having this issue. My configuration for `nvim-compe` bindings can be seen [here](https://gitlab.com/FOSSilized_Daemon/dotfiles/-/blob/master/src/configs/nvim/lua/plugin.lua#L157). Only control J/K are not working.

**Comment by sebui** [comment]
I guess you are using CR mapping. You should check if another plugin use the mapping key you have defined.
Run `:imap` to see the current mapping

The plugin 'cohama/lexima.vim' was the issue in my case

**Comment by FOSSilizedDaemon** [comment]
> I guess you are using CR mapping. You should check if another plugin use the mapping key you have defined.
> Run `:imap` to see the current mapping
> 
> The plugin 'cohama/lexima.vim' was the issue in my case

Oh I forgot about this issue, I moved to just using tab and s-tab.
