### ISSUE TITLE
Crashes when confirming a vsnip option

### ISSUE THREAD

**Issue by sQVe** [hrsh7th/nvim-compe#427]
#### Checkhealth

Put result of `:checkhealth compe`.

```
health#compe#check
========================================================================
## compe:snippet
  - OK: snippet engine detected.

## compe:mapping
  - OK: `compe#complete` is mapped: (`i  <C-Space>   * compe#complete()`)
  - OK: `compe#confirm` is mapped: (`i  <CR>        * compe#confirm('<CR>')`)
  - OK: `compe#close` is mapped: (`i  <C-E>       * compe#close('<C-E>')`)
  - INFO: `compe#scroll` is not mapped
```

#### Describe the bug

I tried creating a snippet today that had options in it. `compe` correctly lists the options but as soon as I confirm one option `compe` crashes.

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. Install `vsnip` and `compe` with the following bindings:
```vim
      inoremap <silent><expr> <C-Space> compe#complete()
      inoremap <silent><expr> <CR> compe#confirm('<CR>')
      inoremap <silent><expr> <C-e> compe#close('<C-e>')
```
2. Use a snippet file like:
```json
{
  "demo": {
    "prefix": "cl",
    "body": "console.log('${1|foo,bar|}')"
  }
}
```
3. Expand `cl` snippet and pick `bar` options. Use <kbd>CR</kbd> to confirm.

#### Actual behavior

`vsnip` crashes and does not confirm choice. Errors with:

```
Error detected while processing function compe#confirm:
line   18:
E716: Key not present in Dictionary: "item.word, 'n')"
Press ENTER or type command to continue
```

#### Expected behavior

It should confirm the choice like the `vsnip` jump does, which works perfectly.

#### Screenshots (optional)

https://user-images.githubusercontent.com/2284724/123330082-d8aefc80-d53d-11eb-8b46-9f25d593c16c.mp4

**Comment by hrsh7th** [comment]
I've fixed it. Thank you.

**Comment by Shatur** [comment]
@hrsh7th After this fix manual confirmation doesn't work. The following code now do nothing: `vim.fn['compe#confirm']({keys = '<C-Space>', select = true})`.

**Comment by hrsh7th** [comment]
Sorry for the annoying. I've fixed it.
