### ISSUE TITLE
Non-ASCII characters break `buffer` completion

### ISSUE THREAD

**Issue by cbarrete** [hrsh7th/nvim-compe#431]
#### Checkhealth

Put result of `:checkhealth compe`.

```
health#compe#check
========================================================================
## compe:snippet
  - OK: snippet engine detected.

## compe:mapping
  - INFO: `compe#complete` is not mapped
  - INFO: `compe#confirm` is not mapped
  - INFO: `compe#close` is not mapped
  - INFO: `compe#scroll` is not mapped
```

#### Describe the bug

Some non-ASCII characters break buffer completion : only the characters up until that one are part of the suggestion.

#### To Reproduce

1. Enable at least `buffer` completion in compe
2. Open a buffer with `Accentuées` in it
3. Type `Acc` on a new line

#### Actual behavior

`Accentu` is part of the pumenu

#### Expected behavior

`Accentuée` is part of the pumenu

#### Screenshots (optional)

![image](https://user-images.githubusercontent.com/62146989/123527002-121d6e80-d6dc-11eb-8abf-3625d3ec1146.png)

#### Additional context (optional)

Using `ins-completion` with compe disabled, the word is properly completed.

**Comment by hrsh7th** [comment]
see https://github.com/hrsh7th/nvim-compe/issues/347
