### ISSUE TITLE
Text is rendered inconsistently in documentation window

### ISSUE THREAD

**Issue by MrAdityaAlok** [hrsh7th/nvim-compe#440]
#### Checkhealth

Put result of `:checkhealth compe`.

```

health#compe#check
========================================================================
## compe:snippet
  - INFO: snippet engine is not detected.

## compe:mapping
  - OK: `compe#complete` is mapped: (`i  <C-Space>   * compe#complete()`)
  - OK: `compe#confirm` is mapped: (`i  <CR>        * compe#confirm('<CR>')`)
  - INFO: `compe#close` is not mapped
  - OK: `compe#scroll` is mapped: (`i  <C-D>       * compe#scroll({ 'delta' : -4 })<Space>`)

```

#### Describe the bug
Text is inconsistently rendered or formatted in documentation  window

*NOTE: This seems to occur only while using pyright(atleast for me, I had no other lsp to test except clangd where no documentation is shown)*

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1.  open a python file
2.  Type something for auto-completion to trigger
3.  Scroll through the presented menu

#### Actual behavior
*See the addition of `<text>` tag in documentation window for `findall` completion item*

https://user-images.githubusercontent.com/73517616/124149850-9aba5700-daae-11eb-8dd4-a493d263598d.mp4

#### Expected behavior

Should render properly everytime

**Comment by folke** [comment]
There's a couple of things here:
1. the pyright lsp server you're using seems to return plaintext instead of markdown. I get proper markdown instead
2. the contents from the lsp server are cached in compe and theres a bug upstream in Neovim that will double existing plaintext markup. (I'll fix that)

This is how it should look like:
![image](https://user-images.githubusercontent.com/292349/124401216-ed795600-dcdc-11eb-96e6-ac84ebe6509b.png)

**Comment by folke** [comment]
I pushed a PR to both neovim, but also to compe for people using Neovim 0.5

**Comment by folke** [comment]
btw, is it possible you are **not** using `pyright`, but `pyls`?

Pyright is the preferred LSP server and that one should return properly formatted markdown instead.

**Comment by MrAdityaAlok** [comment]
> btw, is it possible you are **not** using `pyright`, but `pyls`?

No, I checked twice, I use `pyright`. `Pyls` is not even installed.

> Pyright is the preferred LSP server and that one should return properly formatted markdown instead.

It returns properly formatted markdown, but for the first time I scroll to that completion item, on every next scroll to the same item `<text>` get added to it's documentation window ( as in the video).
