### ISSUE TITLE
In the readme file there is an option for setting tab completion but where should i place that code? 

### ISSUE THREAD

**Issue by 3301n** [hrsh7th/nvim-compe#444]
#### Checkhealth

Put result of `:checkhealth compe`.

```
```

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. ...
2. ...
3. ...

#### Additional context (optional)
Can you add it to readme so that noob users can understand where to place the code for tab completion

**Comment by hrsh7th** [comment]
@3301n Do you have vimrc?
