### ISSUE TITLE
Python Auto Completion Error

### ISSUE THREAD

**Issue by hungrybirder** [hrsh7th/nvim-compe#447]
![image](https://user-images.githubusercontent.com/1021047/124428318-21b54b00-dd9f-11eb-88e7-1d14f27ca0cd.png)

I got error From commit f3b722fb9c0a5a072a4991c10674252e6b516019 to 397cf7e073970736dbae6eec7e1fd7bc7494d997.

When I switch to commit 077329e6bd1704d1acdff087ef1a73df23e92789, it works well.

NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Python 3.6.8

**Comment by hrsh7th** [comment]
I've fixed it. Could you test with latest master?

**Comment by p00f** [comment]
This is fixed for me

**Comment by hungrybirder** [comment]
> I've fixed it. Could you test with latest master?

It works well by using commit 00ebf180d01f7f020c6c19bd8caed59f722ccc04

Thank you for fixing it.

**Comment by Pocco81** [comment]
Hello! Thanks for your hard work on the plugin! I love it. Just wanted to mention that I was experiencing the same with `lua` files but latest commit fixed it all. Thanks :+1:
