### ISSUE TITLE
compe#confirm's 'select': v:true no longer works

### ISSUE THREAD

**Issue by guidocella** [hrsh7th/nvim-compe#449]
#### Checkhealth

Put result of `:checkhealth compe`.

```
health#compe#check
========================================================================
## compe:snippet
- OK: snippet engine detected.

## compe:mapping
- INFO: `compe#complete` is not mapped
- OK: `compe#confirm` is mapped: (`i  <CR>        * compe#confirm({ 'keys': '<CR>', 'select': v:true })`)
- INFO: `compe#close` is not mapped
- INFO: `compe#scroll` is not mapped
```

#### Describe the bug

Commit bdf625e broke `compe#confirm`'s select feature, which automatically confirms the first completion option when none has been selected.

#### To Reproduce

1. Set a keybinding like
```viml
inoremap <silent><expr> <CR> compe#confirm({ 'keys': "<CR>", 'select': v:true })
```
2. Trigger autocompletion and press Enter before selecting any entry

#### Actual behavior

Nothing happens.

#### Expected behavior

The first entry is selected.

**Comment by hrsh7th** [comment]
Thank you for your report.
