### ISSUE TITLE
Completion item `detail` is not shown anymore (only `documentation`)

### ISSUE THREAD

**Issue by marcelbeumer** [hrsh7th/nvim-compe#451]
Since https://github.com/hrsh7th/nvim-compe/commit/70b54cf1811b95513aa3f8d9463ad62be81c6d18#diff-41c540380f07ec958d18a2fcdee66c06c9af4404c9a9a167154a19eb7993d880 the completion item `.detail` is not shown anymore, only documentation.

The `typescript-language-server` provides both `.detail` and `.documentation` depending on the completion item. Both contain "important" info (arguably detail more than documentation but both should be rendered imo)

**Comment by marcelbeumer** [comment]
Example screenshots. 

Old rendering of both detail and documentation:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/111366/124752820-9f589280-df28-11eb-8a39-14711d3c8125.png">

Current rendering of only documentation:
<img width="621" alt="Screen Shot 2021-07-07 at 13 40 39" src="https://user-images.githubusercontent.com/111366/124753146-efcff000-df28-11eb-8fd8-2ac5e68ec8b2.png">

**Comment by hrsh7th** [comment]
I will fix it. Thank you for your report.
