### ISSUE TITLE
compe#close() does not work properly.

### ISSUE THREAD

**Issue by jdhao** [hrsh7th/nvim-compe#452]
#### Checkhealth

Put result of `:checkhealth compe`.

```
health#compe#check
========================================================================
## compe:snippet
  - INFO: snippet engine is not detected.

## compe:mapping
Error detected while processing function <SNR>65_clear:
line    1:
E802: Invalid ID: -1 (must be greater than or equal to 1)
Error detected while processing function <SNR>65_clear:
line    1:
E802: Invalid ID: -1 (must be greater than or equal to 1)
  - OK: compe#complete is mapped: (i  <C-Space>     compe#complete())
  - OK: compe#confirm is mapped: (i  <SNR>36_AutoPairsOldCRWrapper73 &@compe#confirm('<CR>'))
  - OK: compe#close is mapped: (i  <C-E>         compe#close('<C-E>'))
  - OK: compe#scroll is mapped: (i  <C-D>         compe#scroll({'delta': -4}))

Error detected while processing function <SNR>65_update:
line    2:
E802: Invalid ID: -1 (must be greater than or equal to 1)
```

#### Describe the bug

compe#close() does not work, i..e, we can not close the popup menu with it.

#### To Reproduce

nvim-compe is installed under `~/.local/share/nvim/site/pack/packer/start/nvim-compe`.

```
git clone --depth=1 https://github.com/hrsh7th/nvim-compe ~/.local/share/nvim/site/pack/packer/start/nvim-compe
```

1. Use the following minimal config:

```
lua << EOF
  require'compe'.setup {
    enable = true;
    autocomplete = true;

    source = {
      path = true;
      spell = true;
    }
  }

  vim.o.completeopt = "menuone,noselect"
  -- nvim-compe mappings
  vim.api.nvim_set_keymap('i', '<C-Space>', 'compe#complete()', {expr = true})
  vim.api.nvim_set_keymap('i', '<CR>', "compe#confirm('<CR>')", {expr = true})
  vim.api.nvim_set_keymap('i', '<C-e>', "compe#close('<C-e>')", {expr = true})
  vim.api.nvim_set_keymap('i', '<C-f>', "compe#scroll({'delta': +4})", {expr = true})
  vim.api.nvim_set_keymap('i', '<C-d>', "compe#scroll({'delta': -4})", {expr = true})
EOF
```

2. Open a file test.md with the above config: `nvim -u minimal.vim test.md`

3. Go to insert mode, and type `/usr/`, the completion window will show a list of completion candidate.

4. Press `Ctrl-E` to try to close the completion menu.

#### Actual behavior

THe completeion menu won't close. The comand line become `=` and wait for user input? Pressing `Ctrl-e` has no effect at all. If we press `ESC` then, the text becomes a weird `/usr/luaeval('require"compe"._close()')`, and we are in normal mode.

#### Expected behavior

Pressing `Ctrl-e` will close the completion window.

+ nvim version: NVIM v0.6.0-dev+8-g75f758b99
+ compe version: latest master (commit 964ba4a)

**Comment by hrsh7th** [comment]
Could you test with the following mapping? (Why don't you use README.md's codes?)

```
  vim.o.completeopt = "menuone,noselect"
  -- nvim-compe mappings
  vim.api.nvim_set_keymap('i', '<C-Space>', 'compe#complete()', {expr = true, noremap = true})
  vim.api.nvim_set_keymap('i', '<CR>', "compe#confirm('<CR>')", {expr = true, noremap = true})
  vim.api.nvim_set_keymap('i', '<C-e>', "compe#close('<C-e>')", {expr = true, noremap = true})
  vim.api.nvim_set_keymap('i', '<C-f>', "compe#scroll({'delta': +4})", {expr = true, noremap = true})
  vim.api.nvim_set_keymap('i', '<C-d>', "compe#scroll({'delta': -4})", {expr = true, noremap = true})
EOF
```

**Comment by jdhao** [comment]
Thanks, it works. My bad, I am not familiar with the nvim lua interface. I forget to add the `noremap=true` option.

**Comment by jdhao** [comment]
@hrsh7th  I think it is a good idea to add the above lua command to the documentation so that people do not make the same mistake like me.
