### ISSUE TITLE
How to disable LSP snippet?

### ISSUE THREAD

**Issue by uga-rosa** [hrsh7th/nvim-compe#461]
How can I show snippets defined by me, but not those defined by LSP (sumneko_lua)?
Also, is it possible to change the priority of the source?

**Comment by gegoune** [comment]
You might be able to override capabilities sent to sumneko with lspconfig; disable snippet capability. Since it is not enabled by default it must be enabled indoor config.

**Comment by uga-rosa** [comment]
Thx.
I was able to disable it by specifying the following option.
```lua
require"lspconfig".sumneko_lua.setup {
  ~
  settings = {
    Lua = {
      ~
      completion = {
        keywordSnippet = "Disable"
      }
    }
  }
}
```
And, I could specify the priority of source in the following way.
```lua
require'compe'.setup {
  ~
  source = {
    path = true;
    buffer = true;
    nvim_lsp = true;
    nvim_lua = true;
    luasnip = {priority = 10000};
    zsh = true;
  };
}
```
