### ISSUE TITLE
Animated cursor jumps to cmdline

### ISSUE THREAD

**Issue by Shatur** [hrsh7th/nvim-compe#462]
#### Checkhealth

Put result of `:checkhealth compe`.

```
health#compe#check
========================================================================
## compe:snippet
  - OK: snippet engine detected.

## compe:mapping
  - INFO: `compe#complete` is not mapped
  - INFO: `compe#confirm` is not mapped
  - OK: `compe#close` is mapped: (`i  <C-E>       * compe#close("<C-E>")`)
  - INFO: `compe#scroll` is not mapped
```

#### Describe the bug

I use animated cursor feature in [Neovide](https://github.com/Kethku/neovide#animated-cursor). After 4365453208d646276b28d66a6498e6f85b014b93 my cursors animates jumping to the command line and back to the position in insert mode. It looks like you are using `:` to execute a command somewhere that triggers `CmdlineEnter`.

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. Open Neovide
2. Go to insert mode
3. Press `<CR>` multiply times

#### Actual behavior

Cursors play cmdline jumping animation.

#### Expected behavior

The cursor does not animate.

**Comment by hrsh7th** [comment]
Thank you for your report.

Unfortunately, It's reproduced so reverted it...

**Comment by Shatur** [comment]
@hrsh7th, thanks, the issue was fixed!
