### ISSUE TITLE
Flickering when completion from Ultisnips is enabled.

### ISSUE THREAD

**Issue by moshiur-raj** [hrsh7th/nvim-compe#464]
#### Checkhealth

Put result of `:checkhealth compe`.

```
health#compe#check
========================================================================
## compe:snippet
  - OK: snippet engine detected.

## compe:mapping
  - INFO: `compe#complete` is not mapped
  - OK: `compe#confirm` is mapped: (`i  <CR>          (complete_info()["selected"] != "-1") ? compe#confirm({'keys': "\<Plug>(ultisnips_expand)", 'mode': ''}) : "\<Plug>(PearTreeExpand)"`)
  - OK: `compe#close` is mapped: (`i  <C-Y>       * compe#close('<C-Y>')`)
  - INFO: `compe#scroll` is not mapped

```

#### Describe the bug
The satusline flickers in insert mode when completion from ultisnips is enabled. I am using vim-airline.

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. enable ultisnips as a completion source.
2. open an empty buffer (buffer with no filetype seems to produce most flicker)
3. type something in insert mode

#### Actual behavior
The statusline flickers.

#### Expected behavior
The statusline should not flicker.

#### Screenshots (optional)

https://user-images.githubusercontent.com/36466700/125158766-1003e700-e195-11eb-98b3-fecd3928396f.mp4

**Comment by hrsh7th** [comment]
@moshiur-raj Could you test with latest master? (I reverted the cause of flicker.)

**Comment by moshiur-raj** [comment]
@hrsh7th It still flickers.

**Comment by hrsh7th** [comment]
@moshiur-raj Could you provide your dotfiles?
The screencast seems to not use minimal config for me.

**Comment by moshiur-raj** [comment]
@hrsh7th  https://github.com/moshiur-raj/dotfiles/blob/main/.config/nvim/init.vim

**Comment by moshiur-raj** [comment]
Tried disabling other plugins and settings. It's still flickering.

**Comment by hrsh7th** [comment]
Hm... it seems to similar to https://github.com/hrsh7th/nvim-compe/issues/47

**Comment by hrsh7th** [comment]
reproduced.

**Comment by moshiur-raj** [comment]
Thanks.
