### ISSUE TITLE
Intellectual source priority

### ISSUE THREAD

**Issue by timsofteng** [hrsh7th/nvim-compe#465]
Hello. 
Thanks for awesome plugin.
I've noticed that current source priority is not as good as it can be.
E.g. I have LSP servers completion source and vsnip.
When I type `fu` I expect to get snippet for function but I get long list of lsp-completion first and snippet in the bottom.
Can we improve it somehow?
Maybe intellectual prority. Or something like self-learning completion which will save source which user chosed for specific letters combination and sort source list according to this next time.
I don't know. Just thoughts.
Main idea is improving sources priority.

**Comment by Shougo** [comment]
You can change the source priority manually.

**Comment by timsofteng** [comment]
> You can change the source priority manually.

I've tried but it doesn't work.
May you share example of config with priority?

**Comment by hrsh7th** [comment]
The source priority can be customizable via the following settings.

```lua
require'compe'.setup {
  ...
  sources = {
    vsnip = { priority = 100 },
    nvim_lsp = { priority = 99 },
  }
}
```

I'm implementing new completion plugin (or v3 of compe).
It will have a way to customize sort behavior by user-function but current compe can't it. sorry.

**Comment by timsofteng** [comment]
@hrsh7th thanks!
Priority works.
May you tell more about new competition plugin and source sort engine there?

**Comment by hrsh7th** [comment]
I'm developing it in here.
https://github.com/hrsh7th/nvim-cmp/pull/1

**Comment by timsofteng** [comment]
> I'm developing it in here.
> [hrsh7th/nvim-cmp#1](https://github.com/hrsh7th/nvim-cmp/pull/1)

Awesome!
