### ISSUE TITLE
Attempt to call field `stylize_markdown` (a nil value)

### ISSUE THREAD

**Issue by marcushwz** [hrsh7th/nvim-compe#468]
#### Checkhealth

Put result of `:checkhealth compe`.

```
health#compe#check
========================================================================
## compe:snippet
  - OK: snippet engine detected.

## compe:mapping
  - OK: `compe#complete` is mapped: (`i  <C-Space>   * compe#complete()`)
  - OK: `compe#confirm` is mapped: (`i  <CR>        * compe#confirm(lexima#expand('<CR>', 'i'))`)
  - OK: `compe#close` is mapped: (`i  <C-E>       * compe#close('<C-E>')`)
  - OK: `compe#scroll` is mapped: (`i  <C-D>       * compe#scroll({ 'delta': -4 })`)
```

#### Describe the bug
- I have just upgrade compe, and when I am trying to cycle through the completion list, I am seeing this error message
```
Attempt to call field `stylize_markdown` (a nil value)
```

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. Start typing anything that will return a list of completion items such as snippet or lsp
2. Cycle through the items and the error message will show up.

#### Actual behavior
- Cycling through the completion list items triggered error message

#### Expected behavior
- Cycling through the completion list should not trigger error message

#### Screenshots (optional)

![image](https://user-images.githubusercontent.com/40255418/125240294-82eb9a00-e31c-11eb-9a6e-90cb3fcdf210.png)

**Comment by hrsh7th** [comment]
@marcushwz Please update your neovim to stable.

**Comment by marcushwz** [comment]
Hi @hrsh7th, thank you so much it works now after the update.
