### ISSUE TITLE
always in ComplMode?

### ISSUE THREAD

**Issue by smartding** [hrsh7th/nvim-compe#47]
I'm in this `ComplMode` mode as soon as I type something in insert mode, even in markdown files where I have no lsp server configured. 

Does this mean I'm always in the middle of auto completion? I thought auto completion should be trigger by some trigger character.

Below is my config of nvim-compe:
```lua
compe.setup = function()

  -- vim settings
  vim.api.nvim_set_option('completeopt', 'menuone,noinsert,noselect')
  vim.cmd [[set shortmess+=c]]

  -- compe settings
  vim.g.compe_enabled = true
  vim.g.compe_min_length = 1
  -- there's flickering with `compe_auto_preselect = true`, ref issue: #32
  vim.g.compe_auto_preselect = false
  vim.g.compe_source_timeout = 200
  vim.g.compe_incomplete_delay = 400

  -- enable path completion
  vim.cmd [[call compe#source#vim_bridge#register('path',  compe_path#source#create())]]

  -- enable vsnip completion
  vim.cmd [[call compe#source#vim_bridge#register('vsnip', compe_vsnip#source#create())]]
end

```

**Comment by hrsh7th** [comment]
What is your using nvim-compe's branch?

Currently master is not supports `compe.setup` method.

And I want to look your all configs.

**Comment by smartding** [comment]
> What is your using nvim-compe's branch?
> 
> Currently master is not supports `compe.setup` method.
> 
> And I want to look your all configs.

I'm using latest master, `compe.setup` is just a function I created, I call this function in init.lua.

and here's all my config:
```lua

local compe = {}

check_backspace = function()
  local col = vim.fn.col('.') - 1
  if col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') then
    return true
  else
    return false
  end
end

compe.setup = function()

  -- vim settings
  vim.api.nvim_set_option('completeopt', 'menuone,noinsert,noselect')
  vim.cmd [[set shortmess+=c]]

  -- compe settings
  vim.g.compe_enabled = true
  vim.g.compe_min_length = 1
  -- there's flickering with `compe_auto_preselect = true`, ref issue: #32
  vim.g.compe_auto_preselect = false
  vim.g.compe_source_timeout = 200
  vim.g.compe_incomplete_delay = 400

  -- key maps for selecting completion candidate
  vim.api.nvim_set_keymap(
    'i', '<Tab>',
    'pumvisible() ? "<C-n>" : v:lua.check_backspace() ? "<Tab>" : "<C-r>=compe#complete()<CR>"',
    { noremap=true, expr=true, silent=true }
  )

  vim.api.nvim_set_keymap(
    'i', '<S-Tab>',
    'pumvisible() ? "<C-p>" : "<S-Tab>"',
    { noremap=true, expr=true, silent=true }
  )

  -- key map for confirming completion
  vim.api.nvim_set_keymap(
    'i', '<CR>',
    [[compe#confirm('<Plug>delimitMateCR')]],
    { noremap=false, expr=true, silent=true }
  )

  -- key maps for jumping among placeholders in snippet expansion
  vim.api.nvim_set_keymap(
    'i', '<C-j>',
    'vsnip#jumpable(1) ? "<Plug>(vsnip-jump-next)" : "<C-j>"',
    { noremap=false, expr=true, silent=true }
  )
  vim.api.nvim_set_keymap(
    's', '<C-j>',
    'vsnip#jumpable(1) ? "<Plug>(vsnip-jump-next)" : "<C-j>"',
    { noremap=false, expr=true, silent=true }
  )
  vim.api.nvim_set_keymap(
    'i', '<C-k>',
    'vsnip#jumpable(-1) ? "<Plug>(vsnip-jump-prev)" : "<C-k>"',
    { noremap=false, expr=true, silent=true }
  )
  vim.api.nvim_set_keymap(
    's', '<C-k>',
    'vsnip#jumpable(-1) ? "<Plug>(vsnip-jump-prev)" : "<C-k>"',
    { noremap=false, expr=true, silent=true }
  )

  -- enable path completion
  vim.cmd [[call compe#source#vim_bridge#register('path',  compe_path#source#create())]]

  -- enable vsnip completion
  vim.cmd [[call compe#source#vim_bridge#register('vsnip', compe_vsnip#source#create())]]
end

return compe
```
In my init.lua, I will call `require('plugins.compe').setup()`

**Comment by smartding** [comment]
I looked a bit closer, every time I type a letter, neovim goes back to insert mode for several millisecond, then immediately goes back to ComplMode

**Comment by hrsh7th** [comment]
I tried to reproduce with your provided vimrc but I can't...

Hm... What is `ComplMode` mean?

**Comment by smartding** [comment]
> I tried to reproduce with your provided vimrc but I can't...
> 
> Hm... What is `ComplMode` mean?

`ComplMode` is a term used by my status line plugin: https://github.com/tjdevries/express_line.nvim.
Not really sure what it means, it normally appears when I'm in the middle of an auto completion.

**Comment by smartding** [comment]
> I tried to reproduce with your provided vimrc but I can't...
> 
> Hm... What is `ComplMode` mean?

I checked the source code of express_line.nvim, `ComplMode` represents the result `ic` returned by `vim.api.nvim_get_mode().mode`.
So is it normal I'm always in this `ic` mode when typing? Or is it a bug?

**Comment by hrsh7th** [comment]
Ah, reproduced with express_line.

It's wierd...
It is not reprodece withe new version. Please wait it.

**Comment by hrsh7th** [comment]
It should be fixed on latest master.

**Comment by smartding** [comment]
> It should be fixed on latest master.

yes, it's fixed, thanks
