### ISSUE TITLE
Inline suggestiong like fish shell

### ISSUE THREAD

**Issue by IndianBoy42** [hrsh7th/nvim-compe#472]
#### Is your feature request related to a problem? Please describe.

Not a problem just a suggestion based on a autocomplete visual style I like from fish shell

#### Describe the solution you'd like

Fish shell implements a kind of 'inline' suggestions, wherein the first completion is showed as dull text after the cursor, the user can hit <TAB> to get that completion, and then hit it again to get the full list.

I think something similar to the first part could be implemented using virtual text from neovim. Plus some configuration and keymaps to choose when to expand the full completion list, when to accept the first suggestion, when to cycle completion in virtual without opening the completion list, etc

#### Describe alternatives you've considered

The current completion popup window works fine, and should be the default for parity with other IDE, but this behaviour could be a more sleek and less visually disruptive way of presenting autocompletions for some people

#### Additional context

An example from the fish shell website
![image](https://user-images.githubusercontent.com/5981889/125408709-c19d5500-e3ed-11eb-92f7-6d73abee9fa8.png)

**Comment by hrsh7th** [comment]
It's interesting.

I have some random questions about it.

1. should it work if the cursor on the middle of the line?
2. should it work with completion pum or exclusive?
3. how to confirm the suggestion? (CR or Tab or both? some cases it will be annoying)

**Comment by IndianBoy42** [comment]
1. I think yes, although then the question is can/should we push the remaining text to the side or overlap. The former feels better to me

2. I think it can be with both or exclusive. An option could be the pum only comes up when you ask for it but the inline hint is immediately available

3. I guess it would be configurable but either TAB, <right> or <L> feel like reasonable keys. Fish uses <right>, vscode uses tab

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by hrsh7th** [comment]
I will investigate what VSCode does about it. I think the GitHub Copilot is a good reference implementation.

**Comment by hrsh7th** [comment]
VSCode has `GhostText` feature. It seems to different feature than completion.

**Comment by FOSSilizedDaemon** [comment]
I would also love this.

**Comment by Shougo** [comment]
The feature is already implemented in nvim-cmp.
So it should be closed.

**Comment by IndianBoy42** [comment]
Where can I find it in documentation?

**Comment by hrsh7th** [comment]
@IndianBoy42 You can use https://github.com/hrsh7th/nvim-cmp#experimentalghost_text-type-boolean
