### ISSUE TITLE
Regression 8024ea3b to 5640b9b5: completion item also inserts `?`

### ISSUE THREAD

**Issue by marcelbeumer** [hrsh7th/nvim-compe#476]
I'm using compe with a TypeScript codebase. Since 5640b9b50ee51a3df9212857a929ddb6677ff723 completion items also insert the `?` optional token, which it shouldn't.

Before (good, 8024ea3b44db0e90b1048dfbf14cfb97439dd9c0)
<img width="414" alt="Screen Shot 2021-07-13 at 23 02 56" src="https://user-images.githubusercontent.com/111366/125524893-409b0410-bed3-4282-8a88-9a4d8ff9ee9b.png">

After (not good, 5640b9b50ee51a3df9212857a929ddb6677ff723):
<img width="471" alt="Screen Shot 2021-07-13 at 23 02 09" src="https://user-images.githubusercontent.com/111366/125524926-c1b9bff4-b426-4b9f-bb8b-bdfb101869fa.png">

**Comment by hrsh7th** [comment]
Sorry for annoying. It was a my rough work...

**Comment by marcelbeumer** [comment]
No worries, very grateful for your work on nvim-compe!
