### ISSUE TITLE
CSS completion no longer appearing from LSP source (regression?)

### ISSUE THREAD

**Issue by benfrain** [hrsh7th/nvim-compe#480]
#### Checkhealth

Put result of `:checkhealth compe`.

```
health#compe#check
========================================================================
## compe:snippet
  - INFO: snippet engine is not detected.

## compe:mapping
  - INFO: `compe#complete` is not mapped
  - INFO: `compe#confirm` is not mapped
  - INFO: `compe#close` is not mapped
  - INFO: `compe#scroll` is not mapped

```

#### Describe the bug
I recently ran an update on my plugins and I no longer see CSS completions from LSP in CSS files (I do see completions from buffer source).

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. ... Open a CSS  file
2. ... Start typing a property name such as `wid` that instantiates compe

#### Actual behavior
No completions from LSP appear in CSS/SCSS files

#### Expected behavior
Completion such as `width` would appear from LSP

#### Additional context (optional)
This was fine a week ago. Unsure if issue is with Compe or nvim-lspconfig

Other sources, such as TypeScript show LSP completions fine. LSP warnings also still show in CSS/SCSS files.

**Comment by hrsh7th** [comment]
I can't reproduce it.

Could you provide your config?

**Comment by hrsh7th** [comment]
```
  local capabilities = vim.lsp.protocol.make_client_capabilities()
  capabilities.textDocument.completion.completionItem.snippetSupport = true
  capabilities.textDocument.completion.completionItem.resolveSupport = {
    properties = {
      'documentation',
      'detail',
      'additionalTextEdits',
    }
  }
```

You should set the above configuration on your vimrc.

**Comment by benfrain** [comment]
Hi @hrsh7th thanks for taking a look. I added that but same issue. Here is my init.lua: https://gist.github.com/benfrain/97f2b91087121b2d4ba0dcc4202d252f

**Comment by hrsh7th** [comment]
The new cssls needs a snippetSupport capability. So you should modify your configuration as the following faq.

https://github.com/hrsh7th/nvim-compe#how-to-use-lsp-snippet

**Comment by benfrain** [comment]
Hi, I've just added:

```
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
capabilities.textDocument.completion.completionItem.resolveSupport = {
  properties = {
    "documentation",
    "detail",
    "additionalTextEdits"
  }
}

```

Into the init.lua. also added `'hrsh7th/vim-vsnip'` into my plugins list and installed but the problem remains???

**Comment by benfrain** [comment]
Thanks so much for your time @hrsh7th – all working sweet again now!
