### ISSUE TITLE
Option to disable fuzzy matching

### ISSUE THREAD

**Issue by drakari7** [hrsh7th/nvim-compe#481]
#### Is your feature request related to a problem? Please describe.
I use nvim-compe in combination with lsp_signature. When I make a function call and enter into brackets, I want compe to stop giving me suggestions. Because the pmenu is still visible, this fails to trigger lsp_signature. The pmenu is still visible because of fuzzy solutions provided by compe.
<img width="609" alt="image" src="https://user-images.githubusercontent.com/54357427/125882359-97bc3656-c5b0-4841-b458-8bc2ce36eac8.png">

#### Describe the solution you'd like
To get something like this
<img width="701" alt="image" src="https://user-images.githubusercontent.com/54357427/125882870-c363983a-f9d0-4759-a923-0b6312062929.png">

Multiple possibilities.
1. Option to disable fuzzy matching
2. Pmenu should not be triggered without typing atleast 1 letter. Eg.
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/54357427/125882614-5e11498b-a360-40bb-af95-79be3fb50d77.png">
Here pmenu is triggered even though I have not typed a single letter. This is hindering.

3. Pmenu closes upon using brackets and only gives autocomplete solutions when i type something inside the brackets again  

#### Describe alternatives you've considered
1. I thought the option 'min_length' meant the minimum length for autocomplete to be triggered so I set it to 1 but it did not help.
2. Typing some random characters after opening bracket and then backspacing works to trigger lsp_signature, but obviously this is a hassle.

**Comment by cultab** [comment]
This might be related to #436 since if the selection was confirmed upon you pressing '(', lsp_signature could kick in?

**Comment by drakari7** [comment]
Definitely related in the aspect of getting lsp_signature to work nicely with compe. I would still wish if it was possible to have the option to disable fuzzy matching.
