### ISSUE TITLE
Exact match is not preferred if it is also an exact prefix

### ISSUE THREAD

**Issue by flanggut** [hrsh7th/nvim-compe#482]
#### Description
When the query matches an exact entry from the list but also an exact prefix of an entry from the list, the main exact match is not always preferred.

Specifically I believe this is due to this line in matcher.lua
https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe/matcher.lua#L28
and the later sorting of the matches. This puts the exact label on every match, no matter if it is an exact match or an exact prefix match. Later on the items will be sorted only based on this label.

#### To Reproduce
Generate list of completions with exact and exact prefix matches.

#### Actual behavior
![CleanShot 2021-07-16 at 5 52 35](https://user-images.githubusercontent.com/2812612/125975971-4173bae4-b3a4-4dd8-bf45-c6acd267497c.png)

#### Expected behavior
Here I changed the line from 
```
      item.match.exact = input == item.original_abbr
```
to
```
      item.match.exact = input == item.original_word
```
![CleanShot 2021-07-16 at 5 53 12](https://user-images.githubusercontent.com/2812612/125975992-8df8ae60-ad0f-44a1-abae-a6d121203140.png)

**Comment by rhcher** [comment]
It seems that you can turn off it by setting nvim_lsp { sort = false } in compe config function.

**Comment by flanggut** [comment]
I'm not sure if this is a solution. Right now the sorting doesn't distinguish between the two cases that I described, so the final order is dependent on the input order. You can change the input order like you described and it just happens to work; but that is not guaranteed to work in all cases.
