### ISSUE TITLE
Tab to indent when no suggest

### ISSUE THREAD

**Issue by asmin-dev** [hrsh7th/nvim-compe#484]
when i press tab and there is no suggest i want it to change to indent but i get error like this
![Screenshot_2021-07-17-18-23-06-97_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/67496476/126034066-35e4e14e-2cf9-4ad9-8b41-ac14546c03e9.jpg)

**Comment by dhruvmanila** [comment]
That is happening because you don't have a snippet plugin installed. If you're not planning to use any snippet plugin, you can remove the relevant lines from the function. So, your `tab_complete` will be something like this and similar changes to be done for `s_tab_complete`:
```lua
_G.tab_complete = function()
  if vim.fn.pumvisible() == 1 then
    return t "<C-n>"
  elseif check_back_space() then
    return t "<Tab>"
  else
    return vim.fn['compe#complete']()
  end
end
```

**Comment by asmin-dev** [comment]
> That is happening because you don't have a snippet plugin installed. If you're not planning to use any snippet plugin, you can remove the relevant lines from the function. So, your `tab_complete` will be something like this and similar changes to be done for `s_tab_complete`:
> 
> ```lua
> _G.tab_complete = function()
>   if vim.fn.pumvisible() == 1 then
>     return t "<C-n>"
>   elseif check_back_space() then
>     return t "<Tab>"
>   else
>     return vim.fn['compe#complete']()
>   end
> end
> ```

Solve, Thanks
