### ISSUE TITLE
Dictionary Completion

### ISSUE THREAD

**Issue by henry-hsieh** [hrsh7th/nvim-compe#487]
#### Is your feature request related to a problem? Please describe.
No suitable completion type for program language keywords. Take C as example, when I type `con<Tab>`, I thought that the completion engine could give me `const` or `continue` in popup menu. Following are reasons why I feel infeasible.

- Buffer: you should open the keyword file alone with the file that you want to edit.
- Tags: let tag engine generate a tag file with all keywords. This might work, but not straight forward. 
- Spell: In #85, the spell is provided to complete dictionary. It calls `spellsuggest()` to complete the word. The function is used to correct the wording. The major problem is that it only suggests the words with (nearly) the same number of characters. Use previous example, `con<Tab>` results in `cone`, `Con`, `Conn`,  `coin`, `corn`, etc. It can't meet our expectation.
- Snippet extensions: using snippets could cover some keywords. For some language with more keywords, you should create different prefixes for them, which isn't efficient.

#### Describe the solution you'd like
As previous example, filter the dictionary files with providing prefix (prior to the cursor).

For simplified implementation, it could parse `vim.bo.dictionary`, `vim.o.dictionary` and get dictionary file lists. Then parse the contents and filter with prefix.
For advanced implementation, it could monitor the change of the `vim.bo.dictionary`, `vim.o.dictionary` and the file contents using `vim.loop.new_fs_event()`. In my opinion, runtime monitor isn't useful in this case.
#### Describe alternatives you've considered
I don't know whether neovim could intercept the contents of popup menu. If the answer is yes, maybe try to intercept the result of \<c-x\>\<c-k\> (ins-completion of dictionary).
#### Additional context
No.

**Comment by FOSSilizedDaemon** [comment]
I came here to ask the same thing, having the ability to get completions from my dictionary files would be amazing. I was using built-in vim completion the longest time mainly cause it made doing this so easy which is amazing for writing actual documents in neovim as well as writing scripts for long lists of IPs.
