### ISSUE TITLE
Completion list shows duplicates

### ISSUE THREAD

**Issue by insidewhy** [hrsh7th/nvim-compe#488]
#### Is your feature request related to a problem? Please describe.

See the following image:

![duplicates](https://user-images.githubusercontent.com/97685/126060443-0ca20551-6d62-4e25-99dc-c104be8916c5.png)

I am offered 6 completions for el that are all `Variable` and two that are `Constant`.

#### Describe the solution you'd like

I know in certain cases, you need to show the duplicates, i.e. if they correspond to different auto-import entries. In cases where there is no associated action, I wonder if the duplicates could be pruned?

**Comment by hrsh7th** [comment]
I guess you are using TypeScript or JavaScript, right?

It is not a problem because the same identifier can auto-import from different module.

And if it's actual problem, you should report to language server repo instead.

**Comment by insidewhy** [comment]
Ah yeah, as I wrote I'm aware of the auto-import case, but when there are no auto-imports it should be fine to discard the duplicates?
