### ISSUE TITLE
close function completion on open parenthesis 

### ISSUE THREAD

**Issue by gjeusel** [hrsh7th/nvim-compe#490]
#### Is your feature request related to a problem? Please describe.
I would like to automagically close the completion menu when opening a parenthesis, so I can then have completion for variable in signature.

#### Describe the solution you'd like

Current behaviour:
![image](https://user-images.githubusercontent.com/16243660/126288549-d3c04d71-b4eb-4584-b94e-79209d97c317.png)

Expected behaviour (obtained by quitting insert mode, and re-entering it after open parenthesis):
![image](https://user-images.githubusercontent.com/16243660/126288655-644c6eeb-53dd-4391-a0bb-30a6b9fccf6a.png)

#### Describe alternatives you've considered
I tried remaping the "(" in insert mode like follow:

```lua
-- Fix behaviour of completion not closing on (
_G.control_open_parenthesis_close_complete = function()
  if vim.fn.pumvisible() == 1 then
    vim.api.nvim_exec([[call compe#close()]], false)
    return t("(")
  else
    return t("(")
  end
end
vim.api.nvim_set_keymap("i", "(", "v:lua.control_open_parenthesis_close_complete()", mapopts)
```
#### Additional context
Not related to nvim-autopairs (I managed to reproduce when disabling it)

### Question
I have not found any info on it, is it doable ?

Without any success.

**Comment by wookayin** [comment]
Duplicate to which issue? I cannot find one. @gjeusel why was this closed?

**Comment by wookayin** [comment]
@gjeusel `compe#close()` is a function for imap expression -- it evaluates a *string* `\<C-e>\<C-r>=luaeval('require\"compe\"._close()')\<CR>`. 

Please https://github.com/hrsh7th/nvim-compe/issues/436#issuecomment-888286026 for another possible workaround similar to yours.
