### ISSUE TITLE
Selecting snippets with '\' at the beginning of the trigger word causes another extra '\' to be added.

### ISSUE THREAD

**Issue by moshiur-raj** [hrsh7th/nvim-compe#491]
#### Checkhealth

Put result of `:checkhealth compe`.

```
health#compe#check
========================================================================
## compe:snippet
  - OK: snippet engine detected.

## compe:mapping
  - INFO: `compe#complete` is not mapped
  - INFO: `compe#confirm` is not mapped
  - OK: `compe#close` is mapped: (`i  <C-Y>       * compe#close('<C-Y>')`)
  - INFO: `compe#scroll` is not mapped

```

#### Describe the bug
I use ultisnips for snippets. I don't want snippets to trigger everytime I type 'begin" in a latex document. So I have '\\begin' as the trigger. The problem is that when I select the completion compe adds another '\' at the beginning. I haven't checked the bug with other special characters. Only '\\' so far....

#### To Reproduce
1. Create an ultisnips snippet with '\\' at the beginning
2. Open a latex document.
3.  Select the snippet from the popup menu.

#### Actual behavior
Compe add an extra '\\' at the beginning.

#### Expected behavior
Compe should not add an extra '\\'.

#### Screenshots (optional)
![image](https://user-images.githubusercontent.com/36466700/126449707-5e6800ab-adf4-45f2-b9c1-c516b3000d3b.png)

Before selecting...
![image](https://user-images.githubusercontent.com/36466700/126451120-2a2faa60-8f8d-4261-9f43-041e86c48e90.png)

After selecting...

**Comment by taybart** [comment]
I think I am having a similar issue with LSP completions
Setup
![image](https://user-images.githubusercontent.com/3513897/127058113-a7da5ab3-1a72-4113-85a5-ba1cea828a66.png)
Completed
![image](https://user-images.githubusercontent.com/3513897/127058159-904c3738-3b40-475c-b4d6-e88e59660f41.png)
