### ISSUE TITLE
Bindings Using compe#scroll Do Not Work

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [hrsh7th/nvim-compe#494]
#### Checkhealth

Put result of `:checkhealth compe`.

```
I am working in a VM and can't post this, but everything shows OK.
```

#### Describe the bug
I am having an issue where any binding that uses `compe#scroll({ 'delta': +4 })` or any variant of that does not work. No error is provided, the binding simply  does not have the expected behavoir.

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

A minimal configuration needed to reproduce this would be:

1. git submodule add https://github.com/hrsh7th/nvim-compe.git (in the proper directory)
2. [This configuration as init.lua](https://pastebin.com/nD1RnYbP).

#### Actual behavior
When pressing `control +j/k` I `c-j` will cause compe to enter the current completion option, `c-k` causes compe to enter `<BS>`.

#### Expected behavior
When pressing `control +j/k` I expect compe to scroll through the completion suggestions accordingly.

#### Additional context (optional)
I have tested this on the following terminals (you never know):
- st
- kitty
- xfce4-terminal
- gnome-terminal
- alacrity

My full configuration can be seen [here](https://gitlab.com/FOSSilized_Daemon/dotfiles/-/tree/master/src/home/.config/nvim) for context (note: I use git submodule to manage plugins **NOT** packer).

**Comment by hrsh7th** [comment]
Your configuration seems to look doesn't wrong to me.

Could you provide `:imap <C-k>` results?

**Comment by FOSSilizedDaemon** [comment]
> Your configuration seems to look doesn't wrong to me.
> 
> Could you provide `:imap <C-k>` results?

Resulsts:
```
i <C-K>        * compe#scroll({ 'delta': +4 })
```

**Comment by hrsh7th** [comment]
Hm... It's very weird... I can't understand the cause.
