### ISSUE TITLE
[feature] hope compe#confirm() can select the first selection, like vscode, when we set `menuone, noselect`.

### ISSUE THREAD

**Issue by MaiLunJiye** [hrsh7th/nvim-compe#496]
I love this plugin, thanks for your work

#### Is your feature request related to a problem? Please describe.

I config the keymap as following

```lua
_G.tab_complete = function()
    if vim.fn.pumvisible() == 1 then
        return vim.fn['compe#confirm']()
    elseif vim.fn.call("vsnip#available", {1}) == 1 then
        return t "<Plug>(vsnip-expand-or-jump)"
    else
        return t "<Tab>"
    end
end

remap("i", "<Tab>", "v:lua.tab_complete()", {expr = true})
remap("s", "<Tab>", "v:lua.tab_complete()", {expr = true})
```

I hope it can use `<TAB>` to confirm and select the first one as well as vscode.
However,  after setting `set completeopt=menuone,noselect`,required by nvim-compe,
I can't use `<TAB>` to confirm and select the first one.
I have to tap `<C-n>` or `<Down>` to select the first one in popup-menu and then tap `<TAB>` to confirm.
It might be ehanced.

#### Describe the solution you'd like
Maybe `compe#confirm()` can check whether select an item in popup-menu.
if not, select the first one and confirm. if yes, confirm.

#### Additional context

vscode behavior

type something, popup-menu open, but `noselect`.
<img width="288" alt="截屏2021-07-24 下午10 07 06" src="https://user-images.githubusercontent.com/20548127/126871046-73add999-abd3-44f8-b13b-2ba20f83f52e.png">

tap `<TAB>`, confirm  and select the first one.

<img width="238" alt="截屏2021-07-24 下午10 11 13" src="https://user-images.githubusercontent.com/20548127/126871110-150e070d-bbaa-43d9-b97b-20513e9d1289.png">

**Comment by hrsh7th** [comment]
You can use `compe#confirm({ 'keys': '<CR>', 'select': v:true })`. See https://github.com/hrsh7th/nvim-compe#how-to-automatically-select-the-first-match
