### ISSUE TITLE
Docs: create new source

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#5]
Some documentation or wiki entries on creating new source it needed

For example, I use @liquidz 's awesome plugin for clojure development 'vim-iced' and it has omnifunc. Here is omnifunc is supported by default in nvim-compe, or a source needed be created. 

Also I see he create custom source for  [coc source](https://github.com/liquidz/vim-iced-coc-source) and [asyncomplete](https://github.com/liquidz/vim-iced-asyncomplete). How can I create and port these sources using nvim-compe. 

This something the wiki should answer

**Comment by hrsh7th** [comment]
OK.
I will add the documentation for it.

**Comment by tami5** [comment]
Hey @hrsh7th any updates on this? thanks

**Comment by hrsh7th** [comment]
Sorry for delay.

I've created wiki page. Could you see it?

**Comment by tami5** [comment]
@hrsh7th That's okay, I'm checking it out right now

**Comment by tami5** [comment]
@hrsh7th i think the example code has an issue, I copied it to test.vim and source it, but I got all kind of errors. I also tried to add it to plugin/ dir but same erros

```viml
Error detected while processing /home/tami/repos/nvim/plugin/month.vim:
line    1:
E700: Unknown function: s:get_metadata
E700: Unknown function: s:datermine
E700: Unknown function: s:complete
Error detected while processing function compe#source#vim_bridge#register:
line    4:
E5108: Error executing lua Vim(return):E15: Invalid expression: s:sources[a:id].get_metadata()

```
It would be awesome if both lua and vim examples are operational as it would help users quickly test things out in there env.
Could you please fix the code examples to a working ones. I hope I'm not asking a lot. Thanks

**Comment by hrsh7th** [comment]
Sorry. I've updated it.

I'm happy if you update the wiki entry.

**Comment by tami5** [comment]
Nice I will check it out, @hrsh7th I don't think I can edit the wiki, is it open for anyone to edit? or must I clone it? check permissions

**Comment by tami5** [comment]
Yes, I tested the viml version and it worked right a way. 
How about after you give me permissions to edit the wiki, I add general Q/A under "creating new source" section and you would later answer them?

**Comment by hrsh7th** [comment]
I've updated wiki permission.,Thak you!

**Comment by tami5** [comment]
@hrsh7th check it out, I added some todos and a question, also reword introduction, hope you like it

**Comment by hrsh7th** [comment]
Thank you.
Feel free to update it.

**Comment by hrsh7th** [comment]
I will check the todos and add explain for it.
