### ISSUE TITLE
Doesn't select the first item in the completion menu when noselect is false

### ISSUE THREAD

**Issue by s1n7ax** [hrsh7th/nvim-compe#503]
#### Checkhealth
```
## compe:snippet
  - INFO: snippet engine is not detected.

## compe:mapping
  - INFO: `compe#complete` is not mapped
  - OK: `compe#confirm` is mapped: (`i  <SNR>34_AutoPairsOldCRWrapper73 &@compe#confirm('<CR>')`)
  - INFO: `compe#close` is not mapped
  - OK: `compe#scroll` is mapped: (`i  <C-F>       * compe#scroll({ 'delta': +4 })`)
```
NOTE: even though Checkhealth shows `compe#complete` is not mapped, `:imap <c-space>` that it is mapped already.

#### Describe the bug
First item of the completion menu is not selected automatically even though  `completeopt` is `"menuone,noinsert"`
There was a similar issue in [coc.nvim](https://github.com/neoclide/coc.nvim/issues/124)
#### To Reproduce
* Add the default [config available in README](https://github.com/hrsh7th/nvim-compe#lua-config)
* Add [keybinds in README](https://github.com/hrsh7th/nvim-compe#mappings)

#### Actual behavior
In the completion menu, the first item is not selected

![image](https://user-images.githubusercontent.com/18459807/127179906-3ee08038-df6c-4751-8118-5d1e10c2e5b8.png)

#### Expected behavior
When the `noselect` is false, the first item in the completion menu should be selected, BUT without changing the actual text in the buffer. So in below screenshot, the buffer text should be `requir` not `require` after the first item is selected

![image](https://user-images.githubusercontent.com/18459807/127180021-f7f3a349-9638-4d18-8e40-aa12a0e33bc7.png)

**Comment by hrsh7th** [comment]
You can use `preselect = 'always'`. almost completion engine override completeopt. it os not an issue.

**Comment by iotaiota** [comment]
> You can use `preselect = 'always'`. almost completion engine override completeopt. it is not an issue.

I had same issue. This solved it. Thanks!

**Comment by hrsh7th** [comment]
I think it can be closed.
