### ISSUE TITLE
Ultisnippets completion doesn't like "-" character in filename

### ISSUE THREAD

**Issue by joshzcold** [hrsh7th/nvim-compe#507]
#### Checkhealth

Put result of `:checkhealth compe`.

```
health#compe#check
========================================================================
## compe:snippet
  - OK: snippet engine detected.

## compe:mapping
  - OK: `compe#complete` is mapped: (`i  <C-Space>   * compe#complete()`)
  - OK: `compe#confirm` is mapped: (`i  <CR>        * compe#confirm(luaeval("require 'nvim-autopairs'.autopairs_cr()"))`)
  - OK: `compe#close` is mapped: (`i  <C-E>       * compe#close('<C-E>')`)
  - OK: `compe#scroll` is mapped: (`i  <C-D>       * compe#scroll({ 'delta': -4 })`)

```

#### Describe the bug
Not sure if this impacts other snippet completion or is just for ultisnippets. 
snippet files like `javascript-jasmine.js` do not appear in compe
snippet files like `javascript_jasmine.js` DO appear in compe

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-compe'
Plug "SirVer/ultisnips"   " custom code snippets manager
Plug "honza/vim-snippets" " lots of pre-made snippets using convention `filename-extra-information.ext`
call plug#end()
PlugInstall | quit


lua << EOF
    require("compe").setup {
        source = {
            ultisnippets = true
        }
    }
EOF

```
1. check snippets in `~/.config/nvim/Ultisnippets`
2. try to complete a snippet that uses `filename-descript.ext` format
3. rename the snippet file using `_` 
4. verify the snippet now works

#### Actual behavior
compe treats `language-description.snippet` as a separate filename as `language.snippet`

#### Expected behavior
`language-description.snippet` should be added to the snippets of `language.snippet`

**Comment by hrsh7th** [comment]
Sorry. I can't understand the problem. Could you explain it more clearly?

**Comment by joshzcold** [comment]
from https://github.com/honza/vim-snippets/tree/master/UltiSnips
snippet files use both 
`X-Y.snippets`
and
`X_Y.snippets`

but only `X_Y.snippets` appear in compe when both should be supported.

**Comment by joshzcold** [comment]
Its probably a regex tweak right here 
https://github.com/hrsh7th/nvim-compe/blob/8ed6999e005015251b6b05cb5c0bfe857785b1d4/lua/compe_ultisnips/init.lua#L6
