### ISSUE TITLE
Pyright auto-import can't be distinguished from completion

### ISSUE THREAD

**Issue by uninhm** [hrsh7th/nvim-compe#509]
#### Is your feature request related to a problem? Please describe.
I think the title is very clear

#### Describe the solution you'd like
Show a message "auto-import" like CoC

**Comment by wookayin** [comment]
I look forward to this getting improved.

**Comment by Shougo** [comment]
nvim-cmp doesn't support the feature?
If so, it should be requested in nvim-cmp instead.
