### ISSUE TITLE
Ultisnips - When documentation is true and shown, you cannot jump to the next snippet placeholder

### ISSUE THREAD

**Issue by baldore** [hrsh7th/nvim-compe#510]
#### Checkhealth
```
health#compe#check
========================================================================
## compe:snippet
  - OK: snippet engine detected.

## compe:mapping
  - INFO: `compe#complete` is not mapped
  - OK: `compe#confirm` is mapped: (`i  <CR>        * compe#confirm('<CR>')`)
  - INFO: `compe#close` is not mapped
  - INFO: `compe#scroll` is not mapped
```

#### Describe the bug
The bug happens when you select one autocomplete option and the documentation tooltip appears. This disables completely current snippet placeholders, making it unusable.

I suspect the problem happens due to the new buffer created for the documentation.

##### vimrc
```vimrc
call plug#begin('~/.config/nvim/plugged')

Plug 'SirVer/ultisnips'
Plug 'hrsh7th/nvim-compe'

call plug#end()

set completeopt=menuone,noselect

let g:compe = {}
let g:compe.enabled = v:true
let g:compe.autocomplete = v:true
let g:compe.min_length = 1
let g:compe.preselect = v:false

let g:compe.source = {}
let g:compe.source.path = v:true
let g:compe.source.buffer = v:true
let g:compe.source.ultisnips = v:true
```

1. Expand an Ultisnips snippet with multiple placeholders.
2. Write something to show the `autocomplete` options and select one option that displays `documentation`.

**Note**: It works correctly when documentation is false.

```vimrc
let g:compe.documentation = v:false
```

#### Actual behavior
You're unable to jump to the next placeholder, making Ultisnips basically useless.

#### Expected behavior
It should jump correctly between placeholders.

##### Documentation enabled
![documentation-on](https://user-images.githubusercontent.com/3131037/128533952-dd5e096c-b89c-43bd-a086-1c971290e4cb.gif)

##### Documentation disabled
![documentation-off](https://user-images.githubusercontent.com/3131037/128536132-9bd95b54-48fb-45c9-a369-d083eebee0c9.gif)

**Comment by hrsh7th** [comment]
Hm... I can't reproduce it.


https://user-images.githubusercontent.com/629908/128537094-6b375dd6-268d-4632-a48d-9ddf62216819.mp4

**Comment by baldore** [comment]
It happens after the snippet is expanded. For example, when you are inside `href="|"`, select an autocomplete option that shows documentation (like another snippet or lsp function).

**Comment by baldore** [comment]
Also... I'm starting to think that this could be a Ultisnips bug. After disabling the documentation, I have another plugin that shows a popup and breaks the placeholder jump too. Still, please take a look. I would like to get your opinion about it. Thanks.

**Comment by hrsh7th** [comment]
Probably, I found the reason. It caused by `Ultisnips#ExpandSnippet`. If current activated snippet can jumpable, the function would not effect anymore.

**Comment by baldore** [comment]
I think we can close this... Not a simple solution for now it seems. I found this one on Ultisnips https://github.com/SirVer/ultisnips/issues/1188
