### ISSUE TITLE
Announcement: nvim-compe is now deprecated.

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#517]
I'm developing new completion plugin to solve some of the design mistakes (the mistakes was described in [here](https://github.com/hrsh7th/nvim-cmp/issues/2).

Currently, the new plugin can use as *testing*. (But I will apply breaking change without any announcement).

If someone interest it, please feel free to use it and report the issue to the new repo.

https://github.com/hrsh7th/nvim-cmp

**Comment by Shougo** [comment]
I think this issue should be pinned.

**Comment by hrsh7th** [comment]
Thank you! I did it.

**Comment by Iron-E** [comment]
As someone who uses this plugin myself and recommends it to others, I've always found it to be highly dependable. I'm not necessarily big on the idea of [deprecating](https://github.com/hrsh7th/nvim-cmp/issues/2) the entire plugin if instead certain features could be deprecated instead (like, for example, the VimL configuration which you mentioned). 

If that's not possible, what I have noticed about `cmp` was that I think setting Neovim options through a plugin's `setup` function seems unnecessary. It could just be `vim.opt.completeopt = {'menu', 'menuone', 'noselect'}` on the line above `cmp.setup {}` in the README.

**Comment by hrsh7th** [comment]
No. The `completeopt` option is controlled by nvim-cmp. So it should be configuration option, I think.
The option is overwrote and restore by nvim-cmp itself. https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/menu.lua#L166

**Comment by Iron-E** [comment]
That's what I mean, I should have been more specific. I'm not sure the plugin should automatically overwrite settings— in the past plugins have done to my settings and it can be a little dubious to find out which is doing it 😅

Perhaps an error would be good, if the settings aren't what at least what `cmp` expects? That way users at least know and make the change themselves.

**Comment by hrsh7th** [comment]
In general, completion plugin manages `completeopt` setting... So I think it is not a strange way.

**Comment by Iron-E** [comment]
`completion-nvim` doesn't, `compe` issues a warning rather than overriding, and `coc.nvim` doesn't either.

All the "major" completion plugins don't touch user settings and either issue warning or simply have a note in the README

I defer to you on these matters though, you have more experience writing these plugins.

**Comment by Shougo** [comment]
Hm.  `completion-nvim` does not change `completeopt`.
But it is not the perfect solution.  Please read the issue.

https://github.com/nvim-lua/completion-nvim/issues/235

The auto completion breaks `longest` behavior.

**Comment by Shougo** [comment]
I think the issue should not be closed.
