### ISSUE TITLE
Plugin not showing completions at all 

### ISSUE THREAD

**Issue by flosker** [hrsh7th/nvim-compe#518]
#### Checkhealth
https://gist.github.com/flosker/44e44351d5295db0d47775974a7eedf9

#### Describe the bug
Plugin not showing completions at all (First time setting up)

#### To Reproduce
init.lua - https://gist.github.com/flosker/8d97e37b077b005a153ee5c38c7ae4a4

#### Actual behavior
Completion menu not appearing for any completion type

#### Expected behavior
Plugin should work & show completions

**Comment by hrsh7th** [comment]
@flosker I've answered on reddit.

You should add `vim.opt.runtimepath = vim.opt.runtimepath + '~/.local/share/nvim/plugins/completion/after'` too.
