### ISSUE TITLE
Function documetation seperator line doesn't fit within the popup

### ISSUE THREAD

**Issue by flosker** [hrsh7th/nvim-compe#519]
#### Checkhealth
Everything is OK in checkhealth.

#### Describe the bug
See screenshots. The line separating `(method) Document.query...` in function documentation isn't fitting within popup.
It seems to only happen when documentation.max_width is smaller & some text needs to be **wrapped**.

The separator's width is the width of the **longest line** in the docs. It should instead be equal to max_width of a popup. 

#### To Reproduce
See screenshots & try to type those functions in a javascript file.
[Minimal config](https://gist.github.com/flosker/eb3a601655bc691b2ee72136b40b2687)

#### Actual behavior
Separator wraps & doesn't fit within popup window.

#### Expected behavior
Separator shouldn't wrap & fit within popup window. LSPSaga doesn't have this issue.

#### Screenshots (optional)
![Image 1](https://user-images.githubusercontent.com/86894799/128873621-0796f11f-419c-4cc8-b369-d7e9abab06b6.png)
![Image 2](https://user-images.githubusercontent.com/86894799/128873642-22a5ed72-1571-4670-8895-b21e74d30677.png)

#### Additional context (optional)
`nvim`- 0.5v.

**Comment by hrsh7th** [comment]
it should be fixed now.
