### ISSUE TITLE
Force preselect to be false

### ISSUE THREAD

**Issue by elianiva** [hrsh7th/nvim-compe#52]
I have a slight issue with nvim-compe when using it against gopls. I think the LSP is forcing nvim-compe to preselect the first match, the other sources doesn't have this issue. Is it possible to *force* it not to preselect the first item? Or is it have to be done in the lsp level? I can't find any lsp setting for gopls that can disable this behaviour. Here's a video to make it clearer..

https://streamable.com/9wtp5r

..and here's a minimal vimrc to reproduce. Thanks in advance!

```viml
call plug#begin("~/.local/share/nvim/plugged")
Plug 'neovim/nvim-lspconfig'
Plug 'hrsh7th/nvim-compe'
call plug#end()

lua << EOF
require"lspconfig".gopls.setup{
  root_dir = function() return vim.loop.cwd() end,
  settings = {
    gopls = {
      analyses = {
        unusedparams = true,
      },
      staticcheck = true,
      usePlaceholders = true,
    },
  }
}

local remap = vim.api.nvim_set_keymap

require'compe'.setup {
  enabled = true;
  debug = false;
  min_length = 2;
  auto_preselect = false;
  source_timeout = 200;
  incomplete_delay = 400;
  allow_prefix_unmatch = false;
  source = {
    path = true;
    buffer = true;
    vsnip = true;
    nvim_lsp = true;
  };
}

remap(
  'i', '<Tab>',
  'pumvisible() ? "<C-n>" : v:lua.Util.check_backspace() ? "<Tab>" : compe#confirm(lexima#expand("<LT>CR>", "i"))',
  { silent = true, noremap = true, expr = true }
)
EOF
```

**Comment by elianiva** [comment]
update: I think this is due to a bug on neovim side when using `complete()`. I don't know if this is the cause of this issue, but if it is then we'll just have to wait until it gets fixed.

![image](https://user-images.githubusercontent.com/51877647/102208143-9f982e80-3f01-11eb-8b4e-7bf7b3fb1529.png)

**Comment by hrsh7th** [comment]
The preselect is LSP's spec so nvim-compe will preselect it if the server returns it.
But your opinion is reasonable to me. I will add the option for it.

**Comment by hrsh7th** [comment]
Fixed https://github.com/hrsh7th/nvim-compe/commit/fd87cd6dcd0073bf168720cd3bc191154858b237

You can specify `preselect = 'disable'`
