### ISSUE TITLE
Can not get LSP Snippet working

### ISSUE THREAD

**Issue by SleepyCatOnTheBed** [hrsh7th/nvim-compe#524]
I have followed the FAQs sections, but still can't figure out how to let the nvim-compe work for lsp snippet.

Here is my lua file and checkhealth part:
![image](https://user-images.githubusercontent.com/71932200/129357606-50170766-7625-4b02-a760-4610cc70ec30.png)

![image](https://user-images.githubusercontent.com/71932200/129357471-cc9eca2e-f859-471f-9615-c7dd9285a69d.png)

I have installed snippets.nvim.

**Comment by hrsh7th** [comment]
You mist set `compe#confirm` mapping.
Please see the README.md.
