### ISSUE TITLE
problem with vim-rsi pluggin -- <C-e>

### ISSUE THREAD

**Issue by reverseila** [hrsh7th/nvim-compe#539]
This problem arises when I have the [vim-rsi](https://github.com/tpope/vim-rsi) plugin installed (through packer as a start package).
The problem is with the `<C-e>`. There are two cases:
1. If I am selecting a completion candidate, `<C-e>` deselects it, but the pop-up menu is still there.
2. If I am not selecting a completion menu, the pop-up menu doesn't go away with `<C-e>`.

**Comment by reverseila** [comment]
I believe this line creates this issue
```
inoremap <expr> <C-E> col('.')>strlen(getline('.'))<bar><bar>pumvisible()?"\<Lt>C-E>":"\<Lt>End>"
```
https://github.com/tpope/vim-rsi/blob/e181883a0932d9315cceb96b5fffb5e2ec67068e/plugin/rsi.vim#L27

One solution is to comment this line. However, is there  a way to change it so that it works with compe?

**Comment by abzrg** [comment]
I don't use compe anymore…
