### ISSUE TITLE
Auto-import doesn’t work with a bunch of LSPs

### ISSUE THREAD

**Issue by phaazon** [hrsh7th/nvim-compe#540]
#### Checkhealth

Put result of `:checkhealth compe`.

```
health#compe#check
========================================================================
## compe:snippet
  - OK: snippet engine detected.

## compe:mapping
  - OK: `compe#complete` is mapped: (`i  <C-Space>     compe#complete()`)
  - OK: `compe#confirm` is mapped: (`i  <CR>          compe#confirm('<CR>')`)
  - INFO: `compe#close` is not mapped
  - INFO: `compe#scroll` is not mapped


```

#### Describe the bug

Auto-imports doesn’t work with some LSPs (tried with `purescriptls` and `hls`). I figured it’s likely a bug in `nvim-compe` as it works with `rust-analyzer`.

#### To Reproduce

Steps to reproduce the behavior with the [minimal config](https://github.com/hrsh7th/nvim-compe/blob/master/misc/minimal.vim):

1. Open a Haskell or PureScript project.
2. Cry.

**Comment by hrsh7th** [comment]
nvim-compe does not support purescript-ls.

You can use [nvim-cmp](https://github.com/hrsh7th/nvim-cmp) successor of nvim-compe.
