### ISSUE TITLE
Buffer Source Completion: diacritic characters are ignored

### ISSUE THREAD

**Issue by xeluxee** [hrsh7th/nvim-compe#541]
#### Is your feature request related to a problem? Please describe.
Diacritics characters (such as `à`, `ü`, `ô`) are ignored by buffer completion source. That problem is evident especially when editing (for example) tex files, where buffer words completion is really useful.
These characters are considered word separators, like spaces.

![diacritic1](https://user-images.githubusercontent.com/88047141/130515234-03f1a9a0-ab9a-4781-a6df-2d114148d11d.png)
![diacritic2](https://user-images.githubusercontent.com/88047141/130515305-6d9c630f-fe64-4216-8c0f-5143ca07718b.png)

#### Describe the solution you'd like
Diacritic characters should be included in words. 

#### Describe alternatives you've considered
Diacritic characters aren't ignored by other completion engines, such as https://github.com/ycm-core/YouCompleteMe and https://github.com/neoclide/coc.nvim

#### Additional context
Nothing to add

**Comment by dmitmel** [comment]
Try using `\k\+` for the `default_pattern` as described in #495

https://github.com/hrsh7th/nvim-compe/issues/495#issuecomment-895478900
