### ISSUE TITLE
Triggered in command mode.

### ISSUE THREAD

**Issue by singlexyz** [hrsh7th/nvim-compe#544]
When press `:` enter to command mode,
then press `<c-f>` edit the command.
compe still triggered.
Seems to run in insert mode anyway.

<img width="732" alt="图片" src="https://user-images.githubusercontent.com/4456413/131896032-a677a332-4dfd-49ca-8718-25a30b4ef267.png">

**Comment by danielnehrig** [comment]
there is no use in opening issues the project is not maintained anymore
