### ISSUE TITLE
Feature request: let user set completion width

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#55]
Hey @hrsh7th 

I think it will be great if the user can set the width of the completion popup, `set pumwidth=20` for example doesn't seem to have any effect on my iced source.

Thanks

**Comment by hrsh7th** [comment]
It is a good idea. But I'm thinking to apply other changes now.

I think we should remove `v:complete_item.kind` (this is coc's behavior.

**Comment by hrsh7th** [comment]
@tami5 I think this problem has gone for now (because nvim_lsp source does not provide detailed menu now).
What do you think about it?

**Comment by tami5** [comment]
I guess we still have the issue with vim-iced and conjure. It true I haven't seen the issue of width with nvim_lsp

**Comment by hrsh7th** [comment]
Should vim-iced-compe/compe-conjure provide `Source.documentation` instead of a detailed completion-menu?

OK. I will investigate it later.

**Comment by tami5** [comment]
> Should vim-iced-compe/compe-conjure provide `Source.documentation` instead of a detailed completion-menu?
> 
> 
> 
> OK. I will investigate it later.

The things is that item.info has the functions parameters and in the case of clojure there might 5 different args (x y) (x y z) for a single function .. and that what makes the completion menu extend this way.

**Comment by hrsh7th** [comment]
I've merged the PR so I'm closing it now.
If you met some other problem, feel free to re-open it.
