### ISSUE TITLE
Feature request: Choosing filetype and buf_local options

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#56]
e.g. set ft to go or lua instead of markdown

**Comment by tami5** [comment]
E.g. set different conceallevel

**Comment by hrsh7th** [comment]
You should write the issue description more clearly.

Why it is not enough that markdown's fenced language block.

**Comment by tami5** [comment]
Yep I should, sorry about that. I guess you are right about that. markdown's fenced language block is enough. If its possible, can you add a custom filetype on that buffer (extending markdown) so users can attach local option to it.

For example I dislike conceallevel while editing markdown, but I'd like to to temporary set it on the documentation window via filetype autocmd.

Thanks

**Comment by hrsh7th** [comment]
Currently, nvim-compe's documentation window already set &conceallevel=2 as local to it.

**Comment by tami5** [comment]
Yep that doesn't work because I use tpope/vim-markdown plugin that offer an option to disable conceallevel

`let g:markdown_syntax_conceal = 0`

**Comment by hrsh7th** [comment]
It means something like the following, right?

1. set `&conceallevel=2` in nvim-compe.
2. Vim fires `FileType` autocmd.
3. tpope/vim-markdown set to &conceallevel as 2 by `let g:markdown_syntax_conceal = 0`

**Comment by hrsh7th** [comment]
Hm... It is not reproduce on my side with install `tpope/vim-markdown` and set `g:markdown_syntax_conceal = 0`.

**Comment by tami5** [comment]
Thats wired, I'll double check

**Comment by tami5** [comment]
Yep it works okay with lua lisp, not sure why I still see the fenced language block . Maybe something todo with how I setup documentation content. I'll do further testing.

**Comment by hrsh7th** [comment]
The fenced_language_block has a marker that is `ts` in this example \```ts content \```.
The marker is not real `vim's filetype` so vim's markdown syntax has a option for it.

You can add `let g:markdown_fenced_languages = ['typescript=ts']`

**Comment by hrsh7th** [comment]
I've improved the error message for it.

**Comment by hrsh7th** [comment]
@tami5 this issue can be closed, right?

**Comment by tami5** [comment]
Yep
