### ISSUE TITLE
Feature request: navigate documentation buffer and limit height 

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#57]
it would be awesome If I can take advantage of that buffer via navigating and adding large amount of content. Limiting height goes hand in hand with this.

Thanks

**Comment by hrsh7th** [comment]
Could you explain it in more little in detail?

**Comment by tami5** [comment]
So basically, in addition to open/close the documentation window. on event, add `<c-u>` and `<c-d>` to navigated it. This is super useful when the content is 80 lines long and instead of having large preview window, it would be set to minheight and the user can navigate through it.

Does it make sense?

**Comment by hrsh7th** [comment]
I think `documentation scrolling` is easy. So we add it to README.md is enough.

```viml
nnoremap <expr> <C-f> <SID>scroll(+4)
nnoremap <expr> <C-u> <SID>scroll(-4)
inoremap <expr> <C-f> <SID>scroll(+4)
inoremap <expr> <C-u> <SID>scroll(-4)

function! s:scroll(count) abort
  let l:ctx = {}
  function! l:ctx.callback(count) abort
    let l:wins = nvim_list_wins()
    let l:wins = filter(l:wins, '!empty(nvim_win_get_config(v:val).relative)')
    if !empty(l:wins)
      call lamp#view#window#do(l:wins[0], { ->
      \   execute(printf('normal! %s%s%s%s',
      \     abs(a:count),
      \     a:count >= 0 ? "\<C-e>" : "\<C-y>",
      \     abs(a:count),
      \     a:count >= 0 ? 'j' : 'k',
      \   ))
      \ })
    endif
  endfunction
  call timer_start(100, { -> l:ctx.callback(a:count) })
  return "\<Ignore>"
endfunction
```

**Comment by tami5** [comment]
I don't understand how would this control the popup? 🤔 also, scroll will only be useful when the max height of the popup can be limited to certain extend.

**Comment by hrsh7th** [comment]
Ah. You want to enter to popup, right?
It's bit difficult now... hm...

**Comment by tami5** [comment]
I mean by control the popup is to control only what part is visible through scrolling the buffer it self. Hope you understand that way.

For scrolling we can easily attach mapping when the popup get created and destroyed with it. 

That is by normally binding buffer local mapping `nnoremap <buffer>` in the global scope that control that popup and then during close `unmap`

**Comment by hrsh7th** [comment]
I think https://github.com/hrsh7th/nvim-compe/issues/57#issuecomment-751343241 is realizing scrolling...

**Comment by hrsh7th** [comment]
@tami5 I've implemented scrolling mapping. Please see docs.

**Comment by tami5** [comment]
Thanks a lot @hrsh7th, I'll test out soon

**Comment by hrsh7th** [comment]
If this problem was solved, please close this.

**Comment by tami5** [comment]
Well ... it would be nice to only map nav keys when the popup show and map them back when popup closes. I usually have inter mode mapping for c-f,c-b,c-d and it would be cool to have them working if no popup

**Comment by hrsh7th** [comment]
Hm... I can add the `compe#scroll({ 'delta': +4, 'fallback': ... })`

**Comment by tami5** [comment]
Oh @hrsh7th that would be awesome !!!
