### ISSUE TITLE
How to activate lsp source in another filetype

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#6]
Hey @hrsh7th , I'm starting to use luapad again, and I noticed that completion source is disabled . The filetype is lua.luapad, I tried adding the file type to nvim_lsp setup function:

```lua
  require'nvim_lsp'.sumneko_lua.setup({
    on_attach = on_attach,
    filetypes = {'lua', 'lua.luapad'}})
```

But It didn't fix the issue, so I guess it has something to do with nvim_compe, vsnip source and path sources works fine though.

Thanks

**Comment by hrsh7th** [comment]
nvim-compe will detects LSP Client via vim.lsp.buf_get_clients.
So I think the case does not activated language server on the luapad filetype.

**Comment by tami5** [comment]
Thanks
