### ISSUE TITLE
Tag completion broken after last update

### ISSUE THREAD

**Issue by kristijanhusak** [hrsh7th/nvim-compe#60]
Hi,

today I updated packages and tags completion stopped working. I investigated and found out that last commit https://github.com/hrsh7th/nvim-compe/commit/184ecc4bb0c13e25412c9dc68039896bbfe28bc7 broke it. If i go to commit before (https://github.com/hrsh7th/nvim-compe/commit/feec0ae5143a228aa3c3d6560bfa50542704faf0) everything works fine.

**Comment by hrsh7th** [comment]
Oh, Sorry... and thank you.
I will fix it

**Comment by hrsh7th** [comment]
I think the issue was solved. Could you test with latest master?

**Comment by kristijanhusak** [comment]
Thanks. I'll test it tomorrow and let you know.

**Comment by kristijanhusak** [comment]
It works, thanks!
