### ISSUE TITLE
weird backspace behavior

### ISSUE THREAD

**Issue by RishabhRD** [hrsh7th/nvim-compe#61]
Hello @hrsh7th , thanks for the really cool plugin. I shifted from completion-nvim and I feel it has the abstractions that people really want from an auto-completion setup.

Just I found the backspace behavior a little weird. When I leave some suggestion for my own text and then do a backspace it inserts the (left) suggestion text automatically. Very similar to android autocorrection :sweat_smile: 
I have attached a gif that should explain my words more clearly.
![backspace](https://user-images.githubusercontent.com/26287448/103820708-cfff6280-5092-11eb-96ec-83d67076f4d0.gif)
I don't know if it is the intended feature. If it is then is there any option to disable it.

Also, sometimes backspace deletes a big amount of text (like 2 or 3 words) instead of a character.
This gif would show the behavior:
![backmore](https://user-images.githubusercontent.com/26287448/103821041-6f245a00-5093-11eb-8453-61421274e1a7.gif)

(Bottom right of gif shows my keypress in case of any ambiguity)

Thanks

**Comment by hrsh7th** [comment]
Could you provide your config?

**Comment by RishabhRD** [comment]
@hrsh7th I just realized that this is due to my `completeopt`. I also set the longest parameter that was causing this behavior. Sorry for this dumb issue. :sweat_smile: Thanks again for plugin

**Comment by hrsh7th** [comment]
It's weird... nvim-compe should overwrite complwteopthttps://github.com/hrsh7th/nvim-compe/blob/master/lua/compe/completion.lua#L229

**Comment by RishabhRD** [comment]
That's weird. I guess that the function is not being called in case of backspace
but completion is being triggered. This maybe a possible scenario. I would
also check that.

The minimal configuration needed to regenerate the behavior is:

```vim
call plug#begin('~/.vim/plugged')
Plug 'hrsh7th/nvim-compe'
call plug#end()

lua << EOF
require'compe'.setup {
  enabled = true,
  debug = false,
  -- min_length = 1,
  preselect = 'disable',

  source = {
    path = {
	priority = 9
    },
    buffer = {
	priority = 8
    },
    vsnip = {
	priority = 9
    },
    nvim_lsp = {
	priority = 10,
	sort = false
    },
  };
}
EOF
set completeopt=menuone,longest
```

**Comment by hrsh7th** [comment]
Thank you for providing minimal repro.

It's reproduced. It's very weird...

**Comment by hrsh7th** [comment]
Hm... nvim-compe seems to have a possibility of a bug.

In my environment, `local feels feels mo|<BS><BS>` will display pum only for a moment.

**Comment by hrsh7th** [comment]
I've added `set completeopt=menu,menuone,noselect` to README.md as required setting.

And bit improved a backspace behavior.
