### ISSUE TITLE
Any chance of adding ultisnips builtin completion-source?

### ISSUE THREAD

**Issue by RishabhRD** [hrsh7th/nvim-compe#65]
Hello @hrsh7th , currently nvim-compe supports vim-vsnip for snippet completion.

Although Ultisnips is considered to be slow, it remains to be very popular due to pre-available snippet solutions like vim-snippets. This makes it configurable in almost no time with a lot of handy snippets and hence many people still use it.

So, having Ultisnips completion builtin can interest a big user-base. (Maybe I am much opinionated on it)

The only problem with Ultisnips is, its code is not much **public-accessible** and hence something like getting a raw snippet string would result in a huge increase in the codebase. However, something like available snippets at the moment can be provided very easily without increasing the codebase drastically.

If you feel like adding it, I would submit a PR that would implement the feature.

**Comment by hrsh7th** [comment]
No ploblem. Looking forward to the PR.

**Comment by hrsh7th** [comment]
The PR has merged.
