### ISSUE TITLE
Vsnip source

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#7]
Hey @hrsh7th, while using vsnip source, I noticed that typing `rg` gets only LSP source, where as I have a snippet with rguse. It should show both Snippet source and LSP source.

Only when typing `rgu` I get rguse.

Not sure why?

Also I have fun snippet prefix, when I type fun, I only see lsp source

Thanks

**Comment by hrsh7th** [comment]
Could you tell me the your lanuguage server?

**Comment by tami5** [comment]
currently it is nvim_lsp

**Comment by hrsh7th** [comment]
No. I want to ask you about the languafe server, not language client.

I guess you met the problem on the lua filetype.

**Comment by tami5** [comment]
Oh sorry about that, it is sumneko_lua
```lua
  require'nvim_lsp'.sumneko_lua.setup({
    on_attach = on_attach,
    filetypes = {'lua', 'lua.luapad', 'luapad'},
    settings = {
      Lua = {
        runtime = {
          version = "LuaJIT",
          path = vim.split(package.path, ';'), },
          completion = { keywordSnippet = "Enable", },
          diagnostics = {
            enable = true,
            globals = {
              "vim", "describe", "it", "before_each", "after_each"
            },
            disable = {
              "unused-vararg",
              "unused-local",
              "lowercase-global"
            },
          },
          workspace = {
            library = {
              [vim.fn.expand("$VIMRUNTIME/lua")] = true,
              [vim.fn.expand("~/.config/nvim/lua")] = true,
            },
          }
        }
      }
    })

```

**Comment by hrsh7th** [comment]
OK. this problem should be fixed by nvim-compe side.

**Comment by hrsh7th** [comment]
Hm... It needs a consider.

If there is a source completed by the trigger character, nvim-compe will only use that source.

This is because it is more convenient to display only `fmt.{Print,Printf,Println}`, even if the input is `fmt.`.

**Comment by hrsh7th** [comment]
The lua-language-server is the rare language-server that specifies all alphabetical characters as trigger characters so nvim-compe seems only to show lua-language-server's results.

**Comment by hrsh7th** [comment]
I thought we should use character if the character is non-alphabetical characters but it is not perfect solution for it.

If the line is `fmt.`, it means the trigger character is `.` so we should show `Print,Println,Printf`.
But the line is `fmt.P`, it means the trigger character is `P` so, at this time, nvim-compe will show vsnip candidates.

Probably It is a bit of annoying behavior.

**Comment by tami5** [comment]
@hrsh7th oh my god, yes it is. Do you know another reliable lu server I can test out

Thanks

**Comment by hrsh7th** [comment]
I think this problem should be fixed now by https://github.com/hrsh7th/nvim-compe/commit/358aaa736ad927e8edc3421a82f3140744f3c251

**Comment by tami5** [comment]
Testing ...

**Comment by tami5** [comment]
Nice, the issue is fixed. it works very well! Thanks @hrsh7th . Is there a way to make vsnip source showing before lsp completion? perhaps a builtin option? Thanks again

**Comment by hrsh7th** [comment]
Sorry.
Currently, source priorities were hard coded.
