### ISSUE TITLE
add installation details for newbies

### ISSUE THREAD

**Issue by rustiever** [hrsh7th/nvim-compe#72]

**Comment by hrsh7th** [comment]
The issue description is required.

Looking forward to your PR.

**Comment by rustiever** [comment]
is there any dependable plugins are there for this?
give me some glimpse of installation, I'll give you the PR

**Comment by hrsh7th** [comment]
Currently, nvim-compe documentation is improved so far.
So I think this problem is already solved. Do you think about it?

**Comment by cloggier** [comment]
@rustiever Do you have a specific issue that README does not address? What do you think would help you set up that plugin?

**Comment by rustiever** [comment]
nothing much, i found there is no dedicated installation guide for newbies which I wanted to address
