### ISSUE TITLE
How to bind cr work with Raimondi/delimitMate

### ISSUE THREAD

**Issue by glepnir** [hrsh7th/nvim-compe#74]
As title Thanks:)

**Comment by hrsh7th** [comment]
Probably, the below mappings will work.
```
  inoremap <silent><expr> <CR>      compe#confirm('<Plug>delimitMateCR')
```

**Comment by glepnir** [comment]
Ok .found some thing wired with nvim-compe . Use lspsaga rename to rename a function then I enter insert mode, got failed.
`Not allowed here`, works fine with completion-nvim and disable nvim-compe.

**Comment by hrsh7th** [comment]
`Not allowed here` relates to this code https://github.com/hrsh7th/nvim-compe/blob/master/lua/compe/completion.lua#L254

I don't know the actual cause please your guessing.

**Comment by glepnir** [comment]
why this min config does not work what i am  missing?
```vim
set rtp+=~/.cache/vim/dein/repos/github.com/neovim/nvim-lspconfig
set rtp+=~/workstation/vim/lspsaga.nvim
set rtp+=~/.cache/vim/dein/repos/github.com/hrsh7th/nvim-compe

set completeopt=menu,menuone,noselect
lua <<EOF
require'lspconfig'.sumneko_lua.setup {
  cmd = {
    "/Users/stephen/workstation/lua-language-server/bin/macOS/lua-language-server",
    "-E",
    "/Users/stephen/workstation/lua-language-server/main.lua"
  };
  settings = {
    Lua = {
      diagnostics = {
        enable = true,
        globals = {"vim"}
      },
      runtime = {version = "LuaJIT"},
      workspace = {
        library = vim.list_extend({[vim.fn.expand("$VIMRUNTIME/lua")] = true},{}),
      },
    },
  }
}
require'compe'.setup {
  enabled = true;
  debug = false;
  min_length = 1;
  preselect = 'always';
  allow_prefix_unmatch = false;
  source = {
    nvim_lsp = true;
  };
}
EOF
```

**Comment by glepnir** [comment]
solved.

**Comment by glepnir** [comment]
hmm seems like <CR> does not work..
```
-- verbose inoremap <CR>
i  <CR>        * compe#confirm('<Plug>delimitMateCR')
```
then press cr I got `<Plug>delimitMateCR`

**Comment by hrsh7th** [comment]
Oh sorry.
the `<Plug>delimitMateCR` should be expanded but the suggested mapping uses `inoremap`.

It seems to need to fix nvim-compe.

**Comment by glepnir** [comment]
Okay. how about now?

**Comment by onsails** [comment]
I also 

> hmm seems like does not work..
> 
> ```
> -- verbose inoremap <CR>
> i  <CR>        * compe#confirm('<Plug>delimitMateCR')
> ```
> 
> then press cr I got `<Plug>delimitMateCR`
I also noticed this problem when working with nix sources (no problems in rust and python) and fixed that with:
```vim
    inoremap <silent><expr> <CR>      pumvisible() ? compe#confirm('<Plug>delimitMateCR') : '<CR>'
```

**Comment by hrsh7th** [comment]
PR welcome.
I will try it later.

**Comment by onsails** [comment]
> > hmm seems like does not work..
> > ```
> > -- verbose inoremap <CR>
> > i  <CR>        * compe#confirm('<Plug>delimitMateCR')
> > ```
> > 
> > 
> > then press cr I got `<Plug>delimitMateCR`
> 
> I also noticed this problem when working with nix sources (no problems in rust and python) and fixed that with:
> 
> ```viml
> inoremap <silent><expr> <CR>      pumvisible() ? compe#confirm('<Plug>delimitMateCR') : '<CR>'
> ```

Just found out that this fixes problem when there is no any completion candidate but it still puts '<Plug>delimitMateCR' when the first completion candidate is already typed in.

**Comment by hrsh7th** [comment]
Could you test https://github.com/hrsh7th/nvim-compe/pull/80 ?

**Comment by hrsh7th** [comment]
I don't use delimitMate so please test it.
