### ISSUE TITLE
Enter to confirm has a delay

### ISSUE THREAD

**Issue by glepnir** [hrsh7th/nvim-compe#75]

**Comment by hrsh7th** [comment]
Issue description is required.

**Comment by glepnir** [comment]
there is a gif to show that. choose a complete item then press enter to confirm . has a delay to show vsnipt

![1](https://user-images.githubusercontent.com/41671631/106107637-1f145100-6182-11eb-9bd2-579847206ec2.gif)

**Comment by hrsh7th** [comment]
Could you try to use `<nowait>` for `<CR>` mapping?

Please provide minimal vimrc if the problem is not an explicit bug.
