### ISSUE TITLE
Inserting `label` instead of `newText`

### ISSUE THREAD

**Issue by ckipp01** [hrsh7th/nvim-compe#76]
First of all, thanks for this plugin. I was amazed at the speed when I first tried it out. However, one thing that is currently making it unusable for me is that when using [Metals, the Scala language server](https://scalameta.org/metals/), nvim-compe is inserting the `label` instead of the `textEdit.newText`.

### Example

Take the following `completionItem`:

```
{
  "label": "Option scala",
  "kind": 9,
  "detail": " scala",
  "sortText": "00003",
  "filterText": "Option",
  "insertTextFormat": 2,
  "textEdit": {
    "range": {
      "start": {
        "line": 10,
        "character": 10
      },
      "end": {
        "line": 10,
        "character": 11
      }
    },
    "newText": "Option"
  },
  "data": {
    "symbol": "scala/Option.",
    "target": "file:/Users/ckipp/Documents/scala-workspace/tester/?id\u003droot"
  }
}
```

According to the [spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion) when the `textEdit` is present, it should take priority, and when you look at the gif, you'll see that `Option scala` is being added:

![2021-01-28 09 08 40](https://user-images.githubusercontent.com/13974112/106108419-857c7d80-6148-11eb-9be4-d442cf8af14e.gif)

This is happening for almost all the completions.

### Expectation

In this scenario I'd expect just `Option` to be inserted. This is what happens just using ins-completion, `completion-nvim`, or any of the other completion frameworks I've used.

![2021-01-28 09 11 38](https://user-images.githubusercontent.com/13974112/106108750-fcb21180-6148-11eb-9a2c-081388d14590.gif)

### Where is the issue

From what I can tell poking around the issue is here:

https://github.com/hrsh7th/nvim-compe/blob/b78202c7440726b6b22ceef43c66dbf6fa5fcf91/lua/compe_nvim_lsp/source.lua#L109-L131

From my understanding in my case `expandable` is set to `true` here: https://github.com/hrsh7th/nvim-compe/blob/b78202c7440726b6b22ceef43c66dbf6fa5fcf91/lua/compe_nvim_lsp/source.lua#L119

But no matter what in the logic here: https://github.com/hrsh7th/nvim-compe/blob/b78202c7440726b6b22ceef43c66dbf6fa5fcf91/lua/compe_nvim_lsp/source.lua#L125-L131 the `label` is still being used. I have tried playing around and fixing this but the stuff I was trying wasn't working, so I must be missing something.

### Reproduce

You can reproduce this if you want using `nvim-metals`, although it may take a bit for you to get set up since you'll need to download a few things. If you want detailed instructions I can totally provide that, but the details above may be enough for you to spot the issue. If you need anything else, just let me know.

**Comment by hrsh7th** [comment]
It's timely.
I've improved this behavior before just a few hors.
Could you check latest master?

**Comment by hrsh7th** [comment]
BTW, the solution is incorrect that use `newText` instead of `label`.

It has a very complex context in vim because LSP defined to support VSCode.

**Comment by ckipp01** [comment]
> It's timely.
> I've improved this behavior before just a few hors.
> Could you check latest master?

ahh yes, timely! So yea, that change indeed did fix the specific situation that I gave above, however I do have some more issues now 😆. I'll create another issue for it though as it's a bit different.

> BTW, the solution is incorrect that use newText instead of label.

I'm not sure what you mean?

**Comment by hrsh7th** [comment]
I don't know a perfect solution to this problem.
So your issue is very helpful. I'm looking forward to the new issue.

**Comment by hrsh7th** [comment]
The new issue does not relates to `v:complete_item.word`.
So I think this issue can be closed for now.

Feel free to close it.

**Comment by ckipp01** [comment]
👍🏼 thanks for you quick fix!
