### ISSUE TITLE
Different behavior when going back to a completion with a snippet

### ISSUE THREAD

**Issue by ckipp01** [hrsh7th/nvim-compe#77]
This is a bit of an odd one, but when I have a completion with a snippet and it's the first choice in my list, everything works fantastic. For example take this completionItem:

```
{
      "label": "match",
      "kind": 12,
      "detail": "",
      "preselect": true,
      "sortText": "00000",
      "filterText": "match",
      "insertTextFormat": 2,
      "textEdit": {
        "range": {
          "start": {
            "line": 7,
            "character": 4
          },
          "end": {
            "line": 7,
            "character": 5
          }
        },
        "newText": "match {\n\tcase$0\n}"
      },
      "data": {
        "symbol": "local7",
        "target": "file:/Users/ckipp/Documents/scala-workspace/tester/?id\u003droot"
      }
    }
```

![2021-01-28 09 33 42](https://user-images.githubusercontent.com/13974112/106111121-f4a7a100-614b-11eb-8b1d-7f5aa0190491.gif)

However, if I skip over that option and then come back to it and select it, for some reason I only get the first part of it:

![2021-01-28 09 34 37](https://user-images.githubusercontent.com/13974112/106111236-14d76000-614c-11eb-9aaa-26cf9eee7b2e.gif)

I'm not really sure what's happening here, but any idea why it would behave differently when going back to it?

**Comment by hrsh7th** [comment]
It's very weird...
it takes a lot of time to solve may be.

I will investigate it.

**Comment by hrsh7th** [comment]
If you can provide minimal reproducible vimrc, it is very helpful.

**Comment by hrsh7th** [comment]
It has same root cause, I think. https://github.com/hrsh7th/nvim-compe/issues/69

**Comment by ckipp01** [comment]
Alright, so while making the minimal reproduction, I figured out what is actually causing this. I had this leftover in my config from using `completion-nvim`:

```lua
local function map(mode, lhs, rhs, opts)
  local options = {noremap = true, silent = true}
  if opts then
    options = vim.tbl_extend('force', options, opts)
  end
  vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end

map('i', '<S-Tab>', 'pumvisible() ? "\\<C-p>" : "\\<Tab>"', {expr = true})
map('i', '<Tab>', 'pumvisible() ? "\\<C-n>" : "\\<Tab>"', {expr = true})
```

I used this in order to be able to tab through the completion items. Once removing these, then the behavior works as expected. Sorry for the confusion this on.

What's the recommended way to have something similiar with `nvim-compe` to be able to tab through the completion list?

**Comment by hrsh7th** [comment]
Thank you for your investigation!!!

I'm confusing... I don't know why it makes this problem...

I will try to fix it later

**Comment by ckipp01** [comment]
For sure, just in case you do need a minimal reproduction (even though it's not _that_ minimal, this is how you can test with `nvim-metals` and metals.

#### Minimal init file

```lua
-- compe.lua
local cmd = vim.cmd

local function opt(scope, key, value)
  local scopes = {o = vim.o, b = vim.bo, w = vim.wo}
  scopes[scope][key] = value
  if scope ~= 'o' then
    scopes['o'][key] = value
  end
end

cmd [[packadd packer.nvim]]
require('packer').startup(function(use)
  use {'wbthomason/packer.nvim', opt = true}

  use {'hrsh7th/nvim-compe', requires = {{'hrsh7th/vim-vsnip'}, {'hrsh7th/vim-vsnip-integ'}}}
  use 'scalameta/nvim-metals'
end)

require'compe'.setup {
  enabled = true;
  debug = false;
  min_length = 1;

  source = {
    path = true;
    buffer = true;
    vsnip = true;
    nvim_lsp = true;
  };
}

opt('o', 'completeopt', 'menuone,noinsert,noselect')
vim.o.shortmess = string.gsub(vim.o.shortmess, 'F', '') .. 'c'

cmd [[augroup lsp]]
cmd [[autocmd!]]
cmd [[autocmd FileType scala,sbt lua require("metals").initialize_or_attach(metals_config)]]
cmd [[augroup end]]

metals_config = require'metals'.bare_config

metals_config.settings = {
  showImplicitArguments = true,
  excludedPackages = {'akka.actor.typed.javadsl', 'com.github.swagger.akka.javadsl'}
}

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

metals_config.capabilities = capabilities


-- This is what is causing the issues if I uncomment them.
-- map('i', '<S-Tab>', 'pumvisible() ? "\\<C-p>" : "\\<Tab>"', {expr = true})
-- map('i', '<Tab>', 'pumvisible() ? "\\<C-n>" : "\\<Tab>"', {expr = true})
```

1. Ensure the plugins are downloaded (This example is using [packer](https://github.com/wbthomason/packer.nvim)
2. Install [coursier](https://get-coursier.io/docs/cli-installation)
3. Clone this minimal Scala project [here](https://github.com/ckipp01/metals-minimal-sbt)
4. `cd` into the directory and open project `nvim -u compe.lua src/main/scala/example/CompletionError.scala`
5. Do a `:MetalsInstall` which will install metals. After completion close and re-open
6. You should see a message request to import the build. Do that and then it will index your workspace
7. Then attempt the completion in here: https://github.com/ckipp01/metals-minimal-sbt/blob/master/src/main/scala/example/CompletionError.scala

**Comment by hrsh7th** [comment]
I found the cause may be.
You configuration has no `inoremap <expr><CR> compe#confirm('<CR>')`.

**Comment by hrsh7th** [comment]
@ckipp01 I think if you set above mapping, this issue could be solved.

If you get the correct result, feel free to close it.

**Comment by ckipp01** [comment]
So one of the last two commits broke snippet support for me because now this doesn't complete any part of the snippet now:

![2021-01-28 16 25 05](https://user-images.githubusercontent.com/13974112/106159784-6fd97900-6185-11eb-94cd-a583e5ad3e20.gif)

**Comment by hrsh7th** [comment]
Please set `map('i', '<CR>', 'compe#confirm("\\<CR>")', {expr = true})` then re-check it.

**Comment by ckipp01** [comment]
> Please set `map('i', '<CR>', 'compe#confirm("\\<CR>")', {expr = true})` then re-check it.

Corrected it, and same result.

**Comment by hrsh7th** [comment]
Hm... It's weird.

In my environment, the below setting works perfectly.

```
lua <<EOF
local cmd = vim.cmd

local function opt(scope, key, value)
  local scopes = {o = vim.o, b = vim.bo, w = vim.wo}
  scopes[scope][key] = value
  if scope ~= 'o' then
    scopes['o'][key] = value
  end
end

cmd [[packadd packer.nvim]]
require('packer').startup(function(use)
  use {'wbthomason/packer.nvim', opt = true}

  use {'hrsh7th/nvim-compe', requires = {{'hrsh7th/vim-vsnip'}, {'hrsh7th/vim-vsnip-integ'}}}
  use 'scalameta/nvim-metals'
end)

require'compe'.setup {
  enabled = true;
  debug = false;
  min_length = 1;

  source = {
    path = true;
    buffer = true;
    vsnip = true;
    nvim_lsp = true;
  };
}

opt('o', 'completeopt', 'menuone,noinsert,noselect')
vim.o.shortmess = string.gsub(vim.o.shortmess, 'F', '') .. 'c'

metals_config = require'metals'.bare_config

cmd [[augroup lsp]]
cmd [[autocmd!]]
cmd [[autocmd FileType scala,sbt lua require("metals").initialize_or_attach(metals_config)]]
cmd [[augroup end]]


local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

metals_config.capabilities = capabilities


-- This is what is causing the issues if I uncomment them.
local function map(mode, lhs, rhs, opts)
local options = {noremap = true, silent = true}
if opts then
  options = vim.tbl_extend('force', options, opts)
end
vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end
map('i', '<CR>', 'compe#confirm("\\<CR>")', {expr = true})
map('i', '<S-Tab>', 'pumvisible() ? "\\<C-p>" : "\\<Tab>"', {expr = true})
map('i', '<Tab>', 'pumvisible() ? "\\<C-n>" : "\\<Tab>"', {expr = true})
EOF
```

**Comment by ckipp01** [comment]
Alright, it looks like it was another plugin causing issues. Even though I was using `-u` the other plugins were still there. Once I cleared everything, it all got fixed.

🙏🏼 thanks a ton for all your work on this and your responsiveness.

**Comment by hrsh7th** [comment]
I see. If you detect the plugin that makes this issue, feel free to report it.
