### ISSUE TITLE
Unable to get specific completions

### ISSUE THREAD

**Issue by ckipp01** [hrsh7th/nvim-compe#79]
This is sort of a hard one to explain, but I've noticed today while using `nvim-compe` I'm a lot of times unable to get the same completions offered by `completion-nvim` or just with triggering `ins-completion` at a specific point.

For example, if I want to get the `Instant` completion, it's almost impossible for me unless I leave insert mode in the middle of the word, then come back and trigger the completion at that point.

```scala
Inst<cursor>
```

With `ins-completion` if I trigger at this point, I will get `Instant` in the list of completions. Normally with `completion-nvim` as I just type Instant, it also appears. However, with `nvim-compe` it seems that the initial completion request sent for `I` doesn't contain `Instant`, which is fine, but then no other request seems to be made, and then it just never retrieves it. I can confirm that with `ins-completion` a completion request just on `I` also doesn't return it. Either way, I'm unsure how to remedy this because with Metals this ultimately means that there are a lot of completions you'll just never get.

With `nvim-compe`:

![2021-01-28 14 55 39](https://user-images.githubusercontent.com/13974112/106148217-153a2000-6179-11eb-8f7c-799fb948485e.gif)

With `completion-nvim`:

![2021-01-28 14 57 37](https://user-images.githubusercontent.com/13974112/106148325-3733a280-6179-11eb-9afb-08d984f1f2ed.gif)

I can give you pretty detailed logs with this if you want. You can use the same setup instructions as I included in https://github.com/hrsh7th/nvim-compe/issues/77 and just open the same page and try to complete `Instant`.

**Comment by hrsh7th** [comment]
I finally get the scala environment.
I will investigate it.

**Comment by ckipp01** [comment]
> I finally get the scala environment.
> I will investigate it.

Awesome, if you get stuck on any Metals-related stuff please let me know how I can help.

**Comment by ckipp01** [comment]
👍🏼 just confirmed that this is working. Thanks!
