### ISSUE TITLE
Confirming selection without enter?

### ISSUE THREAD

**Issue by tami5** [hrsh7th/nvim-compe#8]
Hey @hrsh7th hope your having a great week.

## My configuration 

```lua
local options = {
  compe_enabled = true,
  compe_min_length = 1,
  compe_auto_preselect = false,
}
```

## Issue:

Selecting an item with `<c-p>` or `<c-n>` doesn't confirm selection, so if I want to have a `<space>` or add `(` after pressing `<c-n/p>` on highlighted item in the popup, I'd need to press the letter twice, which very annoying to be honest.

## expected behavior 

When an item is selected it should be confirmed so that pressing any letter afterwards won't be blocked or need to be pressed twice.

**Comment by hrsh7th** [comment]
Sorry. I couldn't understand your means.

Could you provide animated gif for explanatuon?

**Comment by tami5** [comment]
Here you go https://asciinema.org/a/ARifzGQKArdM1ElPT9v8g13CX. Sorry couldn't explain it better.

**Comment by hrsh7th** [comment]
I've understand.
It's bug of vim-vsnio-integ (maybe).
Thank you for your report.

**Comment by hrsh7th** [comment]
@tami5 Could you test with https://github.com/hrsh7th/vim-vsnip-integ/pull/29 ?

**Comment by hrsh7th** [comment]
If you confirmed the commit, please feel free to close it.

**Comment by tami5** [comment]
Sorry had a busy day yesterday @hrsh7th, it works great thanks so much !!!.

**Comment by hrsh7th** [comment]
Thank you!
