### ISSUE TITLE
Completion confirmation

### ISSUE THREAD

**Issue by tomaskallup** [hrsh7th/nvim-compe#81]
Currently, when using lsp with `typescript-language-server` (`tsserver` in nvim-lspconfig) confirmation doesn't seem to trigger completion resolve, so automatic imports are not triggered.

I'm creating this issue to track [following](https://www.reddit.com/r/neovim/comments/l61gzb/builtin_lsp_client_exeprience/gkytdu6?utm_source=share&utm_medium=web2x&context=3)

**Comment by hrsh7th** [comment]
We should use this https://github.com/hrsh7th/vim-vital-vs/blob/master/autoload/vital/__vital__/VS/LSP/CompletionItem.vim
