### ISSUE TITLE
No dictionary auto-completion?

### ISSUE THREAD

**Issue by coxackie** [hrsh7th/nvim-compe#85]
I may be missing this entirely, but I have not seen dictionary source, and I can confirm that auto-completion is not using dictionary. This is quite an important source for an editor; as I said, i may be missing this altogether. Please advise.

**Comment by elianiva** [comment]
I was also thinking about this last night, being able to auto-complete an actual word and seeing its definition is great. But I'm worried about how big the source would be, [this repo](https://github.com/matthewreagan/WebstersEnglishDictionary) has an English Dictionary in form of JSON that we *could* use but it's huge, around 20MB.

**Comment by hrsh7th** [comment]
I was misunderstanding. vim's `getcompletion` has no returns `dict` completion results.

**Comment by coxackie** [comment]
I think I also did not explain well. I meant the simple spell suggestions one would get spell check on. The ones with C-n or C-p. This should be possible with no overhead in performance, right?

**Comment by hrsh7th** [comment]
If you want to realize vim's native spell completion. You can look `compe_tags` source as reference implementations.

**Comment by elianiva** [comment]
Ah! I forgot if (n)vim has dictionary for completion already.

**Comment by hrsh7th** [comment]
we can use `spellsuggest({word})` ...? I haven't ever used it.

**Comment by coxackie** [comment]
Completion.nvim has something called "modes completion", where you set basically the keyboard trigger from omnicomplete and it triggers it. So you literally just add as a mode the trigger keystroke.

**Comment by hrsh7th** [comment]
I absolutely never implement `modes completion`. sorry.

**Comment by coxackie** [comment]
It is your project and you do what you want. And thank you very.much. If there is another way of doing this and you can, I would be happy and grateful.

**Comment by hrsh7th** [comment]
The spell source has merged. Feel free to close this issue.

I think we can improve spell source by parsing spell files manually by Lua.
I'm looking forward to PR from someone.

**Comment by coxackie** [comment]
OK, many thanks!

 I am going to close this, but maybe you want to open a new issue with your desire for spell source by parsing spell files manually by Lua?
