### ISSUE TITLE
vsnip: show description in completion candidates list or evaluated snippet in hover window

### ISSUE THREAD

**Issue by cloggier** [hrsh7th/nvim-compe#87]
`vim-vsnip` allows to specify `description` for snippet. I use that extensively as I have many single letter snippet shortcuts and was relying on meaningful descriptions printed by `completion.nvim` when choosing snippets. I really like your plugin and wanted to ask whether it would be possible to display `description` field in completions menu.

Thanks!

EDIT: Just noticed that there is a side floating window shown when an item is selected. It wasn't showing for me as I used cursor arrow instead of `<c-n>` and `<c-p>`. It shows *raw* snippet, which is giving me some information, but with too much detail (snippet implementation detail). Would it be possible to pre-evaluate snippet and show what would be inserted if an item is selected? coc does it that way and it was very helpful.

**Comment by hrsh7th** [comment]
Implemented https://github.com/hrsh7th/nvim-compe/commit/d03b2b27870fac0af85b0a74d83a7867a8f66b6f

**Comment by cloggier** [comment]
Works great, thank you!
