### ISSUE TITLE
Improve buffer source

### ISSUE THREAD

**Issue by hrsh7th** [hrsh7th/nvim-compe#9]

**Comment by tami5** [comment]
Yes this very week now, in buffer and open buffer completion sometime give results and sometime not

**Comment by hrsh7th** [comment]
I've pushed the commit to improve the buffer source.

**Comment by tami5** [comment]
I'll tested out now

**Comment by tami5** [comment]
Oh that so much better. I noticed that words with this format `module-keyword` doesn't show only `module_keyword`. Also, it would be cool if completion from other buffers is enabled and have a menu `[other buffers]`

**Comment by hrsh7th** [comment]
Thank you for your point out, It was a bug.

I think so too. We should complete words from other buffers.

**Comment by tami5** [comment]
Yah there is a thin line between good suggestions and bad suggestion, specially with buffer source. User will not like a big list of completion every time he types a letter, so definitely a good strategy of buffer source suggestion is needed. Hmmm let me think, how about suggestion from other buffers are omitted till there are no  suggestion in current buffer or other sources

**Comment by hrsh7th** [comment]
My idea is we should use the buffers displayed on the window.
If the window was split, nvim-compe will use two buffers.

**Comment by tami5** [comment]
Oh thats even better, very smart. I noticed I need other buffer completion when I have a split

**Comment by tami5** [comment]
Just test it out the fix for `module-keyword` it works flawlessly. @hrsh7th I know I said it once, and I will say it again, you framework is truly the best completion framework out there :D. Thanks again

**Comment by hrsh7th** [comment]
Thank you for your words.

I think the buffer source was improved now.
