### ISSUE TITLE
Completion list not refreshed properly with ultisnips source

### ISSUE THREAD

**Issue by ii14** [hrsh7th/nvim-compe#90]
7f69289 introduced a bug:

When `ultisnips` source is included, the completion list is not refreshed properly. The popup opens and shows the completions matched with the first character, but won't update the list on any inserted characters after that.

[![asciicast](https://asciinema.org/a/EFUnseRfg6njN26CepmoB1Zvt.svg)](https://asciinema.org/a/EFUnseRfg6njN26CepmoB1Zvt)

Minimal config:

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'hrsh7th/nvim-compe', {'commit': '7f69289'}
Plug 'SirVer/ultisnips'
call plug#end()

let g:compe = {}
let g:compe.enabled = v:true
let g:compe.source = {
  \ 'buffer': v:true,
  \ 'ultisnips': v:true,
  \ }
```

**Comment by hrsh7th** [comment]
It's wired... reproduced.
