### ISSUE TITLE
Supporting snippets.nvim?

### ISSUE THREAD

**Issue by saadparwaiz1** [hrsh7th/nvim-compe#96]
Hey, just wondering if there are any plans on supporting snippets.nvim :) thank you for a great plugin

**Comment by hrsh7th** [comment]
Currently, No.
I will add it.

**Comment by hrsh7th** [comment]
I've implemented low-level API for it.

Feel free to create PR.

**Comment by saadparwaiz1** [comment]
Thank you so much for your help! and for such a great plugin :)
