### ISSUE TITLE
Autoexpanding vsnip snippet no longer happening

### ISSUE THREAD

**Issue by cloggier** [hrsh7th/nvim-compe#99]
One of the most recent changes broke autoexpanding snippets on selection confirmation. So when I pressed enter to select preselected item it would get expanded (if it was `vim-vsnip` snippet). It does not happen any more and I have to trigger expansion manually after completion menu is closed.

Do you think it's a bug or should I make `<CR>` mapping to handle that? It worked without special mapping before.

**Comment by hrsh7th** [comment]
Hm....

Yes. The recent commit makes not working vim-vsnip-integ anymore.

The vim-vsnip-integ will expand snippet automatically if the user press `any` char.

But latest compe does not handle `any char`. It handles only `compe#complete` mapping. Sorry.

**Comment by hrsh7th** [comment]
It is design decision.
I would not restore previous behavior.

But we can consider new-feature for it may be.

**Comment by cloggier** [comment]
So as a side question - is `vim-vsnip-integ` still required? Should it be removed?

**Comment by hrsh7th** [comment]
If you use `nvim-compe` x `nvim_lsp` x `vim-vsnip`, the vim-vsnip-integ is not required anymore. You should remove it.

**Comment by cloggier** [comment]
OK, thank you for clarifying. Removed but still not having previous functionality/behaviour.

Should I look into mapping/function or is it something that would have to be implemented into `compe`?

**Comment by hrsh7th** [comment]
Currently, nvim-compe needs the below mapping to confirm completion item.
```
inoremap <silent><expr> <CR>      compe#confirm('<CR>')
```

If you have the above mapping but still does not satisfy what you want functionality, we should improve `nvim-compe` itself.

**Comment by cloggier** [comment]
Ah, excellent! Works like before, great thanks!

Last question - is there Lua equivalent I could call instead?

**Comment by cloggier** [comment]
Hmm, interestingly this one does not work though:
`vim.api.nvim_set_keymap("i", "<CR>", "compe#confirm(lexima#expand('<LT>CR>', 'i'))", {expr = true, noremap = true, silent = true})`

**Comment by elianiva** [comment]
try `vim.fn["compe#confirm"](vim.fn["lexima#expand"]("<LT>CR>", "i"))` for lua equivalent. But I don't think you can pass lua function directly to a mapping unless you use astronauta.nvim or wait for it to get merged upstream.

Also, it's strange that your mapping doesn't work. I had the same thing albeit with some extra stuff on it and it works. Here's how mine's look like (I don't use it anymore though)

```lua
vim.api.nvim_set_keymap(
  'i', '<CR>',
  table.concat{
    'pumvisible()',
    '? complete_info()["selected"] != "-1"',
    '? compe#confirm(lexima#expand("<LT>CR>", "i"))',
    ': "<C-g>u".lexima#expand("<LT>CR>", "i")',
    ': v:lua.Util.check_html_char() ? lexima#expand("<LT>CR>", "i")."<ESC>O"',
    ': lexima#expand("<LT>CR>", "i")'
  },
  { silent = true, expr = true }
)
```

**Comment by cloggier** [comment]
Tried that as well but no joy. 

 It in front of computer any more but there is a shorthand or whatever that is that can be used in mappings, like `v:lua.function()`. That's why I have asked about lua function for confirm.

**Comment by cloggier** [comment]
@hrsh7th Apologies for noise. It turned out to be an issue in my setup. All working as expected now. Thank you very much for all your help @elianiva  and @hrsh7th.

**Comment by ckipp01** [comment]
> If you use `nvim-compe` x `nvim_lsp` x `vim-vsnip`, the vim-vsnip-integ is not required anymore. You should remove it.

Just to clarify, what exactly is `nvim_lsp`? Is this the `nvim-lspconfig`?

**Comment by JoseConseco** [comment]
I pad problems with expanding vsnip too but : 
`inoremap <silent><expr> <C-Space> compe#confirm('<CR>')`
And then for jumping around expanded snippet:

```
imap <expr> <Tab>   vsnip#jumpable(1)   ? '<Plug>(vsnip-jump-next)'      : '<Tab>'
imap <expr> <S-Tab> vsnip#jumpable(-1)  ? '<Plug>(vsnip-jump-prev)'      : '<S-Tab>'
```

I removed every other mapping and this works now. Ctrl+space will expand snippets correctly now, and use Tab to jump inside expanded snippet.

**Comment by hrsh7th** [comment]
nvim-compe does not need `vim-vsnip-integ`. That needs only `vim-vsnip` (or snippets.nvim) for expanding LSP snippets.
